### ISSUE TITLE
Alexa Media Player fails login - 'FixedCookieJar' object has no attribute '_quote_cookie'

### ISSUE THREAD

**Issue by mahk8** [custom-components/alexa_media_player#1023]
**Describe the bug**

After installing and restarting version 0.118.x, Alexa Media Player fails to login to Alexa Amazon account and throw the following exception below. Media Player is not active or responsive. Unloading and reloading Alexa Integration does not resolve issue.

**To Reproduce**
Reviewed log file.

**Expected behavior**

Alexa Media Player logged into Amazon account and UI made active. 

**Screenshots**

**System details**
 - Home-assistant (version):  0.118.[0-4]
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 2.8.2
 - alexapy (version from `pip show alexapy` or HA startup): 1.10.0
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: F2A is enabled and works with previous versions (i.e. <=0.117.6)

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

`
`2020-11-23 14:27:14 ERROR (MainThread) [alexapy.helpers] alexalogin.login:An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'FixedCookieJar' object has no attribute '_quote_cookie'",)
2020-11-23 14:27:14 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxx@xxxxxxx.com - amazon.com for alexa_media
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home/.homeassistant/custom_components/alexa_media/__init__.py", line 220, in async_setup_entry
    await login.login_with_cookie()
  File "/home/.homeassistant/deps/lib/python3.8/site-packages/alexapy/alexalogin.py", line 201, in login_with_cookie
    await self.login(cookies=self._cookies)
  File "/home/.homeassistant/deps/lib/python3.8/site-packages/alexapy/helpers.py", line 69, in wrapper
    return await func(*args, **kwargs)
  File "/home/.homeassistant/deps/lib/python3.8/site-packages/alexapy/alexalogin.py", line 374, in login
    if cookies and await self.test_loggedin(cookies):
  File "/home/.homeassistant/deps/lib/python3.8/site-packages/alexapy/alexalogin.py", line 275, in test_loggedin
    get_resp = await self._session.get(
  File "/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/aiohttp/client.py", line 481, in _request
    all_cookies = self._cookie_jar.filter_cookies(url)
  File "/opt/pyenv/versions/3.8.1/lib/python3.8/site-packages/aiohttp/cookiejar.py", line 221, in filter_cookies
    SimpleCookie() if self._quote_cookie else BaseCookie()
AttributeError: 'FixedCookieJar' object has no attribute '_quote_cookie'
`
`

**Additional context**

**Comment by alandtse** [comment]
Your alexapy version is way out of date. It needs to be alexapy==1.16.0

**Comment by mahk8** [comment]
Thanks - I removed and re-installed.
