### ISSUE TITLE
Cannot configure the integration after update to 3.4.0

### ISSUE THREAD

**Issue by bieniu** [custom-components/alexa_media_player#1034]
**Describe the bug**
After update Alexa Media Player to version 3.4.0 I cannot configure the integration. The cookie import also fails with the same error.

**To Reproduce**
1. Go to Integrations -> Add integration -> Alexa Media Player
2. Fill login, password and click Submit
3. See error

**Expected behavior**
The integration should allow for error-free configuration.

**Screenshots**
![image](https://user-images.githubusercontent.com/478555/101337079-8b0dc380-387b-11eb-9c05-48e39dcead18.png)

**System details**
 - Home-assistant (version): 0.118.5
 - Hassio (Yes/No): Supervised installation
 - alexa_media  (version from `const.py` or HA startup): 3.4.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.17.0
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: No

**Logs**
```
2020-12-07 10:57:19 WARNING (MainThread) [custom_components.alexa_media.config_flow] Unknown error: Session is closed
2020-12-07 10:57:33 WARNING (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f7a7196ff10>,), {'cookies': {'DISPLAY_DEPRECATION_BANNER_STATUS': 'false', 'x-amzn-dat-gui-client-v': '1.24.208019.0', 'gw-penalty': '10000', 'gw-timestamp': 'Mon%2C%2007%20Dec%202020%2009%3A18%3A13%20GMT'}, 'data': OrderedDict([('email', 'e***********k@g*******m'), ('password', 'REDACTED 19 CHARS'), ('url', 'amazon.com'), ('debug', True), ('scan_interval', 60), ('include_devices', ''), ('exclude_devices', "This Device,Everywhere,Upstairs,Fire TV,Maciej's Alexa Apps"), ('securitycode', '')])}): An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-12-07 10:57:33 WARNING (MainThread) [custom_components.alexa_media.config_flow] Unknown error: Session is closed
2020-12-07 10:57:33 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 172, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
result: Dict = await getattr(flow, method)(user_input)
File "/config/custom_components/alexa_media/config_flow.py", line 217, in async_step_user
await self.login.login(
File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 127, in wrapper
return await func(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 466, in login
if await self.test_loggedin(cookies):
File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 363, in test_loggedin
get_resp = await self._session.get(
File "/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/client.py", line 377, in _request
raise RuntimeError("Session is closed")
RuntimeError: Session is closed
```

**Additional context**

**Comment by cherokee93** [comment]
I  have the same problem.
Tried setting up 2FA app with no luck, I reach the point where I need to accept the notification on my phone/sms, I approve the access but the integration won't go on with the install.

Even tried the cookie way but throws me some error 🤷‍♂️
![image](https://user-images.githubusercontent.com/12370126/101340833-8bf52400-3880-11eb-80a2-357415c72f4a.png)

**Comment by alandtse** [comment]
If you remove and readd do you see the same issue? What if you restart HA? A session closed would be strange situation when your'e adding as we're creating a new session.

**Comment by alandtse** [comment]
Please also turn on advanced debugging when generating the logs.

**Comment by genem2** [comment]
FWIW: it eventually worked for me after removing the integration, restarting HA, re-adding the integration and going through ~10 captchas (these are a bear).

**Comment by alandtse** [comment]
Based on that, it sounds like a random connection error. I've found the captchas have been getting harder unfortunately.

**Comment by bieniu** [comment]
Today, when I tried to enter alexa.amazon.com page, I was forced to change my password. After that, I was able to configure the integration again.
