### ISSUE TITLE
alexapy.errors.AlexapyConnectionError in update_last_called

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#1117]
**Describe the bug**
Refresh data not working, but there is no prompt to relogin.

**To Reproduce**
1. Check log

**Expected behavior**
Working connection to retrieve updated data

**Screenshots**

**System details**
 - Home-assistant (version): 2021.1.3
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v3.5.0
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account): Yes

**Logs**
```
2021-01-20 20:43:46 WARNING (MainThread) [alexapy.helpers] alexaapi.get_activities((<alexapy.alexalogin.AlexaLogin object at 0x7f6929707c70>, 10), {}): A connection error occured: An exception of type KeyError occurred. Arguments:
('activities',)
2021-01-20 20:43:46 WARNING (MainThread) [alexapy.helpers] alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f6929707c70>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyConnectionError
 occurred. Arguments:
()
2021-01-20 20:43:46 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 141, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexaapi.py", line 1197, in get_activities
    (await response.json(content_type=None))["activities"] if response else None
KeyError: 'activities'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexawebsocket.py", line 144, in process_messages
    await self.on_message(cast(bytes, msg.data))
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexawebsocket.py", line 226, in on_message
    await self.msg_callback(message_obj)
  File "/config/custom_components/alexa_media/__init__.py", line 750, in ws_handler
    await update_last_called(login_obj, last_called)
  File "/config/custom_components/alexa_media/helpers.py", line 162, in _catch_login_errors
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/__init__.py", line 597, in update_last_called
    last_called = await AlexaAPI.get_last_device_serial(login_obj)
  File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 141, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexaapi.py", line 1230, in get_last_device_serial
    response = await AlexaAPI.get_activities(login, items)
  File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 151, in wrapper
    raise AlexapyConnectionError from ex
alexapy.errors.AlexapyConnectionError

```
**Additional context**

**Comment by alandtse** [comment]
Thanks. Already working on this. Temporary workaround is to reload the integration on the integration page. It will reconnect until the next time Amazon provides malformed data.
