### ISSUE TITLE
JSON file read failed (/alexa_media/translations/en.json)

### ISSUE THREAD

**Issue by urechi** [custom-components/alexa_media_player#1141]
HA Version: core-2021.1.5
Operating System: Home Assistant OS 5.10
Code -> Download ZIP, unzip on a MacBook Pro (MacOS Catalina 10.15.7), copy and paste the custom_components/alexa_media to config folder. Restarted HA several times, when going to Configuration -> Integrations -> + ADD INTEGRATION -> alexa_media, I get the following error:

`2021-01-24 23:37:43 ERROR (SyncWorker_5) [homeassistant.util.json] JSON file reading failed: /config/custom_components/alexa_media/translations/en.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 31, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/custom_components/alexa_media/translations/en.json'
2021-01-24 23:37:43 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548179508912] Error handling message: [Errno 20] Not a directory: '/config/custom_components/alexa_media/translations/en.json'
2021-01-24 23:37:48 ERROR (SyncWorker_6) [homeassistant.util.json] JSON file reading failed: /config/custom_components/alexa_media/translations/en.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 31, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/custom_components/alexa_media/translations/en.json'
2021-01-24 23:37:48 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548179508912] Error handling message: [Errno 20] Not a directory: '/config/custom_components/alexa_media/translations/en.json'`

**Comment by alandtse** [comment]
You didn't copy the files correctly. Use HACS or make sure the translations directory is created.

**Comment by urechi** [comment]
<img width="689" alt="Screenshot 2021-01-25 at 00 41 46" src="https://user-images.githubusercontent.com/38536263/105649059-88584380-5ea6-11eb-920a-f581899191d0.png">

The folder came as an alias from the repo, all I've done was to unzip and upload it to the config folder.
I've now created the folder manually and copied the files over. It's working now, thanks for your help.
