### ISSUE TITLE
Service Call Stopped Working

### ISSUE THREAD

**Issue by usedjeans818** [custom-components/alexa_media_player#1143]
After updating to either 3.5.2, 3.6.0, or 3.6.1, my service call to send a TTS to one of my Echo Dots stopped working.  Sorry, I'm not always using this feature and so I cannot determine exactly which update broke the functionality (and these updates were released all within 24 hours).

**The piece that broke is:**
```
  - service: notify.alexa_media_kitchen_dot
    data:
      message: This is a test
      data:
        type: tts
```

**I was able to change the code to the following to get it working again:**
```
  - service: notify.alexa_media
    data:
      target: media_player.kitchen_dot
      message: This is a test
      data:
        type: tts
```

Using the original code above now generates the following error in the logs:
```
2021-01-24 17:21:06 ERROR (MainThread) [homeassistant.components.script.echo_test] Echo Test: Error executing script. Service not found for call_service at pos 1: Unable to find service notify.alexa_media_kitchen_dot
2021-01-24 17:21:06 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1026, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 242, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 250, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 457, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1395, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service notify.alexa_media_kitchen_dot
```

I'm currently on:
Home Assistant 2021.1.5
Home Assistant OS 5.10
Alexa Media Player 3.6.1[](url)

**Comment by alandtse** [comment]
This was fixed in 3.6.2. Dupe #1138
