### ISSUE TITLE
Error while processing template: Template

### ISSUE THREAD

**Issue by isibizi** [custom-components/alexa_media_player#1191]
Hello,

after an Update, my morning routine not workng anymore. I have following message in the log

Logger: homeassistant.helpers.event
Source: helpers/template.py:355
First occurred: 17:09:44 (2 occurrences)
Last logged: 22:26:37

Error while processing template: Template("{% set alarm_time = as_timestamp(states('sensor.echo_schlafzimmer_next_alarm')) %} {% set current_time = as_timestamp(states('sensor.date_time').replace(',', '')) %} {% set pre_time = 3600 %} {{ current_time >= alarm_time - pre_time }}")
Error while processing template: Template("{% set alarm_time = as_timestamp(states('sensor.echo_dot_wohnzimmer_next_alarm')) %} {% set current_time = as_timestamp(states('sensor.date_time').replace(',', '')) %} {% set pre_time = 120 %} {{ current_time >= alarm_time - pre_time }}")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 353, in async_render
    render_result = compiled.render(kwargs)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 462, in async_render_to_info
    render_info._result = self.async_render(variables, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 355, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by alandtse** [comment]
Template issues are not problems with the component. Please use the [forum](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/) or [discussions](https://github.com/custom-components/alexa_media_player/discussions) for this.
