### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by lowrisk75** [custom-components/alexa_media_player#1208]
**Describe the bug**
after adding the custom components HACS, restarting and adding from configuration/integration, I'm getting the following error 
```
Error
Config flow could not be loaded
```
After that if go back to configuration and add integration, I don't have the list of integrations but instead I have this message with seems stuck : `Please wait while the integration is being installed`
**To Reproduce**
1. Go to 'Configuration'
2. Click on 'Add Integration'
3. Scroll down to 'Alexa_media_player'
4. install
5. See error

**Expected behavior**
ask for login details 

**System details**
 - Home-assistant ( 2021.3.3): 
 - Official image from HA for Raspberry Pi 4
 - Alexa account created just for integration, Alexa reseted with new account
 - no 2FA setup

**Logs**
```
2021-03-11 21:47:10 WARNING (MainThread) [homeassistant.loader] You are using a custom integration unifiprotect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-11 21:47:10 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-11 21:47:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration philips_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-11 21:47:15 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'philips_airpurifier'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'philips_airpurifier'
2021-03-11 21:47:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration unifigateway which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-11 21:47:15 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'unifigateway'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'unifigateway'
2021-03-11 21:47:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration samsungtv_tizen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-11 21:47:15 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'samsungtv_tizen'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'samsungtv_tizen'
2021-03-11 21:47:20 WARNING (MainThread) [homeassistant.components.light] Platform netatmo not ready yet. Retrying in 30 seconds.
2021-03-11 21:47:21 WARNING (MainThread) [homeassistant.loader] You are using a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-11 21:47:21 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up unifigateway platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f72697400>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='unifi', port=8443): Max retries exceeded with url: /api/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f72697400>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/unifigateway/sensor.py", line 84, in setup_platform
    ctrl = Controller(host, username, password, port, version='v4',
  File "/usr/local/lib/python3.8/site-packages/pyunifi/controller.py", line 89, in __init__
    self._login()
  File "/usr/local/lib/python3.8/site-packages/pyunifi/controller.py", line 137, in _login
    r = self.session.post(login_url, json=params)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='unifi', port=8443): Max retries exceeded with url: /api/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f72697400>: Failed to establish a new connection: [Errno -3] Try again'))
2021-03-11 21:47:27 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/netatmo/__init__.py", line 145, in register_webhook
    webhook_url = hass.components.webhook.async_generate_url(
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 60, in async_generate_url
    get_url(hass, prefer_external=True, allow_cloud=False),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 84, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 124, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
2021-03-11 21:48:07 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-03-11 21:48:07 ERROR (MainThread) [homeassistant.components.hue.light] Timeout fetching light data
2021-03-11 21:48:36 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-03-11 21:49:36 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-03-11 21:49:36 ERROR (MainThread) [homeassistant.components.hue.light] Timeout fetching light data
2021-03-11 21:50:36 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-03-11 21:50:36 ERROR (MainThread) [homeassistant.components.hue.light] Timeout fetching light data
2021-03-11 21:51:36 ERROR (MainThread) [homeassistant.components.hue.light] Timeout fetching light data
2021-03-11 21:51:36 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-03-11 21:52:07 ERROR (MainThread) [homeassistant.components.hue.light] Timeout fetching light data
2021-03-11 21:53:07 ERROR (MainThread) [homeassistant.components.hue.light] Timeout fetching light data
2021-03-11 21:54:24 ERROR (MainThread) [homeassistant.components.hue.light] Timeout fetching light data
2021-03-11 21:54:24 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data
2021-03-11 21:56:26 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547290481328] 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 188, in async_say_handle
    base = tts.base_url or get_url(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 117, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
2021-03-11 21:56:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547290481328] 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 188, in async_say_handle
    base = tts.base_url or get_url(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 117, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
2021-03-11 21:58:40 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 117, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 133, in async_init
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 216, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/alexa_media/config_flow.py", line 211, in async_step_user
    CONF_HASS_URL, get_url(self.hass, prefer_external=True)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 117, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
2021-03-11 22:00:27 ERROR (MainThread) [homeassistant.components.hue.light] Timeout fetching light data
2021-03-11 22:00:27 ERROR (MainThread) [homeassistant.components.hue.sensor_base] Timeout fetching sensor data

```

***Additional Context***
I'm new to home assistant, and it's very likely that the issue come from me.
also Alexa Echo is connected to a WiFi using the same VLAN (IoT VLAN) than the Raspberry Pi 4 (Home Assistant)
I setup a new amazon account with no two factor, setup the echo with this new settings but never enter the information in home assistant yet (not prompted yet)

**Comment by alandtse** [comment]
You're having massive errors from HA because it can't connect to a network. Please resolve that first as the component needs internet access to even function. I can't even tell if you properly downloaded it.

**Comment by lowrisk75** [comment]
The DNS request not been resolved was due to some amazon block on CloudFlare Team for
```
msh.amazon.co.uk
device-messaging-na.amazon.com
device-metrics-us.amazon.com

```

now that this traffic is allowed here is my logs (same issue though)
[](
21-03-12 06:12:30 INFO (MainThread) [supervisor.host.info] Updating local host information
21-03-12 06:12:31 INFO (MainThread) [supervisor.host.services] Updating service information
21-03-12 06:12:31 INFO (MainThread) [supervisor.host.network] Updating local network information
21-03-12 06:12:33 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-03-12 06:12:33 INFO (MainThread) [supervisor.host] Host information reload completed
21-03-12 06:25:54 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 257:None is not str
21-03-12 06:25:54 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-03-12 06:25:59 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-12 06:25:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-03-12 06:25:59 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-03-12 06:25:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-03-12 06:35:01 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-03-12 06:35:01 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-03-12 06:35:01 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-03-12 06:35:01 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-03-12 06:35:01 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-03-12 06:35:01 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-03-12 06:35:01 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-03-12 06:45:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
21-03-12 06:45:45 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-03-12 06:45:46 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove
21-03-12 06:45:46 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove
21-03-12 06:45:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 257:None is not str
21-03-12 06:45:59 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-03-12 06:46:04 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-03-12 06:46:04 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-03-12 06:46:04 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-03-12 07:05:54 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 257:None is not str
21-03-12 07:05:54 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-03-12 07:06:00 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-12 07:06:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-03-12 07:06:00 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-03-12 07:06:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
21-03-12 07:35:01 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-03-12 07:35:01 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-03-12 07:35:01 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-03-12 07:35:01 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-03-12 07:35:01 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-03-12 07:35:01 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-03-12 07:35:01 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-03-12 07:45:43 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-03-12 08:19:13 INFO (MainThread) [supervisor.host.info] Updating local host information
21-03-12 08:19:13 INFO (MainThread) [supervisor.host.services] Updating service information
21-03-12 08:19:14 INFO (MainThread) [supervisor.host.network] Updating local network information
21-03-12 08:19:16 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-03-12 08:19:16 INFO (MainThread) [supervisor.host] Host information reload completed
21-03-12 08:35:01 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-03-12 08:35:01 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-03-12 08:35:01 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-03-12 08:35:01 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-03-12 08:35:01 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-03-12 08:35:01 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-03-12 08:35:01 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-03-12 09:15:22 INFO (SyncWorker_0) [supervisor.docker.interface] Restarting homeassistant/raspberrypi4-64-homeassistant
21-03-12 09:15:22 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API error: Received message 8:1000 is not str
21-03-12 09:15:22 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
21-03-12 09:15:28 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-03-12 09:15:40 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-12 09:15:40 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-03-12 09:15:51 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
21-03-12 09:15:51 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-03-12 09:15:51 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
21-03-12 09:15:51 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
 
REFRESH)

**Comment by lowrisk75** [comment]
ok... might have an issue somewhere else, not from the DNS server anyway, there is no recent request denied from that host, not from DPI which I have disabled, not sure what's going on

**Comment by alandtse** [comment]
Please enable debug logs per the template.

**Comment by alandtse** [comment]
Also you need to setup the external url for HA.

**Comment by lowrisk75** [comment]
So I didn't release I had to add the parameter in the config file, I added since I read the FAQ for the logs, 
since I added/ rebooted, Alexa Media Player  is automatically detected, however the Captcha image won't load.
I checked the DNS query, no blocks, no block in the firewall neither (CloudFlare)

-- also the external url is set, I just replaced with "host.host.host" in the log for safety.

```
2021-03-12 12:37:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration unifiprotect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-12 12:37:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-12 12:37:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-12 12:37:19 WARNING (MainThread) [homeassistant.loader] You are using a custom integration philips_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-12 12:37:19 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'philips_airpurifier'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'philips_airpurifier'
2021-03-12 12:37:20 WARNING (MainThread) [homeassistant.loader] You are using a custom integration samsungtv_tizen which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-12 12:37:20 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'samsungtv_tizen'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'samsungtv_tizen'
2021-03-12 12:37:24 WARNING (MainThread) [homeassistant.components.light] Platform netatmo not ready yet. Retrying in 30 seconds.
2021-03-12 12:37:27 ERROR (MainThread) [homeassistant.components.netatmo] Error during webhook registration - 400 - Bad request - Allowed ports for webhooks are 80, 88, 443 and 9443. (21) when accessing 'https://api.netatmo.com/api/addwebhook'
2021-03-12 12:37:39 ERROR (MainThread) [frontend.js.latest.202103026] https://host.host.host:8443/config/server_control:1:72 TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('action-button more-actions-button')[0].click')
2021-03-12 12:37:39 ERROR (MainThread) [frontend.js.latest.202103026] https://host.host.host:8443/config/server_control:1:72 TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('action-button more-actions-button')[0].click')
2021-03-12 12:37:39 ERROR (MainThread) [frontend.js.latest.202103026] https://host.host.host:8443/config/server_control:1:62 TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('dialog-button negative ')[0].click')
2021-03-12 12:39:43 ERROR (MainThread) [frontend.js.latest.202103026] https://host.host.host:8443/config/server_control:1:72 TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('action-button more-actions-button')[0].click')
2021-03-12 12:39:43 ERROR (MainThread) [frontend.js.latest.202103026] https://host.host.host:8443/config/server_control:1:72 TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('action-button more-actions-button')[0].click')
2021-03-12 12:39:43 ERROR (MainThread) [frontend.js.latest.202103026] https://host.host.host:8443/config/server_control:1:62 TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('dialog-button negative ')[0].click')
2021-03-12 12:40:24 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2021-03-12 12:40:24 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.samsungtv is taking over 10 seconds
2021-03-12 12:40:36 ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream while finding first packet: Invalid data - got 7 packets with missing DTS while initializing
2021-03-12 12:41:47 ERROR (MainThread) [frontend.js.latest.202103026] https://host.host.host:8443/core_configurator/dashboard:1:72 TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('action-button more-actions-button')[0].click')
2021-03-12 12:41:47 ERROR (MainThread) [frontend.js.latest.202103026] https://host.host.host:8443/core_configurator/dashboard:1:72 TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('action-button more-actions-button')[0].click')
2021-03-12 12:41:48 ERROR (MainThread) [frontend.js.latest.202103026] https://host.host.host:8443/core_configurator/dashboard:1:62 TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('dialog-button negative ')[0].click')
2021-03-12 12:43:52 ERROR (MainThread) [frontend.js.latest.202103026] https://host.host.host:8443/core_configurator/dashboard:1:72 TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('action-button more-actions-button')[0].click')
2021-03-12 12:43:52 ERROR (MainThread) [frontend.js.latest.202103026] https://host.host.host:8443/core_configurator/dashboard:1:72 TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('action-button more-actions-button')[0].click')
2021-03-12 12:43:52 ERROR (MainThread) [frontend.js.latest.202103026] https://host.host.host:8443/core_configurator/dashboard:1:62 TypeError: undefined is not an object (evaluating 'document.getElementsByClassName('dialog-button negative ')[0].click')

```

DNS wise :

```
alexa.na.gateway.devices.a2z.com / A /ALLOW

spectrum.s3.amazonaws.com / A /ALLOW

spectrum.s3.amazonaws.com / AAAA / ALLOW

```

Do I need to attach /config/alexa_mediamy@email.comget.html
/config/alexa_mediamy@email.compost.html ?

**Comment by lowrisk75** [comment]
so somehow the captcha is now working, I'm prompted to open an external website, I'm received a OTP code via email and I'm redirected to 
```
Looking for Something?
We're sorry. The Web address you entered is not a functioning page on our site
 Go to Amazon.com's Home Page
```
assuming because I'm in Ireland and my device is probably registered to .co.uk instead of .com

**Comment by lowrisk75** [comment]
I give up
