### ISSUE TITLE
Integration tries to connect to the non-existent alexa.amazon.pl

### ISSUE THREAD

**Issue by bieniu** [custom-components/alexa_media_player#1212]
**Describe the bug**
During configuration, the integration tries to connect to the non-existent `alexa.amazon.pl` host and it is impossible to complete the configuration.

**To Reproduce**
1. Start config flow and enter email/password (I use `amazon.com` as region domain as always):

![image](https://user-images.githubusercontent.com/478555/111026450-9b898900-83ea-11eb-9471-407ffa756629.png)

2. After click `Submit`, URL `https://MY_HA_DOMAIN/auth/alexamedia/proxy?config_flow_id=0f9bc988cb4d44ceb19f2fef1463dd68&callback_url=https://MY_HA_DOMAIN/auth/alexamedia/callback?flow_id%3D0f9bc988cb4d44ceb19f2fef1463dd68` is opened in the browser and I have to login twice

![image](https://user-images.githubusercontent.com/478555/111026577-29fe0a80-83eb-11eb-8a26-4a745b7701e9.png)

3. I get `Success! This window can be closed` info but on HA I still have this:

![image](https://user-images.githubusercontent.com/478555/111026546-0a66e200-83eb-11eb-97ef-47a19beb6897.png)

4. After those steps I have in log this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/connector.py", line 999, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/connector.py", line 865, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 172, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 141, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 158, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 216, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/alexa_media/config_flow.py", line 405, in async_step_finish_proxy
    if await self.login.test_loggedin():
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 476, in test_loggedin
    get_resp = await self._session.get(
  File "/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
alexapy.aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host alexa.amazon.pl:443 ssl:default [Name does not resolve]
```
The Polish version of Amazon has been operating since the beginning of March, but the host `alexa.amazon.pl` is not available.

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): core-2021.3.4
 - Hassio (Yes/No): No, Supervised installation
 - alexa_media  (version from `const.py` or HA startup): 3.8.4
 - alexapy (version from `pip show alexapy` or HA startup): 1.24.4
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: No

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
Can you check your `configuration.yaml` to confirm there's not an entry please? The url is coming from the configuration and not the component.

**Comment by bieniu** [comment]
Yes, I'm 100% sure I don't have `alexa_media_player` in `configuration.yaml` file. The integration was working properly until yesterday. Today I removed config entry and now I can't reconfigure the integration.

**Comment by alandtse** [comment]
Odd. Can you check your .storage/config_entries.json and see what url is listed under there? I'll look at the code again but I'm pretty sure we're not generating the domain url.

**Comment by bieniu** [comment]
Config flow doesn't end so I don't have config entry for `alexa_media`.

**Comment by bieniu** [comment]
Strange, I restarted my server and after that the config flow ends with success. I'm totally confused.

**Comment by alandtse** [comment]
Me too. I'll keep this open for a bit to see if it comes back. I'll also recheck the code.

**Comment by bieniu** [comment]
I tried to reproduce this once again but so far without success.

**Comment by alandtse** [comment]
I'll close this for now. Please reopen if you see it happen again. I checked the code again and the domain is taken from user input.
