### ISSUE TITLE
error after HA restart increasing

### ISSUE THREAD

**Issue by Pirol62** [custom-components/alexa_media_player#1223]
**Describe the bug**
After HA restart the following error is in the log

**System details**
 - Home-assistant (version): 2021.3.4
 - Hassio (Yes/No): yes

 - alexa_media  (version from `const.py` or HA startup): latest
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). yes

**Logs**
````
Logger: homeassistant.config_entries
Source: custom_components/alexa_media/__init__.py:305
First occurred: 15:03:49 (1 occurrences)
Last logged: 15:03:49

Error setting up entry post@joerg-nauen.de - amazon.de for alexa_media
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 144, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 574, in login
    if await self.test_loggedin(cookies):
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 452, in test_loggedin
    await self.get_tokens()
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 755, in get_tokens
    response = await self._session.post(
  File "/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/streams.py", line 604, in read
    await self._waiter
alexapy.aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/alexa_media/__init__.py", line 305, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 154, in wrapper
    raise AlexapyConnectionError from ex
alexapy.errors.AlexapyConnectionError
````

**Additional context**
I have to restart 3 to 4 times before it loads without issues

**Comment by alandtse** [comment]
Amazon is disconnecting you. Not much we can do about it. Try relogging in.

**Comment by Pirol62** [comment]
OK, understood. What causes Amazon to throw me out?
Interesting thing is, that after the 3rd or 4th try it works.
Is there something which initiates this behavior?
I executed a Host restart yesterday which led to trouble with deConz. During the try to update, I restarted quite often. Could it be that this forced Amazon to thew me out?

**Comment by alandtse** [comment]
It's all a guess on what would trigger a server disconnect. It could be the multiple connections but only amazon knows for certain.

**Comment by Pirol62** [comment]
OK thanks. I close this.
