### ISSUE TITLE
Error installing the integration component

### ISSUE THREAD

**Issue by MarcoFranchi** [custom-components/alexa_media_player#1265]
I have re-installed Alexa Alexa Media Player from HACS without any problem, when I try to install the integration from configuration --> integration I have this message "Config flow could not be loaded" after that I find this error in al log
"AttributeError: module 'pyotp' has no attribute 'TOTP' "
all done in Home Assistant 2021.4.6 installed on Odroid N2+ 
Note before the re-installation of alexa media player integration all worked fine.

any idea? where can I start for the investigations?

this is a complete log

`Logger: aiohttp.server
Source: custom_components/alexa_media/__init__.py:16
First occurred: 3:33:07 PM (1 occurrences)
Last logged: 3:33:07 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 120, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 573, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 485, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.8/site-packages/alexapy/__init__.py", line 16, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexaapi.py", line 23, in <module>
    from .alexalogin import AlexaLogin
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 49, in <module>
    class AlexaLogin:
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 221, in AlexaLogin
    def set_totp(self, otp_secret: Text) -> Optional[pyotp.TOTP]:
AttributeError: module 'pyotp' has no attribute 'TOTP'`

**Comment by alandtse** [comment]
Something changed the version of pyotp on your system.

**Comment by MarcoFranchi** [comment]
MMmm I haven't change anything , how can i check or update this component?
my Python Version is 3.8.7 on core-2021.4.6

**Comment by alandtse** [comment]
```console
pip list | grep pyotp
pyotp                            2.3.0
```

The component needs at least 2.4.1. It appears HA is installing an older version.

**Comment by janfajessen** [comment]
Same for me, impossible to reconfigure Alexa. I try to change password, like every two weeks...but nothing. It say there is a problem, but I don't know what problem.
It's possible that's caused by the new version?

**Comment by alandtse** [comment]
Pyotp 2.3.0 has been there since 2019. Remove and readd the component or manually upgrade.

```console
pip install pyotp~=2.4.1
```

**Comment by MarcoFranchi** [comment]
in hassio with tool "ssh & Web Terminal"  I not look pyopt installed,   I have installed it as alandtse said but the problem remain.. 
where and how can I install the pyotp 2.4.1? I'm newbie sorry.
