### ISSUE TITLE
Remove Alexa Media Integration Error

### ISSUE THREAD

**Issue by mikebol** [custom-components/alexa_media_player#1276]
I have the Alexa Media integration loaded today, all appears to be working but I find I simply do not use it like I had intended. In my attempt to uninstall the integration, I receive this error below. What can I do to either resolve this or cleanly uninstall the integration?  (2021.4.6)

```
Logger: aiohttp.server
Source: loader.py:477
First occurred: 3:03:31 PM (2 occurrences)
Last logged: 3:17:16 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 70, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 684, in async_remove
    unload_success = await self.async_unload(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 786, in async_unload
    return await entry.async_unload(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 331, in async_unload
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 477, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.alexa_media'

```

**Comment by alandtse** [comment]
You need to uninstall from integrations before deleting the files or removing from HACS.
