### ISSUE TITLE
Error Non-base32 digit found

### ISSUE THREAD

**Issue by galtamur** [custom-components/alexa_media_player#1328]
**Describe the bug**
I am using alexa_media_player integration since months without issues, but today, at the startup of HA, it started providing the  error message "alexapy.errors.AlexapyPyotpInvalidKey: Non-base32 digit found".
The integration (Configuration-Integrations page) shows "Failed to set up".
The service notify.alexa<my echo> is not created.
The HA log shows:
Traceback (most recent call last):

  File "/srv/homeassistant/lib/python3.9/site-packages/alexapy/alexalogin.py", line 235, in set_totp
    self.get_totp_token()
  File "/srv/homeassistant/lib/python3.9/site-packages/alexapy/alexalogin.py", line 259, in get_totp_token
    token: Text = self._totp.now()
  File "/srv/homeassistant/lib/python3.9/site-packages/pyotp/totp.py", line 44, in now
    return self.generate_otp(self.timecode(datetime.datetime.now()))
  File "/srv/homeassistant/lib/python3.9/site-packages/pyotp/otp.py", line 33, in generate_otp
    hasher = hmac.new(self.byte_secret(), self.int_to_bytestring(input), self.digest)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyotp/otp.py", line 50, in byte_secret
    return base64.b32decode(self.secret, casefold=True)
  File "/usr/local/lib/python3.9/base64.py", line 231, in b32decode
    raise binascii.Error('Non-base32 digit found') from None
binascii.Error: Non-base32 digit found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/__init__.py", line 303, in async_setup_entry
    AlexaLogin(
  File "/srv/homeassistant/lib/python3.9/site-packages/alexapy/alexalogin.py", line 119, in __init__
    self.set_totp(otp_secret.replace(" ", ""))
  File "/srv/homeassistant/lib/python3.9/site-packages/alexapy/alexalogin.py", line 241, in set_totp
    raise AlexapyPyotpInvalidKey(ex) from ex
alexapy.errors.AlexapyPyotpInvalidKey: Non-base32 digit found

**To Reproduce**
Restart Home Assistant Core or rebooting the Raspberry, the error is there.

**Expected behavior**
I just don't expect the error, the integration to come up and the service to be created normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/65424984/122886823-966c9c00-d340-11eb-946d-24686260cdd9.png)
![image](https://user-images.githubusercontent.com/65424984/122886979-b8feb500-d340-11eb-96ff-29a9ebdaddeb.png)

**System details**
 - Home-assistant (version): 2021.6.5
 - Hassio (Yes/No): No.
 - alexa_media  (version from `const.py` or HA startup): 3.10.6
 - alexapy (version from `pip show alexapy` or HA startup): unknown
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: yes

**Logs**
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/alexapy/alexalogin.py", line 235, in set_totp
    self.get_totp_token()
  File "/srv/homeassistant/lib/python3.9/site-packages/alexapy/alexalogin.py", line 259, in get_totp_token
    token: Text = self._totp.now()
  File "/srv/homeassistant/lib/python3.9/site-packages/pyotp/totp.py", line 44, in now
    return self.generate_otp(self.timecode(datetime.datetime.now()))
  File "/srv/homeassistant/lib/python3.9/site-packages/pyotp/otp.py", line 33, in generate_otp
    hasher = hmac.new(self.byte_secret(), self.int_to_bytestring(input), self.digest)
  File "/srv/homeassistant/lib/python3.9/site-packages/pyotp/otp.py", line 50, in byte_secret
    return base64.b32decode(self.secret, casefold=True)
  File "/usr/local/lib/python3.9/base64.py", line 231, in b32decode
    raise binascii.Error('Non-base32 digit found') from None
binascii.Error: Non-base32 digit found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/__init__.py", line 303, in async_setup_entry
    AlexaLogin(
  File "/srv/homeassistant/lib/python3.9/site-packages/alexapy/alexalogin.py", line 119, in __init__
    self.set_totp(otp_secret.replace(" ", ""))
  File "/srv/homeassistant/lib/python3.9/site-packages/alexapy/alexalogin.py", line 241, in set_totp
    raise AlexapyPyotpInvalidKey(ex) from ex
alexapy.errors.AlexapyPyotpInvalidKey: Non-base32 digit found

**Additional context**

**Comment by alandtse** [comment]
Your Built-in 2FA App Key is invalid. Remove the integration and readd and reenter it.
