### ISSUE TITLE
Setup failed for alexa_media: unknown error

### ISSUE THREAD

**Issue by balkonrad** [custom-components/alexa_media_player#1329]
**Describe the bug**
Logger: homeassistant.setup
Source: custom_components/alexa_media/__init__.py:16
Integration: Alexa Media Player (documentation, issues)
First occurred: 8:55:41 (1 occurrences)
Last logged: 8:55:41

Setup failed for alexa_media: unknown error

**To Reproduce**
1. Execute home assistant
2. See error in logs

**Expected behavior**
alexa_media should work

**Screenshots**
![image](https://user-images.githubusercontent.com/6885412/123051181-cb8cf300-d401-11eb-895b-9a3bd7949164.png)

**System details**
 - Home-assistant (version): 2021.6.6
 - Hassio (Yes/No):  Yes
 - alexa_media  (version from `const.py` or HA startup): 3.8
 - alexapy (version from `pip show alexapy` or HA startup): N/A
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  Yes

**Logs**
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 200, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.8/site-packages/alexapy/__init__.py", line 16, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexaapi.py", line 23, in <module>
    from .alexalogin import AlexaLogin
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 49, in <module>
    class AlexaLogin:
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 221, in AlexaLogin
    def set_totp(self, otp_secret: Text) -> Optional[pyotp.TOTP]:
AttributeError: module 'pyotp' has no attribute 'TOTP'

**Comment by alandtse** [comment]
Please use the latest version of the component. 3.8 is unsupported.
