### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes when using Echo Flex usb night lamp

### ISSUE THREAD

**Issue by ravens** [custom-components/alexa_media_player#1334]
**Describe the bug**
After configuring a connected Echo flex night light to appears in home assistant, the light entity is generating errors when trying to power on/off, or change the color. There is a " TypeError: can't compare offset-naive and offset-aware datetimes" in Homeassistant logs.

**To Reproduce**
0. configure echo device in the integration with an Echo Flex and a usb night light
1. let the new light.* entity appears 
2. try to change settings

**Expected behavior**
When changing settings I expect the light to turn off/on and to change color /intensity. 

**Screenshots**

**System details**
 - Home-assistant (version): 2021.7.1
 - Hassio (Yes/No): no.
 - alexa_media  (version from `const.py` or HA startup): 3.10.6
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.1
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: y

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alexa_media/alexa_entity.py:329 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 12:58:32 (1 occurrences) 
Last logged: 12:58:32

[140460486322112] can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 811, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 458, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/alexa_media/light.py", line 329, in async_turn_on
    await self._set_state(True, brightness, mired, hs)
  File "/config/custom_components/alexa_media/light.py", line 317, in _set_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 453, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 425, in _stringify_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 827, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/alexa_media/light.py", line 215, in is_on
    power = parse_power_from_coordinator(
  File "/config/custom_components/alexa_media/alexa_entity.py", line 277, in parse_power_from_coordinator
    return parse_value_from_coordinator(
  File "/config/custom_components/alexa_media/alexa_entity.py", line 305, in parse_value_from_coordinator
    if is_cap_state_still_acceptable(cap_state, since):
  File "/config/custom_components/alexa_media/alexa_entity.py", line 329, in is_cap_state_still_acceptable
    return time_of_sample >= since
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Additional context**

**Comment by 86lava** [comment]
I am getting a similar errors:  
  
**Failed to call service light/turn_off(turn_on). can't compare offset-naive and offset-aware datetimes**  
  
Every time I command the HA UI to execute an OFF, or ON command to any of the 6 zigbee devices that are paired to my Echo Plus.  The first time for the ON and for the OFF command in HA gets executed, though the error message appears.  After that, only the error message.  These entities in HA also get updated when Alexa changes the states via voice commands any number of times, until a command is issued from HA.  I have enabled logging as explained elsewhere in this topic, but i see no evidence of commands related to ON/OFF/DIMMING commands to the devices in question.
[home-assistant.log.txt](https://github.com/custom-components/alexa_media_player/files/6813258/home-assistant.log.txt)

**Comment by christippett** [comment]
I've been running into the same problem. I've raised a PR (#1338) to fix the issue - since updating my local instance of Home Assistant things are back working again.

**Comment by 86lava** [comment]
I updated my local instance of HA as well, but no luck after restarting twice. Also updated my original comment to include technical details.

**Comment by 86lava** [comment]
Saw the update for the integration 30 minutes ago. Installed it and evaluated my issues. Happy to report that all is well.  Thank you for the quick and thorough resolution.  Will duplicate this comment in #1338
