### ISSUE TITLE
Setup failed for alexa_media

### ISSUE THREAD

**Issue by herbert-roth** [custom-components/alexa_media_player#1336]
Setup failed for alexa_media: unknown error

Core Version: 2021.7.1
Supervisor: 2021.06.8
alexa_media_player version: 3.10.6
Amazon 2FA is enabled (y/n). We will not debug login issues if unanswered: Yes

Logger: homeassistant.setup
Source: custom_components/alexa_media/__init__.py:16 
Integration: Alexa Media Player (documentation, issues) 
First occurred: 8:00:14 (1 occurrences) 
Last logged: 8:00:14

Setup failed for alexa_media: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 201, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 490, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/__init__.py", line 16, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 23, in <module>
    from .alexalogin import AlexaLogin
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 49, in <module>
    class AlexaLogin:
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 221, in AlexaLogin
    def set_totp(self, otp_secret: Text) -> Optional[pyotp.TOTP]:
AttributeError: module 'pyotp' has no attribute 'TOTP'

**Comment by alandtse** [comment]
Remove and readd the component in HACS. The pyotp dependency failed to install properly.
