### ISSUE TITLE
Can't compare offset-naive and offset-aware datetimes - Bluetooth device

### ISSUE THREAD

**Issue by wkethman** [custom-components/alexa_media_player#1349]
**Describe the bug**
After configuring a connected Sengled bluetooth light to appear in Home Assistant, the light entity is generated and can be controlled once (the error occurs after initiating the first command), however, thereafter, the device does not respond and generates errors when trying to power on/off, or change the color. There is a " TypeError: can't compare offset-naive and offset-aware datetimes" in Homeassistant logs.

**To Reproduce**
1. Configure Sengled light device (bluetooth) in the Alexa app
2. After configuring the Alexa Media Player integration, select "Include devices connected via Echo"
3. Wait for the new light entity to appear in Home Assistant
4. Attempt to control the devie

**Expected behavior**
When changing settings I expect the light to turn off/on and to change color/intensity as it does through the Alexa app.

**Screenshots**

**System details**
 - Home-assistant (version): 2021.6.3
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 3.10.6
 - alexapy (version from `pip show alexapy` or HA startup): 
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**

> Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alexa_media/alexa_entity.py:329
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 18:39:03 (4 occurrences)
Last logged: 18:39:21

>[139889474582080] can't compare offset-naive and offset-aware datetimes

>Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service await hass.services.async_call( File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call task.result() File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service await handler.job.target(service_call) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service await self.hass.helpers.service.entity_service_call( File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call future.result() # pop exception if have File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call await coro File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call await result File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 417, in async_handle_light_on_service await light.async_turn_on(**filter_turn_on_params(light, params)) File "/config/custom_components/alexa_media/light.py", line 329, in async_turn_on await self._set_state(True, brightness, mired, hs) File "/config/custom_components/alexa_media/light.py", line 317, in _set_state self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state state = self._stringify_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state state = self.state File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 772, in state return STATE_ON if self.is_on else STATE_OFF File "/config/custom_components/alexa_media/light.py", line 215, in is_on power = parse_power_from_coordinator( File "/config/custom_components/alexa_media/alexa_entity.py", line 277, in parse_power_from_coordinator return parse_value_from_coordinator( File "/config/custom_components/alexa_media/alexa_entity.py", line 305, in parse_value_from_coordinator if is_cap_state_still_acceptable(cap_state, since): File "/config/custom_components/alexa_media/alexa_entity.py", line 329, in is_cap_state_still_acceptable return time_of_sample >= since TypeError: can't compare offset-naive and offset-aware datetimes

**Additional context**
Similar issue: https://github.com/custom-components/alexa_media_player/issues/1334

**Comment by wkethman** [comment]
I thought I was using the most up-to-date version. Wasn't
