### ISSUE TITLE
problem with notify service

### ISSUE THREAD

**Issue by pilot1981** [custom-components/alexa_media_player#1358]
**Describe the bug**
Hi,
I'm trying to use notify service but I receive error: Fallita chiamata a servizio notify.alexa_media

**To Reproduce**
1. Go to 'developer tool'
2. Click on 'service'
3. use service notify.alexa_media
4. write message in message value
5. call service

**Expected behavior**
I would Echo device speak with my message

**Screenshots**
![image](https://user-images.githubusercontent.com/46350465/130810882-93999e63-6f85-480c-99e1-875dad81856f.png)

**System details**
 - Home-assistant (version): core2021.8.8
 - Hassio (Yes/No): YES
 - alexa_media  (version from `const.py` or HA startup): 3.10.8
 - alexapy (version from `pip show alexapy` or HA startup): NA
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: YES

**Logs**
2021-08-25 16:27:17 DEBUG (MainThread) [custom_components.alexa_media] Nothing to import from configuration.yaml, loading from Integrations
2021-08-25 16:27:20 INFO (MainThread) [custom_components.alexa_media]
-------------------------------------------------------------------
alexa_media
Version: 3.10.8
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/alexa_media_player/issues
-------------------------------------------------------------------
2021-08-25 16:27:20 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==1.25.1
2021-08-25 16:27:24 DEBUG (MainThread) [custom_components.alexa_media.helpers] d*************i@g*******m: Returning uuid {'uuid': 'eb6247dfd14874a51f19f88b2c818499', 'index': 0}
2021-08-25 16:27:35 DEBUG (MainThread) [custom_components.alexa_media] Testing login status: {'login_successful': True}
2021-08-25 16:27:35 DEBUG (MainThread) [custom_components.alexa_media] Setting up Alexa devices for d*************i@g*******m
2021-08-25 16:27:35 DEBUG (MainThread) [custom_components.alexa_media] d*************i@g*******m: Websocket created: <alexapy.alexawebsocket.WebsocketEchoClient object at 0x704f3088>
2021-08-25 16:27:37 DEBUG (MainThread) [custom_components.alexa_media] d*************i@g*******m: Websocket successfully connected
2021-08-25 16:27:37 DEBUG (MainThread) [custom_components.alexa_media] d*************i@g*******m: Creating coordinator
2021-08-25 16:27:37 DEBUG (MainThread) [custom_components.alexa_media] d*************i@g*******m: Refreshing coordinator
2021-08-25 16:27:38 DEBUG (MainThread) [custom_components.alexa_media] Alexa entities have been loaded. Prepared for discovery.
2021-08-25 16:27:38 DEBUG (MainThread) [custom_components.alexa_media] d*************i@g*******m: Found 4 devices, 4 bluetooth
2021-08-25 16:27:39 DEBUG (MainThread) [custom_components.alexa_media] d*************i@g*******m: Updated 4 notifications for 2 devices at 2021-08-25 16:27:39.377333+02:00
2021-08-25 16:27:41 DEBUG (MainThread) [custom_components.alexa_media] d*************i@g*******m: Updated last_called: {'serialNumber': 'G************LXD', 'timestamp': 1629692108052, 'summary': 'riproduci stazione relax su amazon music'}
2021-08-25 16:27:41 DEBUG (MainThread) [custom_components.alexa_media] d*************i@g*******m: last_called changed: to {'serialNumber': 'G************LXD', 'timestamp': 1629692108052, 'summary': 'riproduci stazione relax su amazon music'}
2021-08-25 16:27:41 DEBUG (MainThread) [custom_components.alexa_media] Echo Sala da pranzo: Locale it-it timezone Europe/Rome
2021-08-25 16:27:41 DEBUG (MainThread) [custom_components.alexa_media] Echo Sala da pranzo: DND True
2021-08-25 16:27:41 DEBUG (MainThread) [custom_components.alexa_media] d*************i@g*******m: Existing: [] New: ['Echo Sala da pranzo']; Filtered out by not being in include: ['Fire TV Stick Annarita', 'This Device', "daniele's Alexa Apps"] or in exclude: []
2021-08-25 16:27:41 DEBUG (MainThread) [custom_components.alexa_media] Loading config entry for media_player
2021-08-25 16:27:41 DEBUG (MainThread) [custom_components.alexa_media] Finished fetching alexa_media data in 3.857 seconds
2021-08-25 16:27:45 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Trying with limit 5 delay 2 catch_exceptions True
2021-08-25 16:27:45 DEBUG (MainThread) [custom_components.alexa_media.notify] d*************i@g*******m: Media player G************LXD not loaded yet; delaying load
2021-08-25 16:27:45 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Try: 1/5 after waiting 0 seconds result: False
2021-08-25 16:27:45 DEBUG (MainThread) [custom_components.alexa_media.media_player] d*************i@g*******m: Refreshing <Entity Echo Sala da pranzo: standby>
2021-08-25 16:27:45 DEBUG (MainThread) [custom_components.alexa_media.media_player] d*************i@g*******m: Echo Sala da pranzo: Last_called check: self: G************LXD reported:
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.helpers] d*************i@g*******m: Adding [<Entity Echo Sala da pranzo: standby>]
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.media_player] d*************i@g*******m: Loading notify
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.media_player] d*************i@g*******m: Loading config entry for switch
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.media_player] d*************i@g*******m: Loading config entry for sensor
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.media_player] d*************i@g*******m: Loading config entry for alarm_control_panel
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.media_player] d*************i@g*******m: Loading config entry for light
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.switch] d*************i@g*******m: Loading switches
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.switch] d*************i@g*******m: Found G************LXD dnd switch with status: True
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.switch] d*************i@g*******m: Found G************LXD shuffle switch with status: False
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.switch] d*************i@g*******m: Found G************LXD repeat switch with status: False
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.helpers] d*************i@g*******m: Excluding device: <Entity Echo Sala da pranzo do not disturb switch: on>
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.helpers] d*************i@g*******m: Excluding device: <Entity Echo Sala da pranzo shuffle switch: off>
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.helpers] d*************i@g*******m: Excluding device: <Entity Echo Sala da pranzo repeat switch: off>
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.sensor] d*************i@g*******m: Loading sensors
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.sensor] d*************i@g*******m: Found G************LXD Alarm sensor (0) with next: None
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.sensor] d*************i@g*******m: Found G************LXD Timer sensor (0) with next: None
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.sensor] d*************i@g*******m: Found G************LXD Reminder sensor (4) with next: None
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.helpers] d*************i@g*******m: Excluding device: <Entity Echo Sala da pranzo next Alarm: None>
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.helpers] d*************i@g*******m: Excluding device: <Entity Echo Sala da pranzo next Timer: None>
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.helpers] d*************i@g*******m: Excluding device: <Entity Echo Sala da pranzo next Reminder: None>
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.alarm_control_panel] daniele.velardi@gmail.com: No Alexa Guard entity found
2021-08-25 16:27:46 DEBUG (MainThread) [custom_components.alexa_media.alarm_control_panel] d*************i@g*******m: Skipping creation of uninitialized device: None
2021-08-25 16:27:49 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Try: 2/5 after waiting 4 seconds result: <custom_components.alexa_media.notify.AlexaNotificationService object at 0x68380ee0>
2021-08-25 16:27:49 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Trying with limit 5 delay 2 catch_exceptions True
2021-08-25 16:27:49 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Try: 1/5 after waiting 0 seconds result: <custom_components.alexa_media.notify.AlexaNotificationService object at 0x67b12898>
2021-08-25 16:27:56 DEBUG (MainThread) [custom_components.alexa_media.media_player] d*************i@g*******m: Refreshing <Entity Echo Sala da pranzo: standby>
2021-08-25 16:27:56 DEBUG (MainThread) [custom_components.alexa_media.media_player] d*************i@g*******m: Echo Sala da pranzo: Last_called check: self: G************LXD reported: G************LXD
2021-08-25 16:27:56 DEBUG (MainThread) [custom_components.alexa_media.media_player] d*************i@g*******m: Refreshing notify targets
2021-08-25 16:27:56 DEBUG (MainThread) [custom_components.alexa_media.notify] d*************i@g*******m: Creating last_called target last_called using <Entity Echo Sala da pranzo: standby>
2021-08-25 16:27:56 DEBUG (MainThread) [custom_components.alexa_media.notify] d*************i@g*******m: Creating last_called target last_called using <Entity Echo Sala da pranzo: standby>
2021-08-25 16:28:01 DEBUG (MainThread) [custom_components.alexa_media.media_player] d*************i@g*******m: Disabling polling for Echo Sala da pranzo
2021-08-25 16:28:02 DEBUG (MainThread) [custom_components.alexa_media] Completing remaining startup tasks.
2021-08-25 16:28:12 DEBUG (MainThread) [custom_components.alexa_media] Refreshing notify targets
2021-08-25 16:28:12 DEBUG (MainThread) [custom_components.alexa_media.notify] d*************i@g*******m: Creating last_called target last_called using <Entity Echo Sala da pranzo: standby>
2021-08-25 16:28:12 DEBUG (MainThread) [custom_components.alexa_media.notify] d*************i@g*******m: Creating last_called target last_called using <Entity Echo Sala da pranzo: standby>
2021-08-25 16:29:16 DEBUG (MainThread) [custom_components.alexa_media.notify] Message: benvenuti a casa velardi, kwargs: {'data': None}
2021-08-25 16:29:16 DEBUG (MainThread) [custom_components.alexa_media.notify] Target type: <class 'NoneType'>
2021-08-25 16:29:34 DEBUG (MainThread) [custom_components.alexa_media.notify] Message: benvenuti a casa velardi, kwargs: {'target': ['media_player.echo_sala_da_pranzo'], 'data': None}
2021-08-25 16:29:34 DEBUG (MainThread) [custom_components.alexa_media.notify] Target type: <class 'list'>
2021-08-25 16:29:34 DEBUG (MainThread) [custom_components.alexa_media.notify] Processing: media_player.echo_sala_da_pranzo
2021-08-25 16:29:34 DEBUG (MainThread) [custom_components.alexa_media.notify] Processed Target by string: ['media_player.echo_sala_da_pranzo']
**Additional context**

**Comment by stevewrightnz** [comment]
I've got the same issue.

This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/alexa_media/notify.py:216
Integration: Alexa Media Player (documentation, issues)
First occurred: 12:23:51 PM (1 occurrences)
Last logged: 12:23:51 PM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 159, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 216, in async_send_message
    if data["type"] == "tts":
TypeError: 'NoneType' object is not subscriptable

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alexa_media/notify.py:216
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:23:51 PM (1 occurrences)
Last logged: 12:23:51 PM

[547879104960] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 525, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 159, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 216, in async_send_message
    if data["type"] == "tts":
TypeError: 'NoneType' object is not subscriptable

**Comment by stevewrightnz** [comment]
Give this a go.  It was pointed out by a helpful person on discord that I only had half the equation when I was doing what you are doing and getting similar errors. 

You will probably need to jump into YAML mode to see what's going on.

![image](https://user-images.githubusercontent.com/2554268/131204540-49473f70-4eda-4885-a90f-522e5d111d04.png)

**Comment by link82** [comment]
Thank you @stevewrightnz!
It worked perfectly for me too.

**Comment by pilot1981** [comment]
worked also for me! thanks so much @stevewrightnz
