### ISSUE TITLE
unavailable - failed text to speech 

### ISSUE THREAD

**Issue by elifqaoui** [custom-components/alexa_media_player#1363]
Hi all,
I install the Alexa media player (from HACS) and add it in integration whitout a problem.
in my Dashbord, i use the Media Control card and add the alexa media player entity_id.
```
type: media-control
entity: media_player.hicham_echo_show
```
once done, i get in the dashbord, **Unvailable**:
echo show error and text to speech, failed too.
![image](https://user-images.githubusercontent.com/68011710/132018042-ebd552d0-220f-4cdd-812e-74fe5c4f7960.png)

the erros in logs are :confused:

Copy to clipboard

```
[547427154144] Error handling message: Unknown error
7:12:21 PM – (ERROR) Home Assistant WebSocket API (custom integration)
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable
7:12:21 PM – (ERROR) Alexa Media Player (custom integration)
Sorry, text to speech can only be called with the notify.alexa_media service. Please see the alexa_media wiki for details.https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component#use-the-notifyalexa_media-service
7:11:18 PM – (WARNING) Alexa Media Player (custom integration) - message first occurred at 7:10:48 PM and shows up 3 times`
```

I tried also to call service **Notify.alexa_media_hicham_echo_show**, 
```
service: notify.alexa_media_hicham_echo_show
data: 
  message : 'This is a test'
```
I got "unkown error"
in logs:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alexa_media/notify.py:216
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:08:45 PM (1 occurrences)
Last logged: 1:08:45 PM

[547704035216] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 525, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 159, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 216, in async_send_message
    if data["type"] == "tts":
TypeError: 'NoneType' object is not subscriptable
```
any ideas to resolve this ?
Thanks you

**Comment by jusplainmike** [comment]
same issue, I am still able to use the TTS using the mini media player card but can't do tts from service call. Same error message as above.

**Comment by jusplainmike** [comment]
#1358 This is the fix

**Comment by fschaeck** [comment]
Or you do:

    service: notify.alexa_media_hicham_echo_show
    data: 
      message : 'This is a test'
        data:
          type: tts

So that part is kinda your fault ;-)

But the fact, that the text-to-speech-field in the media player's detail window isn't working remains true.

**Comment by elifqaoui** [comment]
> service: notify.alexa_media_hicham_echo_show
> data: 
>   message : 'This is a test'
>   data:
>     type: tts

Thanks **Frank** & **Mike** for your feedback.
i tried both solution, the problem right now is the media player has an **unavailable** statut, sometime it change to **standby**, by just after it become again **unavailable**.

**Comment by alandtse** [comment]
Please fill out the template.

**Comment by alandtse** [comment]
We can try to help you once you fill out the template.
