### ISSUE TITLE
Incorrect padding

### ISSUE THREAD

**Issue by Molodax** [custom-components/alexa_media_player#1402]
**Describe the bug**
After update Home Assistant to 2021.11.x I'm getting this error and the integration fails to set up. Restarts or reinstall of the component do not solve the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 2021.11
 - Hassio (Yes/No): Yes (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 3.10.10
 - alexapy (version from `pip show alexapy` or HA startup): 
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/alexa_media/__init__.py:303
Integration: Alexa Media Player (documentation, issues)
First occurred: 12:12:27 (1 occurrences)
Last logged: 12:12:27

Error setting up entry xxx@xxx.xx - amazon.co.uk for alexa_media
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 235, in set_totp
    self.get_totp_token()
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 259, in get_totp_token
    token: Text = self._totp.now()
  File "/usr/local/lib/python3.9/site-packages/pyotp/totp.py", line 51, in now
    return self.generate_otp(self.timecode(datetime.datetime.now()))
  File "/usr/local/lib/python3.9/site-packages/pyotp/otp.py", line 26, in generate_otp
    hasher = hmac.new(self.byte_secret(), self.int_to_bytestring(input), self.digest)
  File "/usr/local/lib/python3.9/site-packages/pyotp/otp.py", line 44, in byte_secret
    return base64.b32decode(secret, casefold=True)
  File "/usr/local/lib/python3.9/base64.py", line 235, in b32decode
    raise binascii.Error('Incorrect padding')
binascii.Error: Incorrect padding

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/alexa_media/__init__.py", line 303, in async_setup_entry
    AlexaLogin(
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 119, in __init__
    self.set_totp(otp_secret.replace(" ", ""))
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 241, in set_totp
    raise AlexapyPyotpInvalidKey(ex) from ex
alexapy.errors.AlexapyPyotpInvalidKey: Incorrect padding

**Additional context**

**Comment by alandtse** [comment]
The 2FA-Key that is being provided has invalid input.

**Comment by Molodax** [comment]
> The 2FA-Key that is being provided has invalid input.

Is any way to resolve it? The component fails to startup now while it was working with 2FA flawlessly up to a year.

**Comment by alandtse** [comment]
Remove or readd the integration or edit /config/.storage/core.config_entries and clear the entry under `otp_secret`.

**Comment by Molodax** [comment]
OK, thanks. Remove/readd helped to resolve it.
