### ISSUE TITLE
Alexa media fails to load in Home assistant dev (2021.12)

### ISSUE THREAD

**Issue by Petro31** [custom-components/alexa_media_player#1403]
**Describe the bug**
In the daily/dev build, alexa media player fails to load.  It seems something in the backend changed.  I updated to the current daily (11/6) and this error is in the logs:
```
2021-11-07 05:04:27 ERROR (MainThread) [homeassistant.setup] Setup failed for alexa_media: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 206, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/__init__.py", line 16, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 21, in <module>
    from alexapy.aiohttp import ClientConnectionError, ClientResponse
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
```

**To Reproduce**
Update to the latest dev version and load alexa_meda

**Expected behavior**
For it to work.

**Screenshots**
N/A

**System details**
 - Home-assistant (version): supervisor-2021.11.dev0401
 - Hassio (Yes/No): Supervised.
 - alexa_media  (version from `const.py` or HA startup): v3.10.10
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.1
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  y

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```
2021-11-07 05:04:27 ERROR (MainThread) [homeassistant.setup] Setup failed for alexa_media: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 206, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/__init__.py", line 16, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 21, in <module>
    from alexapy.aiohttp import ClientConnectionError, ClientResponse
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
```

**Additional context**

**Comment by drthanwho** [comment]
Indeed also same here in dev20211111

**Comment by alandtse** [comment]
Odd, I'm on dev and I can't reproduce this. Double check you don't have any random dependencies in your /config directory like aiohttp or alexapy.

**Comment by Petro31** [comment]
> Odd, I'm on dev and I can't reproduce this. Double check you don't have any random dependencies in your /config directory like aiohttp or alexapy.

I'm still on 1103, I'll update tonight and see if the error still persists.  I'm 99% sure I don't have any random dependencies, but I'll double check when I get home.

**Comment by Petro31** [comment]
Updated, still getting the issue.  I am only running one other custom integration that requires the http dependency.  Frigate.  Frigate itself isn't loading due to some other import issues. 

I'm actually getting this error across the board i've noticed.  Other notification platforms using http are failing too

**Comment by drthanwho** [comment]
Yeah also seeing the same but so far only from Alexa. On latest release there's a lot of other warnings so not noticed if other notify platforms are also logging errors.

**Comment by zibous** [comment]
@alandtse 
Same problem here with **Alexa Media Player v3.10.12** :

```
**System Health Docker Version:**

version: core-2021.12.0.dev20211121
installation_type: Home Assistant Container
dev: true
hassio: false
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 5.8.0-63-generic
arch: x86_64
timezone: Europe/Vaduz


GitHub API: ok
Github API Calls Remaining: 4923
Installed Version: 1.17.2
Stage: running
Available Repositories: 910
Installed Repositories: 9


logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: failed to load: timeout


dashboards: 3
resources: 12
views: 2
mode: storage
```
**ERROR MESSAGE:**

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: aiohttp.server
Source: custom_components/alexa_media/__init__.py:16
Integration: Alexa Media Player (documentation, issues)
First occurred: 10:50:20 (1 occurrences)
Last logged: 10:50:20

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 430, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 215, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 715, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/__init__.py", line 16, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 21, in <module>
    from alexapy.aiohttp import ClientConnectionError, ClientResponse
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
```

**Comment by alandtse** [comment]
Ok, finally reproduced it. Taking a look now.

**Comment by alandtse** [comment]
Please enable beta release and try out 3.10.13. I may have to bump it as it appears it may break anything before 2012.12.x so I need a version restriction.

**Comment by zibous** [comment]
@alandtse 
Is working now, perfect 💯 
Thanks

**Comment by alandtse** [comment]
Great, there should be a new version 3.10.14 coming shortly, it's identical but has a HA requirement. I assume HACS will let dev versions download it but let me know if not. You should be able to still use 3.10.13 even if doesn't work.

**Comment by Petro31** [comment]
> Ok, finally reproduced it. Taking a look now.

let me know if you need help.

**Comment by drthanwho** [comment]
Works on 2021.12.0.dev20211123 🙌

**Comment by Petro31** [comment]
works

**Comment by johnwyles** [comment]
I am on `dev` and using core Version `core-2021.12.0b3` and still getting the aforementioned errors. Anything I can do to resolve this? I had it working until I had to remove the integration and add it back and then everything just went to crap and I've been trying unsuccessfully for hours trying to narrow it down.

**Comment by johnwyles** [comment]
@zibous I only show versions up to `3.10.12` and then `dev` from within HACS when I check `Show beta versions`?

**Comment by zibous** [comment]
@johnwyles 
Yes, first try `reload`and  than select `beta versions`
![Bildschirmfoto 2021-12-08 um 19 16 51](https://user-images.githubusercontent.com/30198737/145262551-73a27dd3-7db8-452e-8397-4fa984e383fd.png)

**Comment by johnwyles** [comment]
@zibous sadly that didn't work either - i'm now getting rate limited by github for doing this process so many times - is there a way to simply start completely from scratch with whatever must have put itself into the internals of HA from past amazon crap because that seems like what it could be?

**Comment by alandtse** [comment]
Dev will also get the latest version. It's currently identical to 3.10.15. Obviously dev may get updated in the future so I'd advise you to grab a numbered release.

**Comment by johnwyles** [comment]
@zibous I just skipped the whole HACS thing and did the manual steps here and WOW! https://github.com/custom-components/alexa_media_player/wiki/Configuration#manual-mode

Thanks for keeping me persistent!
