### ISSUE TITLE
Alexa Integration - Integration that worked and stopped working

### ISSUE THREAD

**Issue by charles8119** [custom-components/alexa_media_player#1405]
Alexa integration with home assistant worked and stopped working, I redid all the steps, deactivated, reactivated and nothing worked.

I'm new to the group and can someone help me?

Alexa integration with home assistant worked and stopped working, I redid all the steps, deactivated, reactivated and nothing worked.

I'm new to the group and can someone help me?

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/alexa_media/__init__.py:324
Integration: Alexa Media Player (documentation, issues)
First occurred: 11:10:06 (1 occurrences)
Last logged: 11:10:06

Error setting up entry charles.ssilva@gmail.com - amazon.com for alexa_media
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('99.84.27.18', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 144, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 579, in login
    if await self.test_loggedin(cookies):
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 460, in test_loggedin
    get_resp = await self._session.get(
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
alexapy.aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host alexa.amazon.com:443 ssl:<ssl.SSLContext object at 0x7f874b9240> [Connect call failed ('99.84.27.18', 443)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/alexa_media/__init__.py", line 324, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 154, in wrapper
    raise AlexapyConnectionError from ex
alexapy.errors.AlexapyConnectionError

---
Logger: alexapy.helpers
Source: /usr/local/lib/python3.9/site-packages/alexapy/helpers.py:146
First occurred: 11:10:06 (1 occurrences)
Last logged: 11:10:06

alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f86773ac0>,), {'cookies': {'session-id': <Morsel: session-id=137-3141545-2813235; Path=/>, 'session-id-time': <Morsel: session-id-time=2267178504l; Path=/>, 'lc-main': <Morsel: lc-main=en_US; Path=/>, 'ubid-main': <Morsel: ubid-main=133-9147771-1650008; Path=/>, 'session-token': <Morsel: session-token="P+tOnyzGbBVbkeZ/dnBlfwS6RUIxYfW/8fWRHqvosNldBPhzJWab10Qn1OTOUjoQUvtTKv9E6BL24tqFPhxY5HKeallFgQCH0nDypBq+z5IWzXuHPFBh8LyzAyYlONC1aI5OSzjgAxupRubCziw6kljw4JCdR2lLBWnc6SAyGda0IGk7775ZGOYNg8S8s/1e+BEEZ74MRBZws5k2WK9KthnzQ64dvsdtCg2Dk6EJxGM="; Path=/>, 'csrf': <Morsel: csrf=-1688240558; Path=/>, 'x-main': <Morsel: x-main="molnQbklDT62MlQ6c9i3WlezuCPT5?pm"; Path=/>, 'at-main': <Morsel: at-main=Atza|IwEBIKZb3A251lni3Uuthq8fsdIDVDaYIRDtSDg24A6o3jUxcuKZ85FT6I_kXw9_RVt4mp9Tx1JnFsrkdSASJQw3iTlh2gxpbaBq_88HeOtYIXwfNupMI7_-TH8cwDYxWP_9tQnAaaufBroJmmdGQWY98iEV2SXTaLz2nfsyi7_v2OHOrDZPdlVW5Ev5QLnHzgJtu-ksHNsnHq-QP9GRe3J1T1gw7-T_j1mmV4IfmrbjQXHeZ0DXNGKSm-Pxv0QiqwZ78YAzvj84tql7-LyDTH2djkbcM5aSLvE-lMDG868eoo_uWwwTtjUIJS1LivTKZtdYVCZztNXJ-TQE3Hd6mKZ_CN-K2C5s3h9lUZjqfAesGZiasue_lxkepyrF5EgJXXgskFE; Path=/>, 'sess-at-main': <Morsel: sess-at-main="tWf1JPGsfa75UZOz/gWDsl8QD8hlG/0H4Xwbpq2Xx3U="; Path=/>}}): A connection error occured: An exception of type ClientConnectorError occurred. Arguments: (ConnectionKey(host='alexa.amazon.com', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x7f874b9240>, proxy=None, proxy_auth=None, proxy_headers_hash=7887398963429816522), TimeoutError(110, "Connect call failed ('99.84.27.18', 443)"))

**Comment by alandtse** [comment]
Please use the template moving forward. The component is saying it can't connect to Amazon's servers. That normally means you have a network issue. You may need to reboot as it looks like a larger issue with your network connection.
