### ISSUE TITLE
Cant login using 2FA authenticator method

### ISSUE THREAD

**Issue by IroEro** [custom-components/alexa_media_player#1418]
**Describe the bug**
I've been using alexa media for a couple of years now, but every few months i try again to setup using the 2FA authenticator app so i dont have to keep authenticating again every so often. Whenever i try it, i get an error after the OTP submit stage

**To Reproduce**
1. Configure Alexa media
2. Enter password, captcha, and built in 2FA key from amazon
3. (at this point, if i dont check the "use login proxy" option, i get an "incorrect password" error, so i check it)
4. Continue to OTP stage
5. Get OTP from alexa media and insert it into amazon 2FA page
6. amazon accepts the OTP and returns me to the 2FA page with the number of apps incremented by 1
7. Check the "OTP was successful" check box on alexa media
8. Keep getting "Unknown error occurred" on retries

**System details**
 - Home-assistant (version): core-2021.11.4
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 3.10.11
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
2021-11-16 16:09:01 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/alexa_media/config_flow.py", line 557, in async_step_totp_register
    return await self.async_step_start_proxy(user_input)
  File "/config/custom_components/alexa_media/config_flow.py", line 383, in async_step_start_proxy
    self.proxy.session.cookie_jar.update_cookies(
AttributeError: 'AsyncClient' object has no attribute 'cookie_jar'

**Additional context**

**Comment by alandtse** [comment]
I only support the login proxy method for now. The legacy method will be removed in the next release. Please use that. Amazon sometimes requires a resubmission to accept the username/ password.

**Comment by IroEro** [comment]
> I only support the login proxy method for now. The legacy method will be removed in the next release. Please use that. Amazon sometimes requires a resubmission to accept the username/ password.

As I've said in the steps above, I'm using the login proxy method. Is something in my steps wrong?

**Comment by Adamvg** [comment]
I'm having the same error, logs look the same too.

**Comment by alandtse** [comment]
You are adding a new component after removing the existing component? This code should not fire unless you've already logged in using the component before hitting this step. A fresh install won't have this situation.
