### ISSUE TITLE
Problems configuring integration with amazon domain .it

### ISSUE THREAD

**Issue by Whitfy** [custom-components/alexa_media_player#1419]
**Describe the bug**
The configuraton of the integration loops if using amazon.it domain

**To Reproduce**
I have problems in configuring the Alexa Media Player integration (apparently using alexa.it domain). these are theh steps I follow:
- Configure the integration by entering username, password, domain (amazon.it), 2FA code.
   All remaining settings remain unchanged ("Login Proxy" YES, "enable oauth-token" YES)
- On next step i confirm that I have inserted the OTP code in Amazon 2FA page
- An Alexa login web page opens. I login and confirm the pre-compiled OTP code
- The window closes and after a few seconds reopens. On this new window the pre-compiled OTP does not work any more and I can't go further.

I instead I set the "amazon.com" domain the configuration ends correctly and all devices are imported, but they are obviously all with status "unknown".

**System details**
 - Home-assistant (version): 2021.11.4  
 - Hassio (Yes/No): No, using HA Core
 - alexa_media  (version from `const.py` or HA startup): 3.10.11
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.2
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n).: Yes

**Logs** nr. 1/2

Logger: aiohttp.server
Source: custom_components/alexa_media/config_flow.py:680
Integration: Alexa Media Player (documentation, issues)
First occurred: 12:39:58 (1 occurrences)
Last logged: 12:39:58

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 96, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/alexa_media/config_flow.py", line 411, in async_step_finish_proxy
    return await self._test_login()
  File "/config/custom_components/alexa_media/config_flow.py", line 680, in _test_login
    self.hass.data[DATA_ALEXAMEDIA]["accounts"][self.config[CONF_EMAIL]][
KeyError: 'accounts'

**Logs** nr. 2/2

Logger: homeassistant
Source: custom_components/alexa_media/__init__.py:235
Integration: Alexa Media Player (documentation, issues)
First occurred: 12:39:58 (1 occurrences)
Last logged: 12:39:58

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/__init__.py", line 235, in login_success
    login_obj: AlexaLogin = hass.data[DATA_ALEXAMEDIA]["accounts"][email].get(
KeyError: 'accounts'

**Comment by alandtse** [comment]
I just confirmed amazon.it works. Please completely remove the component and readd it on the Integrations page. Ensure that you are not trying to readd an existing account.
