### ISSUE TITLE
AttributeError: 'ClientResponse' object has no attribute 'request'

### ISSUE THREAD

**Issue by larena1** [custom-components/alexa_media_player#1428]
**Describe the bug**
Previous issue https://github.com/custom-components/alexa_media_player/issues/1318 seems to be fixed but now when tryint to reauthenticate there's another error.

**To Reproduce**
1. Reauthenticate
2. Auth website shows 500 error
3. Error being logged

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 2021.11.0
 - Hassio (Yes/No): Yes (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): v3.10.12
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.2
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/config/custom_components/alexa_media/config_flow.py", line 1116, in wrapped
    return await cls.handler(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 390, in all_handler
    print_resp(resp)
  File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/helper.py", line 32, in print_resp
    _LOGGER.debug("%s: redirected from\n%s", item.request.method, item.url)
AttributeError: 'ClientResponse' object has no attribute 'request'

**Additional context**

**Comment by alandtse** [comment]
Thanks. Work around is not to enable the login proxy when submitting data.
