### ISSUE TITLE
Alexa suddenly stop working

### ISSUE THREAD

**Issue by poudenes** [custom-components/alexa_media_player#1430]
HAOS 6.6
Core 2021.11.5
Supervisor 2021.10.8
RRP4 4GB

Hi There all,

I changed something on my input_datetime and rebooted my HAOS and now Alexa is not working anymore... 
For months without problem and since this change I get this error:

```
Logger: homeassistant.config_entries
Source: custom_components/alexa_media/__init__.py:324 
Integration: Alexa Media Player (documentation, issues) 
First occurred: 10:15:59 (1 occurrences) 
Last logged: 10:15:59

Error setting up entry info@hassio.nl - amazon.com for alexa_media
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('65.9.86.22', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 574, in login
    if await self.test_loggedin(cookies):
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 455, in test_loggedin
    get_resp = await self._session.get(
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
alexapy.aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host alexa.amazon.com:443 ssl:<ssl.SSLContext object at 0x7f9821bec0> [Connect call failed ('65.9.86.22', 443)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/alexa_media/__init__.py", line 324, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 147, in wrapper
    raise AlexapyConnectionError from ex
alexapy.errors.AlexapyConnectionError
```

```
PING alexa.amazon.com (65.9.86.22): 56 data bytes
64 bytes from 65.9.86.22: seq=0 ttl=244 time=5.457 ms
64 bytes from 65.9.86.22: seq=1 ttl=244 time=6.297 ms
64 bytes from 65.9.86.22: seq=2 ttl=244 time=5.872 ms
64 bytes from 65.9.86.22: seq=3 ttl=244 time=6.904 ms
^C
--- alexa.amazon.com ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 5.457/6.132/6.904 ms
```

**Comment by poudenes** [comment]
Ok, I tried something out of box: restarted my Asus GT-AX10000 and after that HA and now everything is ok again...

**Comment by poudenes** [comment]
Only what its working now is flash briefing with Home Assistant.
Will search what that can be

**Comment by poudenes** [comment]
When I try to open this link I get below error. If I ask Alexa for my briefing I get the same error

https://mydomain.nl/api/alexa/flash_briefings/ha_briefing?password=MYPASSWORD

In log file of HAOS I see this:
```
2021-11-22 11:04:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 398, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1698, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "<template>", line 1, in template
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 132, in handle
    result = handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/alexa/flash_briefings.py", line 91, in get
    output[ATTR_MAIN_TEXT] = item[CONF_TEXT].async_render(
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 400, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: 'NoneType' object is not iterable
```

**Comment by alandtse** [comment]
None of that is related to the component. You want the core app.

**Comment by poudenes** [comment]
Yes saw it was something of HA itself. I'll will post here the possible solution or what I did to let it work again.

**Comment by poudenes** [comment]
There ware some entities in the text and they not there anymore. Removed the entities incl the text. Reboot HA and now its working again.
