### ISSUE TITLE
Beta 2021.12.0b0 Error

### ISSUE THREAD

**Issue by Wibias** [custom-components/alexa_media_player#1446]
Updated to the newest Homeassistant beta and its giving me this error with the infos. So just a head up!

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alexa_media/__init__.py:16
Integration: Home Assistant WebSocket API (documentation, issues) 

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 733, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 157, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 938, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 218, in async_check_ha_config_file
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/__init__.py", line 16, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 21, in <module>
    from alexapy.aiohttp import ClientConnectionError, ClientResponse
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str

**Comment by tteck** [comment]
https://github.com/custom-components/alexa_media_player/issues/1439#issue-1061520971

Can't use with beta, `"homeassistant": "2021.12.0"`  needs to be `"homeassistant": "2021.12.0b0"` in hacs.json?

**Comment by linus-ha** [comment]
Same error here. Running v3.10.14 on 2021.12.0b0

**Comment by alandtse** [comment]
Thanks. It has to be 3.10.14 for any 2012.12 release but it may be a HACS issue on the proper way to identify beta releases there. I'll raise it. In the meantime, you can manually install it and it should run.

**Comment by Wibias** [comment]
Yea when trying to install 3.10.14 getting ```You are running Home Assistant version '2021.12.0b0', but this repository requires minimum version '2021.12.0' to be installed.```

**Comment by Wibias** [comment]
So the answer on discord was:

This is correct.
2021.12.0 > 2021.12.0bX

**Comment by alandtse** [comment]
> So the answer on discord was:
> 
> This is correct. 2021.12.0 > 2021.12.0bX

If you're talking to Ludeeus already, how do we specify any 2021.12.x build? It worked fine for 2021.12.dev with the 2021.12.0 requirement.

**Comment by Wibias** [comment]
> 

2021.12.0b0

**Comment by linus-ha** [comment]
> Yea when trying to install 3.10.14 getting `You are running Home Assistant version '2021.12.0b0', but this repository requires minimum version '2021.12.0' to be installed.`

Oh, sorry. I thought clicking "Download" with v3.10.14 selected in HACS would ignore the warning message, but it actually doesn't download anything and is just showing a loading animation. That's not very intuitive.

**Comment by alandtse** [comment]
> That's not very intuitive.

That's a HACS complaint. I can't solve that. ;) It should probably allow an override.

**Comment by linus-ha** [comment]
> > That's not very intuitive.
> 
> That's a HACS complaint. I can't solve that. ;) It should probably allow an override.

Yes, I know that.

Installed v3.10.14 manually and everything works as expected. Thank you very much!

**Comment by alandtse** [comment]
3.10.15 should let you download it. It's a beta release.
