### ISSUE TITLE
HA service call not working

### ISSUE THREAD

**Issue by maddeuce** [custom-components/alexa_media_player#1455]
**Describe the bug**
notify.alexa_media doesn't seem to work anymore.  It always give me an error, no matter what type of data input I do.

However the service call still seem to work in Node Red.

**To Reproduce**
General service call via developer tools

**Expected behavior**
See below picture

**Screenshots**
![image](https://user-images.githubusercontent.com/54375636/144880966-5057e0da-75d7-4cc4-af3f-e7671d6b25cc.png)
![image](https://user-images.githubusercontent.com/54375636/144881155-24791c9d-ad17-4c06-b277-f8bbbc3be6df.png)

**System details**
 - Home-assistant (version):  2021.11.5
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): v3.10.12
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: No

**Logs**
![image](https://user-images.githubusercontent.com/54375636/144880966-5057e0da-75d7-4cc4-af3f-e7671d6b25cc.png)
Give the below log.
[140573131806032] Error handling message: expected dict for dictionary value @ data['data']. Got None
8:30:53 AM – (ERROR) Home Assistant WebSocket API
websocket_api script: Error executing script. Invalid data for call_service at pos 1: expected dict for dictionary value @ data['data']
8:30:53 AM – (ERROR) helpers/script.py

![image](https://user-images.githubusercontent.com/54375636/144881155-24791c9d-ad17-4c06-b277-f8bbbc3be6df.png)
Give the below logs.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alexa_media/notify.py:216
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:29:51 AM (1 occurrences)
Last logged: 8:29:51 AM

[140573131806032] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 523, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1243, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 221, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 216, in async_send_message
    if data["type"] == "tts":
TypeError: 'NoneType' object is not subscriptable

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/alexa_media/notify.py:216
Integration: Alexa Media Player (documentation, issues)
First occurred: 8:29:51 AM (1 occurrences)
Last logged: 8:29:51 AM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 221, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 216, in async_send_message
    if data["type"] == "tts":
TypeError: 'NoneType' object is not subscriptable

**Additional context**
Service call still work with Node Red.  Not sure if there in conflict but I do have amazon polly, however the above error still show up even if I take off amazon polly out of my setup.  100% of all my notification is automated via Node Red.  I only find this error when I try to send a quick announcement to my house via tools when I was away at work.  So I have no idea when this error first happen, as you can see below all my message still working inside node red.

![image](https://user-images.githubusercontent.com/54375636/144886321-78fbcc52-f206-422e-93d8-ff701867593a.png)

**Comment by alandtse** [comment]
Please review the [wiki](https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component#use-the-notifyalexa_media--alexa_id-service) or the forums. The error isn't a technical issue.

**Comment by maddeuce** [comment]
> Please review the [wiki](https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component#use-the-notifyalexa_media--alexa_id-service) or the forums. The error isn't a technical issue.
Hmm what wrong with my service call? This format come directly the developer tool menu.
![image](https://user-images.githubusercontent.com/54375636/144894531-9e711460-cb1e-4a27-ba76-0a19aaf908b5.png)

**Comment by maddeuce** [comment]
nvm i see the issue.  I guess hass internal service format is not setup to the format of alexa_media_player components.  I manually change the format hass generate via automation to the link you send and it working thank.
