### ISSUE TITLE
HA 2021.12.0b1-3 and Alexa Media Player not loading

### ISSUE THREAD

**Issue by Dixey-coder** [custom-components/alexa_media_player#1458]
Since upgrading HA to 2021.12.0b1 and up to 0b3, Alexa Media Player will hang upon loading and not function.  Not even function to the ability to remove and reinstall.
Reverting back to 2021.11 resolves everything.

**Comment by mwav3** [comment]
I installed the beta and can report the same.  I enabled advanced logging but have absolutely no log entries related to the failure, and the integration just says "Not Loaded", so I don't know what is causing this. 

These are the breaking changes for the beta so not sure what exactly is causing this - https://rc.home-assistant.io/blog/2021/12/03/release-202112/#breaking-changes

**Comment by acdcnow** [comment]
Still happens on Beta 4

Logger: homeassistant.setup
Source: custom_components/alexa_media/__init__.py:16
Integration: alexa_media (documentation, issues)
First occurred: 10:22:02 (1 occurrences)
Last logged: 10:22:02

**Setup failed for alexa_media: unknown error**
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 181, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/__init__.py", line 16, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 21, in <module>
    from alexapy.aiohttp import ClientConnectionError, ClientResponse
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
**TypeError: function() argument 'code' must be code, not str --->! here**

**Comment by mwav3** [comment]
Looks like there already is a release ready to go to have it work with 2021.12,  I'll give it a try

https://github.com/custom-components/alexa_media_player/releases/tag/v3.10.15

**Comment by alandtse** [comment]
This is a dupe and already resolved. Please refer to #1446.
