### ISSUE TITLE
Error handling message: Unknown error

### ISSUE THREAD

**Issue by nickylo1978** [custom-components/alexa_media_player#1487]
HA 2022.12.8 / HACS 1.19.1 / ALEXA MEDIA PLAYER INTEGRATION v3.10.15

When you try to use a "notify.alexa_media" service and invoke the service, this error appears in the logs:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alexa_media/notify.py:195
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:49:15 (1 occurrences)
Last logged: 23:49:15

[1890776832] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 527, in handle_execute_script
await script_obj.async_run(msg.get("variables"), context=context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1260, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 221, in _async_notify_message_service
await self.async_send_message(**kwargs)
File "/config/custom_components/alexa_media/notify.py", line 195, in async_send_message
for target in targets:
TypeError: 'NoneType' object is not iterable

Is a problem with new version of HA ? Any suggestion ?

Tks

**Comment by alandtse** [comment]
Please use the template and also provide the service call.

**Comment by nickylo1978** [comment]
**Describe the bug**

When you try to use a "notify.alexa_media" service and invoke the service, this error appears in the logs:

**To Reproduce**
Steps to reproduce the behavior:

- Go to developer tools
- Go to Service
- Write to service: notify.alexa_media
- On Message I write "TEST"
- Click to "invoke service"
- The indicated error appears

**Expected behavior**
The ALEXA device should play the TEST message

**Screenshots**

**System details**
 - Home-assistant (version): core-2021.12.8 (Home Assistant Container) on Raspberry PI
 - Hassio (Yes/No): NO
 - alexa_media  (version from `const.py` or HA startup): v3.10.15
 - alexapy (version from `pip show alexapy` or HA startup): //
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n).  YES 

**Logs**


Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alexa_media/notify.py:195
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 23:49:15 (1 occurrences)
Last logged: 23:49:15

[1890776832] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 527, in handle_execute_script
await script_obj.async_run(msg.get("variables"), context=context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1260, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 221, in _async_notify_message_service
await self.async_send_message(**kwargs)
File "/config/custom_components/alexa_media/notify.py", line 195, in async_send_message
for target in targets:
TypeError: 'NoneType' object is not iterable

**Additional context**
Add any other context about the problem here.

**Comment by alandtse** [comment]
You need to define a target if you use the generic notify service. Check the wiki for examples.
https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component

**Comment by nickylo1978** [comment]
Before Upgrade the notify run perfect.
this is the configuration (automation.yalm):

service: notify.alexa_media_ovunque
    data:
      target: media_player.alexa_echo_dot
      message: TEST
      data:
        type: announce
        method: spoken
  mode: single

before the update the integration worked perfectly ! I have study a lot the wiki

Thanks
