### ISSUE TITLE
Infinite Login-Loop with Error | Cannot connect to host alexa.amazon.com:443 ssl

### ISSUE THREAD

**Issue by JAKAMI99** [custom-components/alexa_media_player#1489]
**Describe the bug**
After reinstalling because of "Not loaded"
After logging in, into my amazon account the window closes and the integration prompts me with "Open Website - This step requires you to visit an external website to be completed."

**To Reproduce**
(After uninstalling, deleting the folder in "config\custom_components\alexa_media" and fresh reboot
1. Install alexa_media_player from HACS
2. Restart
3. Install the Integration over Integrations
4. Fill in credentials, new 2FA and "amazon.de"
5. Click on Submit
6. Validate 2FA
7. login on the proxy
8. Submit the already filled in 2FA code
9. Submit

**Expected behavior**
Fill in credentials, submit, login, submit the already filled in 2FA

**System details**
 - Home-assistant (version): 2021.12.9
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): v3.10.15
 - Amazon [2FA is enabled] yes

**Logs**
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/alexa_media/config_flow.py:405
Integration: alexa_media (documentation, issues)
First occurred: 2:36:05 AM (2 occurrences)
Last logged: 2:39:30 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('::', 443, 0, 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 96, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/alexa_media/config_flow.py", line 405, in async_step_finish_proxy
    if await self.login.test_loggedin():
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 455, in test_loggedin
    get_resp = await self._session.get(
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
alexapy.aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host alexa.amazon.com:443 ssl:<ssl.SSLContext object at 0x7f11e38be7c0> [Connect call failed ('::', 443, 0, 0)]

**Additional context**

**Comment by JAKAMI99** [comment]
OMG, I'm so happy :D 
It was my own fault, I should read logs before bruteforcing everything :D
One of my blocklists in my pihole indexed "alexa.amazon.com" into the blocklist.
Removed it, and it worked like a charm ^^

Thanks for the project :) on of my favorite homeassistant features <3

**Comment by sherazlodhi** [comment]
> OMG, I'm so happy :D It was my own fault, I should read logs before bruteforcing everything :D One of my blocklists in my pihole indexed "alexa.amazon.com" into the blocklist. Removed it, and it worked like a charm ^^
> 
> Thanks for the project :) one of my favorite homeassistant features <3

just came here to say that i had same issue :D
