### ISSUE TITLE
KeyError: 'P1M' Error adding entities for domain sensor with platform alexa_media

### ISSUE THREAD

**Issue by nholben** [custom-components/alexa_media_player#1490]
**Describe the bug**
Alexa Media Player generates errors on startup. Everything appears to work afterword. I have tried removing/reinstalling with 2FA key login method but the errors in the logs persist:

Error adding entities for domain sensor with platform alexa_media
Error while setting up alexa_media platform for sensor

**To Reproduce**
1. Restart Home Assistant Core
2. Check Logs

**Expected behavior**
Component Starts up normally and produces no errors

**System details**
 - Home-assistant (version): 2021.12.9
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 3.10.15
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.3
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
2022-01-12 12:24:24 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in add_to_platform_finish
await self.async_added_to_hass()
File "/config/custom_components/alexa_media/sensor.py", line 411, in async_added_to_hass
await self.async_update()
File "/config/custom_components/alexa_media/sensor.py", line 508, in async_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in _async_write_ha_state
extra_state_attributes = self.extra_state_attributes
File "/config/custom_components/alexa_media/sensor.py", line 643, in extra_state_attributes
attr = super().extra_state_attributes
File "/config/custom_components/alexa_media/sensor.py", line 540, in extra_state_attributes
"recurrence": self.recurrence,
File "/config/custom_components/alexa_media/sensor.py", line 529, in recurrence
RECURRING_PATTERN[self._next.get("recurringPattern")]
KeyError: 'P1M'

**Additional context**

**Comment by alandtse** [comment]
Do you have any alarms with a recurring pattern? If so, what are they? This is what we've defined.

https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/const.py#L59-L71

**Comment by nholben** [comment]
Oh, yes we have a number of them set up. Looking through what you have defined I believe the problem is coming from a "bi-weekly" reminder (every other week.

**Comment by alandtse** [comment]
Ok thanks. That's a legit bug then.
