### ISSUE TITLE
Error Handling Message and websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by dwvaughn** [custom-components/alexa_media_player#1494]
**Describe the bug**
Trying to test notify.alexa_media_player_kitchen (device specific) says "Failed to call service: Error Unknown".  Generates two errors in the log.

**To Reproduce**
1. Go to: Developer Tools
2. Go to: Services
3. Call Service:  notify.alexa_media_player_kitchen with the example data

**Expected behavior**
Expect the Kitchen Echo Dot to announce the example data about the Garage door being open.

**Screenshots**

**System details**
 - Home-assistant (version): 2021.12.9
 - Hassio (Yes/No): Yes.  Hassio was restarted 3 times but still saw the same issue.
 - alexa_media:  3.10.15
 - alexapy (version from `pip show alexapy` or HA startup):  "package not found"
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  Yes and built-in key has been enabled

**Logs**
    [1875617296] Error handling message: Unknown error
    [1674408456] Error handling message: Unknown error
    [1645019656] Error handling message: Unknown error

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 527, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1260, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 221, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 216, in async_send_message
    if data["type"] == "tts":
TypeError: 'NoneType' object is not subscriptable

*****************

This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/alexa_media/notify.py:216
Integration: Alexa Media Player (documentation, issues)
First occurred: 8:05:17 PM (13 occurrences)
Last logged: 8:44:20 PM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 221, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 216, in async_send_message
    if data["type"] == "tts":
TypeError: 'NoneType' object is not subscriptable

*** Additional Context ***
I deleted and reinstalled the integration but still saw the same issue.

**Comment by dwvaughn** [comment]
Was able to get it working.  Had to change the example data as below in order to get it to work:

service: notify.alexa_media_kitchen
data:
  message: This is the way we wash our hands
  title: test
  data:
    type: "tts"
