### ISSUE TITLE
Reauthentication fails after opening page and says: 500, server got itself in trouble

### ISSUE THREAD

**Issue by atv2016** [custom-components/alexa_media_player#1495]
I have gotten this in the past, not sure why this keeps happening.

Reauthentication required when it opens the popup, it says 👍 500 Internal Server Error

Server got itself in trouble

This morning somehow i closed the webpage and it succeeded, but it's back to it's unauthenticated state.

**Comment by atv2016** [comment]
![Screenshot 2022-01-18 at 19 58 40](https://user-images.githubusercontent.com/16917203/150009737-f7186a92-f395-4c3a-8c02-13ed91830215.png)

**Comment by atv2016** [comment]
Logger: alexapy.alexawebsocket
Source: /usr/local/lib/python3.9/site-packages/alexapy/alexawebsocket.py:232
First occurred: 19:58:10 (1 occurrences) 
Last logged: 19:58:10

mac_dms not detected; websocket likely won't connect

**Comment by atv2016** [comment]
and: 
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/alexa_media/config_flow.py:1122 
Integration: Alexa Media Player (documentation, issues) 
First occurred: 19:54:24 (2 occurrences) 
Last logged: 19:56:52

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/config/custom_components/alexa_media/config_flow.py", line 1122, in wrapped
    return await cls.handler(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 387, in all_handler
    resp = await getattr(self.session, method)(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1736, in get
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1500, in request
    request = self.build_request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 351, in build_request
    return Request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1099, in __init__
    Cookies(cookies).set_cookie_header(self)
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1792, in set_cookie_header
    self.jar.add_cookie_header(urllib_request)
  File "/usr/local/lib/python3.9/http/cookiejar.py", line 1367, in add_cookie_header
    attrs = self._cookie_attrs(cookies)
  File "/usr/local/lib/python3.9/http/cookiejar.py", line 1326, in _cookie_attrs
    self.non_word_re.search(cookie.value) and version > 0):
TypeError: expected string or bytes-like object

But maybe this is because of an automation and alexa was not configured/running/entities available. Although that error doesn't look right to me.

I wonder how long this re-authentication will last again.

**Comment by alandtse** [comment]
Please use the template. Also, remove and readd the integration in HA.

**Comment by umrath** [comment]
Same problem here today.
The integration was working fine for months and today it suddenly went red.

Re-authentication fails with exactly the same pop up.

Relevant log entry:

```
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:98
First occurred: 08:33:43 (8 occurrences)
Last logged: 08:39:59

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexawebsocket.py", line 275, in process_messages
    await self.on_message(cast(bytes, msg.data))
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexawebsocket.py", line 304, in on_message
    await self.websocket.send_bytes(msg)
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client_ws.py", line 156, in send_bytes
    await self._writer.send(data, binary=True, compress=compress)
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_websocket.py", line 688, in send
    await self._send_frame(message, WSMsgType.BINARY, compress)
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_websocket.py", line 646, in _send_frame
    self._write(header + mask + message)
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

**Comment by Dielee** [comment]
Same here, not working anymore.. 

```
Traceback (most recent call last):
  File "/srv/homeassistant_3.9/lib/python3.9/site-packages/alexapy/alexawebsocket.py", line 275, in process_messages
    await self.on_message(cast(bytes, msg.data))
  File "/srv/homeassistant_3.9/lib/python3.9/site-packages/alexapy/alexawebsocket.py", line 304, in on_message
    await self.websocket.send_bytes(msg)
  File "/srv/homeassistant_3.9/lib/python3.9/site-packages/alexapy/aiohttp/client_ws.py", line 156, in send_bytes
    await self._writer.send(data, binary=True, compress=compress)
  File "/srv/homeassistant_3.9/lib/python3.9/site-packages/alexapy/aiohttp/http_websocket.py", line 688, in send
    await self._send_frame(message, WSMsgType.BINARY, compress)
  File "/srv/homeassistant_3.9/lib/python3.9/site-packages/alexapy/aiohttp/http_websocket.py", line 646, in _send_frame
    self._write(header + mask + message)
  File "/srv/homeassistant_3.9/lib/python3.9/site-packages/alexapy/aiohttp/http_websocket.py", line 663, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

**Comment by Krocko** [comment]
Same here

**Comment by Dielee** [comment]
Works again! Maybe this was an amazon problem..

**Comment by jj-uk** [comment]
I get this happen about once every 4-6 weeks, needing re-authing. I usually remove and re-add the component as re-auth doesn't seem to work for me, ever.

**Comment by broyuken** [comment]
I'm getting this now as well.

**Comment by sphinxlady** [comment]
> I'm getting this now as well.

Everyone is now its failed or the server has.

Have to wait and find out.

**Comment by glassbase** [comment]
also getting

**Comment by broyuken** [comment]
getting this if i go to alexa.amazon.com

![image](https://user-images.githubusercontent.com/1593391/151729488-f474ce68-3f49-40a2-8945-ac6b79cf56c0.png)

**Comment by alandtse** [comment]
All, please read the issue. This is about a server error 500. If you do not see the number 500, you are not having this issue.

**Comment by atv2016** [comment]
This has resolved itself for me over the coming days since I logged it. I feel like closing it but since I got this issue before I’m not sure this has been resolved and I have a feeling I will get it again.

Maybe leave this open until the issue presents itself again?

Yes it asks for reauthentication but then it gives the 500 error server for itself in trouble which is something that should not be happening.
________________________________

**Comment by alandtse** [comment]
Glad to hear it self resolved. Without the logs, I can't fix it.  Unfortunately, leaving it open means random people come in with unrelated authentication issue to add to it. Please open using the template if you run into it again.
