### ISSUE TITLE
HA does not restart due to alexa media player error

### ISSUE THREAD

**Issue by Pirol62** [custom-components/alexa_media_player#1498]
**Describe the bug**
Upgraded HA from 2021.11.5 to 2021.12.10 worked
Update AMP via HACS to x.x.15
Tried to restart HA but the restart was refused due to the error
Deleted Alexa component folder and reloaded via HACS
Restart still refused due to the same error

rolled back to 2021.11.5 - everythings fine.

**To Reproduce**
See  description above

**System details**
 - Home-assistant (version): 2021.11.5
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup): 3.10.12
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: yes

**Logs**
````
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alexa_media/__init__.py:16
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:49:49 (3 occurrences)
Last logged: 09:55:58

[281472370983696] function() argument 'code' must be code, not str
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 586, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 938, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 218, in async_check_ha_config_file
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/__init__.py", line 16, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 21, in <module>
    from alexapy.aiohttp import ClientConnectionError, ClientResponse
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
````

**Additional context**

**Comment by alandtse** [comment]
You need to use 3.10.15. The error is caused by trying to use 3.10.12 code with HA 2021.12. Please update. Make sure you've cleaned out the old files.

**Comment by Pirol62** [comment]
sorry, but I did update to 3.10.15. 
and I deleted the old files (folder)
HA refused to restart

**Comment by Pirol62** [comment]
@alandtse Sorry Alan, but I have to be a little annoying because I would like to update before the 2022.02.x comes out.
What did I wrong when i approach as follows?
1. update HA
2. directly go to Hacs and update AMP to 3.10.15
3. Then try to restart - doesn't work
4. Delete amp component folder and reload amp via HACS
5. Try to restart 

Shall I delete the folder before updating the amp the first time?

**Comment by alandtse** [comment]
Your method isn't working. Remove the integration first. Then upgrade. Then reinstall.

In truth a failing component should not stop a HA start so you have something else wrong you may need to resolve.

**Comment by Pirol62** [comment]
But doesn't removing the complete integration lead to other problems when upgrading HA without amp?
I have tons of yaml code related to amp entities (reading out reminders and timers, music, tts notifications etc)

**Comment by alandtse** [comment]
So you'll have some broken automations until you install it again. Again, the problem is your system doesn't start when a custom component breaks, which isn't how HA should be. That's fundamentally going to cause you many issues moving forward because HA likes to break custom components.

There's nothing else I can do for you here. 3.10.15 doesn't work for 2021.11. Even force upgrading AMP first won't help if it means your HA won't start. Your only hope based on what you've described is to start without AMP and then install it after.

**Comment by Pirol62** [comment]
That sounds like some work for me.😕
Thank you alandtse.

**Comment by Pirol62** [comment]
FYI - did it like recommended. Worked without issue. Thanks again.

**Comment by alandtse** [comment]
Great to hear. Hopefully you also figured out or figure out soon why a broken component stops your HA from starting.

**Comment by Pirol62** [comment]
Yes, interesting thing I have to dig in. I have no single issue so far except an uncought error appearing in the browser console which tells me that a component could not be initialized because it's already there. 
But I definitely haven't declared any front end component twice. But OK,I will look into that tomorrow.
