### ISSUE TITLE
Suddenly after 6-9 months of working, decides I need to reconfigure it.

### ISSUE THREAD

**Issue by scstraus** [custom-components/alexa_media_player#1501]
**Describe the bug**

Alexa media worked for maybe 6-9 months with the built in 2FA client, but suddenly it is asking me to reconfigure the integration. This just started suddenly today.  I'm getting these messages in the log. Check 01:12:32 for a traceback, another one right at the end

```
2022-01-31 15:08:17 DEBUG (MainThread) [alexapy.alexalogin] Successfully updated access_token whi
ch expires at 2022-01-31 16:08:17.841151 in 0:59:59.999981
2022-01-31 15:08:18 DEBUG (MainThread) [alexapy.alexalogin] 5 cookies successfully exchanged for refresh token for domain .amazon.com
2022-01-31 15:08:18 DEBUG (MainThread) [alexapy.alexalogin] CSRF already exists; no need to discover
2022-01-31 15:08:18 DEBUG (MainThread) [alexapy.alexaapi] s******s@g*******m:Login error detected; ignoring post request to /api/behaviors/preview with {'behaviorId': 'PREVIEW', 'sequenceJson': '{"@type": "com.amazon.alexa.behaviors.model.Sequence", "startNode": {"@type": "com.amazon.alexa.behaviors.model.SerialNode", "nodesToExecute": [{"@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode", "type": "Alexa.Speak", "operationPayload": {"deviceType": "A3VRME03NAXFUB", "deviceSerialNumber": "G0014D06951709DB", "locale": "en-us", "customerId": "A22RMRCUGLPE1B", "textToSpeak": "Welcome home. Please remember to plug the car in to charge. Thank you", "target": {"customerId": "A22RMRCUGLPE1B", "devices": [{"deviceSerialNumber": "G0014D06951709DB", "deviceTypeId": "A3VRME03NAXFUB"}]}, "skillId": "amzn1.ask.1p.saysomething"}}]}}', 'status': 'ENABLED'} None
2022-01-31 15:08:18 WARNING (MainThread) [alexapy.helpers] alexaapi.run_behavior((<alexapy.alexaapi.AlexaAPI object at 0x7fccf04f5ac0>, {'@type': 'com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode', 'type': 'Alexa.Speak', 'operationPayload': {'deviceType': 'A3VRME03NAXFUB', 'deviceSerialNumber': 'G************9DB', 'locale': 'en-us', 'customerId': 'A**********E1B', 'textToSpeak': 'Welcome home. Please remember to plug the car in to charge. Thank you', 'target': {'customerId': 'A**********E1B', 'devices': [{'deviceSerialNumber': 'G************9DB', 'deviceTypeId': 'A3VRME03NAXFUB'}]}, 'skillId': 'amzn1.ask.1p.saysomething'}}), {'queue_delay': 1.5}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2022-01-31 15:08:18 WARNING (MainThread) [alexapy.helpers] alexaapi.send_sequence((<alexapy.alexaapi.AlexaAPI object at 0x7fccf04f5ac0>, 'Alexa.Speak'), {'customer_id': 'A22RMRCUGLPE1B', 'textToSpeak': 'Welcome home. Please remember to plug the car in to charge. Thank you', 'target': {'customerId': 'A**********E1B', 'devices': [{'deviceSerialNumber': 'G************9DB', 'deviceTypeId': 'A3VRME03NAXFUB'}]}, 'skillId': 'amzn1.ask.1p.saysomething', 'queue_delay': 1.5}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2022-01-31 15:08:18 WARNING (MainThread) [alexapy.helpers] alexaapi.send_tts((<alexapy.alexaapi.AlexaAPI object at 0x7fccf04f5ac0>, 'Welcome home. Please remember to plug the car in to charge. Thank you'), {'customer_id': 'A22RMRCUGLPE1B', 'queue_delay': 1.5}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2022-01-31 15:08:18 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 851, in send_tts
    await self.send_sequence(
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 476, in send_sequence
    await self.run_behavior(node_data, queue_delay=queue_delay)
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 398, in run_behavior
    await self._post_request("/api/behaviors/preview", data=data)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 202, in _post_request
    return await self._request("post", uri, data)
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 172, in _request
    raise AlexapyLoginError("Login error detected; not contacting API")
alexapy.errors.AlexapyLoginError: Login error detected; not contacting API


```

**Additional context**

**Comment by alandtse** [comment]
It can't login. Remove and readd.

**Comment by alandtse** [comment]
Because that's how HA tells you you need to relogin

**Comment by scstraus** [comment]
Turns out I just had to go click "reconfigure" and then go in and submit all the data that was already in there, not changing anything, and then it worked again.
