### ISSUE TITLE
AlexapyLoginCloseRequested during shutdown

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#1507]
**Describe the bug**
Error logged during HA shutdown/restart

**To Reproduce**
1. Enable Alexa Media Player
2. Restart HA
3. Check log

**Expected behavior**
Clean shutdown/restart

**Screenshots**

**System details**
 - Home-assistant (version): 2022.02.0
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v3.10.15
 - alexapy (version from `pip show alexapy` or HA startup): v1.25.3
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
```
2022-02-03 16:59:38 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 922, in send_announcement
    await self.send_sequence(
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 476, in send_sequence
    await self.run_behavior(node_data, queue_delay=queue_delay)
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 398, in run_behavior
    await self._post_request("/api/behaviors/preview", data=data)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 202, in _post_request
    return await self._request("post", uri, data)
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 162, in _request
    raise AlexapyLoginCloseRequested()
alexapy.errors.AlexapyLoginCloseRequested
```

**Additional context**

**Comment by alandtse** [comment]
As this is cosmetic, this will not be something I'm going to work on as I'm not really working on this anymore. I'll leave it open for someone to fix if they care.
