### ISSUE TITLE
receiving error from Alexa Media player GatheringFuture exception was never retrieved

### ISSUE THREAD

**Issue by Pirol62** [custom-components/alexa_media_player#1518]
**Describe the bug**
when I change the spotify playlist via alexa command, I recieve an error.
Where can I start to dig in?
**To Reproduce**
Executed following script where {{media_content}} is "shuffle meine lazy chill afternoon playlist" and {{media_type}} is "Spotify":
````
command_play_music:
  sequence:
    - choose:
        - conditions:
            - "{{ states('sensor.active_harmony_scene') not in('Blutooth Music','Fire Music') and states('input_select.music_sources') in('Fire Media Center','Erdgeschoss','Alle Etagen','Home Office') }}"
          sequence:
            - service: switch.turn_on
              entity_id: switch.lounge_fire_music
        - conditions:
            - "{{ states('sensor.active_harmony_scene') in('Blutooth Music', 'Fire Music') or states('input_select.music_sources') not in('Fire Media Center','Erdgeschoss','Alle Etagen','Home Office') }}"
          sequence:
            - service: media_player.play_media
              data:
                entity_id: >
                  {% set player = states('input_text.last_alexa_music_source') %} 
                  {% if player in('Fire Media Center','Erdgeschoss','Alle Etagen','Home Office') %}
                     media_player.fire_media_center
                  {% elif player in('Unten','Haus','Wohnzimmer') %}
                     media_player.wohnzimmer
                  {% endif %}
                media_content_id: "stopp"
                media_content_type: "custom"
            - delay: "00:00:02"
    - service: media_player.play_media
      data:
        entity_id: >
          {% set player = states('input_select.music_sources') %}
          {% if player in('Fire Media Center','Erdgeschoss','Alle Etagen','Home Office') %}
              media_player.fire_media_center
          {% elif player in('Unten','Haus','Wohnzimmer') %}
              media_player.wohnzimmer
          {% endif %}
        media_content_id: >
          {% set player = states('input_select.music_sources') %}
          {% if player == 'Erdgeschoss' %}
            {{media_content}} auf erdgeschoss
          {% elif player == 'Alle Etagen' %}
            {{media_content}} auf alle etagen
          {% elif player == 'Home Office' %}
            {{media_content}} im home office
          {% else %}
            {{media_content}} auf fire_media_center
          {% endif %}
        media_content_type: "{{media_type}}"
    - service: media_player.volume_set
      data:
        entity_id:
          - media_player.kuche
          - media_player.office
          - media_player.schlafzimmer
        volume_level: 0.2
    - service: script.turn_on
      entity_id: script.add_log
      data:
        variables:
          name: "{{media_content}} auf {{ states.input_select.music_sources.state }}  - Type: {{media_type}}"
          message: "has been triggered"
    - service: input_text.set_value
      data:
        entity_id: input_text.last_alexa_music_command
        value: "{{media_content}}"
    - service: input_boolean.turn_on
      entity_id: input_boolean.music_playing
````
The script first stop the player and then executes the new command.
The script does exactly what it should do
**Expected behavior**
just no error in log

**Screenshots**

**System details**
 - Home-assistant (version): 2021.12.6
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): latest
 - alexapy (version from `pip show alexapy` or HA startup): latest
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: yes

**Logs**
````
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/alexa_media/media_player.py:891
Integration: Alexa Media Player (documentation, issues)
First occurred: 17:35:28 (1 occurrences)
Last logged: 17:35:28

Error doing job: _GatheringFuture exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/helpers.py", line 156, in _catch_login_errors
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 891, in async_update
    or email not in self.hass.data[DATA_ALEXAMEDIA]["accounts"]
AttributeError: 'NoneType' object has no attribute 'data'

````

**Additional context**

**Comment by alandtse** [comment]
This is saying hass is not populated. This is a bad thing as the component was not properly initialized by hass. Removing and re-adding the integration doesn't fix it?

**Comment by Pirol62** [comment]
I did a restart in the night and the error disappeared.
Interestingly everything worked well even this error was created.
But anyway: I will keep that under control but for now everything is fine.

**Comment by niemyjski** [comment]
I just got this exact error as well @Pirol62 with HA 2022.3.8
