### ISSUE TITLE
Sporadic AlexapyConnectionError during startup

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#1529]
**Describe the bug**
Sometimes Amazon server has trouble accepting new connections. Is such situation you are left with no Alexa Media Player entities.
The only solution is a restart of HA.

**To Reproduce**
1. Restart HA
2. Look at log

**Expected behavior**
Would be nice to trap the error and raise a "`ConfigEntryNotReady`" so that the integrations retries in the background to reconnect.

**Screenshots**

**System details**
 - Home-assistant (version): 2022.3.1
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v3.10.15
 - alexapy (version from `pip show alexapy` or HA startup): v1.25.3
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```
Logger: homeassistant.config_entries
Source: custom_components/alexa_media/__init__.py:324
Integration: Alexa Media Player ([documentation](https://github.com/custom-components/alexa_media_player/wiki), [issues](https://github.com/custom-components/alexa_media_player/issues))
First occurred: 18:52:14 (1 occurrences)
Last logged: 18:52:14

Error setting up entry <email> - amazon.it for alexa_media
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 574, in login
    if await self.test_loggedin(cookies):
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 452, in test_loggedin
    await self.get_tokens()
  File "/usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py", line 755, in get_tokens
    response = await self._session.post(
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/streams.py", line 616, in read
    await self._waiter
alexapy.aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alexa_media/__init__.py", line 324, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.9/site-packages/alexapy/helpers.py", line 147, in wrapper
    raise AlexapyConnectionError from ex
alexapy.errors.AlexapyConnectionError
**Additional context**
Add any other context about the problem here. 


```

**Comment by alandtse** [comment]
Thanks. PR would be appreciated.

**Comment by chemelli74** [comment]
PR ready ;-)

Simone
