### ISSUE TITLE
notifications return  Error handling message: Unknown error (unknown_error)

### ISSUE THREAD

**Issue by ChavasRegal** [custom-components/alexa_media_player#1594]
**Describe the bug**
using the call service to send a notification to a device fail with an error

**To Reproduce**
1. Go to 'developer tools'
2. Click on 'services'
3. fill in the relevant information
4. click call service

**Expected behavior**
send a notification to a device

**Screenshots**
![alexa error](https://user-images.githubusercontent.com/60527938/167288948-1365cda3-2de1-47f1-9e1b-d764e6360f3b.jpg)

**System details**
 - Home-assistant (version):  2022.5.2
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 3.11.3 
 - alexapy (version from `pip show alexapy` or HA startup):  WARNING: package(s) not found: alexapy
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  Y, also reauthenticated after error.

**Logs**
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/alexa_media/notify.py:216
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 09:20:08 (7 occurrences)
Last logged: 09:52:11

[140697270580560] Error handling message: Unknown error (unknown_error)
[140697260617984] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 626, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 229, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 216, in async_send_message
    if data["type"] == "tts":
TypeError: 'NoneType' object is not subscriptable

```

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/alexa_media/notify.py:216
Integration: Alexa Media Player ([documentation](https://github.com/custom-components/alexa_media_player/wiki), [issues](https://github.com/custom-components/alexa_media_player/issues))
First occurred: 09:20:07 (7 occurrences)
Last logged: 09:52:11

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 229, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 216, in async_send_message
    if data["type"] == "tts":
TypeError: 'NoneType' object is not subscriptable

```
**Additional context**

Was working fine before the 2022.5.2 update

Edit: 

Rolled back to 2022.4.7 and the problem still persists.

**Comment by pinnet** [comment]
I have the same problem

**Comment by alandtse** [comment]
Please use the Wiki provided syntax.
https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component

Your logs and screenshot show you don't have the type attribute defined.

**Comment by ChavasRegal** [comment]
> I have the same problem

so its seems I've figured out the problem, 

![image](https://user-images.githubusercontent.com/60527938/168414777-3edaa10f-a733-43ea-950f-b4776ef4f3e2.png)

this seems to work for me now.

**Comment by alandtse** [comment]
Great. It'd be helpful if you help update the wiki I linked to the extent you think it could be clearer.  The goal is everyone helps everyone else out when they figure things out. Thanks!

**Comment by ChavasRegal** [comment]
Done.

**Comment by alandtse** [comment]
Thank you!
