### ISSUE TITLE
500 error (httpx.ConnectError) when completing authentication

### ISSUE THREAD

**Issue by adifelice-godaddy** [custom-components/alexa_media_player#1607]
**Describe the bug**
Creating integration throws a 500 error page on URL: `/auth/alexamedia/proxy?config_flow_id=`

**To Reproduce**
1. Add integration
2. Fill credentials in form and complete 2FA process
3. Click the button to open another browser tab for authentication.
4. Page crashes with 500 error.

**Expected behavior**
Shows Amazon authentication.

**Screenshots**
-

**System details**
 - Home-assistant (version): 2022.6.0b1
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): v3.11.3
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/config/custom_components/alexa_media/config_flow.py", line 1113, in wrapped
    return await cls.handler(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 387, in all_handler
    resp = await getattr(self.session, method)(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1729, in get
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1506, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1593, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1621, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1658, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1695, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError
```

**Comment by adifelice-godaddy** [comment]
The exception is handled, the page now returns a `200` with the following response:
```
Connection Error! Please try refreshing. If this persists, please report this error to <a href=https://github.com/custom-components/alexa_media_player/issues>here</a>:<br /><pre></pre>
```

It's not clear what is happening.

Also, the above URL was marked by Chrome as "Phishing", from Google Search Console:
```
Description
These pages attempt to trick users into doing something dangerous, such as installing unwanted software or revealing personal information. [Learn more](https://support.google.com/webmasters/answer/9044101#phising)
Sample URLs
https://<my-domain>/?homescreen=1
https://<my-domain>/auth/authorize?response_type=code&redirect_uri=https://<my-domain>/?homescreen=1&auth_callback=1&client_id=https://<my-domain>/&state=<secret>
```

**Comment by alandtse** [comment]
Please provide the logs.

**Comment by alandtse** [comment]
If google is blocking whatever url you're using for HA, there's not much I can do for you. You need to whitelist the HA url. 

The component is using a proxy to literally hijack your amazon login process so it can capture your credentials and login on your behalf. If you don't trust the HA url, or the component, then you have bigger issues and shouldn't use the component.

**Comment by adifelice-godaddy** [comment]
Keeps showing the error. I also deleted the cookie file from `.storage` but same outcome.

Logs are not showing what happened:
```
2022-05-30 09:25:24 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating new login
2022-05-30 09:25:24 DEBUG (MainThread) [custom_components.alexa_media.helpers] a*****************e@g*******m: Returning uuid {'uuid': '1d49a959973552c7774f4d45bd935038', 'index': 0}
2022-05-30 09:25:25 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Generating OTP from 252670
2022-05-30 09:25:35 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Starting proxy for a*****************e@g*******m - amazon.com
2022-05-30 09:25:35 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Found flow_id; adding 192.168.1.1 to known_ips for 300 seconds
2022-05-30 09:25:36 WARNING (MainThread) [custom_components.alexa_media.config_flow] Detected Connection error:
```
