### ISSUE TITLE
No devices load

### ISSUE THREAD

**Issue by theOrakle** [custom-components/alexa_media_player#1613]
**Describe the bug**
Media Players & Alarm no longer load.  Last good count was 14 devices and 96 entities.  I have been using since version 1.0.  Based on the log below, I'm wondering if we changed a variable casting.  "Error fetching alexa_media data: Error communicating with API: string index out of range"

**To Reproduce**
I have attempted to delete & re-add several times with no success.  Authentication w/ MFA works every time

**Expected behavior**
Media players & alarm loads

**Screenshots**
N/A

**System details**
 - Home-assistant (version):  core-2022.5.5
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 4.0.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.6
 - Amazon [2FA is enabled]: Yes 

**Logs**
2022-05-29 08:39:33 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry  for media_player
Traceback (most recent call last):
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/components/media_player/__init__.py", line 395, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-05-29 08:39:33 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry  for switch
Traceback (most recent call last):
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/components/switch/__init__.py", line 87, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-05-29 08:39:33 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry  for sensor
Traceback (most recent call last):
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/components/sensor/__init__.py", line 246, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-05-29 08:39:33 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry  for alarm_control_panel
Traceback (most recent call last):
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/components/alarm_control_panel/__init__.py", line 119, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-05-29 08:39:33 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry  for light
Traceback (most recent call last):
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/components/light/__init__.py", line 586, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/opt/homeassistant/3.9.12/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-05-29 08:39:37 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2022-05-29 08:39:37 ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API: string index out of range

**Additional context**
Happy to turn on debugging...

**Comment by aneisch** [comment]
See the same on `2022.6.0b3`

**Comment by alandtse** [comment]
Please update to 4.0.1. If the issue persists, please provide debug logs as the template requests.
