### ISSUE TITLE
No devices loaded in the media player card

### ISSUE THREAD

**Issue by cusstom180** [custom-components/alexa_media_player#1670]
**Describe the bug**
The media player and alarm were not able in the dashboard. I have about 12 devices and over 20 entities. This is a new install and setting this up for the first time. 

**To Reproduce**
I have uninstalled and reinstalled about 5 times.

**Expected behavior**
 media player should show connected devices

**Screenshots**
<img width="323" alt="image" src="https://user-images.githubusercontent.com/29357384/180109690-c57b10c5-fa3a-4221-b85f-e0aee267d51c.png">

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/29357384/180110580-78a97fc2-d178-4a06-9ab0-025686472d87.png">

**System details**
 - Home-assistant (2022.7.6): 
 - Hassio (Yes/No): (no).
 - alexa_media  (v4.0.3):
 - alexapy (1.26.2:
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (Y). We will not debug login issues if unanswered: 

**Logs**
2022-07-20 21:13:22 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Alexa for media_player
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 492, in async_unload
result = await component.async_unload_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 433, in async_unload_entry
return await component.async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-07-20 21:13:22 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Alexa for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 492, in async_unload
result = await component.async_unload_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 87, in async_unload_entry
return await component.async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-07-20 21:13:22 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Alexa for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 492, in async_unload
result = await component.async_unload_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 246, in async_unload_entry
return await component.async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-07-20 21:13:22 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Alexa for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 492, in async_unload
result = await component.async_unload_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 603, in async_unload_entry
return await component.async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-07-20 21:13:22 WARNING (MainThread) [homeassistant.core] Unable to remove unknown service notify/alexa_media

**Additional context**
tell me what you need

**Comment by alandtse** [comment]
Please provide logs showing an install. The logs are only showing an uninstall. You may need to reboot ha after the uninstall so the logs are clean.

**Comment by cusstom180** [comment]
I reinstalled it again and there are no events in the log except a warning about HACS and alexa_media_player not tested by HA. 

I setup the authorization and it say success but never gives me an opinion to import any devices.

**Comment by alandtse** [comment]
Did you enable logging like the template described? You need to edit the configuration.yaml.

**Comment by cusstom180** [comment]
Yes. just the two warnings

**Comment by alandtse** [comment]
That's not possible based on what you described. If you had enabled the logs you would see entries from the custom component and alexapy:

```
2022-07-21 17:44:32 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating new login
2022-07-21 17:44:32 DEBUG (MainThread) [custom_components.alexa_media.helpers] ****: Returning uuid {'uuid': '5e9c8f8222d5d3495aabec99993eaa83', 'index': 0}
2022-07-21 17:44:32 DEBUG (MainThread) [alexapy.alexalogin] Login created for asdf - amazon.com
2022-07-21 17:44:32 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Starting proxy for **** - amazon.com
2022-07-21 17:44:32 DEBUG (MainThread) [alexapy.alexalogin] Attempting oauth login to https://www.amazon.com/ap/signin?openid.return_to=https://www.amazon.com/ap/maplanding&openid.assoc_handle=amzn_dp_project_dee_ios&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_ios&accountStatusPolicy=P1&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.mode=checkid_setup&openid.ns.oa2=http://www.amazon.com/ap/ext/oauth/2&openid.oa2.client_id=device:306566626537343062616331383563613332643737653533353765616262633723413249564c5635564d32573831&openid.ns.pape=http://specs.openid.net/extensions/pape/1.0&openid.oa2.response_type=token&openid.ns=http://specs.openid.net/auth/2.0&openid.pape.max_auth_age=0&openid.oa2.scope=device_auth_access&language=en_US
2022-07-21 17:44:32 DEBUG (MainThread) [alexapy.alexalogin] Unable to generate OTP; 2FA app key not configured
```

**Comment by cusstom180** [comment]
I apologize. I was signed into the wrong Amazon account. Your code is awesome, I suck as a dev.
