### ISSUE TITLE
Constructor parameter should be str

### ISSUE THREAD

**Issue by sineverba** [custom-components/alexa_media_player#1702]
**Describe the bug**
Cannot authenticate anymore.

```shell
alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f22444ec730>,), {'data': OrderedDict([('otp_secret', '3************************************************XOA'), ('email', 'a**************i@g*******m'), ('password', 'REDACTED 15 CHARS'), ('url', 'amazon.it'), ('debug', False), ('scan_interval', 60), ('include_devices', 'Camera, Salone'), ('exclude_devices', ''), ('reauth', True)])}): An error occured accessing AlexaAPI: An exception of type TypeError occurred. Arguments: ('Constructor parameter should be str',)
```

**System details**
 - Home-assistant (version): Docker - V 2022.08.7
 - alexa_media  (version from `const.py` or HA startup): 4.03 and 4.1.0
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). 2FA enabled

**Logs**
```shell
alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f22444ec730>,), {'data': OrderedDict([('otp_secret', '3************************************************XOA'), ('email', 'a**************i@g*******m'), ('password', 'REDACTED 15 CHARS'), ('url', 'amazon.it'), ('debug', False), ('scan_interval', 60), ('include_devices', 'Camera, Salone'), ('exclude_devices', ''), ('reauth', True)])}): An error occured accessing AlexaAPI: An exception of type TypeError occurred. Arguments: ('Constructor parameter should be str',)
```

**Comment by saveriospeziali** [comment]
Hi guys

[This automation ](https://github.com/custom-components/alexa_media_player/issues/1697#issuecomment-1236181530) can help a bit in the mean time

**Comment by alandtse** [comment]
Can you please enable logs per the template and then provide them?

**Comment by 42madorna** [comment]
Hi, I have this error since the last update, which doesn't let me communicate with Alexa :(

> Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alexa_media/__init__.py", line 322, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.10/site-packages/alexapy/helpers.py", line 141, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/alexapy/alexalogin.py", line 656, in login
    post_resp = await self._session.post(
  File "/usr/local/lib/python3.10/site-packages/alexapy/aiohttp/client.py", line 422, in _request
    url = self._build_url(str_or_url)
  File "/usr/local/lib/python3.10/site-packages/alexapy/aiohttp/client.py", line 356, in _build_url
    url = URL(str_or_url)
  File "/usr/local/lib/python3.10/site-packages/yarl/_url.py", line 158, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str

Home Assistant is asking me to relogin, but I see that the error comes from extension when trying to fetch auth token from Amazon
