### ISSUE TITLE
Login prompts are empty

### ISSUE THREAD

**Issue by TobyStoe** [custom-components/alexa_media_player#1703]
Hey,
i'm trying to login with the 2FA. (It already worked in the past)
But the message-box, where the code should be is empty? (see screesnhot)

![tempsnip](https://user-images.githubusercontent.com/97510125/188305711-6a9054b3-4e02-41e8-83da-1dfe7aa65008.png)

[Log_Get.txt](https://github.com/custom-components/alexa_media_player/files/9484347/Log_Get.txt)
[Log_Post.txt](https://github.com/custom-components/alexa_media_player/files/9484348/Log_Post.txt)

**Comment by javiges** [comment]
The same thing happens to me, impossible to solve

**Comment by maury77** [comment]
I have problem with continuos request of reautentication

**Comment by alandtse** [comment]
Refresh the browser cache. If that doesn't work, the string is not translated. Switch to English temporarily.

**Comment by Larry-78** [comment]
I have the same problem even after refreshing the cache. If I try to continue after clicking on the box, I am directed to the Alexa login page but if I confirm I get 500 Internal Server Error.

**Comment by alandtse** [comment]
I can't debug the 500 internal server error without logs. It's also unrelated to this issue so please open up an issue.

**Comment by TobyStoe** [comment]
> Refresh the browser cache. If that doesn't work, the string is not translated. Switch to English temporarily.

Hey, thanks for the input, but both attempts didn't change anything.

**Comment by Larry-78** [comment]
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/alexa_media/config_flow.py:870
Integration: Alexa Media Player (documentation, issues)
First occurred: 22:08:59 (5 occurrences)
Last logged: 22:17:19

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 114, in _send_request_headers
    event = h11.Request(
  File "/usr/local/lib/python3.10/site-packages/h11/_events.py", line 55, in __init__
    self.headers = _headers.normalize_and_validate(
  File "/usr/local/lib/python3.10/site-packages/h11/_headers.py", line 131, in normalize_and_validate
    validate(_field_value_re, value, "Illegal header value {!r}", value)
  File "/usr/local/lib/python3.10/site-packages/h11/_util.py", line 88, in validate
    raise LocalProtocolError(msg)
h11._util.LocalProtocolError: Illegal header value b'gzip,deflate      '

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 105, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 73, in handle_async_request
    await self._send_request_headers(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 113, in _send_request_headers
    with map_exceptions({h11.LocalProtocolError: LocalProtocolError}):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.LocalProtocolError: Illegal header value b'gzip,deflate      '

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/config/custom_components/alexa_media/config_flow.py", line 870, in wrapped
    return await cls.handler(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/authcaptureproxy/auth_capture_proxy.py", line 375, in all_handler
    resp = await getattr(self.session, method)(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1842, in post
    return await self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.LocalProtocolError: Illegal header value b'gzip,deflate      '

**Comment by alandtse** [comment]
@Larry-78 Please open a new issue and follow the template. I need logs showing how you got to this point and other information that the template requests. Again, this is off-topic in this thread.
