### ISSUE TITLE
Alexa Media Reauthentication Required

### ISSUE THREAD

**Issue by cacelotto** [custom-components/alexa_media_player#1717]
Since 2 or 3 days Alexa Media continues to ask for reauthentication. Time interval changes every time (this morning it's the 3rd time I reauthenticate since 6.40AM - Now it's 8:47 am). Then, sometimes, clicking Send in the "Alexa Player - Configuration" window, the browser doesn't open the authentication page. Instead, an "unknown error" message appears. Trying again later, it works.

I have 2FA active and it's not been a problem since a lot of time.

At the moment (9:00 am) Alexa should tell the time and remind to run the washmachine. HA runs well because I got the the persistent notification of the washmachine, but no voice from alexa.
Attached: 
- Log with error before the reauthentication request
- Log with error before telling the time/washmachine

[alexa-before-requesting-authentication.txt](https://github.com/custom-components/alexa_media_player/files/9494138/alexa-before-requesting-authentication.txt)
[alexa-before-telling-the-time.txt](https://github.com/custom-components/alexa_media_player/files/9494139/alexa-before-telling-the-time.txt)

**Comment by nwootton** [comment]
I'm having the same issue. Yesterday I got a notification that it needed reconfiguration. Did it, 2FA all worked as expected. It asked again last night and again this morning. 

This morning it gave an 'unknown error' when I initially tried to reconfigure. I restarted HA and it allowed me to reconfigure.

When I do the reconfiguration I get sent to the Amazon login pge and I also have to put in an additional 'captur' code - type the following letters/numbers into the box - before I can login.

Once logged in, the message in HA is that everything is done OK. Until the next time.

Error logs from this morning are attached in order they appear:

[alexa_error_1.log](https://github.com/custom-components/alexa_media_player/files/9494283/alexa_error_1.log)
[alexa_error_2.log](https://github.com/custom-components/alexa_media_player/files/9494284/alexa_error_2.log)
[alexa_error_3.log](https://github.com/custom-components/alexa_media_player/files/9494285/alexa_error_3.log)
[alexa_error_4.log](https://github.com/custom-components/alexa_media_player/files/9494286/alexa_error_4.log)

Messages appear to reference a JSON decode error that prevents the OAuth from working, meaning it goes back to using username/password.

**Comment by atv2016** [comment]
same, after reconfiguring it doesn't last for a day.

**Comment by Moondevil-ha** [comment]
Same here, every morning for the last 3-4 days

**Comment by EmmanuelThe74** [comment]
Same issue, it doesn't last an hour.
After 5 minutes, TTS stop working and need a reload (when it solve, not every time)

It's really frustrating at this stage

**Comment by atv2016** [comment]
Oh yes, it stopped working again. 5 minutes only this time.

**Comment by Pirol62** [comment]
Hi, we had that same issue until sunday. Its exactly the same error entry.

https://github.com/custom-components/alexa_media_player/issues/1697 

This script helps to solve the issue temporarely:
````
command_restart_alexa:
  alias: restart alexa
  sequence:
    - service: homeassistant.reload_config_entry
      data: {}
      target:
        entity_id: media_player.office
    - service: logbook.log
      data:
        name: "alexa integration"
        message: "has been reloaded"
````

**Comment by margatemarcel** [comment]
Started again for me too (UK).

**Comment by DaveTiff** [comment]
Same here, having to reauthenticat every day.

**Comment by Pirol62** [comment]
Friends please, in cas you haven'T another log or case please use a thumbs up icon on the origin post and do not add an additional comment in order to keep the thread readable and small :-)

**Comment by popy2k14** [comment]
+1 in Austria with germany server, have to reauthenticate every day.

**Comment by EmmanuelThe74** [comment]
![image](https://user-images.githubusercontent.com/108288427/188606554-1f558e44-1eb9-47b5-9145-20e4ecdec8ac.png)


Every day it's just pilling up, i will just have to find an alternative, it's so usefull i can't live without :(

**Comment by sator86** [comment]
same here

**Comment by sator86** [comment]
seems to be fixed with last update !
thank you

**Comment by KHOne23** [comment]
> 

which Version? Problem still there at 4.1.1

**Comment by atv2016** [comment]
yes i have latest updates, i'm having this

**Comment by sator86** [comment]
yes it's 4.1.1
since I installed it, no more asking to reauth
prior to that, I had to reauth every 1 hour ....
may be it's just more than 1 hour to ask again for reauth ? I don't know, but for me it's not the same behavior
I'll let you know if it'll ask again
regards

**Comment by atv2016** [comment]
Hmm i just checked i didn't have 4.1.1 yet, just installing now, let's see. Thanks!

**Comment by Pirol62** [comment]
No, see my post above. Still valid in 4.1.1

**Comment by noob6741** [comment]
+1
Same here (germany/amazon.de).
Updated yesterday to 4.1.1, worked for 12 Hours

**Comment by tempus2016** [comment]
UK user with a couple of different errors.  Was working fine for around 24 hours.

Reauthenticate [b*****k](mailto:b*****k) on the [Integrations](http://homeassistant.local:8123/config/integrations) page. Relogin required after 1 day, 0:55:26.778922 and 1036 api calls.:

`This error originated from a custom integration.

Logger: alexapy.helpers
Source: custom_components/alexa_media/__init__.py:721
Integration: Alexa Media Player (documentation, issues)
First occurred: 16:09:49 (4 occurrences)
Last logged: 16:57:33

alexaapi.get_activities((<alexapy.alexalogin.AlexaLogin object at 0x7f757ef250>, 10), {}): A login error occured: An exception of type JSONDecodeError occurred. Arguments: ('Expecting value: line 1 column 1 (char 0)',)
alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f757ef250>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ()
alexaapi.get_activities((<alexapy.alexalogin.AlexaLogin object at 0x7f757ef250>, 10), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)
alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f757ef250>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)`

`This error originated from a custom integration.

Logger: alexapy.helpers
Source: custom_components/alexa_media/media_player.py:621
Integration: Alexa Media Player (documentation, issues)
First occurred: 16:57:37 (1 occurrences)
Last logged: 16:57:37

alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f794f6a10>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)`

`This error originated from a custom integration.

Logger: alexapy.alexalogin
Source: custom_components/alexa_media/config_flow.py:434
Integration: Alexa Media Player (documentation, issues)
First occurred: 16:57:52 (1 occurrences)
Last logged: 16:57:52

No access token found; falling back to credential login instead of oauth.`

`This error originated from a custom integration.

Logger: alexapy.helpers
Source: custom_components/alexa_media/config_flow.py:434
Integration: Alexa Media Player (documentation, issues)
First occurred: 16:57:54 (1 occurrences)
Last logged: 16:57:54

alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f757ef250>,), {'data': OrderedDict([('otp_secret', 'Z************************************************BTQ'), ('email', 'b*******9@h***********k'), ('password', 'REDACTED 9 CHARS'), ('url', 'amazon.co.uk'), ('debug', False), ('scan_interval', 60), ('include_devices', ''), ('exclude_devices', ''), ('reauth', True)])}): An error occured accessing AlexaAPI: An exception of type TypeError occurred. Arguments: ('Constructor parameter should be str',)`

`This error originated from a custom integration.

Logger: custom_components.alexa_media.config_flow
Source: custom_components/alexa_media/config_flow.py:542
Integration: Alexa Media Player (documentation, issues)
First occurred: 16:57:54 (1 occurrences)
Last logged: 16:57:54

Unknown error: Constructor parameter should be str`

**Comment by netzbus** [comment]
+1

**Comment by Nebur692** [comment]
Same error v4.1.1

`Este error se originó a partir de una integración personalizada.

Logger: aiohttp.server
Source: custom_components/alexa_media/config_flow.py:252
Integration: Alexa Media Player (documentation, issues)
First occurred: 6 de septiembre de 2022, 18:21:24 (9 occurrences)
Last logged: 6 de septiembre de 2022, 23:57:28

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/alexa_media/config_flow.py", line 252, in async_step_user
    async with session.get(hass_url) as resp:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 422, in _request
    url = self._build_url(str_or_url)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 356, in _build_url
    url = URL(str_or_url)
  File "/usr/local/lib/python3.10/site-packages/yarl/_url.py", line 158, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str
`

**Comment by dpembo** [comment]
@alandtse 
I got one notification last night that a re-auth was needed, but it recovered itself (UK), and the custom compenent is still functioning

I'd left the debug log config on, and the only entries I can see which show an issue are:
2```
022-09-07 03:38:15.599 DEBUG (MainThread) [alexapy.alexaapi] *@*: static GET: https://alexa.amazon.co.uk/api/activities?startTime=&size=10&offset=1 returned 400:Bad Request:application/octet-stream
2022-09-07 03:38:15.599 WARNING (MainThread) [alexapy.helpers] alexaapi.get_activities((<alexapy.alexalogin.AlexaLogin object at 0x7f5f5c576b60>, 10), {}): A login error occured: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 1 column 1 (char 0)',)
2022-09-07 03:38:15.601 WARNING (MainThread) [alexapy.helpers] alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f5f5c576b60>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
()
```

**Comment by maury77** [comment]
![image](https://user-images.githubusercontent.com/35746732/188800735-7baa155e-062e-4a61-a58c-840871afdcf6.png)

![image](https://user-images.githubusercontent.com/35746732/188800831-80680b49-57fe-470b-8914-15de5fbf3497.png)

the versio in 4.1.1

**Comment by Pirol62** [comment]
@maury77 
What I did and what worked here: 
- Reload the config with the script shown above if your alexa is already not working
- Check if your alexa is working. If yes:
- restart HA. The dead entries disappeared.

**Comment by Moondevil-ha** [comment]
After updating to 4.1.1, restarting I still had dead entries. However, a full reboot of the host (I run on Nuc) appears to have removed the issue, everything is still working this morning

**Comment by alandtse** [comment]
> @alandtse I got one notification last night that a re-auth was needed, but it recovered itself (UK), and the custom compenent is still functioning
> 
> I'd left the debug log config on, and the only entries I can see which show an issue are:
> 
> ```
> 2022-09-07 03:38:15.599 DEBUG (MainThread) [alexapy.alexaapi] *@*: static GET: https://alexa.amazon.co.uk/api/activities?startTime=&size=10&offset=1 returned 400:Bad Request:application/octet-stream
> 2022-09-07 03:38:15.599 WARNING (MainThread) [alexapy.helpers] alexaapi.get_activities((<alexapy.alexalogin.AlexaLogin object at 0x7f5f5c576b60>, 10), {}): A login error occured: An exception of type JSONDecodeError occurred. Arguments:
> ('Expecting value: line 1 column 1 (char 0)',)
> 2022-09-07 03:38:15.601 WARNING (MainThread) [alexapy.helpers] alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f5f5c576b60>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
> ()
> ```

I just wanted to note that this is actually something I can act on. Thanks.

**Comment by nwootton** [comment]
4.1.1 update didn't work with just a HA restart. I still got a re-auth request.

Doing a complete host reboot however has meant that it's been quiet since yesterday afternoon and overnight.

**Comment by popy2k14** [comment]
Guys, in my case 4.1.1 also doesnt work. After a few hours, same again.

Also after reauth playing a radio station works, but not pause the media player.
Does pause work on your side?

thx

**Comment by dpembo** [comment]
@alandtse - just to comment - no repeat of any re-auth issues since the fix - thank you

**Comment by popy2k14** [comment]
Same here, looking good.

thx

**Comment by jonrupell** [comment]
same for me as well. Hopefully they can fix soon!
