### ISSUE TITLE
2 new errors that arise during startup after update to latest version w/ 2022.9

### ISSUE THREAD

**Issue by Petro31** [custom-components/alexa_media_player#1722]
**Describe the bug**
There's 2 errors in the logs, it doesn't seem like I have control over these errors.

**To Reproduce**
I'm not sure if this can be reproduced, but the errors themselves are pretty easy to follow.

Error 1: discovery info doesn't have ["config"]["email"], no check for it.
Error 2:  the hass object is none when it shouldn't be.

**Expected behavior**
No errors in logs.

**Screenshots**
NA

**System details**
 - Home-assistant (version): 2022.9
 - Hassio (Yes/No): Supervised.
 - alexa_media  (version from `const.py` or HA startup): 4.1.2
 - alexapy (version from `pip show alexapy` or HA startup): 1.26.3
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Y

**Logs**
Error 1
```
2022-09-08 19:19:22.473 ERROR (MainThread) [homeassistant.components.switch] Error while setting up alexa_media platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alexa_media/switch.py", line 44, in async_setup_platform
    account = config[CONF_EMAIL] if config else discovery_info["config"][CONF_EMAIL]
KeyError: 'email'

```

Error 2
```
2022-09-08 19:20:58.366 ERROR (MainThread) [homeassistant] Error doing job: _GatheringFuture exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/helpers.py", line 156, in _catch_login_errors
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 894, in async_update
    or email not in self.hass.data[DATA_ALEXAMEDIA]["accounts"]
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by alandtse** [comment]
Thanks. At this point the component is in a pretty bad state. We can catch for it, but it'll be non functional since even the hass entity is None. hass should always be valid. I'll add it to the backlog of things to catch.

**Comment by JB09** [comment]
I am also getting a NoneType error, but looks a little different->

`Logger: custom_components.alexa_media
Source: custom_components/alexa_media/__init__.py:546
Integration: Alexa Media Player (documentation, issues)

Unexpected error fetching alexa_media data: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alexa_media/__init__.py", line 546, in async_update_data
    if "doNotDisturbDeviceStatusList" in dnd:
TypeError: argument of type 'NoneType' is not iterable`

**Comment by vaibhav2912** [comment]
I am also getting the dnd error on every restart

```
2022-09-15 08:00:15.964 ERROR (MainThread) [custom_components.alexa_media] Unexpected error fetching alexa_media data: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
return await self.update_method()
File "/config/custom_components/alexa_media/__init__.py", line 546, in async_update_data
if "doNotDisturbDeviceStatusList" in dnd:
TypeError: argument of type 'NoneType' is not iterable

**Comment by bobofruit1970** [comment]
The same for me.

Logger: custom_components.alexa_media
Source: custom_components/alexa_media/__init__.py:546
Integration: Alexa Media Player ([documentation](https://github.com/custom-components/alexa_media_player/wiki), [issues](https://github.com/custom-components/alexa_media_player/issues))
First occurred: 19:30:27 (1 occurrences)
Last logged: 19:30:27

Unexpected error fetching alexa_media data: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alexa_media/__init__.py", line 546, in async_update_data
    if "doNotDisturbDeviceStatusList" in dnd:
TypeError: argument of type 'NoneType' is not iterable

**Comment by Petro31** [comment]
issue cleared itself up
