### ISSUE TITLE
component wouldn't load, deleted and redownloaded, now can't use the integrations page and component won't work

### ISSUE THREAD

**Issue by mikebroadway71** [custom-components/alexa_media_player#1733]
**Describe the bug**
After updating to most recent versions of core, os, and this component, component wouldn't load.  
Error received was Component error: alexa_media - Exception importing custom_components.alexa_media

deleted component and redownloaded.  When going to integrations to setup, get:

This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.

Tried latest version, and latest known working for my setup (4.1.0) and in between (4.1.1).

Tried manual install by changing configurations.yaml, but get same error ( Component error: alexa_media - Exception importing custom_components.alexa_media)

**To Reproduce**
Delete non-working component and try to reinstall
goto integrations to setup, but receive not working message
try to install with manual changes in configurations.yaml

**Expected behavior**
Installs as expected and integrations page setup works

**Screenshots**

**System details**
 - Home-assistant 2022.9.5
 - alexa_media  various versions but currently 4.1.2
 - alexapy (version from `pip show alexapy` or HA startup): not sure what this means???
 - Amazon [2FA is enabled](y): 

**Logs**

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 662, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.10/site-packages/alexapy/__init__.py", line 18, in <module>
    from .alexaproxy import AlexaProxy
  File "/usr/local/lib/python3.10/site-packages/alexapy/alexaproxy.py", line 25, in <module>
    class AlexaProxy(authcaptureproxy.AuthCaptureProxy):
AttributeError: module 'authcaptureproxy' has no attribute 'AuthCaptureProxy'

**Comment by alandtse** [comment]
Make sure you don't have a random installation of the dependencies either in you /config or installed. The errors indicate you have an unexpected version installed. You can remove them and then readd the integration. It will then add the correct versions.

Your dependencies should be:
```
alexapy==1.26.3
authcaptureproxy=1.1.4
```

**Comment by mikebroadway71** [comment]
I appreciate your swift response, but I don't know what you mean.  Where would these files be?  And if I deleted the custom_component\alexa_media folder and reinstalled, would that fix the problem?

**Comment by mikebroadway71** [comment]
I'm not sure how to find those files, I tried following the folder structure in my post above, but had no luck.  Could you explain further?

**Comment by newyork167** [comment]
Just an update having ran into this, I was able to fix by making the following update to my alexapy package's alexaproxy.py:
https://gitlab.com/newyork167/alexapy/-/commit/5eb2654eb59e73fac415b2f3f58f2ce0b704e99e

Looks like at some point they moved from authcaptureproxy.AuthCaptureProxy to `authcaptureproxy.auth_capture_proxy.AuthCaptureProxy`

**Comment by alandtse** [comment]
> Just an update having ran into this, I was able to fix by making the following update to my alexapy package's alexaproxy.py: https://gitlab.com/newyork167/alexapy/-/commit/5eb2654eb59e73fac415b2f3f58f2ce0b704e99e
> 
> Looks like at some point they moved from authcaptureproxy.AuthCaptureProxy to `authcaptureproxy.auth_capture_proxy.AuthCaptureProxy`

I'm glad it worked for you, but that shouldn't have been necessary as AuthCaptureProxy is already in the main namespace. https://github.com/alandtse/auth_capture_proxy/blob/main/authcaptureproxy/__init__.py#L17

**Comment by newyork167** [comment]
Agreed, weird that it is not picking that up. I was getting the following error when home assistant would boot up:
`AttributeError: module 'authcaptureproxy' has no attribute 'AuthCaptureProxy'`. 

This is with packages:
- alexapy==1.26.5 
- authcaptureproxy==1.1.4.
