### ISSUE TITLE
string index out of range on login

### ISSUE THREAD

**Issue by mmillmor** [custom-components/alexa_media_player#1778]
**IMPORTANT:  Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
I have an alexa_media_player integration that has been running fine for some time. I use 2FA login and it was stable. Recently (perhaps today) it stopped working. I got a notification that the service notify.alexa_media didn't exist. My entities don't seem to be valid any more either

**To Reproduce**
1. Log in to the service

**Expected behavior**
I have 8 echos which should be shown

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

 - alexa_media  4.3.2:
 - alexapy (version from `pip show alexapy` or HA startup): 1.26.4
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes

**Logs**
```
2022-11-11 18:03:55.613 DEBUG (MainThread) [custom_components.alexa_media] m****n@m**********t: Websocket successfully connected
2022-11-11 18:03:55.613 DEBUG (MainThread) [custom_components.alexa_media] m****n@m**********t: Creating coordinator
2022-11-11 18:03:55.613 DEBUG (MainThread) [custom_components.alexa_media] m****n@m**********t: Refreshing coordinator
2022-11-11 18:03:55.614 DEBUG (MainThread) [alexapy.alexawebsocket] Starting message parsing loop.
2022-11-11 18:03:55.615 DEBUG (MainThread) [alexapy.alexawebsocket] Received raw WebSocket: b'0x37a1b607 0x0000009c {"protocolName":"A:F","parameters":{"AlphaProtocolHandler.maxFragmentSize":"16000","AlphaProtocolHandler.receiveWindowSize":"16"}}TUNE'
2022-11-11 18:03:55.617 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding WebSocket Handshake MSG.
2022-11-11 18:03:55.617 DEBUG (MainThread) [alexapy.alexawebsocket] 0xfe88bc52 0x0000009c {"protocolName":"A:F","parameters":{"AlphaProtocolHandler.receiveWindowSize":"16","AlphaProtocolHandler.maxFragmentSize":"16000"}}TUNE
2022-11-11 18:03:55.618 DEBUG (MainThread) [alexapy.alexawebsocket] A:F Initialization Msg 2 sent: redacted
2022-11-11 18:03:55.672 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding Gateway Register MSG.
2022-11-11 18:03:55.676 DEBUG (MainThread) [alexapy.alexawebsocket] bytearray(b'MSG\redacted1 urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService {"command":"REGISTER_CONNECTION"}FABE')
2022-11-11 18:03:55.677 DEBUG (MainThread) [alexapy.alexawebsocket] A:F Initialization Msg 3 (Register Connection) sent: redacted
2022-11-11 18:03:55.729 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding PING.
2022-11-11 18:03:55.731 DEBUG (MainThread) [alexapy.alexawebsocket] bytearray(b'MSGredacted')
2022-11-11 18:03:55.731 DEBUG (MainThread) [alexapy.alexawebsocket] Send First Ping: redacted
2022-11-11 18:03:55.734 DEBUG (MainThread) [alexapy.alexaapi] m****n@m**********t: static GET: https://alexa.amazon.co.uk/api/phoenix returned 200:OK:application/json
2022-11-11 18:03:55.734 DEBUG (MainThread) [alexapy.alexaapi] m****n@m**********t: get_network_details response: {'locationDetails': {'locationDetails': {'Default_Location': {'locationId': 'Default_Location', 'amazonBridgeDetails': {'amazonBridgeDetails': {}}, 'applianceGroups': {'applianceGroups': {}}}}}, 'version': '1.0', 'relations': []}
2022-11-11 18:03:55.755 DEBUG (MainThread) [alexapy.alexaapi] m****n@m**********t: static GET: https://alexa.amazon.co.uk/api/bootstrap returned 200:OK:application/json
2022-11-11 18:03:55.832 DEBUG (MainThread) [alexapy.alexawebsocket] Received raw WebSocket: b'MSGredacted'
2022-11-11 18:03:56.469 DEBUG (MainThread) [alexapy.alexaapi] m****n@m**********t: static GET: https://alexa.amazon.co.uk/api/dnd/device-status-list returned 200:OK:application/json
2022-11-11 18:03:56.470 DEBUG (MainThread) [alexapy.alexaapi] m****n@m**********t: static GET: https://alexa.amazon.co.uk/api/devices-v2/device returned 200:OK:application/json
2022-11-11 18:03:56.472 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding PING.
2022-11-11 18:03:56.472 DEBUG (MainThread) [alexapy.alexawebsocket] bytearray(b"MSGredacted")
2022-11-11 18:03:56.473 DEBUG (MainThread) [alexapy.alexawebsocket] Send Second Ping: redacted
2022-11-11 18:03:56.769 DEBUG (MainThread) [alexapy.alexaapi] m****n@m**********t: static GET: https://alexa.amazon.co.uk/api/device-preferences returned 200:OK:application/json
2022-11-11 18:03:56.974 DEBUG (MainThread) [alexapy.alexawebsocket] Received raw WebSocket: b'MSG\redacted'
2022-11-11 18:03:57.016 DEBUG (MainThread) [alexapy.alexaapi] m****n@m**********t: static GET: https://alexa.amazon.co.uk/api/bluetooth?cached=false returned 200:OK:application/json
2022-11-11 18:03:57.018 DEBUG (MainThread) [custom_components.alexa_media] Alexa entities have been loaded. Prepared for discovery.
2022-11-11 18:03:57.018 DEBUG (MainThread) [custom_components.alexa_media] m****n@m**********t: Found 27 devices, 27 bluetooth
2022-11-11 18:03:57.683 DEBUG (MainThread) [alexapy.alexaapi] m****n@m**********t: static GET: https://alexa.amazon.co.uk/api/notifications returned 200:OK:application/json
2022-11-11 18:03:57.684 DEBUG (MainThread) [custom_components.alexa_media] m****n@m**********t: Updated 0 notifications for 1 devices at 2022-11-11 18:03:57.684237+00:00
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
await task
TypeError: float() argument must be a string or a real number, not 'NoneType'
2022-11-11 18:03:57.929 DEBUG (MainThread) [alexapy.alexaapi] m****n@m**********t: static GET: https://alexa.amazon.co.uk/api/activities?startTime=&size=10&offset=1 returned 200:OK:application/json
2022-11-11 18:03:57.932 WARNING (MainThread) [alexapy.helpers] alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f542c428f10>,), {}): An error occured accessing AlexaAPI: An exception of type IndexError occurred. Arguments:
('string index out of range',)
2022-11-11 18:03:57.938 ERROR (MainThread) [custom_components.alexa_media] Error fetching alexa_media data: Error communicating with API: string index out of range
2022-11-11 18:03:57.939 DEBUG (MainThread) [custom_components.alexa_media] Finished fetching alexa_media data in 2.326 seconds (success: False)
```

**Additional context**

**Comment by alandtse** [comment]
This is having the error in HA so it's harder to debug. Is this still happening? If it is, I might need to get the json info for https://alexa.amazon.co.uk/api/notifications. It's large and you'll need to clear out sensitive info.

**Comment by mmillmor** [comment]
This no longer reproduces. Closing
