### ISSUE TITLE
Exception raised when setting/canceling timers

### ISSUE THREAD

**Issue by rlippmann** [custom-components/alexa_media_player#1781]
**IMPORTANT:  Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Exception raised when setting timers
**To Reproduce**

Set timer, exception raised, entities not updated
**Expected behavior**

Timer info filled in
**Screenshots**

**System details**
 - Home-assistant (version):  2022.11.2
 - alexa_media  (version from `const.py` or HA startup): 4.3.2
 - alexapy (version from `pip show alexapy` or HA startup): 
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : 
Yes
**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). 

Logger: homeassistant.util.logging
Source: util/logging.py:168 
First occurred: 9:40:18 PM (18 occurrences) 
Last logged: 9:40:47 PM

Exception in _handle_event when dispatching 'alexa_media_r*******n@h*********': ({'notification_update': {'destinationUserId': 'A8JNNMF8MTF6S', 'dopplerId': {'deviceType': 'AA1IN44SS3X6O', 'deviceSerialNumber': 'dee1ccf902754e99837eaf17394bfdad'}, 'notificationId': '99bacba0-a084-3013-869c-95c362e5338a', 'notificationVersion': 3, 'eventType': 'UPDATE'}},) Traceback (most recent call last): File "/config/custom_components/alexa_media/sensor.py", line 454, in _handle_event self.async_schedule_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 688, in async_schedule_update_ha_state self.hass.async_create_task(self.async_update_ha_state(force_refresh)) File "/usr/src/homeassistant/homeassistant/core.py", line 511, in async_create_task task = self.loop.create_task(target) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 438, in create_task task = tasks.Task(coro, loop=self, name=name) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 752, in call_soon self._check_thread() File "/usr/local/lib/python3.10/asyncio/base_events.py", line 789, in _check_thread raise RuntimeError( RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
Exception in _handle_event when dispatching 'alexa_media_r*******n@h*********': ({'notification_update': {'destinationUserId': 'A8JNNMF8MTF6S', 'dopplerId': {'deviceType': 'AA1IN44SS3X6O', 'deviceSerialNumber': 'dee1ccf902754e99837eaf17394bfdad'}, 'notificationId': '99bacba0-a084-3013-869c-95c362e5338a', 'notificationVersion': 4, 'eventType': 'UPDATE'}},) Traceback (most recent call last): File "/config/custom_components/alexa_media/sensor.py", line 454, in _handle_event self.async_schedule_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 688, in async_schedule_update_ha_state self.hass.async_create_task(self.async_update_ha_state(force_refresh)) File "/usr/src/homeassistant/homeassistant/core.py", line 511, in async_create_task task = self.loop.create_task(target) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 438, in create_task task = tasks.Task(coro, loop=self, name=name) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 752, in call_soon self._check_thread() File "/usr/local/lib/python3.10/asyncio/base_events.py", line 789, in _check_thread raise RuntimeError( RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
Exception in _handle_event when dispatching 'alexa_media_r*******n@h*********': ({'notification_update': {'destinationUserId': 'A8JNNMF8MTF6S', 'dopplerId': {'deviceType': 'AA1IN44SS3X6O', 'deviceSerialNumber': 'dee1ccf902754e99837eaf17394bfdad'}, 'notificationId': '99bacba0-a084-3013-869c-95c362e5338a', 'notificationVersion': 5, 'eventType': 'UPDATE'}},) Traceback (most recent call last): File "/config/custom_components/alexa_media/sensor.py", line 454, in _handle_event self.async_schedule_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 688, in async_schedule_update_ha_state self.hass.async_create_task(self.async_update_ha_state(force_refresh)) File "/usr/src/homeassistant/homeassistant/core.py", line 511, in async_create_task task = self.loop.create_task(target) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 438, in create_task task = tasks.Task(coro, loop=self, name=name) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 752, in call_soon self._check_thread() File "/usr/local/lib/python3.10/asyncio/base_events.py", line 789, in _check_thread raise RuntimeError( RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
Exception in _handle_event when dispatching 'alexa_media_r*******n@h*********': ({'notification_update': {'destinationUserId': 'A8JNNMF8MTF6S', 'dopplerId': {'deviceType': 'AA1IN44SS3X6O', 'deviceSerialNumber': 'dee1ccf902754e99837eaf17394bfdad'}, 'notificationId': '0f460fa0-43d0-328c-baa1-63123f2e0a16', 'notificationVersion': 4, 'eventType': 'UPDATE'}},) Traceback (most recent call last): File "/config/custom_components/alexa_media/sensor.py", line 454, in _handle_event self.async_schedule_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 688, in async_schedule_update_ha_state self.hass.async_create_task(self.async_update_ha_state(force_refresh)) File "/usr/src/homeassistant/homeassistant/core.py", line 511, in async_create_task task = self.loop.create_task(target) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 438, in create_task task = tasks.Task(coro, loop=self, name=name) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 752, in call_soon self._check_thread() File "/usr/local/lib/python3.10/asyncio/base_events.py", line 789, in _check_thread raise RuntimeError( RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
Exception in _handle_event when dispatching 'alexa_media_r*******n@h*********': ({'notification_update': {'destinationUserId': 'A8JNNMF8MTF6S', 'dopplerId': {'deviceType': 'AA1IN44SS3X6O', 'deviceSerialNumber': 'dee1ccf902754e99837eaf17394bfdad'}, 'notificationId': '0f460fa0-43d0-328c-baa1-63123f2e0a16', 'notificationVersion': 5, 'eventType': 'UPDATE'}},) Traceback (most recent call last): File "/config/custom_components/alexa_media/sensor.py", line 454, in _handle_event self.async_schedule_update_ha_state(True) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 688, in async_schedule_update_ha_state self.hass.async_create_task(self.async_update_ha_state(force_refresh)) File "/usr/src/homeassistant/homeassistant/core.py", line 511, in async_create_task task = self.loop.create_task(target) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 438, in create_task task = tasks.Task(coro, loop=self, name=name) File "/usr/local/lib/python3.10/asyncio/base_events.py", line 752, in call_soon self._check_thread() File "/usr/local/lib/python3.10/asyncio/base_events.py", line 789, in _check_thread raise RuntimeError( RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one

**Additional context**

**Comment by rlippmann** [comment]
I think the issue was caused by pydebug being on.  Seems to be working now.
