### ISSUE TITLE
AttributeError: module 'wrapt' has no attribute 'decorator'

### ISSUE THREAD

**Issue by jeremyj84** [custom-components/alexa_media_player#1813]
I am seeing the following issue when loading the intergration using Home Assistant 2022.12.8 in docker

2022-12-27 16:20:57.703 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 709, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 49, in <module>
    from .config_flow import in_progess_instances
  File "/config/custom_components/alexa_media/config_flow.py", line 64, in <module>
    from .helpers import calculate_uuid
  File "/config/custom_components/alexa_media/helpers.py", line 143, in <module>
    @wrapt.decorator
AttributeError: module 'wrapt' has no attribute 'decorator'
2022-12-27 16:20:57.708 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration alexa_media: Unable to import component: Exception importing custom_components.alexa_media

_Originally posted by @jeremyj84 in https://github.com/custom-components/alexa_media_player/issues/1808#issuecomment-1366257485_

Results of pipdeptree -r -p wrapt

wrapt==1.14.1
  - aiobotocore==2.1.0 [requires: wrapt>=1.10.10]
  - Deprecated==1.2.13 [requires: wrapt>=1.10,<2]
    - jwcrypto==1.4.2 [requires: deprecated]
      - python-jwt==4.0.0 [requires: jwcrypto>=1.4.2]
        - Pyrebase4==4.6.0 [requires: python-jwt>=2.0.1]
          - thermoworks-smoke==0.1.8 [requires: pyrebase4>=4.3.0]
    - melnor-bluetooth==0.0.20 [requires: Deprecated>=1.2.13]
    - openevsewifi==1.1.2 [requires: Deprecated>=1.2.10,<2.0.0]

**Comment by alandtse** [comment]
There's something wrong with your wrapt installation. The error is literally referring to the basic use case of wrapt. https://github.com/GrahamDumpleton/wrapt/blob/1.14.1/README.rst#quick-start

You can try testing in your dev container. If you don't see something like this identifying the decorator function, then it confirms somethings really wrong with your wrapt.

```python
vscode ➜ /workspaces/home-assistant $ python3
Python 3.9.16 (main, Dec  8 2022, 01:43:07) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wrapt
>>> wrapt.decorator
<function decorator at 0xffffa7d9f4c0>
```

**Comment by jeremyj84** [comment]
Thank you for the hint, I went into the container and forcefully reinstalled wrapt and now it works as intended. I am not entirely sure how it ended up in the broken state.
