### ISSUE TITLE
Unable to delete Alexa Media Player integration

### ISSUE THREAD

**Issue by rogersmj** [custom-components/alexa_media_player#1826]
**Describe the bug**

I no longer use Alexa devices, and I want to clean up my HA instance to get rid of the 60+ entities exposed through the Alexa Media Player integration. I have long ago marked the integration as "disabled", but I am unable to delete it.

**To Reproduce**

1. In HA, go to Settings -> Devices and Services -> Integrations
2. Click on the three dots on the Alexa Media Player integration and select Delete
![image](https://user-images.githubusercontent.com/20134/212366388-e7e8cd47-62b8-4c96-8a74-e979e0c225b4.png)

3. Nothing happens. Go to Settings -> System -> Logs and see error:
![image](https://user-images.githubusercontent.com/20134/212366215-92a00bad-aa01-49e8-8b0d-19f459c56391.png)

**Expected behavior**

The Integration is deleted

**Screenshots**
See above

**System details**

- Home-assistant (version): 2023.1.2
- alexa_media (version from `const.py` or HA startup): 4.5.0 (also had this issue when I was previously on a 3.x version)
- alexapy (version from `pip show alexapy` or HA startup): Initially this command said that the package was not found. So I ran `pip install alexapy`, it installed, I rebooted HA, and now `pip show alexapy` reports version `1.26.4`
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

Each time I attempt to delete the integration, this is what appears in the logs:

```
Logger: aiohttp.server
Source: custom_components/alexa_media/__init__.py:16
Integration: Alexa Media Player ([documentation](https://github.com/custom-components/alexa_media_player/wiki), [issues](https://github.com/custom-components/alexa_media_player/issues))
First occurred: 11:17:02 AM (1 occurrences)
Last logged: 11:17:02 AM
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 86, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 968, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 569, in async_remove
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 725, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
ModuleNotFoundError: No module named 'alexapy'
```

**Additional context**

1. I recently updated Alexa Media Player in HACS and rebooted HA in an attempt to resolve the problem. No change.
2. I manually installed alexapy via an SSH session (see above under System Details), rebooted, still got the same error

**Comment by alandtse** [comment]
Make sure you do pip install instead the HASS container. The fact you're still seeing no module found is showing it's not available. Another option may be to [manually install alexapy in /config/](https://github.com/custom-components/alexa_media_player/wiki/FAQ#modulenotfounderror-no-module-named-alexapy), perform the delete, and then delete alexapy.

HA should automatically install all dependencies if you try to add the integration a second time. The add action should force it to install any missing dependencies. You shouldn't have to actually log in.

**Comment by rogersmj** [comment]
> HA should automatically install all dependencies if you try to add the integration a second time. The add action should force it to install any missing dependencies. 

Heh, that did it. I clicked in Integrations to add the integration again, it spun for a few seconds, then I canceled out of the new integration setup and was able to delete the existing one. Never occurred to me. Thanks!
