### ISSUE TITLE
4.5.1 made Indoor Air Quality Sensor unavailable after a few moments 

### ISSUE THREAD

**Issue by KC-inDomus** [custom-components/alexa_media_player#1830]
**Describe the bug**

After a good start of the custom component with fully retrived data from the IAQS sensors set, they become unavailable.

**System details**

- Home-assistant (version): 2023.1.4
- alexa_media (version from `const.py` or HA startup): 4.5.1

**Logs**
```
2023-01-14 11:10:10.318 ERROR (MainThread) [custom_components.alexa_media] Unexpected error fetching alexa_media data: 'TemperatureSensor' object has no attribute 'alexa_entity_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alexa_media/__init__.py", line 404, in async_update_data
    entities_to_monitor.add(temp.alexa_entity_id)
AttributeError: 'TemperatureSensor' object has no attribute 'alexa_entity_id'
2023-01-14 11:17:38.067 ERROR (MainThread) [custom_components.alexa_media] Unexpected error fetching alexa_media data: 'TemperatureSensor' object has no attribute 'alexa_entity_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alexa_media/__init__.py", line 404, in async_update_data
    entities_to_monitor.add(temp.alexa_entity_id)
AttributeError: 'TemperatureSensor' object has no attribute 'alexa_entity_id'
2023-01-14 11:20:10.323 ERROR (MainThread) [custom_components.alexa_media] Unexpected error fetching alexa_media data: 'TemperatureSensor' object has no attribute 'alexa_entity_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alexa_media/__init__.py", line 404, in async_update_data
    entities_to_monitor.add(temp.alexa_entity_id)
AttributeError: 'TemperatureSensor' object has no attribute 'alexa_entity_id'

```

**Comment by KC-inDomus** [comment]
Now (4.5.2) working like a charm 👍
