### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Buddinski88** [custom-components/alexa_media_player#1881]
**Describe the bug**

Errors are continuously generated in the homeassistant.log.

**To Reproduce**

There are no concrete steps that can be traced.

**Expected behavior**

No error message in the log, as the integration works so far from my point of view.

**System details**

- Home-assistant (version): 2023.3.3
- alexa_media (version from `const.py` or HA startup): 4.6.2
- alexapy (version from `pip show alexapy` or HA startup): latest
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : yes

**Logs**

```
Logger: homeassistant
Source: components/alexa/state_report.py:146
First occurred: 06:15:34 (256 occurrences)
Last logged: 06:28:22

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 104, in async_entity_state_listener
    await async_send_changereport_message(
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 146, in async_send_changereport_message
    response = await session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 423, in _request
    url = self._build_url(str_or_url)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 357, in _build_url
    url = URL(str_or_url)
  File "/usr/local/lib/python3.10/site-packages/yarl/_url.py", line 154, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str
```

**Comment by alandtse** [comment]
Report this to HA. It's not from the custom component.
