### ISSUE TITLE
Multiple errors during startup "Error while setting up alexa_media platform for ......"

### ISSUE THREAD

**Issue by alexisspencer** [custom-components/alexa_media_player#1889]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

During startup of Home Assistant, multiple errors appear from the Alexa Media Player integration:
"Error while setting up alexa_media platform for switch"
"Error while setting up alexa_media platform for sensor"
"Error while setting up alexa_media platform for alarm_control_panel"
"Error while setting up alexa_media platform for light"
"Error while setting up alexa_media platform for binary_sensor"
"Exception in discovery_platform_listener when dispatching 'discovery.platform_discovered_load_platform.notify'...."
As a result, the integration does not load on a restart of Home Assistant.

**To Reproduce**

I'm not sure what to put here except that it happens on restart every time.

**Expected behavior**

No errors in logs and the integration loads in restart of HASS

**Screenshots**
N/A

**System details**

- Home-assistant (version): 2023.3.5
- alexa_media (version from `const.py` or HA startup): 4.6.2
- alexapy (version from `pip show alexapy` or HA startup): 1.26.5
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). y

**Logs**
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alexa_media/switch.py", line 44, in async_setup_platform
    account = config[CONF_EMAIL] if config else discovery_info["config"][CONF_EMAIL]
KeyError: 'email'
`

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alexa_media/sensor.py", line 67, in async_setup_platform
    account = config[CONF_EMAIL] if config else discovery_info["config"][CONF_EMAIL]
KeyError: 'email'
`

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alexa_media/alarm_control_panel.py", line 53, in async_setup_platform
    account = config[CONF_EMAIL] if config else discovery_info["config"][CONF_EMAIL]
KeyError: 'email'`

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alexa_media/light.py", line 72, in async_setup_platform
    account = config[CONF_EMAIL] if config else discovery_info["config"][CONF_EMAIL]
KeyError: 'email'
`

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alexa_media/binary_sensor.py", line 36, in async_setup_platform
    account = config[CONF_EMAIL] if config else discovery_info["config"][CONF_EMAIL]
KeyError: 'email'
`

`Exception in discovery_platform_listener when dispatching 'discovery.platform_discovered_load_platform.notify': ({'service': 'load_platform.notify', 'platform': 'alexa_media', 'discovered': {'name': 'alexa_media', 'config': {}}},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 115, in discovery_platform_listener await task File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 134, in async_platform_discovered await async_setup_platform(platform, discovery_info=info) File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 123, in async_setup_platform await notify_service.async_register_services() File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 288, in async_register_services if self.targets is not None: File "/config/custom_components/alexa_media/notify.py", line 152, in targets entity_name = (entity.entity_id).split(".")[1] AttributeError: 'NoneType' object has no attribute 'split'
Exception in discovery_platform_listener when dispatching 'discovery.platform_discovered_load_platform.notify': ({'service': 'load_platform.notify', 'platform': 'alexa_media', 'discovered': {'name': 'alexa_media', 'config': {'otp_secret': '<sanitized>', 'email': '<sanitized>', 'url': 'amazon.com.au', 'debug': False, 'scan_interval': 60, 'include_devices': '', 'exclude_devices': '', 'oauth': {'access_token': '<sanitized>', 'refresh_token': '<sanitized>', 'expires_in': <sanitized>, 'mac_dms': {'device_private_key': '<sanitized>', 'adp_token': '<sanitized>'}}}}},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/discovery.py", line 115, in discovery_platform_listener await task File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 134, in async_platform_discovered await async_setup_platform(platform, discovery_info=info) File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 123, in async_setup_platform await notify_service.async_register_services() File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 288, in async_register_services if self.targets is not None: File "/config/custom_components/alexa_media/notify.py", line 152, in targets entity_name = (entity.entity_id).split(".")[1] AttributeError: 'NoneType' object has no attribute 'split'
Exception in _handle_event when dispatching 'alexa_media_<sanitized>': ({'last_called_change': {'serialNumber': '<sanitized>', 'timestamp': 1679541397919, 'summary': 'Play "Café del Mar Radio official" from Tunein'}},) Traceback (most recent call last): File "/config/custom_components/alexa_media/media_player.py", line 390, in _handle_event await self._update_notify_targets() File "/config/custom_components/alexa_media/media_player.py", line 1525, in _update_notify_targets await notify.async_register_services() File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 288, in async_register_services if self.targets is not None: File "/config/custom_components/alexa_media/notify.py", line 152, in targets entity_name = (entity.entity_id).split(".")[1] AttributeError: 'NoneType' object has no attribute 'split'
```

**Additional context**

None

**Comment by snipestyle9410** [comment]
I think you have enabled the "Include devices connected via Echo" setting? 
If so, try do disable this setting. I got the same error log with this setting.

**Comment by alandtse** [comment]
Remove and readd. For some reason it can't find any setup Alexa account in HA.  Happy to take PRs to try to improve the logging message, but that won't help with the root cause.

**Comment by alexisspencer** [comment]
Thanks @alandtse, I'll give that a try and let you know what the outcome is in a few days..

**Comment by alexisspencer** [comment]
Hi @alandtse , sadly no luck.  A remove and re-add didn't fix it, it happened again overnight.
