### ISSUE TITLE
Integration stopped working, cannot authenticate when re-setting up - Still Happening

### ISSUE THREAD

**Issue by SGC1990** [custom-components/alexa_media_player#1925]
I am having the same problems as the Original Post I had more screen shots.

I was having problems with my Integration, removed it and added it back. When authenticating, it gets to this point:

![image](https://user-images.githubusercontent.com/19717561/236466496-a65c7e12-dd31-4dd9-81bb-3dcc27fcfb4a.png)

![image](https://user-images.githubusercontent.com/19717561/236466584-f88a10e1-0379-45fa-8874-7e20bc074b8d.png)

![image](https://user-images.githubusercontent.com/19717561/236466706-92fef22a-a0a5-4872-a1b8-170e6fd7ec57.png)

But continues redirecting to URLs with a :0 as a port number. If manually removing those each time, you eventually get to a 500 Internal Server Error page being served by /auth/alexamedia/proxy/ap/signin/133-7493927-9707447 on the HA server.

Original Post: https://github.com/custom-components/alexa_media_player/issues/1921#issue-1695910696

**Comment by iamehkri** [comment]
+1 happening to me as well

**Comment by zeldoy24** [comment]
Same now for me

**Comment by WillBoot** [comment]
Same problem here, changed Amazon account password. HA required reconfiguration as above post, no just times out ... with config flow error

![image](https://user-images.githubusercontent.com/114665176/236509489-566c5000-91ce-4326-8110-3ca30768d263.png)

Has worked perfectly for months until now.

**Comment by SGC1990** [comment]
> Same problem here, changed Amazon account password. HA required reconfiguration as above post, no just times out ... with config flow error
> 
> ![image](https://user-images.githubusercontent.com/114665176/236509489-566c5000-91ce-4326-8110-3ca30768d263.png)
> 
> Has worked perfectly for months until now.

This is what mine was doing and that is why I deleted the integration and tried to readd

**Comment by SGC1990** [comment]
> Same problem here, changed Amazon account password. HA required reconfiguration as above post, no just times out ... with config flow error
> 
> ![image](https://user-images.githubusercontent.com/114665176/236509489-566c5000-91ce-4326-8110-3ca30768d263.png)
> 
> Has worked perfectly for months until now.

This is what mine was doing and that is why i deleted the integration and tried to readd

**Comment by WillBoot** [comment]
> > Same problem here, changed Amazon account password. HA required reconfiguration as above post, no just times out ... with config flow error
> > ![image](https://user-images.githubusercontent.com/114665176/236509489-566c5000-91ce-4326-8110-3ca30768d263.png)
> > Has worked perfectly for months until now.
> 
> This is what mine was doing and that is why I deleted the integration and tried to readd

Oh no ... what a complete pain. I'm not that proficient at this kinda thing, lots of googling and testing to get where i was.

I do have a spare RPi3 and may run a test install on that, its not sounding good though from what you're seeing also!

**Comment by SGC1990** [comment]
> > > Same problem here, changed Amazon account password. HA required reconfiguration as above post, no just times out ... with config flow error
> > > ![image](https://user-images.githubusercontent.com/114665176/236509489-566c5000-91ce-4326-8110-3ca30768d263.png)
> > > Has worked perfectly for months until now.
> > 
> > 
> > This is what mine was doing and that is why I deleted the integration and tried to readd
> 
> Oh no ... what a complete pain. I'm not that proficient at this kinda thing, lots of googling and testing to get where i was.
> 
> I do have a spare RPi3 and may run a test install on that, its not sounding good though from what you're seeing also!

I have tried to start over with a fresh install of ha and it is still happening.

**Comment by WillBoot** [comment]
Its not sounding promising ... It was a great integration for both music player, announcements and the alarm system i had.

**Comment by zeldoy24** [comment]
:( same problem as soon as I tried deleting it and re adding it. I used it for actionable notifications, sensors, alarms, announcement....this is very annoying

**Comment by olgru** [comment]
> > Its not sounding promising ... It was a great integration for both music player, announcements and the alarm system i had.
> 
> I am getting ready to buy replacement devices if this is not fixed soon.

Having the same problem. But what replacement devices? AFAIK there is no full alternative...

**Comment by zeldoy24** [comment]
@alandtse

**Comment by zeldoy24** [comment]
@keatontaylor @alandtse since update also using more than 30 percent cpu usage......

**Comment by alandtse** [comment]
If you don't have time to provide the mandatory information for a bug report, I do not have the time to address it.

**Comment by jazzmonger** [comment]
The problem is in the automated url generation for authorization 
...ui.nabu.casa:0/auth/alexamedia...
The :0 shouldn't be there.  If you remove it, you get a lot further, but it still won't authenticate

**Comment by iamehkri** [comment]
> If you don't have time to provide the mandatory information for a bug report, I do not have the time to address it.


Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
result = func(*args)
File "/usr/local/lib/python3.10/ssl.py", line 917, in read
v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2578)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 34, in read
return await self._stream.receive(max_bytes=max_bytes)
File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 195, in receive
data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 137, in _call_sslobject_method
data = await self.transport_stream.receive()
File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1265, in receive
await self._protocol.read_event.wait()
File "/usr/local/lib/python3.10/asyncio/locks.py", line 214, in wait
await fut
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
yield
File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 32, in read
with anyio.fail_after(timeout):
File "/usr/local/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
raise TimeoutError
TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
yield
File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
resp = await self._pool.handle_async_request(req)
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
raise exc
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
response = await connection.handle_async_request(request)
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
return await self._connection.handle_async_request(request)
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 116, in handle_async_request
raise exc
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 95, in handle_async_request
) = await self._receive_response_headers(**kwargs)
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 159, in _receive_response_headers
event = await self._receive_event(timeout=timeout)
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 195, in _receive_event
data = await self._network_stream.read(
File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 31, in read
with map_exceptions(exc_map):
File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
self.gen.throw(typ, value, traceback)
File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
raise to_exc(exc)
httpcore.ReadTimeout
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
result = await result
File "/config/custom_components/alexa_media/config_flow.py", line 886, in wrapped
return await cls.handler(request, **kwargs)
File "/usr/local/lib/python3.10/site-packages/authcaptureproxy/auth_capture_proxy.py", line 387, in all_handler
resp = await getattr(self.session, method)(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1754, in get
return await self.request(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
return await self.send(request, auth=auth, follow_redirects=follow_redirects)
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
response = await self._send_handling_auth(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
response = await self._send_handling_redirects(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
response = await self._send_single_request(request)
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
response = await transport.handle_async_request(request)
File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
with map_httpcore_exceptions():
File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
self.gen.throw(typ, value, traceback)
File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
raise mapped_exc(message) from exc
httpx.ReadTimeout

**Comment by zeldoy24** [comment]
@iamehkri because he closed it he won't see it ....unless it's open

**Comment by WillBoot** [comment]
Should be fixed now, i tried it last night and it installed okay.

Much appreciate the bug fix @alandtse alandtse
