### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#1932]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version): 2023.5.2
- alexa_media (version from `const.py` or HA startup): 4.6.3
- alexapy (version from `pip show alexapy` or HA startup): 1.26.6
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
```
2023-05-07 16:10:44.543 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry alandtse@gmail.com - amazon.com for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alexa_media/__init__.py", line 326, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.10/site-packages/alexapy/alexalogin.py", line 347, in load_cookie
    return_cookies = self._get_cookies_from_session()
  File "/usr/local/lib/python3.10/site-packages/alexapy/alexalogin.py", line 554, in _get_cookies_from_session
    cookies = cookie_jar.filter_cookies(URL(f"https://{site}"))
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 239, in filter_cookies
    self._do_expiration()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 150, in _do_expiration
    self.clear(lambda x: False)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 115, in clear
    for (domain, path), cookie in self._cookies.items():
ValueError: too many values to unpack (expected 2)
```
**Additional context**
Workaround is to delete the pickle file at `/config/.storage/alexa_media.[email].pickle` and remove and readd the integration which will trigger a reuath. It looks like there may be some old data saved.

**Comment by Intecpsp** [comment]
Came here to report this. So I'm having this same issue

+1

**Comment by reefland** [comment]
I get `not enough values to unpack` ... roll back to 4.6.2 works.

```
2023-05-08 00:54:32.277 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry reefland@gmail.com - amazon.com for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alexa_media/__init__.py", line 326, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/config/deps/lib/python3.10/site-packages/alexapy/alexalogin.py", line 347, in load_cookie
    return_cookies = self._get_cookies_from_session()
  File "/config/deps/lib/python3.10/site-packages/alexapy/alexalogin.py", line 554, in _get_cookies_from_session
    cookies = cookie_jar.filter_cookies(URL(f"https://{site}"))
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 239, in filter_cookies
    self._do_expiration()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 150, in _do_expiration
    self.clear(lambda x: False)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/cookiejar.py", line 115, in clear
    for (domain, path), cookie in self._cookies.items():
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by PrathikGopal** [comment]
Rolling back due to the above issue 👍🏽
