### ISSUE TITLE
Alexa reports setup error when unable to fetch data from Alexa

### ISSUE THREAD

**Issue by zeldoy24** [custom-components/alexa_media_player#1937]
**Describe the bug**

When you go into logs you see that many Error while setting up alexa_media platform for various sensors.

**To Reproduce**

1. Go to 'settings.'
2. Click on 'system'
3. Scroll down to 'logs'

**Expected behavior**

No errors when loading alexa media player
 
![error logs](https://user-images.githubusercontent.com/108962242/236880193-99fa9d14-8f3a-4af4-a0d8-8dfd0f217003.png)

**System details**

- Home-assistant (version):  Home Assistant 2023.5.2
- alexa_media (version from `const.py` or HA startup): v4.6.4 
- alexapy (version from `pip show alexapy` or HA startup): 1.26.8
- Amazon [2FA is enabled (y/n). : yes

**Logs**
4.2023-05-08 12:13:59.756 ERROR (MainThread) [homeassistant.components.switch] Error while setting up alexa_media platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/alexa_media/switch.py", line 50, in async_setup_platform
raise ConfigEntryNotReady
homeassistant.exceptions.ConfigEntryNotReady: None
2023-05-08 12:13:59.768 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/alexa_media/sensor.py", line 73, in async_setup_platform
raise ConfigEntryNotReady
homeassistant.exceptions.ConfigEntryNotReady: None
2023-05-08 12:13:59.773 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up alexa_media platform for alarm_control_panel
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/alexa_media/alarm_control_panel.py", line 59, in async_setup_platform
raise ConfigEntryNotReady
homeassistant.exceptions.ConfigEntryNotReady: None
2023-05-08 12:13:59.778 ERROR (MainThread) [homeassistant.components.light] Error while setting up alexa_media platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/alexa_media/light.py", line 79, in async_setup_platform
raise ConfigEntryNotReady
homeassistant.exceptions.ConfigEntryNotReady: None
2023-05-08 12:13:59.784 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up alexa_media platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/alexa_media/binary_sensor.py", line 43, in async_setup_platform
raise ConfigEntryNotReady
homeassistant.exceptions.ConfigEntryNotReady: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alexa_media/media_player.py", line 96, in async_setup_platform
    if account is None and discovery_info:
UnboundLocalError: local variable 'account' referenced before assignment

**Additional context**

from the logs i keep seeing errors setting it up as well....i tried restarting HA but same problem occurs....

**Comment by sheyman1** [comment]
I'm having the same issue.

**Comment by makgit** [comment]
me too, downgrade resolve the issue for me

**Comment by jhstroebel** [comment]
Same

**Comment by zeldoy24** [comment]
A temporary fix was to disable all entities for Alexa media player and only enable eg: Alexa_media_player echo dot

**Comment by genem2** [comment]
> A temporary fix …

Or just revert to the previous version.

**Comment by jhstroebel** [comment]
Rollback HA?  Or this integration?  To what version?

**Comment by jhstroebel** [comment]
Sorry, I missed that this was due to the integration update that I didn't remember!  Rolled back and back to all good for now.

**Comment by alandtse** [comment]
The logs are reporting errors that do not match the latest version you're reporting. Specifically, you have identified version 4.6.4 but the line doesn't match that version:
```
File "/config/custom_components/alexa_media/media_player.py", line 96, in async_setup_platform
```

https://github.com/custom-components/alexa_media_player/blob/v4.6.4/custom_components/alexa_media/media_player.py#L96

Please ensure you have the latest version of the component. 

Please also provide complete logs. The screenshot doesn't tell me the details but it is reporting a network error which means we're not getting data from Alexa. It also is reporting a login error. If we fail to get data, we can't setup the component so the error messages are correct behavior.

Rolling back will give you a different set of errors but the functionality will be similarly non-functional because we're not in communication with Alexa.

**Comment by radhoo2k10** [comment]
I had the same issue. My solution was to delete the integration from HACS. Then install it from scratch again. https://github.com/custom-components/alexa_media_player/wiki/Configuration#installation-and-configuration

**Comment by snigehere** [comment]
> I had the same issue. My solution was to delete the integration from HACS. Then install it from scratch again. https://github.com/custom-components/alexa_media_player/wiki/Configuration#installation-and-configuration

Thanks - I didn't need to delete from HACS ... just deleted the integration and re-added it and all working again .. odd ... I wonder if it was related to an authorisation
