### ISSUE TITLE
notify service has stopped working. amazon.in

### ISSUE THREAD

**Issue by smartmints** [custom-components/alexa_media_player#1999]
**Describe the bug**

The notify service is not working.
The volume control is also not working.
It will work once in span of 3 - 4 hours time. But stops working immediatly.
Since nobody else is reporting this issue I think it might be limited to amazon.in (India)
I am having the same problem in my other house where I have a fresh install of Home Assistant
I am using the inbuilt app for 2FA. 

**To Reproduce**

'
service: notify.alexa_media
data:
  message: test
  data:
    type: announce
  target: media_player.beau_hall

'

**Expected behavior**

The speaker should say test

**System details**

Home Assistant 2023.8.1
Supervisor 2023.08.1
Operating System 10.4
 
- alexa_media (version from `const.py` or HA startup): 4.6.5
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon 2 factor is enabled

**Logs**

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:137
First occurred: August 10, 2023 at 1:41:16 PM (87 occurrences)
Last logged: 1:33:31 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1155, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -5] Name has no usable address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 430, in run_behavior
    await self._post_request("/api/behaviors/preview", data=data)
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 225, in _post_request
    return await self._request("post", uri, data, query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 201, in _request
    response = await getattr(self._session, method)(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1169, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host alexa.amazon.in:443 ssl:<ssl.SSLContext object at 0x7f1ec34c7260> [Name has no usable address]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 885, in send_tts
    await self.send_sequence(
  File "/usr/local/lib/python3.11/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 508, in send_sequence
    await self.run_behavior(node_data, queue_delay=queue_delay)
  File "/usr/local/lib/python3.11/site-packages/alexapy/helpers.py", line 147, in wrapper
    raise AlexapyConnectionError from ex
alexapy.errors.AlexapyConnectionError

**Comment by smartmints** [comment]
I checked the contents of the file alexa_media.sam********mail.com.pickle and they are as below :
'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

I did a fresh installation with a different account at my other house and the same thing is seen.

**Comment by alandtse** [comment]
You have network errors which is either a hardware or network configuration problem. I can't solve that for you.

```
annot connect to host alexa.amazon.in:443 ssl:<ssl.SSLContext object at 0x7f1ec34c7260> [Name has no usable address]
```

**Comment by smartmints** [comment]
Hi. Yes that was the problem. After updating unifi dream machine pro to the latest on 2 separate sites this problem has come up. I have tplink omada in my office and it working fine here.
The firewall rules are fine since all the IOT devices and even the google nest speakers work with TTS in home assistant. Only the echo and alexa related speakers are giving a problem. 
Thanks for the heads up will look more into this.

**Comment by smartmints** [comment]
Ok. So I found the problem and it was disabling IGMP snooping. All the services start working after this. This option was working before unifi update so I dont know what changed.
