### ISSUE TITLE
Authentication error on HA 2023.10.0 - TypeError: Constructor parameter should be str

### ISSUE THREAD

**Issue by rgrandev** [custom-components/alexa_media_player#2059]
**Describe the bug**

Today I upgraded to HA 2023.10.0 (after upgrade reboot the system) and try to reconfigure alexa_media_player but I get error.

**Screenshots**

![Captura de pantalla 2023-10-05 100822](https://github.com/custom-components/alexa_media_player/assets/97048532/253ef6a3-524e-4bbe-8fc4-ff695c7cf9d4)

**System details**

- Home-assistant (version): 2023.10.0
- alexa_media : 4.7.6
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n).: Y

**Logs**
2023-10-04 23:46:27.397 WARNING (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f8c43e3d0>,), {'cookies': {}}): An error occurred accessing AlexaAPI: An exception of type TypeError occurred. Arguments:
('Constructor parameter should be str',)
2023-10-04 23:46:27.397 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxx@xxxxx.com - amazon.es for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 333, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.11/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexalogin.py", line 685, in login
    post_resp = await self._session.post(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 423, in _request
    url = self._build_url(str_or_url)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 357, in _build_url
    url = URL(str_or_url)
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yarl/_url.py", line 179, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str

**Comment by poudenes** [comment]
Same here. Even when everything went ok and I restart HA again I have to do everything again.
I revert back to 4.7.4. This version seems to work normal

**Comment by mwunderling** [comment]
Remove this comment if not related. I haven't updated HA to 2023.10.0 yet (still on 2023.9.3). However, I updated alexa.media player to 4.7.6 four days ago and have had to reauth the integration 4 times since then after not having to touch it for months. Seems like there is an authentication issue with this version of alexa.media player???

**Comment by zSprawl** [comment]
I’m seeing the same issue. For me, I’m still running 2023.09.03 but I updated to 4.7.6 last night. This morning it was trying to get me to
reauth and it kept failing with the same “str” error above. I rolled back to 4.7.2 and rebooted. It is working again without issue.

**Comment by mwunderling** [comment]
Follow up to my last post. having to reauth after 48mins. Looks like it's making too many api call and Amazon is booting it. Am going to roll back to a prior version of this integration.
![chrome_YhfrR2imra](https://github.com/custom-components/alexa_media_player/assets/22336325/e826a5b1-3926-4817-a4ae-831e236f467b)

**Comment by poudenes** [comment]
> Follow up to my last post. having to reauth after 48mins. Looks like it's making too many api call and Amazon is booting it. Am going to roll back to a prior version of this integration. ![chrome_YhfrR2imra](https://user-images.githubusercontent.com/22336325/272978469-e826a5b1-3926-4817-a4ae-831e236f467b.png)

I tried 4.7.4 and had same issue on 2023.10.0. Maybe 4.7.3 will be the last good working version then.

**Comment by poudenes** [comment]
Some log before I did reauth:
```
2023-10-05 19:07:47.414 WARNING (MainThread) [alexapy.helpers] alexaapi.get_notifications((<alexapy.alexalogin.AlexaLogin object at 0x7f96704cd0>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2023-10-05 19:07:47.422 WARNING (MainThread) [alexapy.helpers] alexaapi.get_activities((<alexapy.alexalogin.AlexaLogin object at 0x7f96704cd0>, 10), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2023-10-05 19:07:47.424 WARNING (MainThread) [alexapy.helpers] alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f96704cd0>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2023-10-05 19:07:47.789 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:47.791 WARNING (MainThread) [alexapy.helpers] alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f8146d390>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2023-10-05 19:07:47.798 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:47.804 WARNING (MainThread) [alexapy.helpers] alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f83c781d0>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2023-10-05 19:07:47.811 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:47.818 WARNING (MainThread) [alexapy.helpers] alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f72036290>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2023-10-05 19:07:47.824 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:47.940 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:47.943 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:47.945 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:47.945 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:47.946 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:47.947 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:47.948 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:47.951 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:47.954 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:47.955 WARNING (MainThread) [alexapy.alexaapi] AlexaLogin session is missing required token: 'csrf' This may result in authorization errors, please report if unable to login
2023-10-05 19:07:48.024 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alexa_media/sensor.py", line 162, in async_setup_entry
    return await async_setup_platform(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/sensor.py", line 93, in async_setup_platform
    if key in account_dict["notifications"]
              ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'notifications'
2023-10-05 19:07:58.020 WARNING (MainThread) [alexapy.helpers] alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f8146d390>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2023-10-05 19:07:58.026 WARNING (MainThread) [alexapy.helpers] alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f83c781d0>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2023-10-05 19:07:58.032 WARNING (MainThread) [alexapy.helpers] alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f72036290>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2023-10-05 19:09:33.646 WARNING (MainThread) [alexapy.helpers] alexaapi.get_activities((<alexapy.alexalogin.AlexaLogin object at 0x7f96704cd0>, 10), {}): A login error occurred: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 1 column 1 (char 0)',)
2023-10-05 19:09:33.647 WARNING (MainThread) [alexapy.helpers] alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f96704cd0>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
()
2023-10-05 19:09:33.665 WARNING (MainThread) [alexapy.helpers] alexaapi.get_activities((<alexapy.alexalogin.AlexaLogin object at 0x7f96704cd0>, 10), {}): A login error occurred: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 1 column 1 (char 0)',)
2023-10-05 19:09:33.668 WARNING (MainThread) [alexapy.helpers] alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f96704cd0>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
()
2023-10-05 19:13:45.775 WARNING (MainThread) [alexapy.helpers] alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f72036290>,), {}): Timeout error occurred accessing AlexaAPI: An exception of type CancelledError occurred. Arguments:
()
2023-10-05 19:13:48.488 WARNING (MainThread) [alexapy.helpers] alexaapi.run_behavior((<alexapy.alexaapi.AlexaAPI object at 0x7f72036290>, {'@type': 'com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode', 'type': 'AlexaAnnouncement', 'operationPayload': {'deviceType': 'A32DOYMUN6DTXA', 'deviceSerialNumber': 'G************EXX', 'locale': 'en-us', 'customerId': 'A**********3UP', 'expireAfter': 'PT5S', 'content': [{'locale': 'en-us', 'display': {'title': 'Home Assistant', 'body': 'Good evening. I activated the scene evening.'}, 'speak': {'type': 'text', 'value': 'Good evening. I activated the scene evening.'}}], 'target': {'customerId': 'A**********3UP', 'devices': [{'deviceSerialNumber': 'G************EXX', 'deviceTypeId': 'A32DOYMUN6DTXA'}]}, 'skillId': 'amzn1.ask.1p.routines.messaging'}}), {'queue_delay': 1.5}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Unauthorized',)
2023-10-05 19:13:48.491 WARNING (MainThread) [alexapy.helpers] alexaapi.send_sequence((<alexapy.alexaapi.AlexaAPI object at 0x7f72036290>, 'AlexaAnnouncement'), {'customer_id': 'A23TNXO6ZSS3UP', 'expireAfter': 'PT5S', 'content': [{'locale': 'en-us', 'display': {'title': 'Home Assistant', 'body': 'Good evening. I activated the scene evening.'}, 'speak': {'type': 'text', 'value': 'Good evening. I activated the scene evening.'}}], 'target': {'customerId': 'A**********3UP', 'devices': [{'deviceSerialNumber': 'G************EXX', 'deviceTypeId': 'A32DOYMUN6DTXA'}]}, 'skillId': 'amzn1.ask.1p.routines.messaging', 'queue_delay': 1.5}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Unauthorized',)
2023-10-05 19:13:48.495 WARNING (MainThread) [alexapy.helpers] alexaapi.send_announcement((<alexapy.alexaapi.AlexaAPI object at 0x7f72036290>, 'Good evening. I activated the scene evening.'), {'customer_id': 'A23TNXO6ZSS3UP', 'targets': ['G090U60783520EXX'], 'title': 'Home Assistant', 'method': 'all', 'queue_delay': 1.5}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Unauthorized',)
2023-10-05 19:13:48.497 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 956, in send_announcement
    await self.send_sequence(
  File "/usr/local/lib/python3.11/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 508, in send_sequence
    await self.run_behavior(node_data, queue_delay=queue_delay)
  File "/usr/local/lib/python3.11/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 430, in run_behavior
    await self._post_request("/api/behaviors/preview", data=data)
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 225, in _post_request
    return await self._request("post", uri, data, query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 217, in _request
    return await self._process_response(response, self._login)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alexapy/alexaapi.py", line 120, in _process_response
    raise AlexapyLoginError(response.reason)
alexapy.errors.AlexapyLoginError: Unauthorized
```

**Comment by cg089** [comment]
I have to reauthenticate permanently after the last plugin update, I am still on HA 2023.09.

**Comment by gabrymed** [comment]
Same problem

**Comment by admin-lm** [comment]
Same, and google seams to mark the hassio-domain (if external access enabled) as dangerous:

![image](https://github.com/custom-components/alexa_media_player/assets/14347987/db88ceba-c337-4f56-b2d1-99c9e819f5f7)

**Comment by AdrianPal** [comment]
Same for me, but not related to 2023-10-0 version but to the last plugin version.

**Comment by popy2k14** [comment]
Same here on 4.7.6 an HA we 2023.9.3.
Notifications are working since last plugin update.

Sadly, reauthenticate issue after a few days (2-3) of use.

**Comment by ryanlocey** [comment]
> > Follow up to my last post. having to reauth after 48mins. Looks like it's making too many api call and Amazon is booting it. Am going to roll back to a prior version of this integration. ![chrome_YhfrR2imra](https://user-images.githubusercontent.com/22336325/272978469-e826a5b1-3926-4817-a4ae-831e236f467b.png)
> 
> I tried 4.7.4 and had same issue on 2023.10.0. Maybe 4.7.3 will be the last good working version then.

i rolled back to 4.7.3 and am back working.

**Comment by popy2k14** [comment]
But device data changes does not come thru which those versions.

**Comment by serlinGi** [comment]
![Screenshot_2023-10-06-08-22-05-81_c3a231c25ed346e59462e84656a70e50](https://github.com/custom-components/alexa_media_player/assets/63103970/3bf2f03c-969b-41ff-a5e9-f440ceded284)

same for mewith 4.7.4; I haven't updated HA yet, I'm with 2023.9.3

**Comment by fwartner** [comment]
Same over here. Authentication works until the redirect to my instance is processing.

**Comment by alexisspencer** [comment]
Same thing here, still on HA 2023.9.3 and only started after upgrading Amp to 4.7.6

**Comment by bushcraftytim** [comment]
Same thing here. I also have the same as above : "Authentication works until the redirect to my instance is processing."

**Comment by poudenes** [comment]
I revert back to 4.7.3 and now I can restart HA without Authentication issues. Did multiple restarts of HA.

**Comment by ukcavhead** [comment]
Morning and please excuse the ignorance but how do you roll back to 4.7.3? Is it a full back up from HA or are you able to just roll back the Alex integration?
Thanks

**Comment by popy2k14** [comment]
> Fix for me so far:
> 
> Delete the integration and add it again.
> 
> Works without any issues so far.

Alrady done multiple timers. Reauth will come back on 4.7.6



> I revert back to 4.7.3 and now I can restart HA without Authentication issues. Did multiple restarts of HA.

On This version media playing state, timers, alarms, ... notifications doesnt work. 
So no real workaround.

**Comment by fwartner** [comment]
> > Fix for me so far:
> > Delete the integration and add it again.
> > Works without any issues so far.
> 
> Alrady done multiple timers. Reauth will come back on 4.7.6
> 
> > I revert back to 4.7.3 and now I can restart HA without Authentication issues. Did multiple restarts of HA.
> 
> On This version media playing state, timers, alarms, ... notifications doesnt work. So no real workaround.

You`ll need to restart HA before re-adding the integration. That worked for me.

**Comment by popy2k14** [comment]
> > > Fix for me so far:
> > > Delete the integration and add it again.
> > > Works without any issues so far.
> > 
> > 
> > Alrady done multiple timers. Reauth will come back on 4.7.6
> > > I revert back to 4.7.3 and now I can restart HA without Authentication issues. Did multiple restarts of HA.
> > 
> > 
> > On This version media playing state, timers, alarms, ... notifications doesnt work. So no real workaround.
> 
> You`ll need to restart HA before re-adding the integration. That worked for me.

I think i have restarted HA after removing.
When did you do that and how long does login lasts for you already without reauthenticate issue?

**Comment by poudenes** [comment]
> > Fix for me so far:
> > Delete the integration and add it again.
> > Works without any issues so far.
> 
> Alrady done multiple timer. Reauth will come back on 4.7.6
> 
> > I revert back to 4.7.3 and now I can restart HA without Authentication issues. Did multiple restarts of HA.
> 
> On This version media playing state, timers, alarms, ... notifications doesnt work. So no real workaround.

for now its better for me. I only use it for notifications. And reauthenticate all the time is not a option for me :)

**Comment by poudenes** [comment]
> Fix for me so far:
> 
> Delete the integration and add it again.
> 
> Works without any issues so far.

Let me try this also. Remove integration, restart HA and add it again.

**Comment by atv2016** [comment]
Same problem here. Reauthentication keeps popping up, sometimes unknown error, sometimes it works, but when it does i still don't get TTS notifications, so clearly something is not working.

**Comment by VicenteKER** [comment]
Same error at first. But 
-Uninstall alexa media player from hacs. 
-Reboot HA. 
-Install again alexa media player
-Reboot HA. 
-Configure Alexa media player. 
-Reboot HA. 
and it works again

**Comment by bushcraftytim** [comment]
Followed ViceneKERs steps above - worked perfectly.

**Comment by Impedanz** [comment]
my workaround was: reload the addon and set the nabucasa URL in the addon again (the acutall Link are not working for me, get the new from nabu case and works fine)

**Comment by poudenes** [comment]
The Uninstall, Reboot HA, Install Alexa, Reboot HA, Config ALexa, Reboot HA didn't work for me. After some hours I was reboot HA and now again have to do reauth procedure again.

Here log lines after the HA reboot:

```
2023-10-06 15:37:51.551 WARNING (MainThread) [alexapy.helpers] alexaapi.get_guard_details((<alexapy.alexalogin.AlexaLogin object at 0x7f71be9a50>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2023-10-06 15:37:51.553 WARNING (MainThread) [alexapy.helpers] alexaapi.get_network_details((<alexapy.alexalogin.AlexaLogin object at 0x7f71be9a50>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
2023-10-06 15:37:51.554 WARNING (MainThread) [alexapy.helpers] alexaapi.get_device_preferences((<alexapy.alexalogin.AlexaLogin object at 0x7f71be9a50>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Login error detected; not contacting API',)
```

**Comment by jorgezazo** [comment]
+1 here. I tried every method here and worked a few hours. After that reauthetication is requested again. Any solution in sight?

**Comment by barto95100** [comment]
Not worked for me problem 404 not found

**Comment by popy2k14** [comment]
Just a side note, when i just go to HomeAssistant integrations page and press reconfigure on the red "alexa media player" integration and don't touch anything (email, pw, site url, 2FA, ...) the integration works a few hours again.

So the infos to relogin ware here.

**Comment by JvdMaat** [comment]
> Morning and please excuse the ignorance but how do you roll back to 4.7.3? Is it a full back up from HA or are you able to just roll back the Alex integration? Thanks

Go to HACS -> Integrations -> Alexa Media Player, and then from the top right 3 dots select Redownload, and it'll allow you to specify the version.

**Comment by popy2k14** [comment]
Dont roll back, with 4.7.3 many features doesnt work!

**Comment by JvdMaat** [comment]
> Dont roll back, with 4.7.3 many features doesnt work!

Like what? 4.7.3 is only a week old (29 Sep). Everything I used it for last week still works in 4.7.3
(Granted, it's mostly telling a speaker to play Sirius for me)
So far 2 hours with 4.7.3 and I'm having no issues. And my integrations Dashboard is usable again (instead of having a dozen pages of AMP needs reconfig boxes)

**Comment by popy2k14** [comment]
It has issues for other countrys & reconnect issues.
Read the changelog.

**Comment by cg089** [comment]
4.7.3 works just fine for me, I just use it as a TTS device.

**Comment by jorgezazo** [comment]
After many tries, this is working from this morning until now (finger crossed). I did the steps discussed a few messages above with some additions:

-Uninstall alexa media player from hacs.
- Remove Alexa Media Player integration from Settings -> Integrations
- Delete config files from /.config/storage alexa and alexa_media.emailUsedToRegister@thisComponent.com
- Delete Home Assistant skill from alexa app in your phone
-Reboot HA.
-Install again alexa media player,
-Reboot HA.
-Configure Alexa media player.
-Reboot HA.
- Install Home Assistant skill in your phone

Still working all features provided by Nabu Casa.

Hops this work for you all too.
Regards

**Comment by justinmaiuto** [comment]
> After many tries, this is working from this morning until now (finger crossed). I did the steps discussed a few messages above with some additions:
> 
> -Uninstall alexa media player from hacs.
> 
>     * Remove Alexa Media Player integration from Settings -> Integrations
> 
>     * Delete config files from /.config/storage alexa and [alexa_media.emailUsedToRegister@thisComponent.com](mailto:alexa_media.emailUsedToRegister@thisComponent.com)
> 
>     * Delete Home Assistant skill from alexa app in your phone
>       -Reboot HA.
>       -Install again alexa media player,
>       -Reboot HA.
>       -Configure Alexa media player.
>       -Reboot HA.
> 
>     * Install Home Assistant skill in your phone
> 
> 
> Still working all features provided by Nabu Casa.
> 
> Hope this work for you all too. Regards

Seems like a lot of work to get this functioning again, will it be fixed properly with a new release in the future or will we all have to follow the above?

**Comment by alexisspencer** [comment]
> After many tries, this is working from this morning until now (finger crossed). I did the steps discussed a few messages above with some additions:
> 
> -Uninstall alexa media player from hacs.
> 
> * Remove Alexa Media Player integration from Settings -> Integrations
> * Delete config files from /.config/storage alexa and [alexa_media.emailUsedToRegister@thisComponent.com](mailto:alexa_media.emailUsedToRegister@thisComponent.com)
> * Delete Home Assistant skill from alexa app in your phone
>   -Reboot HA.
>   -Install again alexa media player,
>   -Reboot HA.
>   -Configure Alexa media player.
>   -Reboot HA.
> * Install Home Assistant skill in your phone
> 
> Still working all features provided by Nabu Casa.
> 
> Hope this work for you all too. Regards

I have tried alot of this too, and it sticks around for a few days or so but then fails.
The only solution I've found was to download / install the 4.7.4 version.
I'm on HAOS 2023.9.3 still, haven't upgraded to 2023.10 yet, I'll wait for the .1 release first to avoid bugs.

**Comment by jorgezazo** [comment]
@alandtse Thank you very much for your hard work and for put up us all the users. I will try your new release ASAP.

**Comment by popy2k14** [comment]
@alandtse Thanks for the fast fix!

**Comment by steviloidz** [comment]
@alandtse many thanks for the fix. I upgraded in HACS and everything started working again without any reconfiguration.

**Comment by barto95100** [comment]
The same jsut upgrade and all work

thank's you :)

**Comment by poudenes** [comment]
Thanks for the good support!!!!
