### ISSUE TITLE
'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by Maurotb** [custom-components/alexa_media_player#299]
**Describe the bug**

After ugrade my homassistant (docker) to 0.97.2 and alexa_media to 2.0 
when i click on "Please hit confirm to begin login attempt." i have 

2019-08-23 14:28:35 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1864377072] 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 128, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/configurator/__init__.py", line 235, in async_handle_service_call
    await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
  File "/config/custom_components/alexa_media/__init__.py", line 152, in configuration_callback
    login, callback_data)
  File "/config/custom_components/alexa_media/__init__.py", line 142, in setup_platform_callback
    await login.login(data=callback_data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 327, in login
    await self._process_page(await post_resp.text(), site)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 372, in _process_page
    find_links()
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 338, in find_links
    string = link.string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by felipemfa** [comment]
I had the same problem, I removed the alexa_media.xxxxxxxxxxxxx.com.pickle file, tried to reconfigure however unsuccessfully. I downgraded, reconfigured and then I upgraded, so it worked.

**Comment by Maurotb** [comment]
Ok, downgrading to 1.4.0 , authenticate and upgrade now work...
But this is an issue...

**Comment by felipemfa** [comment]
certainly! just a tip to help until it is fixed ;)

**Comment by gemixsan** [comment]
have the same problem, how can I download version 1.4.0? thanks

**Comment by felipemfa** [comment]
I use the Community addon.
just change  in the "Available versions"

**Comment by alandtse** [comment]
Thanks for reporting. We'll fix it.

**Comment by gemixsan** [comment]
i just installed 1.4.0 my problem is when i am trying to login, ask me a validation method i introduce my email and it os starting all over again so i can not login

**Comment by alandtse** [comment]
Please make sure you follow the instructions on how to select your validation method. The options are case sensitive. 

If the problem persists, what is the error message Amazon is providing? Please start a new thread with that info. It's possible Amazon may require you to wait a few hours before they will send additional verification requests.

**Comment by gemixsan** [comment]
Can you help me and tell me exactly what I have to write If I choose my email? It is only my email adress or I have to add something before or later?

**Comment by alandtse** [comment]
It depends on the configurator page and the instructions, but you'd type in `email`, `sms`, or `0`, `1` or whatever.

**Comment by matteos1** [comment]
same problem
