### ISSUE TITLE
KeyError: 'bluetoothStates' with websocket update

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#309]
yea. this seems to work now.
while monitoring the logs I also noticed this
`
2019-08-27 21:31:51 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 135, in process_messages
    await self.on_message(cast(bytes, msg.data))
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 217, in on_message
    await self.msg_callback(message_obj)
  File "/config/custom_components/alexa_media/__init__.py", line 590, in ws_handler
    serial)
  File "/config/custom_components/alexa_media/__init__.py", line 465, in update_bluetooth_state
    for b_state in bluetooth['bluetoothStates']:
KeyError: 'bluetoothStates'
`

_Originally posted by @danielmihalache1983 in https://github.com/keatontaylor/alexa_media_player/issues/302#issuecomment-525431094_

**Comment by danielmihalache1983** [comment]
it is showing fine:
`
{
bluetoothStates: [
{
deviceSerialNumber: "G090LF1073131J7J",
deviceType: "A3S5BH2HU6VAYF",
friendlyName: null,
gadgetPaired: false,
online: true,
pairedDeviceList: [
{
address: "70:99:1C:3E:2F:2E",
connected: false,
deviceClass: "OTHER",
friendlyName: "JBL GO 2",
profiles: [
"A2DP-SINK",
"AVRCP"
]
}
],
sconeBattery: null,
sconePaired: false,
softwareVersion: "641575220",
streamingState: null
},
{
deviceSerialNumber: "9f1cbdd591e24915888ec05ad4845292",
deviceType: "A2TF17PFR55MTB",
friendlyName: null,
gadgetPaired: false,
online: false,
pairedDeviceList: null,
sconeBattery: null,
sconePaired: false,
softwareVersion: "130050002",
streamingState: null
},
{
deviceSerialNumber: "0FE7C4D44F0F42FB95F88F9834136036",
deviceType: "A3NWHXTQ4EBCZS",
friendlyName: null,
gadgetPaired: false,
online: false,
pairedDeviceList: null,
sconeBattery: null,
sconePaired: false,
softwareVersion: "1",
streamingState: null
}
]
}
`

**Comment by danielmihalache1983** [comment]
btw, media_player entity in HA is freezed. I can`t interact with any of it`s functions

**Comment by danielmihalache1983** [comment]
No, no error since the one showed yesterday.
I didn`t restart HA either and media_player is in a freezed state as I said. I will restart HA and see if it starts working again

**Comment by danielmihalache1983** [comment]
So after restart, it updated the state but as soon as I started music to play, HA media player entity freezed. No errors in the ha log though.

**Comment by alandtse** [comment]
I'm not sure I understand what you mean by freeze. Can you provide screenshots? I may also need you to turn on debug logging for the component and alexa_media.

**Comment by danielmihalache1983** [comment]
ok so I fiddled out some more with alexa. scenario is like so.
1.I ask alexa to pair bluetooth
2. ha logs show the error
`
2019-08-29 08:01:40 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 135, in process_messages
    await self.on_message(cast(bytes, msg.data))
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 217, in on_message
    await self.msg_callback(message_obj)
  File "/config/custom_components/alexa_media/__init__.py", line 590, in ws_handler
    serial)
  File "/config/custom_components/alexa_media/__init__.py", line 465, in update_bluetooth_state
    for b_state in bluetooth['bluetoothStates']:
KeyError: 'bluetoothStates'
`
3. media_player in HA becomes unresponsive
![image](https://user-images.githubusercontent.com/35133347/63911712-dd82f200-ca33-11e9-9411-ca6f583dfb34.png)

4. node red entity outputs no message on state change
![image](https://user-images.githubusercontent.com/35133347/63911744-f8edfd00-ca33-11e9-9774-e2d7821420f8.png)

5. alexa api responds file
https://alexa.amazon.com/api/bluetooth
`
bluetoothStates: [
{
deviceSerialNumber: "G090LF1073131J7J",
deviceType: "A3S5BH2HU6VAYF",
friendlyName: null,
gadgetPaired: false,
online: true,
pairedDeviceList: [
{
address: "20:17:02:08:04:56",
connected: true,
deviceClass: "OTHER",
friendlyName: "Ugreen-Bluetooth05",
profiles: [
"AVRCP",
"A2DP-SINK"
]
},
{
address: "70:99:1C:3E:2F:2E",
connected: false,
deviceClass: "OTHER",
friendlyName: "JBL GO 2",
profiles: [
"A2DP-SINK",
"AVRCP"
]
}
],
sconeBattery: null,
sconePaired: false,
softwareVersion: "641575220",
streamingState: null
},
{
deviceSerialNumber: "9f1cbdd591e24915888ec05ad4845292",
deviceType: "A2TF17PFR55MTB",
friendlyName: null,
gadgetPaired: false,
online: false,
pairedDeviceList: null,
sconeBattery: null,
sconePaired: false,
softwareVersion: "130050002",
streamingState: null
},
{
deviceSerialNumber: "0FE7C4D44F0F42FB95F88F9834136036",
deviceType: "A3NWHXTQ4EBCZS",
friendlyName: null,
gadgetPaired: false,
online: false,
pairedDeviceList: null,
sconeBattery: null,
sconePaired: false,
softwareVersion: "1",
streamingState: null
}
]
}
`

**Comment by danielmihalache1983** [comment]
I will also enable debug logging when I get back home

**Comment by alandtse** [comment]
Can you try renaming your .pickle file? The fact the bluetooth check is breaking is what's causing the websocket to stop updating events. However, the bluetooth check normally shouldn't break unless your session is expired.

**Comment by danielmihalache1983** [comment]
I renamed, it didn-t help.
I activated debug.
While alexa_media is freezed in the interface, I can see this logs when I connect to bluetooth
`
2019-08-29 20:08:00 DEBUG (MainThread) [custom_components.alexa_media] d*****************3@gmail.com: Existing: [<Entity Daniel's Echo Dot: standby>, <Entity This Device: standby>, <Entity Daniel's Alexa Apps: standby>] New: []; Filtered by: include_devices: [] exclude_devices:[]
2019-08-29 20:08:00 DEBUG (MainThread) [custom_components.alexa_media] d*****************3@gmail.com: Updated last_called: {'serialNumber': 'G************J7J', 'timestamp': 1567098434829}
2019-08-29 20:08:01 DEBUG (MainThread) [alexapy.alexawebsocket] msg: WSMessage(type=<WSMsgType.BINARY: 2>, data=b'MSG 0x00000362 0x646eb021 f 0x00000001 0x1642b429 0x0000026e GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:**************:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:************** {"payload":"{\\"destinationUserId\\":\\"**************\\",\\"dopplerId\\":{\\"deviceSerialNumber\\":\\"**************\\",\\"deviceType\\":\\"A3S5BH2HU6VAYF\\"},\\"bluetoothEvent\\":\\"DEVICE_CONNECTED\\",\\"bluetoothEventPayload\\":null,\\"bluetoothEventSuccess\\":false}","command":"PUSH_BLUETOOTH_STATE_CHANGE"}FABE', extra='')
2019-08-29 20:08:01 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket MSG.
2019-08-29 20:08:01 DEBUG (MainThread) [alexapy.alexawebsocket] Received b'MSG 0x00000362 0x646eb021 f 0x00000001 0x1642b429 0x0000026e GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:**************:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:************** {"payload":"{\\"destinationUserId\\":\\"**************\\",\\"dopplerId\\":{\\"deviceSerialNumber\\":\\"**************\\",\\"deviceType\\":\\"A3S5BH2HU6VAYF\\"},\\"bluetoothEvent\\":\\"DEVICE_CONNECTED\\",\\"bluetoothEventPayload\\":null,\\"bluetoothEventSuccess\\":false}","command":"PUSH_BLUETOOTH_STATE_CHANGE"}FABE'
2019-08-29 20:08:01 DEBUG (MainThread) [alexapy.alexawebsocket] Received Standard MSG.
2019-08-29 20:08:01 DEBUG (MainThread) [custom_components.alexa_media] d*****************3@gmail.com: Received websocket command: PUSH_BLUETOOTH_STATE_CHANGE : {'destinationUserId': '**************', 'dopplerId': {'deviceSerialNumber': '**************', 'deviceType': 'A3S5BH2HU6VAYF'}, 'bluetoothEvent': 'DEVICE_CONNECTED', 'bluetoothEventPayload': None, 'bluetoothEventSuccess': False}
2019-08-29 20:08:01 DEBUG (MainThread) [custom_components.alexa_media] Updating media_player bluetooth {'destinationUserId': '**************', 'dopplerId': {'deviceSerialNumber': '**************', 'deviceType': 'A3S5BH2HU6VAYF'}, 'bluetoothEvent': 'DEVICE_CONNECTED', 'bluetoothEventPayload': None, 'bluetoothEventSuccess': False}
2019-08-29 20:08:04 DEBUG (MainThread) [alexapy.alexawebsocket] msg: WSMessage(type=<WSMsgType.BINARY: 2>, data=b'MSG 0x00000362 0x646eb2ef f 0x00000001 0x35a7b8df 0x00000271 GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:**************:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:************** {"payload":"{\\"destinationUserId\\":\\"**************\\",\\"dopplerId\\":{\\"deviceSerialNumber\\":\\"**************\\",\\"deviceType\\":\\"A3S5BH2HU6VAYF\\"},\\"bluetoothEvent\\":\\"ENTERED_PAIRING_MODE\\",\\"bluetoothEventPayload\\":null,\\"bluetoothEventSuccess\\":true}","command":"PUSH_BLUETOOTH_STATE_CHANGE"}FABE', extra='')
2019-08-29 20:08:04 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket MSG.
2019-08-29 20:08:04 DEBUG (MainThread) [alexapy.alexawebsocket] Received b'MSG 0x00000362 0x646eb2ef f 0x00000001 0x35a7b8df 0x00000271 GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:**************:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:************** {"payload":"{\\"destinationUserId\\":\\"**************\\",\\"dopplerId\\":{\\"deviceSerialNumber\\":\\"**************\\",\\"deviceType\\":\\"A3S5BH2HU6VAYF\\"},\\"bluetoothEvent\\":\\"ENTERED_PAIRING_MODE\\",\\"bluetoothEventPayload\\":null,\\"bluetoothEventSuccess\\":true}","command":"PUSH_BLUETOOTH_STATE_CHANGE"}FABE'
2019-08-29 20:08:04 DEBUG (MainThread) [alexapy.alexawebsocket] Received Standard MSG.
2019-08-29 20:08:04 DEBUG (MainThread) [custom_components.alexa_media] d*****************3@gmail.com: Received websocket command: PUSH_BLUETOOTH_STATE_CHANGE : {'destinationUserId': '**************', 'dopplerId': {'deviceSerialNumber': '**************', 'deviceType': 'A3S5BH2HU6VAYF'}, 'bluetoothEvent': 'ENTERED_PAIRING_MODE', 'bluetoothEventPayload': None, 'bluetoothEventSuccess': True}
2019-08-29 20:08:04 DEBUG (MainThread) [custom_components.alexa_media] Updating media_player bluetooth {'destinationUserId': '**************', 'dopplerId': {'deviceSerialNumber': '**************', 'deviceType': 'A3S5BH2HU6VAYF'}, 'bluetoothEvent': 'ENTERED_PAIRING_MODE', 'bluetoothEventPayload': None, 'bluetoothEventSuccess': True}
2019-08-29 20:08:25 DEBUG (MainThread) [alexapy.alexawebsocket] msg: WSMessage(type=<WSMsgType.BINARY: 2>, data=b'MSG 0x00000362 0x646ec88f f 0x00000001 0x112359a0 0x0000026d GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:**************:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:************** {"payload":"{\\"destinationUserId\\":\\"**************\\",\\"dopplerId\\":{\\"deviceSerialNumber\\":\\"**************\\",\\"deviceType\\":\\"A3S5BH2HU6VAYF\\"},\\"bluetoothEvent\\":\\"DEVICE_CONNECTED\\",\\"bluetoothEventPayload\\":null,\\"bluetoothEventSuccess\\":true}","command":"PUSH_BLUETOOTH_STATE_CHANGE"}FABE', extra='')
2019-08-29 20:08:25 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket MSG.
2019-08-29 20:08:25 DEBUG (MainThread) [alexapy.alexawebsocket] Received b'MSG 0x00000362 0x646ec88f f 0x00000001 0x112359a0 0x0000026d GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:**************:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:************** {"payload":"{\\"destinationUserId\\":\\"**************\\",\\"dopplerId\\":{\\"deviceSerialNumber\\":\\"**************\\",\\"deviceType\\":\\"A3S5BH2HU6VAYF\\"},\\"bluetoothEvent\\":\\"DEVICE_CONNECTED\\",\\"bluetoothEventPayload\\":null,\\"bluetoothEventSuccess\\":true}","command":"PUSH_BLUETOOTH_STATE_CHANGE"}FABE'
2019-08-29 20:08:25 DEBUG (MainThread) [alexapy.alexawebsocket] Received Standard MSG.
2019-08-29 20:08:25 DEBUG (MainThread) [custom_components.alexa_media] d*****************3@gmail.com: Received websocket command: PUSH_BLUETOOTH_STATE_CHANGE : {'destinationUserId': '**************', 'dopplerId': {'deviceSerialNumber': '**************', 'deviceType': 'A3S5BH2HU6VAYF'}, 'bluetoothEvent': 'DEVICE_CONNECTED', 'bluetoothEventPayload': None, 'bluetoothEventSuccess': True}
2019-08-29 20:08:25 DEBUG (MainThread) [custom_components.alexa_media] Updating media_player bluetooth {'destinationUserId': '**************', 'dopplerId': {'deviceSerialNumber': '**************', 'deviceType': 'A3S5BH2HU6VAYF'}, 'bluetoothEvent': 'DEVICE_CONNECTED', 'bluetoothEventPayload': None, 'bluetoothEventSuccess': True}
2019-08-29 20:08:31 DEBUG (MainThread) [alexapy.alexawebsocket] msg: WSMessage(type=<WSMsgType.BINARY: 2>, data=b'MSG 0x00000362 0x646ecec9 f 0x00000001 0xdfe374ec 0x00000240 GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:**************:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:************** {"payload":"{\\"destinationUserId\\":\\"**************\\",\\"dopplerId\\":{\\"deviceSerialNumber\\":\\"B02402F24B334AD19FC26AD2F24E343D\\",\\"deviceType\\":\\"A2IVLV5VM2W81\\"},\\"dopplerConnectionState\\":\\"OFFLINE\\"}","command":"PUSH_DOPPLER_CONNECTION_CHANGE"}FABE', extra='')
2019-08-29 20:08:31 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket MSG.
2019-08-29 20:08:31 DEBUG (MainThread) [alexapy.alexawebsocket] Received b'MSG 0x00000362 0x646ecec9 f 0x00000001 0xdfe374ec 0x00000240 GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:**************:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:************** {"payload":"{\\"destinationUserId\\":\\"**************\\",\\"dopplerId\\":{\\"deviceSerialNumber\\":\\"***********\\",\\"deviceType\\":\\"A2IVLV5VM2W81\\"},\\"dopplerConnectionState\\":\\"OFFLINE\\"}","command":"PUSH_DOPPLER_CONNECTION_CHANGE"}FABE'
2019-08-29 20:08:31 DEBUG (MainThread) [alexapy.alexawebsocket] Received Standard MSG.
2019-08-29 20:08:31 DEBUG (MainThread) [custom_components.alexa_media] d*****************3@gmail.com: Received websocket command: PUSH_DOPPLER_CONNECTION_CHANGE : {'destinationUserId': '**************', 'dopplerId': {'deviceSerialNumber': '**************', 'deviceType': 'A2IVLV5VM2W81'}, 'dopplerConnectionState': 'OFFLINE'}
2019-08-29 20:08:31 DEBUG (MainThread) [custom_components.alexa_media] Discovered new media_player B02402F24B334AD19FC26AD2F24E343D
2019-08-29 20:08:32 DEBUG (MainThread) [custom_components.alexa_media] d*****************3@gmail.com: Found 3 devices, 1 bluetooth
2019-08-29 20:08:32 DEBUG (MainThread) [custom_components.alexa_media] Locale en-us found for G************J7J
2019-08-29 20:08:32 DEBUG (MainThread) [custom_components.alexa_media] DND False found for G************J7J
2019-08-29 20:08:32 DEBUG (MainThread) [custom_components.alexa_media] Locale en-us found for 9****************************292
2019-08-29 20:08:32 DEBUG (MainThread) [custom_components.alexa_media] DND False found for 9****************************292
2019-08-29 20:08:32 DEBUG (MainThread) [custom_components.alexa_media] Locale en-us found for 0****************************036
2019-08-29 20:08:32 DEBUG (MainThread) [custom_components.alexa_media] DND False found for 0****************************036
2019-08-29 20:08:32 DEBUG (MainThread) [custom_components.alexa_media] d*****************3@gmail.com: Existing: [<Entity Daniel's Echo Dot: standby>, <Entity This Device: standby>, <Entity Daniel's Alexa Apps: standby>] New: []; Filtered by: include_devices: [] exclude_devices:[]
2019-08-29 20:08:33 DEBUG (MainThread) [custom_components.alexa_media] d*****************3@gmail.com: Updated last_called: {'serialNumber': 'G************J7J', 'timestamp': 1567098434829}
core-ssh:/config#
`

**Comment by alandtse** [comment]
Please try the proposed fix and let me know if it solves the problem.

**Comment by danielmihalache1983** [comment]
Yep. Issue is fixed. Thanks for the fix.

There is one more thing about the bluetooth...it does not show in the source list.

![image](https://user-images.githubusercontent.com/35133347/64033300-d8699400-cb54-11e9-9c67-03fa488e5c52.png)

yet, when I catch the state change in node-red and verify the json object, I can see the bluetooth as source...yet not in the source list.
![image](https://user-images.githubusercontent.com/35133347/64033470-34ccb380-cb55-11e9-8644-6f9ebc1055d8.png)
can we fix this to?
