### ISSUE TITLE
A lot errors after update to 2.0.1

### ISSUE THREAD

**Issue by bieniu** [custom-components/alexa_media_player#331]
**Describe the bug**
I have a lot of those errors in log after update component to version 2.0.1 (media_player.echo_plus has always the same state: `standby`):
```
2019-09-02 18:53:43 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/alexa/state_report.py", line 45, in async_entity_state_listener
    hass, smart_home_config, alexa_changed_entity
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/alexa/state_report.py", line 103, in async_send_changereport_message
    response_json = json.loads(response_text)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**System details**
 - Home-assistant (version): 0.98.2 (Raspbian, Python 3.7.2, venv)
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 2.0.1 (via HACS)
 - alexapy (version from `pip show alexapy` or HA startup): 1.0.1

**Additional context**
My device: Echo Plus
My config:
```
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
      exclude_devices:
        - "Maciej's Alexa Apps"
        - "This Device"
```

**Comment by bieniu** [comment]
Stupid me, it's not from Alexa media player.
