### ISSUE TITLE
Failed call to service configurator/configure . get

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#344]
**Describe the bug**
Configurator can fail in the login in situations where Amazon attempts to reset cookies to `-` and that is then submitted back to Amazon. Because the cookies are invalid, Amazon then redirects to a page that says to enable javascript. There is a form which the `_process_page` function is pulling the action `get`.  This is then submitted to and it fails because it's an invalid url.

This appears to only happen for the `amazon.it` domain.

**To Reproduce**
1. Set domain to amazon.it
2. Try to log in using configurator
3. Error will display eventually

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7086117/64314402-c37d6e00-cf63-11e9-8f2c-82f6f34e722c.png)

**System details**
 - Home-assistant (version): 0.98.1
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 2.1.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.0.2

**Logs**
```
get
11:20 custom_components/alexa_media/__init__.py (ERROR) - message first occured at 11:17 and shows up 2 times

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/configurator/__init__.py", line 235, in async_handle_service_call
    await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
  File "/config/custom_components/alexa_media/__init__.py", line 153, in configuration_callback
    login, callback_data)
  File "/config/custom_components/alexa_media/__init__.py", line 143, in setup_platform_callback
    await login.login(data=callback_data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 306, in login
    headers=self._headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 466, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 286, in __init__
    self.update_host(url)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 340, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: get
```
**Additional context**
The root cause is the fact something is causing Amazon to invalidate the cookies in the login process. However, the code can probably be fixed to properly handle the page providing `get` so it restarts the login process.

https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/3123
https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/3141

**Comment by alandtse** [comment]
Potential fix in alexapy [here](https://gitlab.com/keatontaylor/alexapy/merge_requests/60). Need an advanced tester who has this problem to try it. Otherwise, I'll handle it as soon as Amazon unthrottles me. ;)

**Comment by gericho** [comment]
I can be you advanced tester, let me know

**Comment by alandtse** [comment]
@gericho thanks. I'll need to get logs from trying to login to a non-US domain.

1. Ensure you have alexa_media 2.1.0 installed and working first.
2. Replace your alexapy with the files in the PR on gitlab. Make backups if you need to.
3. Rename your .pickle file. 
4. Enable logging for `alexa_media` and `alexapy`
5. Try to login.

Hopefully it works successfully. If not, provide logs here or in a private gist.

**Comment by gericho** [comment]
I cannot login, so I cannot pass step 1 (2.1.0 installed with HACS)

came up a banner with:
`Failed to call service configurator/configure. Cannot be called from within the event loop`

My configuration.yaml:
```
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.it
```

**Comment by engior** [comment]
> I cannot login, so I cannot pass step 1 (2.1.0 installed with HACS)
> 
> came up a banner with:
> `Failed to call service configurator/configure. Cannot be called from within the event loop`
> 
> My configuration.yaml:
> 
> ```
> alexa_media:
>   accounts:
>     - email: !secret amazon_user
>       password: !secret amazon_password
>       url: amazon.it
> ```
> 
> PS: the 6 digit code come into the email normally

I have exactly the same problem with the same configuration.
I get my 2FA code but when I confirm that code in the notification come up the same banner:
> `Failed to call service configurator/configure. Cannot be called from within the event loop`

**Comment by alandtse** [comment]
Thanks. Sorry, I shouldn't have said "and working" for step 1. Can you go ahead and replace alexapy?

**Comment by gericho** [comment]
I tried but maybe is over my talents...

I enabled logs as follow:
```
logger:      
  default: fatal
  logs:
    homeassistant.core: fatal
    custom_components.alexa_media: debug
    custom_components.alexapy: debug
```

and then installed the venv, what I get is:
```
✔ Successfully created virtual environment!
Virtualenv location: /root/.local/share/virtualenvs/custom_components-qua5qjbV
Installing dependencies from Pipfile.lock (f8c41d)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 92/92 — 00:04:54
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```
Frankly I'm not sure how to continue.

**Comment by alandtse** [comment]
One small change in your logger:
```
logger:      
  default: fatal
  logs:
    homeassistant.core: fatal
    custom_components.alexa_media: debug
    alexapy: debug
```

Your logs should be in the config directory under homeassistant.log.  I'm at work so can't check specifically.  The UI also has some logs in the Developer Tools section if you can't find the raw file.

**Comment by gericho** [comment]
So the log is as follow:
```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/configurator/__init__.py", line 235, in async_handle_service_call
    await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/__init__.py", line 166, in configuration_callback
    login, callback_data)
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/__init__.py", line 158, in setup_platform_callback
    setup_platform_callback)
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/__init__.py", line 295, in test_login_status
    setup_platform_callback)
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/__init__.py", line 246, in request_configuration
    fields=[{'id': 'verificationcode', 'name': 'Verification Code'}]
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/configurator/__init__.py", line 93, in request_config
    hass.loop, ft.partial(async_request_config, hass, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/async_.py", line 201, in run_callback_threadsafe
    raise RuntimeError("Cannot be called from within the event loop")
RuntimeError: Cannot be called from within the event loop
```

**Comment by alandtse** [comment]
Thanks @gericho. Go ahead and restore your alexapy. I've been testing it tonight and that is probably not the solution. Trying a different angle now.

**Comment by alandtse** [comment]
Ok playing around more with this, it feels like only `alexa.it` has this problem and only if you have 2FA enabled. I have a new build I'll push that resolves the specific error but not the inability to use 2FA for amazon.it.

Workaround when I do the new release will be to disable 2FA to get the cookie and then reenable.
