### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by glugoboni** [custom-components/alexa_media_player#354]
I'm not able to relogin and configuratore your plug-in.

from some versions I am no longer able, before everything worked correctly

**Comment by alandtse** [comment]
Is this #353?

**Comment by glugoboni** [comment]
Hello, i check my amazon account but i don’t have 2fa enable 

 



Giovanni Lugoboni
tel. +39 348 8402153
www.lugoboni.it


Inviato da iPad

> Il giorno 9 set 2019, alle ore 20:00, Alan Tse <notifications@github.com> ha scritto:
> 

﻿
Is this #353?

**Comment by glugoboni** [comment]
i reinstall the component and after insert captcha i see this screen.



 

 



Giovanni Lugoboni
tel. +39 348 8402153
www.lugoboni.it <http://www.lugoboni.it/>

Il giorno 9 set 2019, alle ore 20:34, Giovanni Lugoboni <info@lugoboni.it> ha scritto:

Hello, i check my amazon account but i don’t have 2fa enable 

 


Giovanni Lugoboni
tel. +39 348 8402153 <tel:+39%20348%208402153>
www.lugoboni.it <http://www.lugoboni.it/>

Inviato da iPad

> Il giorno 9 set 2019, alle ore 20:00, Alan Tse <notifications@github.com> ha scritto:
> 

﻿
Is this #353 <https://github.com/custom-components/alexa_media_player/issues/353>?

**Comment by alandtse** [comment]
Did you not post an image? You may have to go to GitHub to post.

**Comment by glugoboni** [comment]
Hi...this is the image:
![Schermata 2019-09-10 alle 09 21 15](https://user-images.githubusercontent.com/48253557/64592619-ad7d0c80-d3ac-11e9-8f5b-48a3f684b369.jpg)
 and the second:
![Schermata 2019-09-09 alle 20 41 30](https://user-images.githubusercontent.com/48253557/64592663-c38acd00-d3ac-11e9-8bbe-ead605bdb2e4.jpg)

**Comment by glugoboni** [comment]
in log file:
Cannot connect to host alexa.amazon.it:443 ssl:<ssl.SSLContext object at 0x722caab0> [Try again]
09:28 custom_components/alexa_media/__init__.py (ERROR)

**Comment by alandtse** [comment]
Please provide the full logs. I don't have enough information to help you. Your last ssl error indicates you can't connect to the domain alexa.amazon.it.  Do you have connectivity on the device?

**Comment by glugoboni** [comment]
Tue Sep 10 2019 12:17:15 GMT+0200 (CEST)

Cannot connect to host alexa.amazon.it:443 ssl:<ssl.SSLContext object at 0x726bffb0> [Try again]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 955, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 825, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/configurator/__init__.py", line 235, in async_handle_service_call
    await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
  File "/config/custom_components/alexa_media/__init__.py", line 165, in configuration_callback
    login, callback_data)
  File "/config/custom_components/alexa_media/__init__.py", line 155, in setup_platform_callback
    await login.login(data=callback_data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 350, in login
    ssl=self._ssl)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 959, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host alexa.amazon.it:443 ssl:<ssl.SSLContext object at 0x726bffb0> [Try again]

**Comment by alandtse** [comment]
This is just indicating a network failure. Are you able to ping or access alexa.amazon.it from the HA device?

**Comment by glugoboni** [comment]
Yes i ping Alexa.amazon.it from my device

**Comment by alandtse** [comment]
The logs aren't describing the problem then. I won't be able to help unless there's some logs showing the specific error. Did you enable debug logging per the wiki? We'll need the full log with you configurator attempt. Please scrub any private info from the file.

**Comment by alandtse** [comment]
Could be related to #362 and #363. May need the system health info from HA. 

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.4
timezone | America/Los_Angeles
version | 0.98.5
virtualenv | false

**Comment by alandtse** [comment]
This should be resolved by 2.2.1, please try and let me know if it doesn't work.
