### ISSUE TITLE
Alexa media player - Front end inaccessible after about 2 weeks (no reboot)

### ISSUE THREAD

**Issue by String-656** [custom-components/alexa_media_player#356]
**Describe the bug**
Continued use without restarting HA (hass.io), (or the controller), alexa_media player seems to cause the frontend of HA to hang/not load. This has consecutively occurred 3 times.  

**To Reproduce**
Leave operating continually.. about 2 weeks without a reboot or any changes to config. 

**Screenshots**
Unable to access front end (on local network/port - 192.168.0.50:8123). However HA is executing (automation running - e.g. lights) 

**System details**
 - Home-assistant (HassOS 2.12 (HA 0.98.4) ): 
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): '2.0.0'
 - alexapy (version from `pip show alexapy` or HA startup): ? not sure, but the latest was copied 2 months ago from github repos

**Logs**
Unable to retrieve the detailed alexa_logs, as it was not enabled... but here's HA logs. 

`2019-09-10 14:54:54 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 199, in _handle_event
    await self.async_schedule_update_ha_state()
TypeError: object NoneType can't be used in 'await' expression
2019-09-10 14:54:54 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 199, in _handle_event
    await self.async_schedule_update_ha_state()
TypeError: object NoneType can't be used in 'await' expression
2019-09-10 14:54:55 WARNING (Recorder) [homeassistant.components.recorder] Event is not JSON serializable: <Event state_changed[L]: entity_id=media_player.joshuas_echo_dot, old_state=<state media_player.joshuas_echo_dot=paused; volume_level=0.75, is_volume_muted=False, media_content_type=music, media_duration=278, media_position=47, media_position_updated_at=2019-09-10T14:54:38.459692+08:00, media_title=Be Yourself, media_artist=Audioslave, media_album_name=Guitar, source=Local Speaker, source_list=['Local Speaker', 'Galaxy S9', 'MI19900514', 'Samsung Galaxy S7 edge', 'Mi Phone', 'Mi Phone'], available=True, last_called=True, friendly_name=Joshua's Echo Dot, entity_picture=/api/media_player_proxy/media_player.joshuas_echo_dot?token=**<token retracted>**&cache=2ffe1c0bc2ab38e2, supported_features=56253 @ 2019-09-10T14:54:38.461796+08:00>, new_state=<state media_player.joshuas_echo_dot=paused; volume_level=0.75, is_volume_muted=False, media_content_type=music, media_duration=278, media_position=47, media_position_updated_at=2019-09-10T14:54:38.459692+08:00, media_title=Be Yourself, media_artist=Audioslave, media_album_name=Guitar, source=<coroutine object AlexaClient._get_source at 0x70eb3fa8>, source_list=<coroutine object AlexaClient._get_source_list at 0x713e1c00>, available=True, last_called=True, friendly_name=Joshua's Echo Dot, entity_picture=/api/media_player_proxy/media_player.joshuas_echo_dot?token=**<token retracted>**&cache=2ffe1c0bc2ab38e2, supported_features=56253 @ 2019-09-10T14:54:38.461796+08:00>>
2019-09-10 14:54:55 WARNING (Recorder) [homeassistant.components.recorder] State is not JSON serializable: <state media_player.joshuas_echo_dot=paused; volume_level=0.75, is_volume_muted=False, media_content_type=music, media_duration=278, media_position=47, media_position_updated_at=2019-09-10T14:54:38.459692+08:00, media_title=Be Yourself, media_artist=Audioslave, media_album_name=Guitar, source=<coroutine object AlexaClient._get_source at 0x70eb3fa8>, source_list=<coroutine object AlexaClient._get_source_list at 0x713e1c00>, available=True, last_called=True, friendly_name=Joshua's Echo Dot, entity_picture=/api/media_player_proxy/media_player.joshuas_echo_dot?token=**<token retracted>**&cache=2ffe1c0bc2ab38e2, supported_features=56253 @ 2019-09-10T14:54:38.461796+08:00>
2019-09-10 14:54:55 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 199, in _handle_event
    await self.async_schedule_update_ha_state()
TypeError: object NoneType can't be used in 'await' expression
2019-09-10 14:54:55 WARNING (Recorder) [homeassistant.components.recorder] Event is not JSON serializable: <Event state_changed[L]: entity_id=media_player.joshuas_echo_dot, old_state=<state media_player.joshuas_echo_dot=paused; volume_level=0.75, is_volume_muted=False, media_content_type=music, media_duration=278, media_position=47, media_position_updated_at=2019-09-10T14:54:38.459692+08:00, media_title=Be Yourself, media_artist=Audioslave, media_album_name=Guitar, source=<coroutine object AlexaClient._get_source at 0x70eb3fa8>, source_list=<coroutine object AlexaClient._get_source_list at 0x713e1c00>, available=True, last_called=True, friendly_name=Joshua's Echo Dot, entity_picture=/api/media_player_proxy/media_player.joshuas_echo_dot?token=**<token retracted>**&cache=2ffe1c0bc2ab38e2, supported_features=56253 @ 2019-09-10T14:54:38.461796+08:00>, new_state=<state media_player.joshuas_echo_dot=paused; volume_level=0.75, is_volume_muted=False, media_content_type=music, media_duration=278, media_position=47, media_position_updated_at=2019-09-10T14:54:38.459692+08:00, media_title=Be Yourself, media_artist=Audioslave, media_album_name=Guitar, source=Local Speaker, source_list=['Local Speaker', 'MI19900514', 'Galaxy S9', 'Samsung Galaxy S7 edge', 'Mi Phone', 'Mi Phone'], available=True, last_called=True, friendly_name=Joshua's Echo Dot, entity_picture=/api/media_player_proxy/media_player.joshuas_echo_dot?token=**<token retracted>**&cache=2ffe1c0bc2ab38e2, supported_features=56253 @ 2019-09-10T14:54:38.461796+08:00>>
2019-09-10 14:54:55 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: Instance <Events at 0x7002dfb0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
2019-09-10 14:54:55 ERROR (Recorder) [homeassistant.components.recorder] Error saving event: <Event state_changed[L]: entity_id=media_player.joshuas_echo_dot, old_state=<state media_player.joshuas_echo_dot=paused; volume_level=0.75, is_volume_muted=False, media_content_type=music, media_duration=278, media_position=47, media_position_updated_at=2019-09-10T14:54:38.459692+08:00, media_title=Be Yourself, media_artist=Audioslave, media_album_name=Guitar, source=<coroutine object AlexaClient._get_source at 0x70eb3fa8>, source_list=<coroutine object AlexaClient._get_source_list at 0x713e1c00>, available=True, last_called=True, friendly_name=Joshua's Echo Dot, entity_picture=/api/media_player_proxy/media_player.joshuas_echo_dot?token=**<token retracted>**&cache=2ffe1c0bc2ab38e2, supported_features=56253 @ 2019-09-10T14:54:38.461796+08:00>, new_state=<state media_player.joshuas_echo_dot=paused; volume_level=0.75, is_volume_muted=False, media_content_type=music, media_duration=278, media_position=47, media_position_updated_at=2019-09-10T14:54:38.459692+08:00, media_title=Be Yourself, media_artist=Audioslave, media_album_name=Guitar, source=Local Speaker, source_list=['Local Speaker', 'MI19900514', 'Galaxy S9', 'Samsung Galaxy S7 edge', 'Mi Phone', 'Mi Phone'], available=True, last_called=True, friendly_name=Joshua's Echo Dot, entity_picture=/api/media_player_proxy/media_player.joshuas_echo_dot?token=**<token retracted>**&cache=2ffe1c0bc2ab38e2, supported_features=56253 @ 2019-09-10T14:54:38.461796+08:00>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 353, in run
    dbstate.event_id = dbevent.event_id
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 705, in get
    value = state._load_expired(state, passive)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 660, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 913, in load_scalar_attributes
    "attribute refresh operation cannot proceed" % (state_str(state))
sqlalchemy.orm.exc.DetachedInstanceError: Instance <Events at 0x7002dfb0> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
2019-09-10 14:54:56 WARNING (Recorder) [homeassistant.components.recorder] Event is not JSON serializable: <Event state_changed[L]: entity_id=media_player.joshuas_echo_dot, old_state=<state media_player.joshuas_echo_dot=standby; is_volume_muted=False, media_content_type=standby, media_position_updated_at=2019-09-10T14:54:55.352207+08:00, source=Local Speaker, source_list=['Local Speaker', 'MI19900514', 'Galaxy S9', 'Samsung Galaxy S7 edge', 'Mi Phone', 'Mi Phone'], available=True, last_called=True, friendly_name=Joshua's Echo Dot, supported_features=56253 @ 2019-09-10T14:54:55.353577+08:00>, new_state=<state media_player.joshuas_echo_dot=standby; is_volume_muted=False, media_content_type=standby, media_position_updated_at=2019-09-10T14:54:55.352207+08:00, source=<coroutine object AlexaClient._get_source at 0x70190ae0>, source_list=<coroutine object AlexaClient._get_source_list at 0x70b81f18>, available=True, last_called=True, friendly_name=Joshua's Echo Dot, supported_features=56253 @ 2019-09-10T14:54:55.353577+08:00>>
2019-09-10 14:54:56 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 199, in _handle_event
    await self.async_schedule_update_ha_state()
TypeError: object NoneType can't be used in 'await' expression
2019-09-10 14:54:56 WARNING (Recorder) [homeassistant.components.recorder] State is not JSON serializable: <state media_player.joshuas_echo_dot=standby; is_volume_muted=False, media_content_type=standby, media_position_updated_at=2019-09-10T14:54:55.352207+08:00, source=<coroutine object AlexaClient._get_source at 0x70190ae0>, source_list=<coroutine object AlexaClient._get_source_list at 0x70b81f18>, available=True, last_called=True, friendly_name=Joshua's Echo Dot, supported_features=56253 @ 2019-09-10T14:54:55.353577+08:00>
2019-09-10 14:54:56 WARNING (Recorder) [homeassistant.components.recorder] Event is not JSON serializable: <Event state_changed[L]: entity_id=media_player.joshuas_echo_dot, old_state=<state media_player.joshuas_echo_dot=standby; is_volume_muted=False, media_content_type=standby, media_position_updated_at=2019-09-10T14:54:55.352207+08:00, source=<coroutine object AlexaClient._get_source at 0x70190ae0>, source_list=<coroutine object AlexaClient._get_source_list at 0x70b81f18>, available=True, last_called=True, friendly_name=Joshua's Echo Dot, supported_features=56253 @ 2019-09-10T14:54:55.353577+08:00>, new_state=<state media_player.joshuas_echo_dot=standby; is_volume_muted=False, media_content_type=standby, media_position_updated_at=2019-09-10T14:54:55.352207+08:00, source=<coroutine object AlexaClient._get_source at 0x70b81e40>, source_list=<coroutine object AlexaClient._get_source_list at 0x70bec660>, available=True, last_called=True, friendly_name=Joshua's Echo Dot, supported_features=56253 @ 2019-09-10T14:54:55.353577+08:00>>
2019-09-10 14:54:56 WARNING (Recorder) [homeassistant.components.recorder] State is not JSON serializable: <state media_player.joshuas_echo_dot=standby; is_volume_muted=False, media_content_type=standby, media_position_updated_at=2019-09-10T14:54:55.352207+08:00, source=<coroutine object AlexaClient._get_source at 0x70b81e40>, source_list=<coroutine object AlexaClient._get_source_list at 0x70bec660>, available=True, last_called=True, friendly_name=Joshua's Echo Dot, supported_features=56253 @ 2019-09-10T14:54:55.353577+08:00>
2019-09-10 14:54:56 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 199, in _handle_event
    await self.async_schedule_update_ha_state()
TypeError: object NoneType can't be used in 'await' expression
2019-09-10 14:54:56 WARNING (Recorder) [homeassistant.components.recorder] Event is not JSON serializable: <Event state_changed[L]: entity_id=media_player.joshuas_echo_dot, old_state=<state media_player.joshuas_echo_dot=standby; is_volume_muted=False, media_content_type=standby, media_position_updated_at=2019-09-10T14:54:55.352207+08:00, source=<coroutine object AlexaClient._get_source at 0x70b81e40>, source_list=<coroutine object AlexaClient._get_source_list at 0x70bec660>, available=True, last_called=True, friendly_name=Joshua's Echo Dot, supported_features=56253 @ 2019-09-10T14:54:55.353577+08:00>, new_state=<state media_player.joshuas_echo_dot=standby; is_volume_muted=False, media_content_type=standby, media_position_updated_at=2019-09-10T14:54:55.352207+08:00, source=<coroutine object AlexaClient._get_source at 0x70bec3d8>, source_list=<coroutine object AlexaClient._get_source_list at 0x70bec108>, available=True, last_called=True, friendly_name=Joshua's Echo Dot, supported_features=56253 @ 2019-09-10T14:54:55.353577+08:00>>
2019-09-10 14:54:56 WARNING (Recorder) [homeassistant.components.recorder] State is not JSON serializable: <state media_player.joshuas_echo_dot=standby; is_volume_muted=False, media_content_type=standby, media_position_updated_at=2019-09-10T14:54:55.352207+08:00, source=<coroutine object AlexaClient._get_source at 0x70bec3d8>, source_list=<coroutine object AlexaClient._get_source_list at 0x70bec108>, available=True, last_called=True, friendly_name=Joshua's Echo Dot, supported_features=56253 @ 2019-09-10T14:54:55.353577+08:00>
2019-09-10 14:54:56 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 199, in _handle_event
    await self.async_schedule_update_ha_state()
TypeError: object NoneType can't be used in 'await' expression`

**Additional context**
First and second time this occurred, I had to completely rebuild from a fresh HA Hass.io image. However the third, I when through the logs, identified it was alexa_media. Commenting out alexa_media from the configuration.yaml file and hard rebooted the Rpi. This then restored HA / frontend. Note. I have tried hard rebooting the controller on the first and second occurrences, but no luck, same errors. It seems it is related to recorder, and this --- "Event is not JSON serializable" 

The only difference in config compared to a standard Hass.io install is that I'm using a maria DB on my synology NAS instead of the standard SQL lite DB on the RPi SD Card.

**Comment by alandtse** [comment]
If you have a manual install of alexapy you should remove it. The bug you're referring to was fixed recently #302 but it looks like you may be loading an old version. On start-up it should report the alexapy version in the logs.

**Comment by String-656** [comment]
Legend. Thank you.
