### ISSUE TITLE
RuntimeError: Cannot be called from within the event loop - request_configuration

### ISSUE THREAD

**Issue by itajackass** [custom-components/alexa_media_player#428]
After upgrade on latest version, on HA 0.100.1 I get a notification to configure alexa media player via sms or email. Both options i try i get error popup

Fallita chiamata a servizio configurator/configure . Cannot be called from within the event loop

**Comment by alandtse** [comment]
Can you please provide the HA logs for this?

**Comment by itajackass** [comment]
Log Details (ERROR)
Sat Oct 12 2019 11:18:09 GMT+0200 (Ora legale dell’Europa centrale)
Cannot be called from within the event loop
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1233, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1258, in _execute_service
    await handler.func(service_call)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/configurator/__init__.py", line 235, in async_handle_service_call
    await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/__init__.py", line 187, in configuration_callback
    login, callback_data)
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/__init__.py", line 178, in setup_platform_callback
    setup_platform_callback)
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/__init__.py", line 320, in test_login_status
    setup_platform_callback)
  File "/home/homeassistant/.homeassistant/custom_components/alexa_media/__init__.py", line 267, in request_configuration
    fields=[{'id': 'verificationcode', 'name': 'Verification Code'}]
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/configurator/__init__.py", line 93, in request_config
    hass.loop, ft.partial(async_request_config, hass, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/async_.py", line 63, in run_callback_threadsafe
    raise RuntimeError("Cannot be called from within the event loop")
RuntimeError: Cannot be called from within the event loop

**Comment by alandtse** [comment]
Thanks for reporting. Please use the file in the referenced fix. I'll push a new version probably in a week.
