### ISSUE TITLE
TTS Notifications no longer work after move to .100.3

### ISSUE THREAD

**Issue by scstraus** [custom-components/alexa_media_player#449]
**Describe the bug**
I had scripts that were working perfectly under .97 now which don't work at all and create a traceback in the logs

**To Reproduce**
Run following script

```
  where_is_sophie:
    sequence:
      - service: alexa_media.update_last_called  #this will force update the last Alexa attribute used by the sensor
      - delay: 00:00:01  # you may need to increase this value if you dont get the response on the echo you asked the question
      - service: notify.alexa_media
        data_template:
          target: 
            - '{{ states.sensor.last_alexa.state }}' 
          data:
            type: tts
          message: >-
            Sophie is {{ states.sensor.sophie_location.state }}
```

**Expected behavior**
To read the sensor value which is "At home"

**Screenshots**

**System details**
 - Home-assistant (version): 
100.3
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
Yes
 - alexa_media  (version from `const.py` or HA startup):
2.3.1
 - alexapy (version from `pip show alexapy` or HA startup):
1.3.2
**Logs**
```
ERROR (MainThread) [homeassistant.components.script] Error executing script script.where_is_sophie. Unknown error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 209, in async_turn_on
    await self.script.async_run(kwargs.get(ATTR_VARIABLES), context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 181, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 265, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 348, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 97, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1233, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1258, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/alexa_media/__init__.py", line 620, in last_call_handler
    await update_last_called(login_obj)
  File "/config/custom_components/alexa_media/__init__.py", line 531, in update_last_called
    last_called = await AlexaAPI.get_last_device_serial(login_obj)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 587, in get_last_device_serial
    response = await AlexaAPI.get_activities(login, items)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 551, in get_activities
    return (await response.json(content_type=None))['activities']
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-10-26 13:13:11 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall script.where_is_sophie (c:89240090b398495f9afbd9c36c82c1da)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1241, in _safe_execute
    await self._execute_service(handler, service_call)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1258, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 142, in service_handler
    await script.async_turn_on(variables=service.data, context=service.context)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 214, in async_turn_on
    raise err
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 209, in async_turn_on
    await self.script.async_run(kwargs.get(ATTR_VARIABLES), context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 181, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 265, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 348, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 97, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1233, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1258, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/alexa_media/__init__.py", line 620, in last_call_handler
    await update_last_called(login_obj)
  File "/config/custom_components/alexa_media/__init__.py", line 531, in update_last_called
    last_called = await AlexaAPI.get_last_device_serial(login_obj)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 587, in get_last_device_serial
    response = await AlexaAPI.get_activities(login, items)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 551, in get_activities
    return (await response.json(content_type=None))['activities']
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
**Additional context**

From what I can tell in the logs, alexa_media starts up correctly, logs in and gets the status of a bunch of stuff.  Was thinking to post the log but there's a lot of cookies in there which I'm not sure if it's safe to re-post here.

**Comment by scstraus** [comment]
I upgraded to the latest version and it's working again.. I'll close this.
