### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'entity_id'

### ISSUE THREAD

**Issue by lweberru** [custom-components/alexa_media_player#458]
**Describe the bug**
Not all devices (reminder, alarms, ...) are available. And log get spammed with errors

**My config**
I have a simple config without any filters:
`
alexa_media:
  accounts:
    - email: !secret amazon_username
      password: !secret amazon_password
      url: amazon.de 
`

**System details**
 - Home-assistant (version): 0.101.3
 - Alexa Media Player (version): 2.3.4
 - Hassio (Yes/No): yes

**Logs**

`2019-11-02 16:33:29 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 181, in async_send_delete_message alexa_entity = ENTITY_ADAPTERS[domain](hass, config, hass.states.get(entity_id)) File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 150, in __init__ self.entity_conf = config.entity_config.get(entity.entity_id, {}) AttributeError: 'NoneType' object has no attribute 'entity_id' 
2019-11-02 16:33:29 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 147, in async_send_add_or_update_message alexa_entity = ENTITY_ADAPTERS[domain](hass, config, hass.states.get(entity_id)) File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 150, in __init__ self.entity_conf = config.entity_config.get(entity.entity_id, {}) AttributeError: 'NoneType' object has no attribute 'entity_id' `

**Additional context**

**Comment by lweberru** [comment]
Ok this error has nothing to do with the alexa_media player. It is related to the alexa skill integration somehow. So you can close this issue here...
