### ISSUE TITLE
Cannot connect to host alexa.amazon.de:443 - socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by zibous** [custom-components/alexa_media_player#489]
```
Home Assistant 0.103.3
arch	x86_64
dev	false
docker	false
hassio	false
os_name	Linux
python_version	3.7.5
timezone	Europe/Vaduz
version	0.103.3
virtualenv	true
Lovelace
mode	yaml
resources	20
views	9
```

**Alexa Media Player - Installed: v2.3.6**

I have received these error messages since the last update.

```
Dez 22 15:12:25 zeusus hass[28631]: 2019-12-22 15:12:25 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.echo2 fails
Dez 22 15:12:25 zeusus hass[28631]: Traceback (most recent call last):
Dez 22 15:12:25 zeusus hass[28631]:   File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/connector.py", line 967, in _create_direct_connection
Dez 22 15:12:25 zeusus hass[28631]:     traces=traces), loop=self._loop)
Dez 22 15:12:25 zeusus hass[28631]:   File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
Dez 22 15:12:25 zeusus hass[28631]:     self._resolver.resolve(host, port, family=self._family)
Dez 22 15:12:25 zeusus hass[28631]:   File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
Dez 22 15:12:25 zeusus hass[28631]:     host, port, type=socket.SOCK_STREAM, family=family)
Dez 22 15:12:25 zeusus hass[28631]:   File "/usr/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
Dez 22 15:12:25 zeusus hass[28631]:     None, getaddr_func, host, port, family, type, proto, flags)
Dez 22 15:12:25 zeusus hass[28631]:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Dez 22 15:12:25 zeusus hass[28631]:     result = self.fn(*self.args, **self.kwargs)
Dez 22 15:12:25 zeusus hass[28631]:   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
Dez 22 15:12:25 zeusus hass[28631]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Dez 22 15:12:25 zeusus hass[28631]: socket.gaierror: [Errno -2] Name or service not known
Dez 22 15:12:25 zeusus hass[28631]: The above exception was the direct cause of the following exception:
Dez 22 15:12:25 zeusus hass[28631]: Traceback (most recent call last):
Dez 22 15:12:25 zeusus hass[28631]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 281, in async_update_ha_state
Dez 22 15:12:25 zeusus hass[28631]:     await self.async_device_update()
Dez 22 15:12:25 zeusus hass[28631]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 459, in async_device_update
Dez 22 15:12:25 zeusus hass[28631]:     await self.async_update()
Dez 22 15:12:25 zeusus hass[28631]:   File "/home/homeassistant/.homeassistant/custom_components/alexa_media/media_player.py", line 565, in async_update
Dez 22 15:12:25 zeusus hass[28631]:     no_throttle=True)
Dez 22 15:12:25 zeusus hass[28631]:   File "/home/homeassistant/.homeassistant/custom_components/alexa_media/helpers.py", line 143, in wrapper
Dez 22 15:12:25 zeusus hass[28631]:     result = await func(*args, **kwargs)
Dez 22 15:12:25 zeusus hass[28631]:   File "/home/homeassistant/.homeassistant/custom_components/alexa_media/media_player.py", line 362, in refresh
Dez 22 15:12:25 zeusus hass[28631]:     session = await self.alexa_api.get_state()
Dez 22 15:12:25 zeusus hass[28631]:   File "/srv/homeassistant/lib/python3.7/site-packages/alexapy/alexaapi.py", line 456, in get_state
Dez 22 15:12:25 zeusus hass[28631]:     '&screenWidth=2560')
Dez 22 15:12:25 zeusus hass[28631]:   File "/srv/homeassistant/lib/python3.7/site-packages/alexapy/alexaapi.py", line 104, in _get_request
Dez 22 15:12:25 zeusus hass[28631]:     return await self._request('get', uri, data)
Dez 22 15:12:25 zeusus hass[28631]:   File "/srv/homeassistant/lib/python3.7/site-packages/alexapy/alexaapi.py", line 73, in _request
Dez 22 15:12:25 zeusus hass[28631]:     ssl=self._login._ssl)
Dez 22 15:12:25 zeusus hass[28631]:   File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
Dez 22 15:12:25 zeusus hass[28631]:     timeout=real_timeout
Dez 22 15:12:25 zeusus hass[28631]:   File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
Dez 22 15:12:25 zeusus hass[28631]:     proto = await self._create_connection(req, traces, timeout)
Dez 22 15:12:25 zeusus hass[28631]:   File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
Dez 22 15:12:25 zeusus hass[28631]:     req, traces, timeout)
Dez 22 15:12:25 zeusus hass[28631]:   File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
Dez 22 15:12:25 zeusus hass[28631]:     raise ClientConnectorError(req.connection_key, exc) from exc
Dez 22 15:12:25 zeusus hass[28631]: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host alexa.amazon.de:443 ssl:<ssl.SSLContext object at 0x7f7b1da1dfa0> [Name or service not known]
```

How can I fix the error ?

**Comment by alandtse** [comment]
We haven't changed any of the code related to the connection. The error in the logs indicates you're having a DNS resolution error on the HA machine.

**Comment by zibous** [comment]
@alandtse 
Yesterday,  I installed the new HAS version 0.103.4 and added the following entry in the configuration:

```
alexa_media:
  accounts:
  - email:! secret alexa_user
    password:! secret alexa_pass
    url: amazon.de
    include_devices:
      - dining room
      - living room
      - Office
      - fitness room
      - Bath
    exclude_devices:
      - "Peter's Alexa Apps"
```
I had previously configured the devices using the HAS integration. Now it seems to run without errors.  But still don't know why.

DNS is working:
```
$ nmap -Pn alexa.amazon.de
Starting Nmap 7.80 (https://nmap.org) at 2019-12-23 08:31 CET
Nmap scan report for alexa.amazon.de (99.86.238.54)
Host is up (0.020s latency).
rDNS record for 99.86.238.54: server-99-86-238-54.vie50.r.cloudfront.net
Not shown: 998 filtered ports
PORT STATE SERVICE
80 / tcp open http
443 / tcp open https

Nmap done: 1 IP address (1 host up) scanned in 4.91 seconds

$ dig alexa.amazon.de
; << >> DiG 9.11.5-P4-5.1ubuntu2.1-Ubuntu << >> alexa.amazon.de
;; global options: + cmd
;; Got answer:
;; - >> HEADER << - opcode: QUERY, status: NOERROR, id: 47483
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags :; udp: 4096
;; QUESTION SECTION:
; Alexa.amazon.de. IN A

;; ANSWER SECTION:
alexa.amazon.de. 630 IN CNAME layla.amazon.com.
layla.amazon.com. 1682 IN CNAME layla.amazon.com.frontier.a2z.com.
layla.amazon.com.frontier.a2z.com. 58 IN CNAME d3rsqup3tcxj1a.cloudfront.net.
d3rsqup3tcxj1a.cloudfront.net. 9 IN A 99.86.238.54

;; Query time: 23 msec
;; SERVER: 10.1.1.35 # 53 (10.1.1.35)
;; WHEN: Mon Dec 23 08:32:20 CET 2019
;; MSG SIZE rcvd: 177
```

**Comment by alandtse** [comment]
It shouldn't matter if you use the integration or the configuration.yaml for the DNS error you're reporting as the configuration.yaml data is automatically imported into the integration page for you. It's the same code path for connecting.  

If you do run into a DNS error, you can simply remove and readd and it'll try to connect again.

As a note, your use of `exclude_devices` doesn't do anything as it is processed after the `include_devices`.

**Comment by zibous** [comment]
@alandtse 

Yes, you're right it's a DNS problem. I deactivated **PIHOLE** for the computer and now it runs without error messages.

Basically, the possibilities I use from alexa_media_player works, only that if I have activated **PIHOLE**, the error message fills my HASS log.

Thanks for the tip of the settings.
