### ISSUE TITLE
KeyError in v.2.4.0 in ['media_player'][x].state == STATE_PLAYING)

### ISSUE THREAD

**Issue by caiosweet** [custom-components/alexa_media_player#496]
**Describe the bug**
After installed alexa_media v.2.4.0 error appears in log file.
Everything seems to be working properly...

**System details**
 - Home-assistant (0.103.5): 
 - Hassio (Yes)
 - alexa_media  (Installed: v2.4.0):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
```
2020-01-01 10:47:45 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 260, in _handle_event
    await self.async_update()
  File "/config/custom_components/alexa_media/helpers.py", line 143, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 667, in async_update
    no_throttle=True)
  File "/config/custom_components/alexa_media/helpers.py", line 143, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 371, in refresh
    self._parent_clusters))
  File "/config/custom_components/alexa_media/media_player.py", line 370, in <lambda>
    ['media_player'][x].state == STATE_PLAYING),
KeyError: 'a6cd9003eaf44edc83025260bd45382e'
```

**Comment by caiosweet** [comment]
After many reboots it seems to have disappeared.

**Comment by finity69x2** [comment]
Just tested the PR to fix it and it seems to be working.
