### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#501]
**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
```
2020-01-01 20:40:25 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/alexa_media/sensor.py", line 128, in async_setup_entry
    hass, config_entry.data, async_add_devices, discovery_info=None
  File "/config/custom_components/alexa_media/helpers.py", line 111, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/sensor.py", line 89, in async_setup_platform
    account,
  File "/config/custom_components/alexa_media/sensor.py", line 343, in __init__
    client, n_json, "date_time", account, f"next {self._type}", "mdi:alarm"
  File "/config/custom_components/alexa_media/sensor.py", line 170, in __init__
    self._all = list(map(self._fix_alarm_date_time, self._all))
  File "/config/custom_components/alexa_media/sensor.py", line 186, in _fix_alarm_date_time
    value[1][self._sensor_property] = timezone.localize(naive_time)
  File "/usr/local/lib/python3.7/site-packages/pytz/tzinfo.py", line 317, in localize
    if dt.tzinfo is not None:
AttributeError: 'NoneType' object has no attribute 'tzinfo'
```

**Additional context**

**Comment by pickerin** [comment]
Which Timezone is being checked?  Where would I set it to prevent the error?

**Comment by alandtse** [comment]
Did you try using the code? It will also generate some other diagnostics. It's looking for the timezone set for each Alexa device. If you have non-Alexa devices, it's possible they are not populating that field at all and causing the error. However I need the logs to know.
