### ISSUE TITLE
Runtime

### ISSUE THREAD

**Issue by steve28** [custom-components/alexa_media_player#531]
**Describe the bug**
After "a while" I will get a RuntimeError: Session is closed.  With the following trace:
```
2020-01-17 14:00:14 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 46, in async_entity_state_listener
    hass, smart_home_config, alexa_changed_entity
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 97, in async_send_changereport_message
    allow_redirects=True,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
```

After this, it seems to "crash" something with hassio - I can no longer use the sidebar items associated with hassio add ons (HACS, NodeRed, etc.) . I get this:

![image](https://user-images.githubusercontent.com/5874433/72667789-6d6e0c00-39d4-11ea-8b9f-b873982b9556.png)

Once this error occurs, I have to log in to ssh into hassio (ssh community add-on) and restart that way - going to Configuration->Server Controls->Restart has no effect (i.e., nothing happens when you click "restart")

**System details**
 - Home-assistant (version): 104.1 (but also occured under 103.6)
 - Hassio (Yes/No): YES.
 - alexa_media  (version from `const.py` or HA startup): 2.5.2
 - alexapy (version from `pip show alexapy` or HA startup):

**Comment by alandtse** [comment]
This is not related to `alexa_media`. You're looking at bugs from the official component. Please report there.
