### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Krocko** [custom-components/alexa_media_player#549]
With homeassistant 0.105 beta I got this error:

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 161, in async_platform_discovered
    await async_setup_platform(platform, discovery_info=info)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 95, in async_setup_platform
    notify_service.hass = hass
AttributeError: 'bool' object has no attribute 'hass'
```
See also here: 
https://github.com/home-assistant/home-assistant/issues/31343

**Comment by iStefo** [comment]
I get a similar erorr (differen stacktrace, though) written to the protocol output using Home Assistant 0.105.0.dev20200119 when trying to activate the integration via the web interace.

Stacktrace:
```
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/discovery/__init__.py", line 204, in scan_devices
    results = await hass.async_add_job(_discover, netdisco)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/discovery/__init__.py", line 232, in _discover
    for service in netdisco.get_info(disc):
  File "/usr/local/lib/python3.7/site-packages/netdisco/discovery.py", line 104, in get_info
    return self.discoverables[dis].get_info()
  File "/usr/local/lib/python3.7/site-packages/netdisco/discoverables/__init__.py", line 28, in get_info
    return [self.info_from_entry(entry) for entry in self.get_entries()]
  File "/usr/local/lib/python3.7/site-packages/netdisco/discoverables/__init__.py", line 28, in <listcomp>
    return [self.info_from_entry(entry) for entry in self.get_entries()]
  File "/usr/local/lib/python3.7/site-packages/netdisco/discoverables/homekit.py", line 14, in info_from_entry
    info = super(Discoverable, self).info_from_entry(entry)
  File "/usr/local/lib/python3.7/site-packages/netdisco/discoverables/__init__.py", line 125, in info_from_entry
    ATTR_HOST: str(ipaddress.ip_address(entry.address)),
  File "/usr/local/lib/python3.7/ipaddress.py", line 54, in ip_address
    address)
ValueError: None does not appear to be an IPv4 or IPv6 address
```

**Comment by alandtse** [comment]
They are changing the whole service structure in 105. I'm not aware of the docs explaining what has changed.

@iStefo are you saying that you don't see the error anymore in 105.0b2?

**Comment by Krocko** [comment]
Now the following error occurred:

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 347, in _handle_event
    await _refresh_if_no_audiopush(already_refreshed)
  File "/config/custom_components/alexa_media/media_player.py", line 239, in _refresh_if_no_audiopush
    await self.async_update()
  File "/config/custom_components/alexa_media/helpers.py", line 146, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 724, in async_update
    device, no_throttle=True
  File "/config/custom_components/alexa_media/helpers.py", line 146, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 487, in refresh
    session = await self.alexa_api.get_state()
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 525, in get_state
    return await response.json(content_type=None)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by alandtse** [comment]
@Krocko delete your `alexamedia.*.pickle` file from your config directory

**Comment by iStefo** [comment]
@alandtse Jepp, using media features and pushing announcements to alexa devices and also mobile phones works for me using 105.0b2

**Comment by alandtse** [comment]
@Krocko please reopen if deleting the pickle doesn't resolve it.

**Comment by Krocko** [comment]
This doesn’t help. I still get this error.
