### ISSUE TITLE
ERROR TASK EXCEPTION

### ISSUE THREAD

**Issue by Aiace88** [custom-components/alexa_media_player#570]
Hi, yesterday i add another echoplus, and now i have this error:

2020-02-27 14:04:26 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 347, in _handle_event
    await _refresh_if_no_audiopush(already_refreshed)
  File "/config/custom_components/alexa_media/media_player.py", line 239, in _refresh_if_no_audiopush
    await self.async_update()
  File "/config/custom_components/alexa_media/helpers.py", line 146, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 724, in async_update
    device, no_throttle=True
  File "/config/custom_components/alexa_media/helpers.py", line 146, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 487, in refresh
    session = await self.alexa_api.get_state()
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 583, in get_state
    return await response.json(content_type=None)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Francisk0** [comment]
Are u sure the folder in HA have the correct permissions?

**Comment by alandtse** [comment]
Rename your .pickle file. Your cookies are likely expired.
