### ISSUE TITLE
Error: Task exception was never retrieved

### ISSUE THREAD

**Issue by Aiace88** [custom-components/alexa_media_player#586]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![2020-03-12 14_30_26-Window](https://user-images.githubusercontent.com/35429685/76527043-d0c56900-646e-11ea-83ff-5c99537569a4.png)

**System details**
 - Home-assistant (version): 0.106.6
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). Yes, i have restart, the problem is present after a day of use, suddenly out of nowhere. at the time of the event nobody was using alexa
 - alexa_media  (version from `const.py` or HA startup): __version__ = "2.5.6"
 - alexapy (version from `pip show alexapy` or HA startup): i don't know

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
2020-03-12 14:22:58 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/__init__.py", line 444, in update_devices
    preferences = await AlexaAPI.get_device_preferences(login_obj)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 703, in get_device_preferences
    "get", login, "/api/device-preferences", query={}
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 163, in _static_request
    ssl=login._ssl,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

**Additional context**

**Comment by alandtse** [comment]
Does it ever actually connect? This bug is saying Amazon is disconnecting you. In theory it should reconnect but if it never reconnects there's a bigger issue at play.
