### ISSUE TITLE
TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by genem2** [custom-components/alexa_media_player#596]
Just updated Alexa Media Player to v2.5.7. Shut down HA and updated the HA Docker to 0.107.4 .

I'm now receiving the log entry below on each restart.
Didn't receive this yesterday with 107.3 and v2.5.6.
Naturally, I regret doing both simultaneously.

> pip show alexapy
> Name: alexapy
> Version: 1.5.2

```
2020-03-21 11:26:32 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/alexa_media/sensor.py", line 151, in async_setup_entry
    hass, config_entry.data, async_add_devices, discovery_info=None
  File "/config/custom_components/alexa_media/helpers.py", line 111, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/sensor.py", line 112, in async_setup_platform
    account,
  File "/config/custom_components/alexa_media/sensor.py", line 414, in __init__
    client, n_json, "date_time", account, f"next {self._type}", "mdi:alarm"
  File "/config/custom_components/alexa_media/sensor.py", line 192, in __init__
    self._process_raw_notifications()
  File "/config/custom_components/alexa_media/sensor.py", line 200, in _process_raw_notifications
    self._all = list(map(self._update_recurring_alarm, self._all))
  File "/config/custom_components/alexa_media/sensor.py", line 252, in _update_recurring_alarm
    and alarm.isoweekday not in RECURRING_PATTERN_ISO_SET[recurring_pattern]
TypeError: argument of type 'int' is not iterable
```

> arch | x86_64
> -- | --
> dev | false
> docker | true
> hassio | false
> os_name | Linux
> os_version | 4.19.107-Unraid
> python_version | 3.7.7
> timezone | America/Los_Angeles
> version | 0.107.4
> virtualenv | false

**Comment by alandtse** [comment]
Can you enable `alexa_media` logs and show me the lines right before the exception please?

**Comment by genem2** [comment]
> do you have any alarms that have a recurrence?

I do nothing (that I know of) in HA with alarms. I don't use the Guard feature. I assume someone has set wake-me-up alarms on their units if that's what you're referring to.

Log attached.
[MyuHA.txt](https://github.com/custom-components/alexa_media_player/files/4364521/MyuHA.txt)

**Comment by alandtse** [comment]
> I do nothing (that I know of) in HA with alarms. I don't use the Guard feature. I assume someone has set wake-me-up alarms on their units if that's what you're referring to.

Thanks. Found the issue. The issue is we weren't handling a weekly alarm properly. You had one set for Tuesday's but it was turned off. I'm deleting your prior comment so your logs won't be available anymore on GitHub.

**Comment by genem2** [comment]
Thank you, and I appreciate you removing the logs.

**Comment by alandtse** [comment]
2.5.8 should resolve this and it should be available.

**Comment by genem2** [comment]
Perfectly! Thank you.
