### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'datetime.datetime'

### ISSUE THREAD

**Issue by rrubin0** [custom-components/alexa_media_player#602]
**Describe the bug**
Error occurs on startup:
```
2020-03-21 22:36:30 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/alexa_media/sensor.py", line 151, in async_setup_entry
    hass, config_entry.data, async_add_devices, discovery_info=None
  File "/config/custom_components/alexa_media/helpers.py", line 111, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/sensor.py", line 118, in async_setup_platform
    account,
  File "/config/custom_components/alexa_media/sensor.py", line 467, in __init__
    client, n_json, "alarmTime", account, f"next {self._type}", "mdi:reminder"
  File "/config/custom_components/alexa_media/sensor.py", line 192, in __init__
    self._process_raw_notifications()
  File "/config/custom_components/alexa_media/sensor.py", line 200, in _process_raw_notifications
    self._all = list(map(self._update_recurring_alarm, self._all))
  File "/config/custom_components/alexa_media/sensor.py", line 253, in _update_recurring_alarm
    and alarm < dt.now()
TypeError: '<' not supported between instances of 'int' and 'datetime.datetime'
```

**To Reproduce**
1. Update to 2.5.8 via HACS (home assistant core 0.106.5 on docker)
2. restart hass
3. See error

**Expected behavior**
I did not receive the above error prior to the update

**System details**
 - Home-assistant (version): 0.106.5
 - Hassio (Yes/No): NO
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Comment by alandtse** [comment]
Please provide the logs right before this exception.

**Comment by cgc007** [comment]
Seems like version 2.5.6 works. I tried 2.5.7 and 2.5.8 and both were giving me the errors like this. I'm running HA version 0.98.4 on docker.

```home-assistant                | exec(code, run_globals)
home-assistant                |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 409, in <module>
home-assistant                |     sys.exit(main())
home-assistant                |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 401, in main
home-assistant                |     exit_code = asyncio_run(setup_and_run_hass(config_dir, args))
home-assistant                |   File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
home-assistant                |     return loop.run_until_complete(main)
home-assistant                |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
home-assistant                |     return future.result()
home-assistant                |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 304, in setup_and_run_hass
home-assistant                |     log_no_color=args.log_no_color,
home-assistant                |   File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 139, in async_from_config_file
home-assistant                |     config_dict, hass, enable_log=False, skip_pip=skip_pip
home-assistant                |   File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 95, in async_from_config_dict
home-assistant                |     await _async_set_up_integrations(hass, config)
home-assistant                |   File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 365, in _async_set_up_integrations
home-assistant                |     *(async_setup_component(hass, domain, config) for domain in domains_to_load)
home-assistant                |   File "/usr/src/homeassistant/homeassistant/setup.py", line 52, in async_setup_component
home-assistant                |     return await task  # type: ignore
home-assistant                |   File "/usr/src/homeassistant/homeassistant/setup.py", line 137, in _async_setup_component
home-assistant                |     hass, config, integration
home-assistant                |   File "/usr/src/homeassistant/homeassistant/config.py", line 725, in async_process_component_config
home-assistant                |     component = integration.get_component()
home-assistant                |   File "/usr/src/homeassistant/homeassistant/loader.py", line 226, in get_component
home-assistant                |     cache[self.domain] = importlib.import_module(self.pkg_path)
home-assistant                |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
home-assistant                |     return _bootstrap._gcd_import(name[level:], package, level)
home-assistant                |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
home-assistant                |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
home-assistant                |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
home-assistant                |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
home-assistant                |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
home-assistant                |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
home-assistant                |   File "/config/custom_components/alexa_media/__init__.py", line 14, in <module>
home-assistant                |     from alexapy import AlexapyLoginError, WebsocketEchoClient, hide_email, hide_serial
home-assistant                |   File "/usr/local/lib/python3.7/site-packages/alexapy/__init__.py", line 11, in <module>
home-assistant                |     from .alexaapi import AlexaAPI
home-assistant                |   File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 37, in <module>
home-assistant                |     class AlexaAPI:
home-assistant                |   File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 85, in AlexaAPI
home-assistant                |     ) -> ClientResponse:
home-assistant                |   File "/usr/local/lib/python3.7/site-packages/backoff/_decorator.py", line 181, in decorate
home-assistant                |     "backoff.on_exception applied to a regular function "
home-assistant                | TypeError: backoff.on_exception applied to a regular function inside coroutine, this will lead to event loop hiccups. Use backoff.on_exception on coroutines in asynchronous code.`

**Comment by alandtse** [comment]
@cgc007 please start a new issue. This is a different.

**Comment by rrubin0** [comment]
the error only occurs on startup and as far as I can tell, alexa media (features I use at least) continue to function. I primarily use Alexa TTS for announcements. the error is immediately upon startup, as follows:
```
2020-03-22 12:06:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-03-22 12:07:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-03-22 12:07:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for apple_tv which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-03-22 12:07:19 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2020-03-22 12:07:20 WARNING (MainThread) [homeassistant.setup] Setup of group is taking over 10 seconds.
2020-03-22 12:07:20 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2020-03-22 12:07:22 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2020-03-22 12:07:22 WARNING (MainThread) [homeassistant.setup] Setup of timer is taking over 10 seconds.
2020-03-22 12:07:22 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2020-03-22 12:07:43 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform alexa_media is taking over 10 seconds.
2020-03-22 12:07:43 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform alexa_media is taking over 10 seconds.
2020-03-22 12:07:43 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/alexa_media/sensor.py", line 151, in async_setup_entry
    hass, config_entry.data, async_add_devices, discovery_info=None
  File "/config/custom_components/alexa_media/helpers.py", line 111, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/sensor.py", line 118, in async_setup_platform
    account,
  File "/config/custom_components/alexa_media/sensor.py", line 467, in __init__
    client, n_json, "alarmTime", account, f"next {self._type}", "mdi:reminder"
  File "/config/custom_components/alexa_media/sensor.py", line 192, in __init__
    self._process_raw_notifications()
  File "/config/custom_components/alexa_media/sensor.py", line 200, in _process_raw_notifications
    self._all = list(map(self._update_recurring_alarm, self._all))
  File "/config/custom_components/alexa_media/sensor.py", line 253, in _update_recurring_alarm
    and alarm < dt.now()
TypeError: '<' not supported between instances of 'int' and 'datetime.datetime'
2020-03-22 12:07:45 WARNING (MainThread) [homeassistant.setup] Setup of xiaomi_aqara is taking over 10 seconds.
2020-03-22 12:08:54 INFO (MainThread) [homeassistant.helpers.script] Script Master Bedroom Fan Speed State Restore: Running script
```

**Comment by alandtse** [comment]
Thanks, can you please enable debug logs for alexa_media? It would only impact you if you were looking at the timer sensors. With the debug logs on, it will tell me what value is causing the exception.

**Comment by rrubin0** [comment]
Ah, yes - of course. Sorry, I haven’t had to debug in some time. I’ll do
this ASAP.

Thanks for the quick response.

**Comment by rrubin0** [comment]
I enabled debugging as follows:
```
    homeassistant.components.alexa_media: debug
    homeassistant.components.sensor: debug
```
Here is the log output after restart:
```
2020-03-22 22:25:44 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform alexa_media is taking over 10 seconds.
2020-03-22 22:25:44 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform alexa_media is taking over 10 seconds.
2020-03-22 22:25:44 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/alexa_media/sensor.py", line 151, in async_setup_entry
    hass, config_entry.data, async_add_devices, discovery_info=None
  File "/config/custom_components/alexa_media/helpers.py", line 111, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/sensor.py", line 118, in async_setup_platform
    account,
  File "/config/custom_components/alexa_media/sensor.py", line 467, in __init__
    client, n_json, "alarmTime", account, f"next {self._type}", "mdi:reminder"
  File "/config/custom_components/alexa_media/sensor.py", line 192, in __init__
    self._process_raw_notifications()
  File "/config/custom_components/alexa_media/sensor.py", line 200, in _process_raw_notifications
    self._all = list(map(self._update_recurring_alarm, self._all))
  File "/config/custom_components/alexa_media/sensor.py", line 253, in _update_recurring_alarm
    and alarm < dt.now()
TypeError: '<' not supported between instances of 'int' and 'datetime.datetime'
```

**Comment by rrubin0** [comment]
Output from debug log (loading sensors) as follows:
```
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Loading sensors
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Master Bedroom TV next Alarm: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Master Bedroom TV next Timer: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Master Bedroom TV next Reminder: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Downstairs Fire Tablet next Alarm: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Downstairs Fire Tablet next Timer: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Downstairs Fire Tablet next Reminder: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Fire Tablet Orange next Alarm: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Fire Tablet Orange next Timer: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Fire Tablet Orange next Reminder: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Upstairs Fire Tablet Blue next Alarm: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Upstairs Fire Tablet Blue next Timer: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Upstairs Fire Tablet Blue next Reminder: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Office TV next Alarm: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Office TV next Timer: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Skipping already added device: <Entity Office TV next Reminder: unavailable>
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Found G************KMU Alarm sensor (0) with next: unavailable
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Found G************KMU Timer sensor (0) with next: unavailable
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Found G************KMU Reminder sensor (0) with next: unavailable
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Found G************VVD Alarm sensor (0) with next: unavailable
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] ******k@c******: Found G************VVD Timer sensor (0) with next: unavailable
2020-03-22 22:40:57 DEBUG (MainThread) [custom_components.alexa_media.sensor] value ('93c4310f-1d7a-39cc-a2bf-113ae9d759e1', {'alarmTime': 1585320300000, 'automationId': None, 'createdDate': 1560535665928, 'deferredAtTime': None, 'deliveryType': None, 'deviceName': None, 'deviceSerialNumber': 'G090P30874570VVD', 'deviceType': 'A7WXQPH584YP', 'extensibleAttribute': None, 'geoLocationTriggerData': None, 'id': 'A7WXQPH584YP-G090P30874570VVD-93c4310f-1d7a-39cc-a2bf-113ae9d759e1', 'lastOccurrenceTimeInMilli': 0, 'lastUpdatedDate': 0, 'musicAlarmId': None, 'musicEntity': None, 'notificationIndex': '93c4310f-1d7a-39cc-a2bf-113ae9d759e1', 'originalDate': '2020-03-27', 'originalTime': '07:45:00.000', 'personProfile': None, 'provider': None, 'rRuleData': {'byMonthDays': None, 'byWeekDays': ['FR'], 'flexibleRecurringPatternType': 'X_TIMES_A_WEEK', 'frequency': None, 'intervals': [1], 'nextTriggerTimes': None, 'notificationTimes': ['07:45:00.000'], 'recurEndDate': None, 'recurEndTime': None, 'recurStartDate': None, 'recurStartTime': None, 'recurrenceRules': ['FREQ=WEEKLY;BYDAY=FR;BYHOUR=7;BYMINUTE=45;BYSECOND=0;INTERVAL=1;']}, 'recurrenceEligibility': False, 'recurringPattern': 'XXXX-WXX-5', 'remainingTime': 0, 'reminderAppLabel': None, 'reminderLabel': 'Lock the dogs in the bathroom', 'reminderSubLabel': None, 'skillInfo': None, 'snoozedToTime': None, 'sound': {'displayName': 'Simple Alarm', 'folder': None, 'id': 'system_alerts_melodic_01', 'providerId': 'ECHO', 'sampleUrl': 'https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3'}, 'status': 'ON', 'targetPersonProfiles': None, 'timeZoneId': None, 'timerLabel': None, 'tmwNotificationProperties': None, 'triggerTime': 0, 'type': 'Reminder', 'version': '181', 'date_time': '2020-03-27 07:45:00.000'})
2020-03-22 22:40:57 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/alexa_media/sensor.py", line 151, in async_setup_entry
    hass, config_entry.data, async_add_devices, discovery_info=None
  File "/config/custom_components/alexa_media/helpers.py", line 111, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/sensor.py", line 118, in async_setup_platform
    account,
  File "/config/custom_components/alexa_media/sensor.py", line 467, in __init__
    client, n_json, "alarmTime", account, f"next {self._type}", "mdi:reminder"
  File "/config/custom_components/alexa_media/sensor.py", line 192, in __init__
    self._process_raw_notifications()
  File "/config/custom_components/alexa_media/sensor.py", line 200, in _process_raw_notifications
    self._all = list(map(self._update_recurring_alarm, self._all))
  File "/config/custom_components/alexa_media/sensor.py", line 253, in _update_recurring_alarm
    and alarm < dt.now()
TypeError: '<' not supported between instances of 'int' and 'datetime.datetime'
```

**Comment by alandtse** [comment]
Thanks again, can you please try replacing your `sensor.py` file to see if I fixed it?

**Comment by rrubin0** [comment]
Looks like that did the trick!
I just replaced it and restarted and the error did not occur. Alexa TTS is functioning and all entities appear to be normal.

Thanks for the fix - and of course, all of your work on this project, it's excellent!
