### ISSUE TITLE
With alexa_media 2.5.7-8 installed, HA fails to start

### ISSUE THREAD

**Issue by cgc007** [custom-components/alexa_media_player#607]
**Describe the bug**
After installing alexa_media 2.5.7 or 2.5.8 HA fails to startup properly. The HA web interface doesn't load and there are constant looping of errors in the HA log.

**To Reproduce**
1. Install alexa_media 2.5.7 or 2.5.8 on HA 0.98.4
2. Restart HA (or in my case, bring the container up)

**Expected behavior**
I expected it to get past the startup phase.

**System details**
 - Home-assistant (version): 0.98.4
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 2.5.7 and 2.5.8 both give the same error. 
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
```home-assistant                | exec(code, run_globals)
home-assistant                |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 409, in <module>
home-assistant                |     sys.exit(main())
home-assistant                |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 401, in main
home-assistant                |     exit_code = asyncio_run(setup_and_run_hass(config_dir, args))
home-assistant                |   File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
home-assistant                |     return loop.run_until_complete(main)
home-assistant                |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
home-assistant                |     return future.result()
home-assistant                |   File "/usr/src/homeassistant/homeassistant/__main__.py", line 304, in setup_and_run_hass
home-assistant                |     log_no_color=args.log_no_color,
home-assistant                |   File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 139, in async_from_config_file
home-assistant                |     config_dict, hass, enable_log=False, skip_pip=skip_pip
home-assistant                |   File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 95, in async_from_config_dict
home-assistant                |     await _async_set_up_integrations(hass, config)
home-assistant                |   File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 365, in _async_set_up_integrations
home-assistant                |     *(async_setup_component(hass, domain, config) for domain in domains_to_load)
home-assistant                |   File "/usr/src/homeassistant/homeassistant/setup.py", line 52, in async_setup_component
home-assistant                |     return await task  # type: ignore
home-assistant                |   File "/usr/src/homeassistant/homeassistant/setup.py", line 137, in _async_setup_component
home-assistant                |     hass, config, integration
home-assistant                |   File "/usr/src/homeassistant/homeassistant/config.py", line 725, in async_process_component_config
home-assistant                |     component = integration.get_component()
home-assistant                |   File "/usr/src/homeassistant/homeassistant/loader.py", line 226, in get_component
home-assistant                |     cache[self.domain] = importlib.import_module(self.pkg_path)
home-assistant                |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
home-assistant                |     return _bootstrap._gcd_import(name[level:], package, level)
home-assistant                |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
home-assistant                |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
home-assistant                |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
home-assistant                |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
home-assistant                |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
home-assistant                |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
home-assistant                |   File "/config/custom_components/alexa_media/__init__.py", line 14, in <module>
home-assistant                |     from alexapy import AlexapyLoginError, WebsocketEchoClient, hide_email, hide_serial
home-assistant                |   File "/usr/local/lib/python3.7/site-packages/alexapy/__init__.py", line 11, in <module>
home-assistant                |     from .alexaapi import AlexaAPI
home-assistant                |   File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 37, in <module>
home-assistant                |     class AlexaAPI:
home-assistant                |   File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 85, in AlexaAPI
home-assistant                |     ) -> ClientResponse:
home-assistant                |   File "/usr/local/lib/python3.7/site-packages/backoff/_decorator.py", line 181, in decorate
home-assistant                |     "backoff.on_exception applied to a regular function "
home-assistant                | TypeError: backoff.on_exception applied to a regular function inside coroutine, this will lead to event loop hiccups. Use backoff.on_exception on coroutines in asynchronous code.`

**Additional context**
Rolling alexa_media back to 2.5.6 causes this issue to go away entirely.

**Comment by alandtse** [comment]
What version of backoff is installed? 
`pip3 show backoff`.

```
Name: backoff
Version: 1.10.0
Summary: Function decoration for backoff and retry
Home-page: https://github.com/litl/backoff
Author: Bob Green
Author-email: rgreen@goscoutgo.com
License: MIT
Location: /usr/local/lib/python3.7/site-packages
Requires:
Required-by: teslajsonpy, ipify, integrationhelper, alexapy, aiogithubapi
```
You may have to run this in your homeassistant container.
`docker exec -it homeassistant bash`

**Comment by cgc007** [comment]
```Name: backoff
Version: 1.10.0
Summary: Function decoration for backoff and retry
Home-page: https://github.com/litl/backoff
Author: Bob Green
Author-email: rgreen@goscoutgo.com
License: MIT
Location: /usr/local/lib/python3.7/site-packages
Requires:
Required-by: ipify, integrationhelper, AlexaPy, aiogithubapi

**Comment by alandtse** [comment]
That doesn't make any sense as the code referenced in the logs for backoff doesn't exist in [1.10.0 (line 181)](https://github.com/litl/backoff/blob/v1.10.0/backoff/_decorator.py). Can you try uninstalling it and reinstalling it?

**Comment by cgc007** [comment]
I tried using HACS to upgrade to 2.5.8 this morning. I got another backoff error.

On the subsequent deletion of 2.5.8 out of the `custom_components` directory, the HA log showed that it was installing backoff 1.10.0:

```
2020-03-25 10:29:00 INFO (SyncWorker_7) [homeassistant.util.package] Attempting install of backoff==1.10.0
```

I then uninstalled and installed via HACS, v2.5.8. This is what was in the logs then:

```
2020-03-25 10:35:44 ERROR (MainThread) [homeassistant.setup] Error during setup of component wemo
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 304, in setup_and_run_hass
    log_no_color=args.log_no_color,
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 139, in async_from_config_file
    config_dict, hass, enable_log=False, skip_pip=skip_pip
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 95, in async_from_config_dict
    await _async_set_up_integrations(hass, config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 365, in _async_set_up_integrations
    *(async_setup_component(hass, domain, config) for domain in domains_to_load)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 52, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 137, in _async_setup_component
    hass, config, integration
  File "/usr/src/homeassistant/homeassistant/config.py", line 767, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 235, in get_platform
    "{}.{}".format(self.pkg_path, platform_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 14, in <module>
    from alexapy import AlexapyLoginError, WebsocketEchoClient, hide_email, hide_serial
  File "/usr/local/lib/python3.7/site-packages/alexapy/__init__.py", line 11, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 37, in <module>
    class AlexaAPI:
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 85, in AlexaAPI
    ) -> ClientResponse:
  File "/usr/local/lib/python3.7/site-packages/backoff/_decorator.py", line 181, in decorate
    "backoff.on_exception applied to a regular function "
TypeError: backoff.on_exception applied to a regular function inside coroutine, this will lead to event loop hiccups. Use backoff.on_exception on coroutines in asynchronous code.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 172, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
concurrent.futures._base.CancelledError
2020-03-25 10:35:44 ERROR (MainThread) [homeassistant.components.hue] Unknown error connecting with Hue bridge at 192.168.1.107
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 304, in setup_and_run_hass
    log_no_color=args.log_no_color,
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 139, in async_from_config_file
    config_dict, hass, enable_log=False, skip_pip=skip_pip
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 95, in async_from_config_dict
    await _async_set_up_integrations(hass, config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 365, in _async_set_up_integrations
    *(async_setup_component(hass, domain, config) for domain in domains_to_load)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 52, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 137, in _async_setup_component
    hass, config, integration
  File "/usr/src/homeassistant/homeassistant/config.py", line 767, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 235, in get_platform
    "{}.{}".format(self.pkg_path, platform_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 14, in <module>
    from alexapy import AlexapyLoginError, WebsocketEchoClient, hide_email, hide_serial
  File "/usr/local/lib/python3.7/site-packages/alexapy/__init__.py", line 11, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 37, in <module>
    class AlexaAPI:
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 85, in AlexaAPI
    ) -> ClientResponse:
  File "/usr/local/lib/python3.7/site-packages/backoff/_decorator.py", line 181, in decorate
    "backoff.on_exception applied to a regular function "
TypeError: backoff.on_exception applied to a regular function inside coroutine, this will lead to event loop hiccups. Use backoff.on_exception on coroutines in asynchronous code.
```

Now, the version of backoff installed for 2.5.8 seems to be 1.8.0 for some reason:
```
Name: backoff
Version: 1.8.0
Summary: Function decoration for backoff and retry
Home-page: https://github.com/litl/backoff
Author: Bob Green
Author-email: rgreen@goscoutgo.com
License: MIT
Location: /usr/local/lib/python3.7/site-packages
Requires:
Required-by: ipify, alexapy
```

However, when I installed alexa_media 2.5.6, backoff 1.10.0 was installed. I ran `pip3 install --upgrade backoff` and it installed 1.10.0. Then I rebooted, and HA installed alexapy 1.5.2 during startup, which seemingly reinstalled 1.8.0 of backoff.

```
2020-03-25 10:46:27 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-03-25 10:46:27 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-03-25 10:46:27 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for bond which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-03-25 10:46:28 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.0 seconds.
2020-03-25 10:46:28 INFO (MainThread) [homeassistant.setup] Setting up http
2020-03-25 10:46:28 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.0 seconds.
2020-03-25 10:46:28 INFO (MainThread) [homeassistant.setup] Setting up system_log
2020-03-25 10:46:28 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.0 seconds.
2020-03-25 10:46:28 INFO (MainThread) [homeassistant.setup] Setting up recorder
2020-03-25 10:46:28 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=105 from 2020-03-25 10:35:02.483162)
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 0.7 seconds.
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setting up hue
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setup of domain hue took 0.0 seconds.
2020-03-25 10:46:29 INFO (SyncWorker_8) [homeassistant.util.package] Attempting install of alexapy==1.5.2
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.0 seconds.
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setting up input_text
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setting up zone
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 0.0 seconds.
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setting up group
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setup of domain group took 0.0 seconds.
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setting up person
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setting up sun
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.1 seconds.
2020-03-25 10:46:29 INFO (SyncWorker_13) [homeassistant.loader] Loaded template from homeassistant.components.template
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setting up shell_command
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setup of domain shell_command took 0.0 seconds.
2020-03-25 10:46:29 INFO (MainThread) [homeassistant.setup] Setting up input_boolean
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setting up scene
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.components.scene] Setting up scene.homeassistant
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.components.scene] Setting up scene.homeassistant
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.components.scene] Setting up scene.homeassistant
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setting up device_tracker
2020-03-25 10:46:30 INFO (SyncWorker_6) [homeassistant.loader] Loaded time_date from homeassistant.components.time_date
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setting up auth
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds.
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setting up webhook
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.0 seconds.
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setting up config
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.0 seconds.
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setting up light
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setting up system_health
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.0 seconds.
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setting up cover
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setting up history
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setup of domain history took 0.0 seconds.
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setting up script
2020-03-25 10:46:30 INFO (MainThread) [homeassistant.setup] Setting up api
2020-03-25 10:46:30 INFO (SyncWorker_12) [homeassistant.loader] Loaded command_line from homeassistant.components.command_line
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.cover] Setting up cover.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.cover] Setting up cover.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.cover] Setting up cover.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.cover] Setting up cover.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.cover] Setting up cover.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.cover] Setting up cover.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.cover] Setting up cover.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.cover] Setting up cover.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.cover] Setting up cover.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.cover] Setting up cover.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.cover] Setting up cover.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.cover] Setting up cover.group
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setting up sensor
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.1 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.time_date
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.template
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.template
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.template
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setting up gpslogger
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain gpslogger took 0.0 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setting up automation
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setting up switch
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.4 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.3 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.switch] Setting up switch.command_line
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.4 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain device_tracker took 0.7 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.scene] Setting up scene.homeassistant
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.gpslogger
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.3 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain input_text took 2.1 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain input_boolean took 2.0 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain person took 2.1 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain cover took 0.7 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain scene took 0.9 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain switch took 0.3 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.5 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.switch
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.switch
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.switch
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.switch
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.switch
2020-03-25 10:46:31 INFO (SyncWorker_17) [homeassistant.loader] Loaded binary_sensor from homeassistant.components.binary_sensor
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hue
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 0.0 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.hue
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.hue.sensor_base] Starting sensor polling loop with 5.0 second interval
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.setup] Setup of domain light took 0.8 seconds.
2020-03-25 10:46:31 INFO (MainThread) [homeassistant.components.light] Setting up light.hue
2020-03-25 10:47:09 INFO (MainThread) [homeassistant.setup] Setting up wemo
2020-03-25 10:47:09 INFO (MainThread) [homeassistant.setup] Setting up met
2020-03-25 10:47:09 INFO (MainThread) [homeassistant.setup] Setup of domain met took 0.0 seconds.
2020-03-25 10:47:09 INFO (MainThread) [homeassistant.setup] Setting up ssdp
2020-03-25 10:47:09 INFO (MainThread) [homeassistant.setup] Setup of domain ssdp took 0.0 seconds.
2020-03-25 10:47:09 INFO (MainThread) [homeassistant.setup] Setup of domain wemo took 0.2 seconds.
2020-03-25 10:47:09 INFO (Wemo HTTP Thread) [pywemo.subscribe] Listening on port 8989
2020-03-25 10:47:09 INFO (MainThread) [homeassistant.setup] Setting up tplink
2020-03-25 10:47:09 INFO (MainThread) [homeassistant.setup] Setup of domain tplink took 0.0 seconds.
2020-03-25 10:47:09 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Wemo for wemo
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 304, in setup_and_run_hass
    log_no_color=args.log_no_color,
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 139, in async_from_config_file
    config_dict, hass, enable_log=False, skip_pip=skip_pip
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 95, in async_from_config_dict
    await _async_set_up_integrations(hass, config)
  File "/usr/src/homeassistant/homeassistant/bootstrap.py", line 365, in _async_set_up_integrations
    *(async_setup_component(hass, domain, config) for domain in domains_to_load)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 52, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 137, in _async_setup_component
    hass, config, integration
  File "/usr/src/homeassistant/homeassistant/config.py", line 767, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 235, in get_platform
    "{}.{}".format(self.pkg_path, platform_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 14, in <module>
    from alexapy import AlexapyLoginError, WebsocketEchoClient, hide_email, hide_serial
  File "/usr/local/lib/python3.7/site-packages/alexapy/__init__.py", line 11, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 37, in <module>
    class AlexaAPI:
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 85, in AlexaAPI
    ) -> ClientResponse:
  File "/usr/local/lib/python3.7/site-packages/backoff/_decorator.py", line 181, in decorate
    "backoff.on_exception applied to a regular function "
TypeError: backoff.on_exception applied to a regular function inside coroutine, this will lead to event loop hiccups. Use backoff.on_exception on coroutines in asynchronous code.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 190, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/wemo/__init__.py", line 100, in async_setup_entry
    await hass.async_add_executor_job(SUBSCRIPTION_REGISTRY.start)
concurrent.futures._base.CancelledError
```

I'm a bit beyond my depth here, but I'm trying to be far more thorough this time around.

Hopefully this helps!

**Comment by alandtse** [comment]
Can you try to manually upgrade to 1.10.0 again after installing 2.5.8 of `alexa_media`?  Not sure why it'd downgrade it on install as we have it pinned at 1.10.0 in `alexapy`.

**Comment by cgc007** [comment]
I updated HA to 0.107.7 and that's fixed this issue. I have no idea why alexa_media 2.5.8 wasn't installing backoff 1.10.0 when alexa_media 2.5.6 was, but at least it's working now!
