### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by Krocko** [custom-components/alexa_media_player#610]
**Des cribe the bug**
After HA restart I got the following errors

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version):  0.107.7
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). Yes
 - alexa_media  (version from `const.py` or HA startup):  2.5.8
 - alexapy (version from `pip show alexapy` or HA startup): 1.5.2

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
```
Logger: homeassistant.core
Source: custom_components/alexa_media/__init__.py:442 
First occurred: 7:48:45 (1 occurrences) 
Last logged: 7:48:45

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/__init__.py", line 442, in update_devices
    devices = await AlexaAPI.get_devices(login_obj)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 676, in get_devices
    AlexaAPI.devices[login.email] = (await response.json(content_type=None))[
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```
Logger: homeassistant.core
Source: custom_components/alexa_media/media_player.py:488
First occurred: 7:47:43 (4 occurrences) 
Last logged: 7:53:17

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 348, in _handle_event
    await _refresh_if_no_audiopush(already_refreshed)
  File "/config/custom_components/alexa_media/media_player.py", line 240, in _refresh_if_no_audiopush
    await self.async_update()
  File "/config/custom_components/alexa_media/helpers.py", line 146, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 725, in async_update
    device, no_throttle=True
  File "/config/custom_components/alexa_media/helpers.py", line 146, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 488, in refresh
    session = await self.alexa_api.get_state()
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 615, in get_state
    return await response.json(content_type=None)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Additional context**

**Comment by alandtse** [comment]
Please fill out the bug template.

**Comment by Krocko** [comment]
Done.

**Comment by alandtse** [comment]
I need the full logs from the component leading into the error to debug this. Please ensure `alexapy` is captured.

**Comment by alandtse** [comment]
Closing as we may have addressed it with some rewrites.
