### ISSUE TITLE
Error happening if I upgrade from v2.5.6

### ISSUE THREAD

**Issue by laca75tn** [custom-components/alexa_media_player#621]
I get the following error when running the following script.  IF I install v2.5.6 everything works fine.  As soon as I upgrade to any higher version I get the errors.

Adding a delay of 1 second between commands solves the issue. 

**ERROR LOG**
Logger: homeassistant.components.script
Source: custom_components/alexa_media/media_player.py:1053
Integration: Script (documentation, issues)
First occurred: 3:57:37 PM (1 occurrences)
Last logged: 3:57:37 PM

Alexa Wake Up Message: Error executing script. Unexpected error for call_service at pos 9: Too Many Requests
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 138, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 233, in _async_call_service_step
    context=self._context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 101, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1234, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 402, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 599, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 433, in _handle_entity_call
    await result
  File "/config/custom_components/alexa_media/helpers.py", line 146, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 1053, in async_play_media
    media_type, media_id, customer_id=self._customer_id, **kwargs
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 376, in play_music
    musicProviderId=provider_id,
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 296, in send_sequence
    await self.run_behavior(node_data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 247, in run_behavior
    await self._post_request("/api/behaviors/preview", data=data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 118, in _post_request
    return await self._request("post", uri, data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 111, in _request
    raise AlexapyTooManyRequestsError(response.reason)
alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests

**Comment by laca75tn** [comment]
Adding a delay of 1 second between commands solves the issue.

**Comment by laca75tn** [comment]
Adding a delay of 1 second between commands solves the issue.
