### ISSUE TITLE
KeyError: 'originalTime'

### ISSUE THREAD

**Issue by rrosson** [custom-components/alexa_media_player#641]
**Describe the bug**
No Alexa devices appear when doing integration

**To Reproduce**
Lost all Alexa devices. Cleared configuration, Alexa_media_player, etc along with pickle and restarted. Re-add no devices populated.

```
2020-04-10 15:25:43 ERROR (MainThread) [homeassistant.components.alexa.state_report] Timeout sending report to Alexa.
2020-04-10 15:24:15 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 152, in process_messages
    await self.on_message(cast(bytes, msg.data))
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexawebsocket.py", line 234, in on_message
    await self.msg_callback(message_obj)
  File "/config/custom_components/alexa_media/__init__.py", line 926, in ws_handler
    login_obj, no_throttle=True
  File "/config/custom_components/alexa_media/__init__.py", line 469, in update_devices
    await process_notifications(login_obj, raw_notifications)
  File "/config/custom_components/alexa_media/__init__.py", line 613, in process_notifications
    n_time = notification["originalTime"]
KeyError: 'originalTime'
2020-04-10 15:24:36 ERROR (MainThread) [homeassistant.core] Error doing job: Unclosed client session
```

**Expected behavior**
Working integration of alexa_media player
**Screenshots**

**System details**
 - Home-assistant (version): 108.2 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 2.5.12
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by digimystigi** [comment]
Same issue for me.  Started Wednesday night (~10 pm PT) and haven't been able to get entities back.  Originally running HAss.io 1.107.7 with alexa_media_player version 2.5.11.  Upgraded to alexa_media_player v2.5.12 and lost all Alexa entities.  A chunk of my log is attached:
[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/4463717/home-assistant.log)

I downgraded alexa_media_player back to v2.5.11 and continued to have the same issue.  After wrestling with my server, trying to restore a full snapshot from two days prior and continued to have the same problem - the existing entities were "unavailable".  I decided to do a full rebuild of my server from scratch and found HAss.io on 1.108.2.  I tried using alexa_media_player v2.5.11 and 2.5.12, neither of which would see my Alexa devices.

**Comment by alandtse** [comment]
Please provide logs. This should've been resolved in 2.5.12.

**Comment by digimystigi** [comment]
```
2020-04-10 04:05:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-10 04:05:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-10 04:05:10 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.async_setup_entry: Trying with limit 5 delay 5 catch_exceptions True
2020-04-10 04:05:10 INFO (MainThread) [custom_components.alexa_media] 
-------------------------------------------------------------------
alexa_media
Version: 2.5.12
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/alexa_media_player/issues
-------------------------------------------------------------------

2020-04-10 04:05:10 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==1.5.2
2020-04-10 04:05:10 DEBUG (MainThread) [alexapy.alexalogin] Trying to load pickled cookie from file /config/alexa_media.<redacted>@gmail.com.pickle
2020-04-10 04:05:13 DEBUG (MainThread) [alexapy.alexalogin] cookie loaded: <class 'collections.defaultdict'> defaultdict(<class 'http.cookies.SimpleCookie'>, {'amazon.com': <SimpleCookie: at-main='<redacted>' csrf='<redacted>' sess-at-main='<redacted>' session-id='<redacted>' session-id-time='<redacted>' session-token='<redacted>' ubid-main='<redacted>' x-main='<redacted>'>})
2020-04-10 04:05:14 DEBUG (MainThread) [alexapy.alexalogin] Trying to load aiohttpCookieJar to session
2020-04-10 04:05:14 DEBUG (MainThread) [alexapy.alexalogin] Updating self._cookies with amazon.com session cookies:
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: session-id=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: session-id-time=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: ubid-main=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age:630720000 session-token=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: x-main=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: at-main=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age:630720000 sess-at-main=<redacted>
amazon.com: expires:Wed, 10-Apr-2030 10:48:37 GMT max-age: csrf=<redacted>

2020-04-10 04:05:14 DEBUG (MainThread) [alexapy.alexalogin] Loaded 8 cookies
2020-04-10 04:05:16 DEBUG (MainThread) [alexapy.alexalogin] GET: 
https://alexa.amazon.com/api/bootstrap with
<CIMultiDictProxy('Host': 'alexa.amazon.com', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml, application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': '*', 'Accept-Encoding': 'gzip, deflate', 'Cookie': 'at-main=<redacted>; csrf=<redacted>; sess-at-main="<redacted>"; session-id=<redacted>; session-id-time=<redacted>; session-token="<redacted>"; ubid-main=<redacted>; x-main=<redacted>')>
 returned 200:OK with response <CIMultiDictProxy('Content-Type': 'application/json', 'Content-Length': '144', 'Connection': 'keep-alive', 'Server': 'Server', 'Date': 'Fri, 10 Apr 2020 11:05:15 GMT', 'x-amzn-RequestId': '<redacted>', 'Content-Encoding': 'gzip', 'x-amz-rid': '<redacted>', 'Vary': 'Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent', 'X-Cache': 'Miss from cloudfront', 'Via': '<redacted> (CloudFront)', 'X-Amz-Cf-Pop': '<redacted>', 'X-Amz-Cf-Id': '<redacted>')>
2020-04-10 04:05:16 DEBUG (MainThread) [alexapy.alexalogin] Logged in as <redacted>
2020-04-10 04:05:16 DEBUG (MainThread) [alexapy.alexalogin] Using cookies to log in
2020-04-10 04:05:16 DEBUG (MainThread) [alexapy.alexalogin] Log in successful with cookies
2020-04-10 04:05:16 DEBUG (MainThread) [alexapy.alexalogin] Updating self._cookies with amazon.com session cookies:
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: session-id=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: session-id-time=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: ubid-main=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age:630720000 session-token=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: x-main=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: at-main=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age:630720000 sess-at-main=<redacted>
amazon.com: expires:Wed, 10-Apr-2030 10:48:37 GMT max-age: csrf=<redacted>

2020-04-10 04:05:16 DEBUG (MainThread) [custom_components.alexa_media] Testing login status: {'login_successful': True}
2020-04-10 04:05:16 DEBUG (MainThread) [custom_components.alexa_media] Setting up Alexa devices for <redacted>
2020-04-10 04:05:16 DEBUG (MainThread) [custom_components.alexa_media] <redacted>: Websocket created: <alexapy.alexawebsocket.WebsocketEchoClient object at 0x6d87c230>
2020-04-10 04:05:16 DEBUG (MainThread) [alexapy.alexawebsocket] Connecting to wss://dp-gw-na-js.amazon.com/?x-amz-device-type=<redacted>&x-amz-device-serial=<redacted>-1586516716000 with {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml, application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': '*', 'Referer': 'https://alexa.amazon.com/api/bootstrap', 'Cookie': 'session-id=<redacted>; session-id-time=<redacted>; ubid-main=<redacted>; session-token=<redacted>; x-main=<redacted>; at-main=<redacted>; sess-at-main=<redacted>; csrf=<redacted>; ', 'Origin': 'https://alexa.amazon.com'}
2020-04-10 04:05:18 DEBUG (MainThread) [alexapy.alexawebsocket] Initating Async Handshake.
2020-04-10 04:05:18 DEBUG (MainThread) [alexapy.alexawebsocket] Starting message parsing loop.
2020-04-10 04:05:18 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: <redacted> {"protocolName":"A:H","parameters":{"AlphaProtocolHandler.supportedEncodings":"GZIP","AlphaProtocolHandler.maxFragmentSize":"16000","AlphaProtocolHandler.receiveWindowSize":"16"}}TUNE
2020-04-10 04:05:18 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding WebSocket Handshake MSG.
2020-04-10 04:05:18 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding Gateway Handshake MSG.
2020-04-10 04:05:18 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG <redacted> END FABE
2020-04-10 04:05:18 DEBUG (MainThread) [alexapy.alexawebsocket] Received ACK MSG for Registration.
2020-04-10 04:05:18 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding Gateway Register MSG.
2020-04-10 04:05:18 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding PING.
2020-04-10 04:05:19 DEBUG (MainThread) [custom_components.alexa_media] <redacted>: Websocket succesfully connected
2020-04-10 04:05:19 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/bootstrap returned 200:OK:application/json
2020-04-10 04:05:19 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/devices-v2/device returned 200:OK:application/json
2020-04-10 04:05:19 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/bluetooth?cached=false returned 200:OK:application/json
2020-04-10 04:05:20 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/device-preferences returned 200:OK:application/json
2020-04-10 04:05:20 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/dnd/device-status-list returned 200:OK:application/json
2020-04-10 04:05:21 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/notifications returned 200:OK:application/json
2020-04-10 04:05:21 DEBUG (MainThread) [custom_components.alexa_media] <redacted>: Found 6 devices, 6 bluetooth
2020-04-10 04:05:21 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.async_setup_entry: failure caught due to exception: An exception of type KeyError occurred. Arguments:
('originalTime',)
2020-04-10 04:05:21 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.async_setup_entry: Try: 1/5 after waiting 0 seconds result: False
2020-04-10 04:05:31 INFO (MainThread) [custom_components.alexa_media] 
-------------------------------------------------------------------
alexa_media
Version: 2.5.12
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/alexa_media_player/issues
-------------------------------------------------------------------

2020-04-10 04:05:31 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==1.5.2
2020-04-10 04:05:31 ERROR (MainThread) [homeassistant.core] Error doing job: Unclosed client session
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexalogin] Trying to load pickled cookie from file /config/alexa_media.<redacted>.pickle
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexalogin] cookie loaded: <class 'collections.defaultdict'> defaultdict(<class 'http.cookies.SimpleCookie'>, {'amazon.com': <SimpleCookie: at-main='<redacted>' csrf='<redacted>' sess-at-main='<redacted>' session-id='<redacted>' session-id-time='<redacted>' session-token='<redacted>' ubid-main='<redacted>' x-main='<redacted>'>})
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexalogin] Trying to load aiohttpCookieJar to session
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexalogin] Updating self._cookies with amazon.com session cookies:
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: session-id=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: session-id-time=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: ubid-main=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age:630720000 session-token=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: x-main=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: at-main=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age:630720000 sess-at-main=<redacted>
amazon.com: expires:Wed, 10-Apr-2030 10:48:37 GMT max-age: csrf=<redacted>

2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexalogin] Loaded 8 cookies
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexalogin] GET: 
https://alexa.amazon.com/api/bootstrap with
<CIMultiDictProxy('Host': 'alexa.amazon.com', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml, application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': '*', 'Accept-Encoding': 'gzip, deflate', 'Cookie': 'at-main=<redacted>; csrf=<redacted>; sess-at-main="<redacted>"; session-id=<redacted>; session-id-time=<redacted>; session-token="<redacted>"; ubid-main=<redacted>; x-main=<redacted>')>
 returned 200:OK with response <CIMultiDictProxy('Content-Type': 'application/json', 'Content-Length': '144', 'Connection': 'keep-alive', 'Server': 'Server', 'Date': 'Fri, 10 Apr 2020 11:05:31 GMT', 'x-amzn-RequestId': '<redacted>', 'Content-Encoding': 'gzip', 'x-amz-rid': '<redacted>', 'Vary': 'Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent', 'X-Cache': 'Miss from cloudfront', 'Via': '<redacted> (CloudFront)', 'X-Amz-Cf-Pop': '<redacted>', 'X-Amz-Cf-Id': '<redacted>')>
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexalogin] Logged in as <redacted>
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexalogin] Using cookies to log in
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexalogin] Log in successful with cookies
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexalogin] Updating self._cookies with amazon.com session cookies:
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: session-id=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: session-id-time=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: ubid-main=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age:630720000 session-token=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: x-main=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age: at-main=<redacted>
amazon.com: expires:Thu, 05-Apr-2040 10:48:37 GMT max-age:630720000 sess-at-main=<redacted>
amazon.com: expires:Wed, 10-Apr-2030 10:48:37 GMT max-age: csrf=<redacted>

2020-04-10 04:05:31 DEBUG (MainThread) [custom_components.alexa_media] Testing login status: {'login_successful': True}
2020-04-10 04:05:31 DEBUG (MainThread) [custom_components.alexa_media] Setting up Alexa devices for <redacted>
2020-04-10 04:05:31 DEBUG (MainThread) [custom_components.alexa_media] <redacted>: Websocket created: <alexapy.alexawebsocket.WebsocketEchoClient object at 0x6e365730>
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexawebsocket] Connecting to wss://dp-gw-na-js.amazon.com/?x-amz-device-type=<redacted>&x-amz-device-serial=<redacted>-<redacted> with {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml, application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': '*', 'Referer': 'https://alexa.amazon.com/api/bootstrap', 'Cookie': 'session-id=<redacted>; session-id-time=<redacted>; ubid-main=<redacted>; session-token=<redacted>; x-main=<redacted>; at-main=<redacted>; sess-at-main=<redacted>; csrf=<redacted>; ', 'Origin': 'https://alexa.amazon.com'}
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexawebsocket] Initating Async Handshake.
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexawebsocket] Starting message parsing loop.
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: <redacted> {"protocolName":"A:H","parameters":{"AlphaProtocolHandler.supportedEncodings":"GZIP","AlphaProtocolHandler.maxFragmentSize":"16000","AlphaProtocolHandler.receiveWindowSize":"16"}}TUNE
2020-04-10 04:05:31 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding WebSocket Handshake MSG.
2020-04-10 04:05:32 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding Gateway Handshake MSG.
2020-04-10 04:05:32 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG <redacted>9 ACK <redacted> END FABE
2020-04-10 04:05:32 DEBUG (MainThread) [alexapy.alexawebsocket] Received ACK MSG for Registration.
2020-04-10 04:05:32 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding Gateway Register MSG.
2020-04-10 04:05:32 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding PING.
2020-04-10 04:05:32 DEBUG (MainThread) [custom_components.alexa_media] <redacted>: Websocket succesfully connected
2020-04-10 04:05:32 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/bootstrap returned 200:OK:application/json
2020-04-10 04:05:33 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/devices-v2/device returned 200:OK:application/json
2020-04-10 04:05:33 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/bluetooth?cached=false returned 200:OK:application/json
2020-04-10 04:05:33 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/device-preferences returned 200:OK:application/json
2020-04-10 04:05:34 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/dnd/device-status-list returned 200:OK:application/json
2020-04-10 04:05:34 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/notifications returned 200:OK:application/json
2020-04-10 04:05:34 DEBUG (MainThread) [custom_components.alexa_media] <redacted>: Found 6 devices, 6 bluetooth
2020-04-10 04:05:34 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.async_setup_entry: failure caught due to exception: An exception of type KeyError occurred. Arguments:
('originalTime',)
2020-04-10 04:05:34 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.async_setup_entry: Try: 2/5 after waiting 10 seconds result: False
2020-04-10 04:05:54 INFO (MainThread) [custom_components.alexa_media] 
-------------------------------------------------------------------
alexa_media
Version: 2.5.12
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/alexa_media_player/issues
-------------------------------------------------------------------

```

**Comment by digimystigi** [comment]
v2.5.13 resolved my issue.  Thank you for the quick turnaround!
