### ISSUE TITLE
Can't install alexa_media player

### ISSUE THREAD

**Issue by mrnix1001** [custom-components/alexa_media_player#647]
**Describe the bug**
No matter what method I use to install alexa_media player errors are thrown and it cannot be configured.

To make a long-story short I was attempting to upgrade from HA 0.10.5 to 0.108.4, I couldn't upgrade because alexa_media would throw errors and HA wouldn't start. So I uninstalled alexa_media and was able to upgrade. Then I tried to re-install alexa_media.

I've done the following:

Attempt #1: 
1. Install via HACS
2. Configure via integrations
3. Errors are immediately thrown in the log
4. Restart - can't, the errors prevent HA from restarting

Attempt #2: 
1. Install via HACS
2. Restart - can't, errors are stopping HA from restarting

Attempt #3: 
1. Install via HACS
2. Reboot machine 
3. System comes up but with the same errors in the logs. 

Attempt #4: 
1. Install manually
2. Same issues, can't restart, reboot doesn't do anything

**To Reproduce**
See any of the above steps.

**Expected behavior**
Installation without errors.

**Screenshots**
N/A

**System details**
 - Home-assistant (version): 0.108.4
 - Hassio (Yes/No):  Yes
 - alexa_media  (version from `const.py` or HA startup): 2.5.13
 - alexapy (version from `pip show alexapy` or HA startup): Not sure, it never loads successfully.

**Logs**
`2020-04-15 10:45:04 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 62, in post
    handler, context={"source": config_entries.SOURCE_USER}
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 100, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 277, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 15, in <module>
    from alexapy import AlexapyLoginError, WebsocketEchoClient, hide_email, hide_serial
  File "/usr/local/lib/python3.7/site-packages/alexapy/__init__.py", line 11, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 37, in <module>
    class AlexaAPI:
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 85, in AlexaAPI
    ) -> ClientResponse:
  File "/usr/local/lib/python3.7/site-packages/backoff/_decorator.py", line 181, in decorate
    "backoff.on_exception applied to a regular function "
TypeError: backoff.on_exception applied to a regular function inside coroutine, this will lead to event loop hiccups. Use backoff.on_exception on coroutines in asynchronous code.
`

**Additional context**

**Comment by alandtse** [comment]
You have some component that is forcing an old version of backoff. Please see #607.

**Comment by mrnix1001** [comment]
Interesting! I didn't see that issue even though I looked for it. But you are correct I'm experiencing the exact same thing so now I know where to look and hopefully I can find a resolution, though I did upgrade home assistant 0.108.4 in my attempts but I had other issues so I went back to the 0.105.

Thank you!

**Comment by mrnix1001** [comment]
Closing as dup
