### ISSUE TITLE
Lost my entity and, when re-login, no device found

### ISSUE THREAD

**Issue by Scialla** [custom-components/alexa_media_player#648]
**Describe the bug**
Hello, until this morning all work fine with my device integrated in HA; today my device are offline. i’ve tried to remove integration, remove components from hacs, delete .pickle file, change passwd on amazon, turn off RPi, turn on, reinstall components, make integration. All this many time but, every time, integration don’t find my device and my entity on HA are lost.
Install custom_components without hacs, return same problem;

Sometimes found two virtual device, sometimes nothing, but physical device are not found.

Any suggestion?

Thanks

**To Reproduce**
1. Remove integration
2. Reinstall integration
**Expected behavior**
Re-found my device

**Screenshots**
![Schermata 2020-04-17 alle 15 30 58](https://user-images.githubusercontent.com/49528981/79581531-d0059f80-80ca-11ea-8716-b6173574261e.png)

**System details**
 - Home-assistant (version): 0.108.4
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup):2.5.13 (trying with older same results)
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
When install components with hacs, this is log:
```
Apr 17 16:32:20 raspberrypi hass[3324]: 2020-04-17 16:32:20 INFO (MainThread) [hacs.repository.integration.custom-components.alexa_media_player] ref: tags/v2.5.13  ---  tag: v2.5.13
Apr 17 16:32:20 raspberrypi hass[3324]: 2020-04-17 16:32:20 INFO (MainThread) [hacs.repository.integration.custom-components.alexa_media_player] ref: tags/v2.5.13  ---  tag: v2.5.12
Apr 17 16:32:20 raspberrypi hass[3324]: 2020-04-17 16:32:20 INFO (MainThread) [hacs.repository.integration.custom-components.alexa_media_player] ref: tags/v2.5.13  ---  tag: v2.5.11
Apr 17 16:32:20 raspberrypi hass[3324]: 2020-04-17 16:32:20 INFO (MainThread) [hacs.repository.integration.custom-components.alexa_media_player] ref: tags/v2.5.13  ---  tag: v2.5.10
Apr 17 16:32:20 raspberrypi hass[3324]: 2020-04-17 16:32:20 INFO (MainThread) [hacs.repository.integration.custom-components.alexa_media_player] ref: tags/v2.5.13  ---  tag: v2.5.9
Apr 17 16:32:21 raspberrypi hass[3324]: 2020-04-17 16:32:21 INFO (MainThread) [hacs.repository.integration.custom-components.alexa_media_player] download of alexa_media.zip complete
Apr 17 16:32:21 raspberrypi hass[3324]: 2020-04-17 16:32:21 INFO (MainThread) [hacs.repository.integration.custom-components.alexa_media_player] Reloading custom_component cache
Apr 17 16:32:22 raspberrypi hass[3324]: 2020-04-17 16:32:22 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```

When proceed with integration this is log:
```
Apr 17 16:34:03 raspberrypi hass[3324]: 2020-04-17 16:34:03 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1494130000] Connection closed by client
Apr 17 16:34:37 raspberrypi hass[3324]: 2020-04-17 16:34:37 INFO (MainThread) [homeassistant.setup] Setting up alexa_media
Apr 17 16:34:37 raspberrypi hass[3324]: 2020-04-17 16:34:37 INFO (MainThread) [homeassistant.setup] Setup of domain alexa_media took 0.0 seconds.
Apr 17 16:34:37 raspberrypi hass[3324]: 2020-04-17 16:34:37 INFO (MainThread) [custom_components.alexa_media]
Apr 17 16:34:37 raspberrypi hass[3324]: -------------------------------------------------------------------
Apr 17 16:34:37 raspberrypi hass[3324]: alexa_media
Apr 17 16:34:37 raspberrypi hass[3324]: Version: 2.5.13
Apr 17 16:34:37 raspberrypi hass[3324]: This is a custom component
Apr 17 16:34:37 raspberrypi hass[3324]: If you have any issues with this you need to open an issue here:
Apr 17 16:34:37 raspberrypi hass[3324]: https://github.com/custom-components/alexa_media_player/issues
Apr 17 16:34:37 raspberrypi hass[3324]: -------------------------------------------------------------------
Apr 17 16:34:37 raspberrypi hass[3324]: 2020-04-17 16:34:37 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==1.5.2
Apr 17 16:34:43 raspberrypi hass[3324]: 2020-04-17 16:34:43 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.alexa_media
Apr 17 16:34:43 raspberrypi hass[3324]: 2020-04-17 16:34:43 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarm_control_panel.alexa_media
Apr 17 16:34:43 raspberrypi hass[3324]: 2020-04-17 16:34:43 INFO (MainThread) [homeassistant.components.switch] Setting up switch.alexa_media
Apr 17 16:34:43 raspberrypi hass[3324]: 2020-04-17 16:34:43 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.alexa_media
Apr 17 16:34:43 raspberrypi hass[3324]: 2020-04-17 16:34:43 INFO (MainThread) [homeassistant.components.notify] Setting up notify.alexa_media
Apr 17 16:34:43 raspberrypi hass[3324]: 2020-04-17 16:34:43 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.alexa_media entity: switch.davide_s_reverb_ai_do_not_disturb_switch
Apr 17 16:34:43 raspberrypi hass[3324]: 2020-04-17 16:34:43 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.alexa_media entity: switch.davide_s_reverb_ai_shuffle_switch
Apr 17 16:34:43 raspberrypi hass[3324]: 2020-04-17 16:34:43 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.alexa_media entity: switch.davide_s_reverb_ai_repeat_switch
Apr 17 16:34:43 raspberrypi hass[3324]: 2020-04-17 16:34:43 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alexa_media entity: sensor.davide_s_reverb_ai_next_alarm
Apr 17 16:34:43 raspberrypi hass[3324]: 2020-04-17 16:34:43 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alexa_media entity: sensor.davide_s_reverb_ai_next_timer
Apr 17 16:34:44 raspberrypi hass[3324]: 2020-04-17 16:34:44 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.alexa_media entity: sensor.davide_s_reverb_ai_next_reminder
Apr 17 16:34:53 raspberrypi hass[3324]: 2020-04-17 16:34:53 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform alexa_media is taking over 10 seconds.
Apr 17 16:34:53 raspberrypi hass[3324]: 2020-04-17 16:34:53 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform alexa_media is taking over 10 seconds.
Apr 17 16:34:53 raspberrypi hass[3324]: 2020-04-17 16:34:53 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform alexa_media is taking over 10 seconds.
Apr 17 16:34:53 raspberrypi hass[3324]: 2020-04-17 16:34:53 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.alexa_media entity: switch.dappertutto_do_not_disturb_switch
Apr 17 16:34:53 raspberrypi hass[3324]: 2020-04-17 16:34:53 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.alexa_media entity: switch.dappertutto_shuffle_switch
Apr 17 16:34:54 raspberrypi hass[3324]: 2020-04-17 16:34:54 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.alexa_media entity: switch.dappertutto_repeat_switch
Apr 17 16:35:43 raspberrypi hass[3324]: 2020-04-17 16:35:43 ERROR (MainThread) [homeassistant.components.media_player] Setup of platform alexa_media is taking longer than 60 seconds. Startup will proceed without waiting any longer.
Apr 17 16:35:43 raspberrypi hass[3324]: 2020-04-17 16:35:43 ERROR (MainThread) [homeassistant.components.switch] Setup of platform alexa_media is taking longer than 60 seconds. Startup will proceed without waiting any longer.
Apr 17 16:35:43 raspberrypi hass[3324]: 2020-04-17 16:35:43 ERROR (MainThread) [homeassistant.components.sensor] Setup of platform alexa_media is taking longer than 60 seconds. Startup will proceed without waiting any longer.
Apr 17 16:35:43 raspberrypi hass[3324]: 2020-04-17 16:35:43 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Apr 17 16:35:43 raspberrypi hass[3324]: Traceback (most recent call last):
Apr 17 16:35:43 raspberrypi hass[3324]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/notify/__init__.py", line 161, in async_platform_discovered
Apr 17 16:35:43 raspberrypi hass[3324]:     await async_setup_platform(platform, discovery_info=info)
Apr 17 16:35:43 raspberrypi hass[3324]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/notify/__init__.py", line 95, in async_setup_platform
Apr 17 16:35:43 raspberrypi hass[3324]:     notify_service.hass = hass
Apr 17 16:35:43 raspberrypi hass[3324]: AttributeError: 'bool' object has no attribute 'hass'
```

This is log error at startup:

```Apr 17 19:57:41 raspberrypi hass[3250]: 2020-04-17 19:57:41 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform alexa_media is taking over 10 seconds.
Apr 17 19:57:41 raspberrypi hass[3250]: 2020-04-17 19:57:41 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform alexa_media is taking over 10 seconds.
Apr 17 19:57:45 raspberrypi hass[3250]: 2020-04-17 19:57:45 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform alexa_media is taking over 10 seconds.
Apr 17 19:58:31 raspberrypi hass[3250]: 2020-04-17 19:58:31 ERROR (MainThread) [homeassistant.components.media_player] Setup of platform alexa_media is taking longer than 60 seconds. Startup will proceed without waiting any longer.
Apr 17 19:58:31 raspberrypi hass[3250]: 2020-04-17 19:58:31 ERROR (MainThread) [homeassistant.components.switch] Setup of platform alexa_media is taking longer than 60 seconds. Startup will proceed without waiting any longer.
Apr 17 19:58:35 raspberrypi hass[3250]: 2020-04-17 19:58:35 ERROR (MainThread) [homeassistant.components.sensor] Setup of platform alexa_media is taking longer than 60 seconds. Startup will proceed without waiting any longer.
Apr 17 19:58:35 raspberrypi hass[3250]: 2020-04-17 19:58:35 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Apr 17 19:58:35 raspberrypi hass[3250]: Traceback (most recent call last):
Apr 17 19:58:35 raspberrypi hass[3250]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/notify/__init__.py", line 161, in async_platform_discovered
Apr 17 19:58:35 raspberrypi hass[3250]:     await async_setup_platform(platform, discovery_info=info)
Apr 17 19:58:35 raspberrypi hass[3250]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/notify/__init__.py", line 95, in async_setup_platform
Apr 17 19:58:35 raspberrypi hass[3250]:     notify_service.hass = hass
Apr 17 19:58:35 raspberrypi hass[3250]: AttributeError: 'bool' object has no attribute 'hass'
```

and many of this event appears:

```
Apr 17 20:04:31 raspberrypi hass[3250]: 2020-04-17 20:04:31 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry mymail@me.com - amazon.it for media_player
Apr 17 20:04:31 raspberrypi hass[3250]: Traceback (most recent call last):
Apr 17 20:04:31 raspberrypi hass[3250]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 216, in async_setup
Apr 17 20:04:31 raspberrypi hass[3250]:     hass, self
Apr 17 20:04:31 raspberrypi hass[3250]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py", line 329, in async_setup_entry
Apr 17 20:04:31 raspberrypi hass[3250]:     return await hass.data[DOMAIN].async_setup_entry(entry)
Apr 17 20:04:31 raspberrypi hass[3250]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 163, in async_setup_entry
Apr 17 20:04:31 raspberrypi hass[3250]:     raise ValueError("Config entry has already been setup!")
Apr 17 20:04:31 raspberrypi hass[3250]: ValueError: Config entry has already been setup!
```

Last info:
i've tried tu use an old SD card (makes some monthly ago) with alexa_media configured and working but, in this case too, entity configured are not available

Something is changing from amazon?

**Comment by alandtse** [comment]
Can you please enable the debug logs for `alexapy` as well?

**Comment by Scialla** [comment]
Hi Alan,
yesterday i continuously trying from 11am to 1am and it didn't work.
Today i read your request and i remove integration, remove, component, enabled debug log, restart, install component, integration and..... WORK!!!!
I think there are two possible cases:
1. yesterday there where problems with amazon connection 
2. yesterday was friday 17 (in Italy brings bad luck) :)

In any case thanks for your attention and your time, i'm happy again... :)
