### ISSUE TITLE
Vera - Unhandled exception errors

### ISSUE THREAD

**Issue by grantclem** [custom-components/alexa_media_player#655]
**Describe the bug**
Log filling up with Vera errors

**To Reproduce**

**Expected behavior**

**Screenshots**
```

**Logs**
These are all Aeotec 6 in 1 sensors throughout the house.

2020-04-20 16:53:15 ERROR (Vera Poll Thread) [pyvera.subscribe] Unhandled exception in callback for device #700 (Temperature Bed 2)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/pyvera/subscribe.py", line 155, in _event_device
    callback(device)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/vera/__init__.py", line 162, in _update_callback
    self.schedule_update_ha_state(True)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 430, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2020-04-20 16:53:19 ERROR (Vera Poll Thread) [pyvera.subscribe] Unhandled exception in callback for device #362 (Humidity Kitchen)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/pyvera/subscribe.py", line 155, in _event_device
    callback(device)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/vera/__init__.py", line 162, in _update_callback
    self.schedule_update_ha_state(True)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 430, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2020-04-20 16:53:26 ERROR (Vera Poll Thread) [pyvera.subscribe] Unhandled exception in callback for device #717 (Light Study)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/pyvera/subscribe.py", line 155, in _event_device
    callback(device)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/vera/__init__.py", line 162, in _update_callback
    self.schedule_update_ha_state(True)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 430, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2020-04-20 16:53:31 ERROR (Vera Poll Thread) [pyvera.subscribe] Unhandled exception in callback for device #704 (Temperature Garage)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/pyvera/subscribe.py", line 155, in _event_device
    callback(device)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/vera/__init__.py", line 162, in _update_callback
    self.schedule_update_ha_state(True)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 430, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2020-04-20 16:53:32 ERROR (Vera Poll Thread) [pyvera.subscribe] Unhandled exception in callback for device #705 (Light Garage)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/pyvera/subscribe.py", line 155, in _event_device
    callback(device)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/vera/__init__.py", line 162, in _update_callback
    self.schedule_update_ha_state(True)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 430, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2020-04-20 16:53:37 ERROR (Vera Poll Thread) [pyvera.subscribe] Unhandled exception in callback for device #712 (Temperature Living)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/pyvera/subscribe.py", line 155, in _event_device
    callback(device)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/vera/__init__.py", line 162, in _update_callback
    self.schedule_update_ha_state(True)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 430, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2020-04-20 16:53:45 ERROR (Vera Poll Thread) [pyvera.subscribe] Unhandled exception in callback for device #700 (Temperature Bed 2)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/pyvera/subscribe.py", line 155, in _event_device
    callback(device)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/vera/__init__.py", line 162, in _update_callback
    self.schedule_update_ha_state(True)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 430, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
2020-04-20 16:53:58 ERROR (Vera Poll Thread) [pyvera.subscribe] Unhandled exception in callback for device #708 (Temperature Laundry)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/pyvera/subscribe.py", line 155, in _event_device
    callback(device)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/vera/__init__.py", line 162, in _update_callback
    self.schedule_update_ha_state(True)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 430, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh

**Additional context**

vera:
  vera_controller_url: http://192.168.1.3:3480/

Happening since 0.108
Vera Zwave response appears to be quite slow now.
Rebooting the HA NUC seems to be taking longer than usual to reinstate.

**Comment by grantclem** [comment]
Apologies, totally in the wrong area :)
