### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by stuartlea** [custom-components/alexa_media_player#656]
I have tried to install alexa_media initially through HACS which installs the integration ok but when I go to configure it it appears on screen for a second then goes off. The error log shows an error "backoff.on_exception applied to a regular function".

I remove from HACS and try a manual install with the same result.

**System details**
 - Home-assistant (version): 0.108.6
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 2.5.14
 - alexapy (version from `pip show alexapy` or HA startup): 1.6.0

**Logs**
2020-04-21 19:01:36 ERROR (MainThread) [homeassistant.setup] Setup failed for alexa_media: unknown error,
Traceback (most recent call last):,
  File "/usr/src/homeassistant/homeassistant/setup.py", line 137, in _async_setup_component,
    component = integration.get_component(),
  File "/usr/src/homeassistant/homeassistant/loader.py", line 268, in get_component,
    cache[self.domain] = importlib.import_module(self.pkg_path),
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked,
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked,
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module,
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed,
  File "/config/custom_components/alexa_media/__init__.py", line 17, in <module>,
    from alexapy import AlexapyLoginError, WebsocketEchoClient, hide_email, hide_serial,
  File "/usr/local/lib/python3.7/site-packages/alexapy/__init__.py", line 11, in <module>,
    from .alexaapi import AlexaAPI,
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 37, in <module>,
    class AlexaAPI:,
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 85, in AlexaAPI,
    ) -> ClientResponse:,
  File "/usr/local/lib/python3.7/site-packages/backoff/_decorator.py", line 181, in decorate,
    "backoff.on_exception applied to a regular function ",
TypeError: backoff.on_exception applied to a regular function inside coroutine, this will lead to event loop hiccups. Use backoff.on_exception on coroutines in asynchronous code.,

The system is run through Docker.

Thanks

**Comment by alandtse** [comment]
See #607 . Something is forcing your backoff version to something less than 1.10.0.

**Comment by alandtse** [comment]
What version of HACS were you using?

**Comment by stuartlea** [comment]
Thanks @alandtse - this pointed me in the right direction.
I cant tell you what version of HACS that I was using but fair to say it was an older one. I attempted an U/G which failed but after a reboot it is running 0.24.1. Tried to install alexa_media again and it has worked fine. Thank you.
From a quick glance it looks like exactly what I have been looking for.
