### ISSUE TITLE
AttributeError: 'AlexaNotificationService' object has no attribute 'email'

### ISSUE THREAD

**Issue by pilip87** [custom-components/alexa_media_player#666]
Just updated alexa media and homassistant, Alexa announce stopped working and getting this:

Logger: homeassistant.components.websocket_api.http.connection.1833247056
Source: custom_components/alexa_media/notify.py:209
Integration: websocket_api (documentation, issues)
First occurred: 15:28:53 (1 occurrences)
Last logged: 15:28:53

'AlexaNotificationService' object has no attribute 'email'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1232, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1255, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 119, in async_notify_message
    await notify_service.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 209, in async_send_message
    self.email
AttributeError: 'AlexaNotificationService' object has no attribute 'email'

Can someone help me?

**Comment by pilip87** [comment]
with older version of alexa_media it works

**Comment by alandtse** [comment]
Please fill out the template.

**Comment by alandtse** [comment]
This was resolved.
