### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host alexa.amazon.co.uk:443 [Address family not supported by protocol]

### ISSUE THREAD

**Issue by poudenes** [custom-components/alexa_media_player#675]
**Describe the bug**
After HA updater 0.109.2 I get errors
Removed the integration, add it again. The adding went ok.

**To Reproduce**

**Expected behavior**
no errors...

**Screenshots**

**System details**
 - Home-assistant (version): 0.109.1
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v2.6.0
 - alexapy (version from `pip show alexapy` or HA startup): unknown

**Logs**
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 381, in _handle_event
    await _refresh_if_no_audiopush(already_refreshed)
  File "/config/custom_components/alexa_media/media_player.py", line 271, in _refresh_if_no_audiopush
    await self.async_update()
  File "/config/custom_components/alexa_media/helpers.py", line 148, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 769, in async_update
    device, no_throttle=True
  File "/config/custom_components/alexa_media/helpers.py", line 148, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 532, in refresh
    session = await self.alexa_api.get_state()
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 656, in get_state
    + "&screenWidth=2560"
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 130, in _get_request
    return await self._request("get", uri, data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 98, in _request
    ssl=self._login._ssl,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host alexa.amazon.co.uk:443 ssl:<ssl.SSLContext object at 0xab4cdc30> [Connect call failed ('127.0.0.1', 443)]

2020-05-02 10:58:22 ERROR (MainThread) [homeassistant.util.logging] Exception in _handle_event when dispatching 'alexa_media_i**o@o**************': ({'player_state': {'destinationUserId': 'XX<REMOVED PRIVACY>XX', 'dopplerId': {'deviceType': 'XX<REMOVED PRIVACY>XX', 'deviceSerialNumber': 'XX<REMOVED PRIVACY>XX'}, 'bass': 3, 'midrange': -1, 'treble': 0}},)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 962, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 928, in create_connection
    sock = socket.socket(family=family, type=type, proto=proto)
  File "/usr/local/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 381, in _handle_event
    await _refresh_if_no_audiopush(already_refreshed)
  File "/config/custom_components/alexa_media/media_player.py", line 271, in _refresh_if_no_audiopush
    await self.async_update()
  File "/config/custom_components/alexa_media/helpers.py", line 148, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 769, in async_update
    device, no_throttle=True
  File "/config/custom_components/alexa_media/helpers.py", line 148, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 532, in refresh
    session = await self.alexa_api.get_state()
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 656, in get_state
    + "&screenWidth=2560"
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 130, in _get_request
    return await self._request("get", uri, data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 98, in _request
    ssl=self._login._ssl,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host alexa.amazon.co.uk:443 ssl:<ssl.SSLContext object at 0xab4cdc30> [Address family not supported by protocol]
```

**Additional context**

**Comment by poudenes** [comment]
Renoved integration again, restart HA, add integration again. Now with amazon.co.uk instead of amazon.com include all devices. Before excluded 2. now all 3 devices are added, and no errors

**Comment by alandtse** [comment]
That's a really weird error.  Before your reboot it looks like it resolved it to localhost.
```
Cannot connect to host alexa.amazon.co.uk:443 ssl:<ssl.SSLContext object at 0xab4cdc30> [Connect call failed ('127.0.0.1', 443)]
```

I didn't change anything on the aiohttp side from 2.5.15. I assume you were fine on that version?

Can the device ping `alexa.amazon.co.uk`? Are you using ipv6 in your network?

**Comment by poudenes** [comment]
Here the ping:

root@hassio:~# ping alexa.amazon.co.uk
PING d3rsqup3tcxj1a.cloudfront.net (52.222.140.125) 56(84) bytes of data.
64 bytes from server-52-222-140-125.ams50.r.cloudfront.net (52.222.140.125): icmp_seq=1 ttl=245 time=11.8 ms
64 bytes from server-52-222-140-125.ams50.r.cloudfront.net (52.222.140.125): icmp_seq=2 ttl=245 time=22.10 ms
64 bytes from server-52-222-140-125.ams50.r.cloudfront.net (52.222.140.125): icmp_seq=3 ttl=245 time=10.10 ms
64 bytes from server-52-222-140-125.ams50.r.cloudfront.net (52.222.140.125): icmp_seq=4 ttl=245 time=10.2 ms
64 bytes from server-52-222-140-125.ams50.r.cloudfront.net (52.222.140.125): icmp_seq=5 ttl=245 time=9.84 ms
64 bytes from server-52-222-140-125.ams50.r.cloudfront.net (52.222.140.125): icmp_seq=6 ttl=245 time=11.6 ms
64 bytes from server-52-222-140-125.ams50.r.cloudfront.net (52.222.140.125): icmp_seq=7 ttl=245 time=10.7 ms
64 bytes from server-52-222-140-125.ams50.r.cloudfront.net (52.222.140.125): icmp_seq=8 ttl=245 time=10.5 ms
64 bytes from server-52-222-140-125.ams50.r.cloudfront.net (52.222.140.125): icmp_seq=9 ttl=245 time=11.7 ms
^C
--- d3rsqup3tcxj1a.cloudfront.net ping statistics ---
9 packets transmitted, 9 received, 0% packet loss, time 18ms
rtt min/avg/max/mdev = 9.842/12.259/22.993/3.849 ms

**Comment by alandtse** [comment]
Older versions don't have this problem?

**Comment by poudenes** [comment]
Installed: v2.6.1 and restart HA. As I speak no errors in the log.
Only 3 entities are not available:

alarm, timer and the reminder

**Comment by joselito11** [comment]
> Older versions don't have this problem?

Error with 2.5.15, 2.60, 2.6.1. Reverted to 2.5.13 and it is working back. I think error started with the translation update

**Comment by poudenes** [comment]
I reverted also back. But when it ask for captcha it goes into a loop. All the time captcha is correct but keeps coming back to fill in a new one.

**Comment by alandtse** [comment]
2.6.0 fixed the login issues. You'll need to use a workaround in #568 to get past it to save a new .pickle if you're on the older version. 

I can't see any reason aiohttp would be impacted. We didn't change any code related to how it connects recently.

**Comment by poudenes** [comment]
@alandtse tried you idea. Maybe im blind, but cant find the workaround, only thing is replace the alexalogin.py part.
Also tried to do it using HA Mobile App, then i see more field to fill in... but also without success

**Comment by poudenes** [comment]
Still Alarm, Timer and Notifications entity is still not available

**Comment by alandtse** [comment]
Logs needed for that issue. Please start a new one.

**Comment by poudenes** [comment]
Here the debug output:

```
2020-05-03 14:56:11 DEBUG (MainThread) [custom_components.alexa_media.configurator] Testing login status: {'login_successful': True}
2020-05-03 14:56:11 DEBUG (MainThread) [custom_components.alexa_media.configurator] Setting up Alexa devices for i**o@o*****************y
2020-05-03 14:56:11 DEBUG (MainThread) [custom_components.alexa_media] i**o@o*****************y: Websocket created: <alexapy.alexawebsocket.WebsocketEchoClient object at 0xad251b10>
2020-05-03 14:56:14 DEBUG (MainThread) [custom_components.alexa_media] i**o@o*****************y: Websocket succesfully connected
2020-05-03 14:56:14 DEBUG (MainThread) [custom_components.alexa_media] Creating coordinator
2020-05-03 14:56:14 DEBUG (MainThread) [custom_components.alexa_media] Refreshing coordinator
2020-05-03 14:56:14 DEBUG (MainThread) [custom_components.alexa_media] i**o@o*****************y: Found 3 devices, 3 bluetooth
2020-05-03 14:56:14 DEBUG (MainThread) [custom_components.alexa_media] i**o@o*****************y: Updated 2 notifications for 2 devices at 2020-05-03 14:56:14.914138+02:00
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media] i**o@o*****************y: Updated last_called: {'serialNumber': 'G************EXX', 'timestamp': 1588494902195}
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media] i**o@o*****************y: last_called changed:  to {'serialNumber': 'G************EXX', 'timestamp': 1588494902195}
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media] Peter's Echo Dot: Locale en-us timezone Europe/Amsterdam
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media] Peter's Echo Dot: DND False
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media] i**o@o*****************y: Existing: [] New: ["Peter's Echo Dot"]; Filtered out by not being in include: ['This Device', "Peter's Alexa Apps"] or in exclude: []
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media] Loading media_player
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media] Finished fetching alexa_media data in 1.075 seconds
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.media_player] i**o@o*****************y: Refreshing Peter's Echo Dot
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.media_player] Peter's Echo Dot: Last_called check: self: G************EXX reported:
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.helpers] i**o@o*****************y: Adding [<Entity Peter's Echo Dot: standby>]
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.switch] i**o@o*****************y: Loading switches
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.switch] i**o@o*****************y: Found G************EXX dnd switch with status: False
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.switch] i**o@o*****************y: Found G************EXX shuffle switch with status: False
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.switch] i**o@o*****************y: Found G************EXX repeat switch with status: False
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.helpers] i**o@o*****************y: Excluding device: <Entity Peter's Echo Dot do not disturb switch: off>
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.helpers] i**o@o*****************y: Excluding device: <Entity Peter's Echo Dot shuffle switch: off>
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.helpers] i**o@o*****************y: Excluding device: <Entity Peter's Echo Dot repeat switch: off>
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Trying with limit 5 delay 2 catch_exceptions True
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Try: 1/5 after waiting 0 seconds result: <custom_components.alexa_media.notify.AlexaNotificationService object at 0xae41f7d0>
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.alarm_control_panel] i**o@o*****************y: No Alexa Guard entity found
2020-05-03 14:56:15 DEBUG (MainThread) [custom_components.alexa_media.alarm_control_panel] i**o@o*****************y: Skipping creation of uninitialized device: <Entity Alexa Guard: None>
2020-05-03 14:56:29 DEBUG (MainThread) [custom_components.alexa_media.sensor] i**o@o*****************y: Loading sensors
2020-05-03 14:56:29 DEBUG (MainThread) [custom_components.alexa_media.sensor] Sensor value ('c0e08abe-6d98-3f77-bc33-0940da6c0145', {'alarmTime': 0, 'automationId': None, 'createdDate': 1588409913568, 'deferredAtTime': None, 'deliveryType': None, 'deviceName': None, 'deviceSerialNumber': 'G090U60783520EXX', 'deviceType': 'A32DOYMUN6DTXA', 'extensibleAttribute': None, 'geoLocationTriggerData': None, 'id': 'A32DOYMUN6DTXA-G090U60783520EXX-c0e08abe-6d98-3f77-bc33-0940da6c0145', 'lastOccurrenceTimeInMilli': 0, 'lastUpdatedDate': 0, 'musicAlarmId': None, 'musicEntity': None, 'notificationIndex': 'c0e08abe-6d98-3f77-bc33-0940da6c0145', 'originalDate': '2020-05-02', 'originalTime': '12:00:00.000', 'personProfile': None, 'provider': None, 'rRuleData': None, 'recurrenceEligibility': False, 'recurringPattern': None, 'remainingTime': 0, 'reminderAppLabel': None, 'reminderLabel': None, 'reminderSubLabel': None, 'skillInfo': None, 'snoozedToTime': None, 'sound': {'displayName': 'Simple Alarm', 'folder': None, 'id': 'system_alerts_melodic_01', 'providerId': 'ECHO', 'sampleUrl': 'https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3'}, 'status': 'OFF', 'targetPersonProfiles': None, 'timeZoneId': None, 'timerLabel': None, 'tmwNotificationProperties': None, 'triggerTime': 0, 'type': 'Alarm', 'version': '4', 'date_time': datetime.datetime(2020, 5, 2, 12, 0, tzinfo=<DstTzInfo 'Europe/Amsterdam' CEST+2:00:00 DST>)})
2020-05-03 14:56:29 DEBUG (MainThread) [custom_components.alexa_media.sensor] i**o@o*****************y: Found G************EXX Alarm sensor (1) with next: unavailable
2020-05-03 14:56:29 DEBUG (MainThread) [custom_components.alexa_media.sensor] Sensor value ('16b9c78b-e094-3643-9e25-ba83ed91534c', {'alarmTime': 0, 'automationId': None, 'createdDate': 1588494833431, 'deferredAtTime': None, 'deliveryType': None, 'deviceName': None, 'deviceSerialNumber': 'G090U60783520EXX', 'deviceType': 'A32DOYMUN6DTXA', 'extensibleAttribute': None, 'geoLocationTriggerData': None, 'id': 'A32DOYMUN6DTXA-G090U60783520EXX-16b9c78b-e094-3643-9e25-ba83ed91534c', 'lastOccurrenceTimeInMilli': 0, 'lastUpdatedDate': 0, 'musicAlarmId': None, 'musicEntity': None, 'notificationIndex': '16b9c78b-e094-3643-9e25-ba83ed91534c', 'originalDate': None, 'originalTime': None, 'personProfile': None, 'provider': None, 'rRuleData': None, 'recurrenceEligibility': False, 'recurringPattern': None, 'remainingTime': 0, 'reminderAppLabel': None, 'reminderLabel': None, 'reminderSubLabel': None, 'skillInfo': None, 'snoozedToTime': None, 'sound': {'displayName': 'Simple Timer', 'folder': None, 'id': 'system_alerts_melodic_02', 'providerId': 'ECHO', 'sampleUrl': 'https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_02.mp3'}, 'status': 'OFF', 'targetPersonProfiles': None, 'timeZoneId': None, 'timerLabel': None, 'tmwNotificationProperties': None, 'triggerTime': 0, 'type': 'Timer', 'version': '4'})
2020-05-03 14:56:29 DEBUG (MainThread) [custom_components.alexa_media.sensor] i**o@o*****************y: Found G************EXX Timer sensor (1) with next: unavailable
2020-05-03 14:56:29 DEBUG (MainThread) [custom_components.alexa_media.sensor] i**o@o*****************y: Found G************EXX Reminder sensor (0) with next: unavailable
2020-05-03 14:56:29 DEBUG (MainThread) [custom_components.alexa_media.helpers] i**o@o*****************y: Excluding device: <Entity Peter's Echo Dot next Alarm: unavailable>
2020-05-03 14:56:29 DEBUG (MainThread) [custom_components.alexa_media.helpers] i**o@o*****************y: Excluding device: <Entity Peter's Echo Dot next Timer: unavailable>
2020-05-03 14:56:29 DEBUG (MainThread) [custom_components.alexa_media.helpers] i**o@o*****************y: Excluding device: <Entity Peter's Echo Dot next Reminder: unavailable>
2020-05-03 14:56:29 ERROR (MainThread) [homeassistant.components.cert_expiry.sensor] Connection refused by server: rpi.oudenes.photography:443
2020-05-03 14:56:43 DEBUG (MainThread) [custom_components.alexa_media.media_player] i**o@o*****************y: Refreshing Peter's Echo Dot
2020-05-03 14:56:43 DEBUG (MainThread) [custom_components.alexa_media.media_player] Peter's Echo Dot: Last_called check: self: G************EXX reported: G************EXX
2020-05-03 14:56:43 DEBUG (MainThread) [custom_components.alexa_media.media_player] Disabling polling for Peter's Echo Dot
```

**Comment by alandtse** [comment]
If you're using `include_device` you need to manually include all the timers, etc. It's a white list so if you don't list it, of course it doesn't load. See https://github.com/custom-components/alexa_media_player/wiki/Configuration#configuring-inclusions-or-exclusions-versions--096

This is a separate issue, so please open a new issue if it continues.

**Comment by poudenes** [comment]
AHa... thanks !!
