### ISSUE TITLE
Exception in _handle_event when dispatching

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#700]
**Describe the bug**
Issues with plugin updates, log exception

**To Reproduce**
1. Restart HA
2. Look at home-assistant.log

**Expected behavior**
Plugin always working and log clean

**Screenshots**

**System details**
 - Home-assistant (version): 0.109.5
- Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v2.7.0
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```
2020-05-10 13:52:31 ERROR (MainThread) [homeassistant.util.logging] Exception in _handle_event when dispatching 'alexa_media_s*************i@g***': ({'player_state': {'destinationUserId': 'xxxxxxxxxxxxxxx', 'dopplerId': {'deviceType': 'xxxxxxxxxxxxxxxx', 'deviceSerialNumber': 'xxxxxxxxxxxxxx'}, 'bass': 0, 'midrange': 0, 'treble': 0}},)
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 381, in _handle_event
    await _refresh_if_no_audiopush(already_refreshed)
  File "/config/custom_components/alexa_media/media_player.py", line 271, in _refresh_if_no_audiopush
    await self.async_update()
  File "/config/custom_components/alexa_media/helpers.py", line 148, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 769, in async_update
    device, no_throttle=True
  File "/config/custom_components/alexa_media/helpers.py", line 148, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 532, in refresh
    session = await self.alexa_api.get_state()
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 687, in get_state
    return await response.json(content_type=None)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1040, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
**Additional context**

**Comment by alandtse** [comment]
Thanks. Work around would be to refresh your cookie. It's being rejected. But we'll need to catch this error.

**Comment by chemelli74** [comment]
Anything I can do to help debugging before refreshing ?
Is disable/enable plugin the only and best way to refresh ?

Simone

**Comment by alandtse** [comment]
Thanks but no, that's enough info for me to track this error down. Rename your .pickle file. It's in your config/.storage/ directory.

**Comment by alandtse** [comment]
@keatontaylor I think I need your eyes on this. This should already be caught by the [wrapper](https://gitlab.com/keatontaylor/alexapy/-/blob/dev/alexapy/alexaapi.py#L677) [`_catch_all_exceptions`](https://gitlab.com/keatontaylor/alexapy/-/blob/dev/alexapy/helpers.py#L78) in AlexaAPI but for some reason it isn't. I think the issue may be caused by the fact the async call is dispatched? But I'm not that familiar with that level of python. Any thoughts?
