### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by drthanwho** [custom-components/alexa_media_player#714]
**Describe the bug**

All of a sudden after my last restart I've been getting the below error in the log. 
First error leads to --> AttributeError: 'NoneType' object has no attribute 'get'
Next errors that show up --> ValueError: Config entry has already been setup!

In the meantime all Echos on home assistant are unavailable 

I also tried restarting again but keep getting same errors. On the other hand, I have restarted several other times, in the past I don't know how long since I set it up, and this hasn't happened.

**To Reproduce**
Unknown. Happened after HA restart.

**Expected behavior**
No errors and Echo media players to be available in HA

**System details**
 - Home-assistant (version): 0.109.2
 - Hassio (Yes/No): Yes
 - alexa_media: 2.7.3
 - alexapy: 1.8.4

**Logs**
```yaml
020-05-12 21:46:23 DEBUG (MainThread) [custom_components.alexa_media] Nothing to import from configuration.yaml, loading from Integrations
2020-05-12 21:46:23 INFO (MainThread) [custom_components.alexa_media] 
-------------------------------------------------------------------
alexa_media
Version: 2.7.3
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/alexa_media_player/issues
-------------------------------------------------------------------

2020-05-12 21:46:23 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==1.8.4
2020-05-12 21:46:23 DEBUG (MainThread) [alexapy.alexalogin] Trying to load pickled cookie from file /config/.storage/alexa_media.t*********5@gmail.com.pickle
2020-05-12 21:46:26 DEBUG (MainThread) [alexapy.alexalogin] Trying to load aiohttpCookieJar to session
2020-05-12 21:46:26 DEBUG (MainThread) [alexapy.alexalogin] Loaded 9 cookies
2020-05-12 21:46:27 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2020-05-12 21:46:27 WARNING (MainThread) [homeassistant.setup] Setup of updater is taking over 10 seconds.
2020-05-12 21:46:28 DEBUG (MainThread) [alexapy.alexalogin] GET: 
https://alexa.amazon.co.uk/api/bootstrap returned 200:OK with response <CIMultiDictProxy('Content-Type': 'application/json', 'Content-Length': '156', 'Connection': 'keep-alive', 'Server': 'Server', 'Date': 'Tue, 12 May 2020 18:46:28 GMT', 'x-amzn-RequestId': 'db4fcd9a-ce74-493c-b9d5-d17fa227eb3b', 'Content-Encoding': 'gzip', 'x-amz-rid': 'AB78B4B7ZCE19YK2W4H2', 'Vary': 'Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 98f1fdf093c866d186183399254afdf0.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ATH50-C1', 'X-Amz-Cf-Id': 'Ae14d8YAyjptn8qWpJXngZVtxiAnw0z4cbSXHkCdB-NeRsW9fK6LdQ==')>
2020-05-12 21:46:28 DEBUG (MainThread) [alexapy.alexalogin] Logged in as t*********5@gmail.com
2020-05-12 21:46:28 DEBUG (MainThread) [alexapy.alexalogin] Using cookies to log in
2020-05-12 21:46:28 DEBUG (MainThread) [alexapy.alexalogin] Log in successful with cookies
2020-05-12 21:46:28 DEBUG (MainThread) [custom_components.alexa_media.configurator] Testing login status: {'login_successful': True}
2020-05-12 21:46:28 DEBUG (MainThread) [custom_components.alexa_media.configurator] Setting up Alexa devices for t*********5@g*******m
2020-05-12 21:46:28 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Websocket created: <alexapy.alexawebsocket.WebsocketEchoClient object at 0x6ed59410>
2020-05-12 21:46:28 DEBUG (MainThread) [alexapy.alexawebsocket] Connecting to wss://dp-gw-na.amazon.co.uk/?x-amz-device-type=ALEGCNGL9K0HM&x-amz-device-serial=**** with {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml, application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': '*', 'Referer': 'https://alexa.amazon.co.uk/api/bootstrap', 'Cookie': 'session-id=***; session-id-time=***; ubid-acbuk=***; session-token=***; x-acbuk=***; at-acbuk=***; sess-at-acbuk=***; sst-acbuk=***; csrf=***; ', 'Origin': 'https://alexa.amazon.co.uk'}
2020-05-12 21:46:31 DEBUG (MainThread) [alexapy.alexawebsocket] Initating Async Handshake.
2020-05-12 21:46:31 DEBUG (MainThread) [alexapy.alexawebsocket] Starting message parsing loop.
2020-05-12 21:46:31 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding WebSocket Handshake MSG.
2020-05-12 21:46:31 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: 0xbafef3f3 0x000000cd {"protocolName":"A:H","parameters":{"AlphaProtocolHandler.supportedEncodings":"GZIP","AlphaProtocolHandler.maxFragmentSize":"16000","AlphaProtocolHandler.receiveWindowSize":"16"}}TUNE
2020-05-12 21:46:31 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding Gateway Handshake MSG.
2020-05-12 21:46:31 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding Gateway Register MSG.
2020-05-12 21:46:31 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG 0x00000361 0x3ff2313f f 0x00000001 0xc784e881 0x000000b9 ACK 0x00000003 1.0 0x00000024 01e09e62-f504-476c-85c8-9c97c8da26ed 0x00000064 0x0000016978ff598c 0x000001720a35b563 END FABE
2020-05-12 21:46:31 DEBUG (MainThread) [alexapy.alexawebsocket] Received ACK MSG for Registration.
2020-05-12 21:46:31 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding PING.
2020-05-12 21:46:32 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Websocket succesfully connected
2020-05-12 21:46:32 DEBUG (MainThread) [custom_components.alexa_media] Creating coordinator
2020-05-12 21:46:32 DEBUG (MainThread) [custom_components.alexa_media] Refreshing coordinator
2020-05-12 21:46:32 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/devices-v2/device returned 200:OK:application/json
2020-05-12 21:46:32 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/notifications returned 200:OK:application/json
2020-05-12 21:46:32 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/bootstrap returned 200:OK:application/json
2020-05-12 21:46:33 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/dnd/device-status-list returned 200:OK:application/json
2020-05-12 21:46:33 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/bluetooth?cached=false returned 200:OK:application/json
2020-05-12 21:46:33 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/device-preferences returned 200:OK:application/json
2020-05-12 21:46:33 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Found 7 devices, 7 bluetooth
2020-05-12 21:46:33 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Updated 6 notifications for 2 devices at 2020-05-12 21:46:33.768585+03:00
2020-05-12 21:46:34 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/activities?startTime=&size=10&offset=1 returned 200:OK:application/json
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Updated last_called: {'serialNumber': 'G************UK5', 'timestamp': 1589308035728}
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: last_called changed:  to {'serialNumber': 'G************UK5', 'timestamp': 1589308035728}
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] Thanasis' Dot: Locale en-gb timezone Europe/Vienna
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] Thanasis' Dot: DND False
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] Bedroom: DND False
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] Home Echo: Locale en-gb timezone Europe/Athens
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] Home Echo: DND False
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] This Device: Locale en-gb timezone Europe/Vienna
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] This Device: DND False
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] Thanasis's Alexa Apps: Locale en-us timezone None
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] Thanasis's Alexa Apps: DND False
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Existing: [] New: ["Thanasis' Dot", 'Bedroom', 'Home Echo', 'This Device', "Thanasis's Alexa Apps"]; Filtered out by not being in include: [] or in exclude: ["Thanasis' Flex"]
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] Loading media_player
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media] Finished fetching alexa_media data in 2.097 seconds
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Trying with limit 5 delay 2 catch_exceptions True
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media.notify] t*********5@g*******m: Media player G************UK5 not loaded yet; delaying load
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Try: 1/5 after waiting 0 seconds result: False
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media.media_player] t*********5@g*******m: Refreshing Thanasis' Dot
2020-05-12 21:46:34 DEBUG (MainThread) [custom_components.alexa_media.media_player] Thanasis' Dot: Last_called check: self: G************UK5 reported: 
2020-05-12 21:46:35 DEBUG (MainThread) [alexapy.alexaapi] GET: https://alexa.amazon.co.uk/api/np/player?deviceSerialNumber=***=2560 returned 200:OK:application/json
2020-05-12 21:46:35 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up alexa_media platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/alexa_media/media_player.py", line 109, in async_setup_entry
    hass, config_entry.data, async_add_devices, discovery_info=None
  File "/config/custom_components/alexa_media/media_player.py", line 89, in async_setup_platform
    await alexa_client.init(device)
  File "/config/custom_components/alexa_media/media_player.py", line 211, in init
    await self.refresh(device)
  File "/config/custom_components/alexa_media/helpers.py", line 148, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 563, in refresh
    self._media_image_url = self._session.get("mainArt", {}).get("url")
AttributeError: 'NoneType' object has no attribute 'get'
2020-05-12 21:46:38 DEBUG (MainThread) [custom_components.alexa_media.notify] t*********5@g*******m: Media player G************UK5 not loaded yet; delaying load
2020-05-12 21:46:38 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Try: 2/5 after waiting 4 seconds result: False
2020-05-12 21:46:46 DEBUG (MainThread) [custom_components.alexa_media.notify] t*********5@g*******m: Media player G************UK5 not loaded yet; delaying load
2020-05-12 21:46:46 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Try: 3/5 after waiting 8 seconds result: False
2020-05-12 21:47:02 DEBUG (MainThread) [custom_components.alexa_media.notify] t*********5@g*******m: Media player G************UK5 not loaded yet; delaying load
2020-05-12 21:47:02 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Try: 4/5 after waiting 16 seconds result: False
2020-05-12 21:47:34 DEBUG (MainThread) [custom_components.alexa_media.notify] t*********5@g*******m: Media player G************UK5 not loaded yet; delaying load
2020-05-12 21:47:34 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Try: 5/5 after waiting 32 seconds result: False
2020-05-12 21:47:34 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 95, in async_setup_platform
    notify_service.hass = hass
AttributeError: 'bool' object has no attribute 'hass'
2020-05-12 21:47:44 ERROR (MainThread) [homeassistant.components.automation] Home Assistant Startup: Error executing script. Service not found for call_service at pos 2: Unable to find service notify/alexa_media_thanasis_dot
2020-05-12 21:58:30 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG 0x00000362 0x3ff5dbcd f 0x00000001 0x0ddef2c0 0x00000225 GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:**** {"payload":"{\"destinationUserId\":\"***\",\"dopplerId\":{\"deviceType\":\"***\",\"deviceSerialNumber\":\"****\"},\"volumeSetting\":47,\"isMuted\":false}","command":"PUSH_VOLUME_CHANGE"}FABE
2020-05-12 21:58:30 DEBUG (MainThread) [alexapy.alexawebsocket] Received Standard MSG.
2020-05-12 21:58:30 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Received websocket command: PUSH_VOLUME_CHANGE : {'destinationUserId': 'A**********4T6', 'dopplerId': {'deviceType': '***', 'deviceSerialNumber': 'G************UK5'}, 'volumeSetting': 47, 'isMuted': False}
2020-05-12 21:58:30 DEBUG (MainThread) [custom_components.alexa_media] Adding PUSH_VOLUME_CHANGE to seen_commands: {'PUSH_VOLUME_CHANGE': 1589309910.9605808}
2020-05-12 21:58:30 DEBUG (MainThread) [custom_components.alexa_media] Discovered new media_player ***
2020-05-12 21:58:31 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/notifications returned 200:OK:application/json
2020-05-12 21:58:31 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/bootstrap returned 200:OK:application/json
2020-05-12 21:58:31 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/devices-v2/device returned 200:OK:application/json
2020-05-12 21:58:32 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/dnd/device-status-list returned 200:OK:application/json
2020-05-12 21:58:32 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/device-preferences returned 200:OK:application/json
2020-05-12 21:58:32 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/bluetooth?cached=false returned 200:OK:application/json
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Found 7 devices, 7 bluetooth
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Updated 6 notifications for 2 devices at 2020-05-12 21:58:32.529738+03:00
2020-05-12 21:58:32 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/activities?startTime=&size=10&offset=1 returned 200:OK:application/json
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Updated last_called: {'serialNumber': 'G************UK5', 'timestamp': 1589308035728}
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] Thanasis' Dot: Locale en-gb timezone Europe/Vienna
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] Thanasis' Dot: DND False
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] Bedroom: DND False
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] Home Echo: Locale en-gb timezone Europe/Athens
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] Home Echo: DND False
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] This Device: Locale en-gb timezone Europe/Vienna
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] This Device: DND False
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] Thanasis's Alexa Apps: Locale en-us timezone None
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] Thanasis's Alexa Apps: DND False
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Existing: [] New: ["Thanasis' Dot", 'Bedroom', 'Home Echo', 'This Device', "Thanasis's Alexa Apps"]; Filtered out by not being in include: [] or in exclude: ["Thanasis' Flex"]
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] Loading media_player
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] Finished fetching alexa_media data in 1.918 seconds
2020-05-12 21:58:32 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry t*********5@gmail.com - amazon.co.uk for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 332, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 163, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2020-05-12 21:58:32 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG 0x00000362 0x3ff5dbe0 f 0x00000001 0x4ff9228d 0x0000022e GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:***:deviceType:*** {"payload":"{\"destinationUserId\":\"***\",\"dopplerId\":{\"deviceType\":\"***\",\"deviceSerialNumber\":\"***\"},\"bass\":0,\"midrange\":1,\"treble\":6}","command":"PUSH_EQUALIZER_STATE_CHANGE"}FABE
2020-05-12 21:58:32 DEBUG (MainThread) [alexapy.alexawebsocket] Received Standard MSG.
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Received websocket command: PUSH_EQUALIZER_STATE_CHANGE : {'destinationUserId': 'A**********4T6', 'dopplerId': {'deviceType': '***', 'deviceSerialNumber': 'G************UK5'}, 'bass': 0, 'midrange': 1, 'treble': 6}
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] Adding PUSH_EQUALIZER_STATE_CHANGE to seen_commands: {'PUSH_VOLUME_CHANGE': 1589309910.9605808, 'PUSH_EQUALIZER_STATE_CHANGE': 1589309912.9135938}
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] Discovered new media_player ***
2020-05-12 21:58:32 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG 0x00000362 0x3ff5dbf4 f 0x00000001 0x3fd80fc1 0x0000022e GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:***:deviceType:*** {"payload":"{\"destinationUserId\":\"***\",\"dopplerId\":{\"deviceType\":\"A3VRME03NAXFUB\",\"deviceSerialNumber\":\"***\"},\"bass\":0,\"midrange\":0,\"treble\":0}","command":"PUSH_EQUALIZER_STATE_CHANGE"}FABE
2020-05-12 21:58:32 DEBUG (MainThread) [alexapy.alexawebsocket] Received Standard MSG.
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Received websocket command: PUSH_EQUALIZER_STATE_CHANGE : {'destinationUserId': 'A**********4T6', 'dopplerId': {'deviceType': 'A3VRME03NAXFUB', 'deviceSerialNumber': 'G************SUG'}, 'bass': 0, 'midrange': 0, 'treble': 0}
2020-05-12 21:58:32 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG 0x00000362 0x3ff5dbf5 f 0x00000001 0xc6bee5f7 0x00000225 GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:***:deviceType:*** {"payload":"{\"destinationUserId\":\"***\",\"dopplerId\":{\"deviceType\":\"A3VRME03NAXFUB\",\"deviceSerialNumber\":\"***\"},\"volumeSetting\":63,\"isMuted\":false}","command":"PUSH_VOLUME_CHANGE"}FABE
2020-05-12 21:58:32 DEBUG (MainThread) [alexapy.alexawebsocket] Received Standard MSG.
2020-05-12 21:58:32 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Received websocket command: PUSH_VOLUME_CHANGE : {'destinationUserId': 'A**********4T6', 'dopplerId': {'deviceType': 'A3VRME03NAXFUB', 'deviceSerialNumber': 'G************SUG'}, 'volumeSetting': 63, 'isMuted': False}
2020-05-12 21:58:43 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/bootstrap returned 200:OK:application/json
2020-05-12 21:58:50 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/notifications returned 200:OK:application/json
2020-05-12 21:58:50 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/devices-v2/device returned 200:OK:application/json
2020-05-12 21:58:50 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/dnd/device-status-list returned 200:OK:application/json
2020-05-12 21:58:50 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/bluetooth?cached=false returned 200:OK:application/json
2020-05-12 21:58:50 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/device-preferences returned 200:OK:application/json
2020-05-12 21:58:50 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Found 7 devices, 7 bluetooth
2020-05-12 21:58:50 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Updated 6 notifications for 2 devices at 2020-05-12 21:58:50.815032+03:00
2020-05-12 21:58:51 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/activities?startTime=&size=10&offset=1 returned 200:OK:application/json
2020-05-12 21:58:51 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Updated last_called: {'serialNumber': 'G************UK5', 'timestamp': 1589308035728}
2020-05-12 21:58:51 DEBUG (MainThread) [custom_components.alexa_media] Thanasis' Dot: Locale en-gb timezone Europe/Vienna
2020-05-12 21:58:51 DEBUG (MainThread) [custom_components.alexa_media] Thanasis' Dot: DND False
2020-05-12 21:58:51 DEBUG (MainThread) [custom_components.alexa_media] Bedroom: DND False
2020-05-12 21:58:51 DEBUG (MainThread) [custom_components.alexa_media] Home Echo: Locale en-gb timezone Europe/Athens
2020-05-12 21:58:51 DEBUG (MainThread) [custom_components.alexa_media] Home Echo: DND False
2020-05-12 21:58:51 DEBUG (MainThread) [custom_components.alexa_media] This Device: Locale en-gb timezone Europe/Vienna
2020-05-12 21:58:51 DEBUG (MainThread) [custom_components.alexa_media] This Device: DND False
2020-05-12 21:58:51 DEBUG (MainThread) [custom_components.alexa_media] Thanasis's Alexa Apps: Locale en-us timezone None
2020-05-12 21:58:51 DEBUG (MainThread) [custom_components.alexa_media] Thanasis's Alexa Apps: DND False
2020-05-12 21:58:51 DEBUG (MainThread) [custom_components.alexa_media] t*********5@g*******m: Existing: [] New: ["Thanasis' Dot", 'Bedroom', 'Home Echo', 'This Device', "Thanasis's Alexa Apps"]; Filtered out by not being in include: [] or in exclude: ["Thanasis' Flex"]
2020-05-12 21:58:51 DEBUG (MainThread) [custom_components.alexa_media] Loading media_player
2020-05-12 21:58:51 DEBUG (MainThread) [custom_components.alexa_media] Finished fetching alexa_media data in 8.202 seconds
2020-05-12 21:58:51 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry t*********5@gmail.com - amazon.co.uk for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 332, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 163, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

**Comment by alandtse** [comment]
Thanks. Can you provide the json for the link https://alexa.amazon.co.uk/api/np/player?deviceSerialNumber=***=2560 ? You'll need to add your device serial number back in.

**Comment by drthanwho** [comment]
I'm sorry I won't be able to. I never saved the original file before removing the SN# and I have since rebooted HA several times so original log is also been overwritten. 

I tried removing the HA integration, uninstalling it from HACS and reinstalling but this time when I add it back it never asks for captcha or for two factor authentication. I get the _"integration was added successfully"_ pop up but no devices coming through.

I'll re enable debug on the logs and see if I get any serial numbers but I'd assume since the devices aren't coming up on the integration there will be nothing relating to that in the logs either?

Without debug on I've been getting the first error 
`"AttributeError: 'NoneType' object has no attribute 'get'`

and nothing else, compared to before where these errors were following 
`Error setting up entry t*********5@gmail.com - amazon.co.uk for media_player`

**Comment by alandtse** [comment]
I just need you to go to the link using your browser and provide me the results. The link doesn't work now because the serial number is missing. The full link is in your logs.

**Comment by drthanwho** [comment]
Can I do that by getting the serial number from my Amazon account and putting in on the link?

**Comment by drthanwho** [comment]
Ok here you go. Although this just shows what was playing last so hoping this is actually what you wanted?

```json
{
"playerInfo":{
"hint":null,
"infoText":{
"header":"",
"headerSubtext1":"Άχρηστο Podcast",
"multiLineMode":false,
"subText1":"Άχρηστο Podcast",
"subText2":"Άχρηστο Podcast",
"title":"Αιμόμικτο Πόνυ - Bonus Track by Thanos Avgerinos"
},
"isPlayingInLemur":false,
"lemurVolume":null,
"lyrics":null,
"mainArt":null,
"mediaId":"spotify:episode:6WmW4D18Is5lLYT9xHMzuK",
"miniArt":{
"altText":"externalMediaPlayer-logo",
"artType":"IconArtSource",
"iconId":"salmon",
"iconStyles":null
},
"miniInfoText":{
"header":"",
"headerSubtext1":"Άχρηστο Podcast",
"multiLineMode":false,
"subText1":"Άχρηστο Podcast",
"subText2":"Άχρηστο Podcast",
"title":"Αιμόμικτο Πόνυ - Bonus Track by Thanos Avgerinos"
},
"playbackSource":null,
"playingInLemurId":null,
"progress":{
"allowScrubbing":true,
"locationInfo":null,
"mediaLength":154,
"mediaProgress":153,
"showTiming":true,
"visible":true
},
"provider":{
"artOverlay":null,
"fallbackMainArt":null,
"providerDisplayName":"Spotify",
"providerLogo":{
"altText":"externalMediaPlayer-logo",
"artType":"IconArtSource",
"iconId":"salmon",
"iconStyles":null
},
"providerName":"Spotify"
},
"quality":null,
"queueId":"spotify:show:3rwnGOIqgavyWVwZxqp3uF",
"state":"PAUSED",
"template":null,
"transport":{
"closedCaptions":null,
"layoutType":"MusicTransportLayout",
"lyrics":null,
"next":"ENABLED",
"playPause":"ENABLED",
"previous":"ENABLED",
"repeat":"ENABLED",
"shuffle":"ENABLED"
},
"upNextItems":null,
"volume":{
"muted":false,
"volume":47
}
}
}
```

**Comment by alandtse** [comment]
Ok thanks. I see the issue.

**Comment by alandtse** [comment]
Can you please try replacing the media_player.py with the one in the fix and let me know if it works?
