### ISSUE TITLE
ValueError: Config entry has already been setup!

### ISSUE THREAD

**Issue by RobinCutshaw** [custom-components/alexa_media_player#755]
**Describe the bug**
ValueError: Config entry has already been setup!
This error is printed every 10 minutes for a while then pauses for a while then starts back up.

**To Reproduce**
I configured the custom component with the wrong amazon account and then deleted the integration and re-added with the correct account.  I have restarted hass with no effect.

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): commit be416d9fc66306027991afbc2d9f22557bde794c (HEAD -> dev, upstream/dev)
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): __version__ = "2.8.0" (git ed7c21a)
 - alexapy (version from `pip show alexapy` or HA startup): Version: 1.10.1

**Logs**
2020-05-27 10:45:38 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@example.com - amazon.com for media_player
Traceback (most recent call last):
  File "/home/robin/github/core/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/home/robin/github/core/homeassistant/components/media_player/__init__.py", line 333, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/home/robin/github/core/homeassistant/helpers/entity_component.py", line 163, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2020-05-27 10:45:50 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@example.com - amazon.com for media_player
Traceback (most recent call last):
  File "/home/robin/github/core/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/home/robin/github/core/homeassistant/components/media_player/__init__.py", line 333, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/home/robin/github/core/homeassistant/helpers/entity_component.py", line 163, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Additional context**

**Comment by alandtse** [comment]
Do you have it setup in your configuration.yaml too? Try deleting it from the integration page and from the configuration.yaml and then restart HA. After it restarts, add it through the integration page.

**Comment by RobinCutshaw** [comment]
I do not have in configuration.yaml.

**Comment by alandtse** [comment]
Did you remove it and readd it?

**Comment by RobinCutshaw** [comment]
Yes, that is how the problem started.  I configured it, deleted it, and then re-added/configured it.

**Comment by alandtse** [comment]
Please provide your startup logs.

**Comment by RobinCutshaw** [comment]
I just restarted again and received no error messages upon startup and haven't received the ConfigEntry error that showed up during multiple restarts before.  I've not changed anything in the config and have not pulled from core.  Self healing?  :)

**Comment by alandtse** [comment]
No idea without logs. I'm glad that it went away. If you see it again, let me know. I'll plan to close this out in a week or so.
