### ISSUE TITLE
Alexa Notify Text to Speech error

### ISSUE THREAD

**Issue by tux43** [custom-components/alexa_media_player#792]
Hi,
I’ve installed https://github.com/custom-components/alexa_media_player/

I’m trying to do TTS and receive the error below.

<img width="607" alt="Screen Shot 2020-06-20 at 9 34 24 am" src="https://user-images.githubusercontent.com/53364421/85186920-f5857400-b2da-11ea-844c-af3f942699eb.png">

`2020-06-20 09:36:22 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.240165373216230] 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 119, in async_notify_message
    await notify_service.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 189, in async_send_message
    if data["type"] == "tts":
TypeError: 'NoneType' object is not subscriptable`

**Comment by alandtse** [comment]
Please review the documentation.
https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component#how-to-use
