### ISSUE TITLE
An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments: ('Session is closed',)

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#796]
**Describe the bug**
After a relogin attempt, the component reconnects succesfully and performs static gets without error.

**To Reproduce**
1. Relogin with configurator after session expires.
2. See error

**Expected behavior**
Session should automatically be refreshed for all commands.

**Screenshots**

**System details**
 - Home-assistant (version):  111.4
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). Yes
 - alexa_media  (version from `const.py` or HA startup): 2.8.6
 - alexapy (version from `pip show alexapy` or HA startup): 1.10.4

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```
2020-06-21 12:36:29 ERROR (MainThread) [alexapy.helpers] alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0xa8cddbd0>,), {}): An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-06-21 12:36:29 ERROR (MainThread) [homeassistant.util.logging] Exception in _handle_event when dispatching 'alexa_media_a******e@g*******m': ({'player_state': {'destinationUserId': 'XXX', 'dopplerId': {'deviceType': 'AB72C64C86AW2', 'deviceSerialNumber': 'XXX'}, 'audioPlayerState': 'PLAYING', 'quality': None, 'error': False, 'errorMessage': None, 'mediaReferenceId': '78e56ac3-4ab4-4c85-86b4-3d9bb3f5ae60:6'}},)
Traceback (most recent call last):
  File "/config/custom_components/alexa_media/media_player.py", line 369, in _handle_event
    await self.async_update()
  File "/config/custom_components/alexa_media/helpers.py", line 148, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 802, in async_update
    device, no_throttle=True
  File "/config/custom_components/alexa_media/helpers.py", line 148, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 545, in refresh
    session = await self.alexa_api.get_state()
  File "/usr/local/lib/python3.7/site-packages/alexapy/helpers.py", line 69, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 761, in get_state
    + "&screenWidth=2560"
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 122, in _get_request
    return await self._request("get", uri, data)
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 93, in _request
    ssl=self._login._ssl,
  File "/usr/local/lib/python3.7/site-packages/alexapy/aiohttp/client.py", line 377, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
```

**Additional context**

**Comment by alandtse** [comment]
Workaround is to just restart HA or remove and readd the integration.
