### ISSUE TITLE
ModuleNotFoundError: No module named 'alexapy.aiohttp'

### ISSUE THREAD

**Issue by ransom3910** [custom-components/alexa_media_player#799]
When trying to install the Alexa media component I am getting an error in the log "ModuleNotFoundError: No module named 'alexapy.aiohttp'

I then went to the CLI and just ran python.  I did an import of alexapy and I get this error just from trying to import the module.

Before this I also ran pip3 install alexapy.  It said all requirements are already met.

Full Traceback
>>> >>> import alexapy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/homeassistant/lib/python3.8/site-packages/alexapy/__init__.py", line 11, in <module>
    from .alexaapi import AlexaAPI
  File "/srv/homeassistant/lib/python3.8/site-packages/alexapy/alexaapi.py", line 16, in <module>
    from alexapy.aiohttp import ClientConnectionError, ClientResponse
ModuleNotFoundError: No module named 'alexapy.aiohttp'

**Comment by ransom3910** [comment]
After digging into the lib directory in python and looking in the alexapy directory, I found the aiohttp directory was missing.  I did a pip3 uninstall alexapy then reinstalled it which fixed the problem.
