### ISSUE TITLE
Log error "Session is closed"

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#809]
**Describe the bug**
Echo devices not working and log traced

**To Reproduce**
1. Restart HA
2. Check log

**Expected behavior**
No error logged and plugin working as designed

**System details**
 - Home-assistant (version): 0.111.4
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v2.8.7
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**

```
2020-06-25 20:19:38 ERROR (MainThread) [alexapy.helpers] alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f28aa86a850>,), {}): An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
('Session is closed',)
2020-06-25 20:19:38 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.in_tutta_la_casa fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/alexa_media/helpers.py", line 148, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 802, in async_update
    device, no_throttle=True
  File "/config/custom_components/alexa_media/helpers.py", line 148, in wrapper
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/media_player.py", line 545, in refresh
    session = await self.alexa_api.get_state()
  File "/usr/local/lib/python3.7/site-packages/alexapy/helpers.py", line 69, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 761, in get_state
    + "&screenWidth=2560"
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 122, in _get_request
    return await self._request("get", uri, data)
  File "/usr/local/lib/python3.7/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexaapi.py", line 93, in _request
    ssl=self._login._ssl,
  File "/usr/local/lib/python3.7/site-packages/alexapy/aiohttp/client.py", line 377, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

```

**Additional context**

**Comment by alandtse** [comment]
We need the logs before it gets to this state. Did the configurator appear? Does it happen if you reboot? If you reinstall the integration?

**Comment by alandtse** [comment]
Your version information appears incorrect. Line [545](https://github.com/custom-components/alexa_media_player/blob/v2.8.7/custom_components/alexa_media/media_player.py#L545) in media_player.py isn't what your log is reporting. It looks like your'e on 2.8.6.  Please delete and reinstall. 

Please reopen if the issues persists on the latest version.

**Comment by chemelli74** [comment]
Don't know why but there was a mix of versions; reinstalled latest and cannot reproduce.

Simone
