### ISSUE TITLE
notify.alexa_media not working

### ISSUE THREAD

**Issue by pizzakid25** [custom-components/alexa_media_player#822]
**Describe the bug**
Unable to use notify.alexa_media service, returns error: ```'NoneType' object is not iterable```

**To Reproduce**
1. Go to 'Developer Tools'
2. Click on 'Services'
3. Select 'notify.alexa_media'
4. Input service data: 
```
message: test
data: 
  type: tts
  target: 
    - media_player.edward_s_tv
```
5. See error

**Expected behavior**
TV says the word 'test'

**System details**
 - Home-assistant (version): 0.112.0
 - Hassio (Yes/No): Yes; HassOS 4.10
 - alexa_media: 2.8.9
 - alexapy (version from `pip show alexapy` or HA startup): 1.10.7

**Logs**
```
2020-07-02 11:50:11 INFO (MainThread) [custom_components.alexa_media] 
-------------------------------------------------------------------
alexa_media
Version: 2.8.9
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/alexa_media_player/issues
-------------------------------------------------------------------

2020-07-02 11:50:11 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==1.10.7
2020-07-02 11:50:11 DEBUG (MainThread) [alexapy.alexalogin] Trying to load pickled cookie from file /config/.storage/alexa_media.7******305.pickle
2020-07-02 11:50:13 DEBUG (MainThread) [alexapy.alexalogin] Trying to load aiohttpCookieJar to session
2020-07-02 11:50:13 DEBUG (MainThread) [alexapy.alexalogin] Loaded 8 cookies
2020-07-02 11:50:13 DEBUG (MainThread) [alexapy.alexalogin] Using cookies to log in
2020-07-02 11:50:16 DEBUG (MainThread) [alexapy.alexalogin] GET: 
https://alexa.amazon.com/api/bootstrap returned 200:OK with response <CIMultiDictProxy('Content-Type': 'application/json', 'Content-Length': '133', 'Connection': 'keep-alive', 'Server': 'Server', 'Date': 'Thu, 02 Jul 2020 15:50:15 GMT', 'x-amzn-RequestId': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Content-Encoding': 'gzip', 'Vary': 'Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent', 'x-amz-rid': 'xxxxxxxxxxxxxxxxxxxxx', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 ba82151bf51e4c722c5305c983d8b71e.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'IAD89-C3', 'X-Amz-Cf-Id': 'O1r7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-hJDgyh-ngM2OYrg==')>
2020-07-02 11:50:16 DEBUG (MainThread) [alexapy.alexalogin] Logged in as mobile account 
2020-07-02 11:50:16 DEBUG (MainThread) [alexapy.alexalogin] Log in successful with cookies
2020-07-02 11:50:16 DEBUG (MainThread) [custom_components.alexa_media.configurator] Testing login status: {'login_successful': True}
2020-07-02 11:50:16 DEBUG (MainThread) [custom_components.alexa_media.configurator] Setting up Alexa devices for 7******305
2020-07-02 11:50:16 DEBUG (MainThread) [custom_components.alexa_media] 7******305: Websocket created: <alexapy.alexawebsocket.WebsocketEchoClient object at 0x6de450f0>
2020-07-02 11:50:16 DEBUG (MainThread) [alexapy.alexawebsocket] Connecting to wss://dp-gw-na-js.amazon.com/?x-amz-device-type=ALEGCNGL9K0HM&x-amz-device-serial=135xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx with {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml, application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': '*', 'Referer': 'https://alexa.amazon.com/api/bootstrap', 'Cookie': 'session-id=140-xxxxxxx-6847763; session-id-time=2223982821l; ubid-main=135-xxxxxxx-3390638; session-token=XhUfMRqgIzvJQmgTQR86lNld4GIgZBje/mRoYTme6QtJ410ScWtHHvB1Tfr2M4s8Us9rK6XUyo4m6Dq5VGLne3TGvpDurEtEUM8OSlfIyVLgTKhvmXO4CnsudD2W2OFSCIL+H8lVQ89En7EM3KaFcqpDj/YwMnb2n3lBJPBFnRRI2uex636swB0/Mj7e8Ngdz/YPcGc2Gt6+qka4XUIfFC77cBjCaWg1ExF5zBD+4tk=; x-main=Kl0BGOWT5CrUbLCpPRPXfvhyIHKt7nqOXedOMwFynGDUGefAJWF6ARLd69CcCUc0; at-main=Atza|IwEBIKAcsbPTWqz6JcMWNoHHRfgTvLt0TJA8tnYFh6v3YBpf1EWdeZSVREO8z2_KzmW6ViEhZW5G65Z8UuTaRlI_Awwr3JYUg595Th2hZQgH20Yu-oqdvUMnNDYNm-YiAsNF5fgjQRBX8MvY1Ev5_a7TrzD_JPl5urhx0zvMkPg3ZaDkOv2znQYYOU-9Ap4UuRY6kQPaNVF6PAtL8L4Wnqxj6uEU; sess-at-main=kejhsRXhfR2v3UETPBnj9XKcTqC+1iHTe0W6zNEpFCw=; csrf=-1468769599; ', 'Origin': 'https://alexa.amazon.com'}
2020-07-02 11:50:19 DEBUG (MainThread) [alexapy.alexawebsocket] Initating Async Handshake.
2020-07-02 11:50:19 DEBUG (MainThread) [alexapy.alexawebsocket] Starting message parsing loop.
2020-07-02 11:50:19 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: 0x37a3b607 0x0000009c {"protocolName":"A:H","parameters":{"AlphaProtocolHandler.maxFragmentSize":"16000","AlphaProtocolHandler.receiveWindowSize":"16"}}TUNE
2020-07-02 11:50:19 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding WebSocket Handshake MSG.
2020-07-02 11:50:19 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding Gateway Handshake MSG.
2020-07-02 11:50:19 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG 0x00000361 0x00f8b29f f 0x00000001 0xce83af88 0x000000b9 ACK 0x00000003 1.0 0x00000024 01e09e62-f504-476c-85c8-9c97c8da26ed 0x00000064 0x0000016978ff598c 0x000001731038b920 END FABE
2020-07-02 11:50:19 DEBUG (MainThread) [alexapy.alexawebsocket] Received ACK MSG for Registration.
2020-07-02 11:50:19 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding Gateway Register MSG.
2020-07-02 11:50:19 DEBUG (MainThread) [alexapy.alexawebsocket] Encoding PING.
2020-07-02 11:50:20 DEBUG (MainThread) [custom_components.alexa_media] 7******305: Websocket succesfully connected
2020-07-02 11:50:20 DEBUG (MainThread) [custom_components.alexa_media] Creating coordinator
2020-07-02 11:50:20 DEBUG (MainThread) [custom_components.alexa_media] Refreshing coordinator
2020-07-02 11:50:20 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/devices-v2/device returned 200:OK:application/json
2020-07-02 11:50:20 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/bootstrap returned 200:OK:application/json
2020-07-02 11:50:20 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/bluetooth?cached=false returned 200:OK:application/json
2020-07-02 11:50:20 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/dnd/device-status-list returned 200:OK:application/json
2020-07-02 11:50:20 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/device-preferences returned 200:OK:application/json
2020-07-02 11:50:20 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/notifications returned 200:OK:application/json
2020-07-02 11:50:20 DEBUG (MainThread) [custom_components.alexa_media] 7******305: Found 7 devices, 7 bluetooth
2020-07-02 11:50:21 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/notifications returned 200:OK:application/json
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] 7******305: Updated 0 notifications for 1 devices at 2020-07-02 11:50:21.180346-04:00
2020-07-02 11:50:21 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/activities?startTime=&size=10&offset=1 returned 200:OK:application/json
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] 7******305: Updated last_called: {'serialNumber': 'G************2EM', 'timestamp': 1593704005796}
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] 7******305: last_called changed:  to {'serialNumber': 'G************2EM', 'timestamp': 1593704005796}
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] Diz: Locale en-us timezone America/New_York
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] Diz: DND False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] Isaac's TV: Locale en-us timezone America/New_York
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] Isaac's TV: DND False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] Edward's TV: Locale en-us timezone America/New_York
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] Edward's TV: DND False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] William's TV: Locale en-us timezone America/New_York
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] William's TV: DND False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] Echo Dot: Locale en-us timezone America/New_York
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] Echo Dot: DND False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] This Device: Locale en-us timezone America/New_York
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] This Device: DND False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] Rob's Alexa Apps: Locale en-us timezone None
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] Rob's Alexa Apps: DND False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] 7******305: Existing: [] New: ['Diz', "Isaac's TV", "Edward's TV", "William's TV", 'Echo Dot', 'This Device', "Rob's Alexa Apps"]; Filtered out by not being in include: [] or in exclude: []
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] Loading media_player
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media] Finished fetching alexa_media data in 0.904 seconds
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.media_player] 7******305: Refreshing Isaac's TV
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.media_player] Isaac's TV: Last_called check: self: G************2EU reported: 
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.media_player] 7******305: Refreshing Edward's TV
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.media_player] Edward's TV: Last_called check: self: G************198 reported: 
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.media_player] 7******305: Refreshing William's TV
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.media_player] William's TV: Last_called check: self: G************2EM reported: 
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.media_player] 7******305: Refreshing Echo Dot
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.media_player] Echo Dot: Last_called check: self: G************U3K reported: 
2020-07-02 11:50:21 DEBUG (MainThread) [alexapy.alexaapi] GET: https://alexa.amazon.com/api/np/player?deviceSerialNumber+xxxxxxxxxxxxxxxxx&deviceType=A3S5BH2HU6VAYF&screenWidth=2560 returned 400:Bad Request:application/json
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.media_player] 7******305: Refreshing This Device
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.media_player] This Device: Last_called check: self: f****************************5c9 reported: 
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.helpers] 7******305: Adding [<Entity Diz: unavailable>, <Entity Isaac's TV: standby>, <Entity Edward's TV: standby>, <Entity William's TV: standby>, <Entity Echo Dot: standby>, <Entity This Device: standby>, <Entity Rob's Alexa Apps: unavailable>]
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Loading switches
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Found G************J76 dnd switch with status: False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Skipping shuffle for G************J76
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Skipping repeat for G************J76
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Found G************2EU dnd switch with status: False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Skipping shuffle for G************2EU
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Skipping repeat for G************2EU
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Found G************198 dnd switch with status: False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Skipping shuffle for G************198
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Skipping repeat for G************198
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Found G************2EM dnd switch with status: False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Skipping shuffle for G************2EM
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Skipping repeat for G************2EM
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Found G************U3K dnd switch with status: False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Found G************U3K shuffle switch with status: False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Found G************U3K repeat switch with status: False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Found f****************************5c9 dnd switch with status: False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Skipping shuffle for f****************************5c9
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Skipping repeat for f****************************5c9
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Found 6****************************9e9 dnd switch with status: False
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Skipping shuffle for 6****************************9e9
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.switch] 7******305: Skipping repeat for 6****************************9e9
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.helpers] 7******305: Adding [<Entity Diz do not disturb switch: off>, <Entity Isaac's TV do not disturb switch: off>, <Entity Edward's TV do not disturb switch: off>, <Entity William's TV do not disturb switch: off>, <Entity Echo Dot do not disturb switch: off>, <Entity Echo Dot shuffle switch: off>, <Entity Echo Dot repeat switch: off>, <Entity This Device do not disturb switch: off>, <Entity Rob's Alexa Apps do not disturb switch: off>]
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Loading sensors
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************J76 Alarm sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************J76 Timer sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************J76 Reminder sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************2EU Alarm sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************2EU Timer sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************2EU Reminder sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************198 Alarm sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************198 Timer sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************198 Reminder sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************2EM Alarm sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************2EM Timer sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************2EM Reminder sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************U3K Alarm sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************U3K Timer sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found G************U3K Reminder sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found f****************************5c9 Alarm sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found f****************************5c9 Timer sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.sensor] 7******305: Found f****************************5c9 Reminder sensor (0) with next: unavailable
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.helpers] 7******305: Adding [<Entity Diz next Alarm: unavailable>, <Entity Diz next Timer: unavailable>, <Entity Diz next Reminder: unavailable>, <Entity Isaac's TV next Alarm: unavailable>, <Entity Isaac's TV next Timer: unavailable>, <Entity Isaac's TV next Reminder: unavailable>, <Entity Edward's TV next Alarm: unavailable>, <Entity Edward's TV next Timer: unavailable>, <Entity Edward's TV next Reminder: unavailable>, <Entity William's TV next Alarm: unavailable>, <Entity William's TV next Timer: unavailable>, <Entity William's TV next Reminder: unavailable>, <Entity Echo Dot next Alarm: unavailable>, <Entity Echo Dot next Timer: unavailable>, <Entity Echo Dot next Reminder: unavailable>, <Entity This Device next Alarm: unavailable>, <Entity This Device next Timer: unavailable>, <Entity This Device next Reminder: unavailable>]
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Trying with limit 5 delay 2 catch_exceptions True
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.helpers] alexa_media.notify.async_get_service: Try: 1/5 after waiting 0 seconds result: <custom_components.alexa_media.notify.AlexaNotificationService object at 0x6a80c2d0>
2020-07-02 11:50:21 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/phoenix returned 200:OK:application/json
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.alarm_control_panel] 7******305: No Alexa Guard entity found
2020-07-02 11:50:21 DEBUG (MainThread) [custom_components.alexa_media.alarm_control_panel] 7******305: Skipping creation of uninitialized device: <Entity Alexa Guard: None>
2020-07-02 11:50:28 DEBUG (MainThread) [custom_components.alexa_media.notify] Message: test213fgd, kwargs: {'title': 'test', 'data': {'type': 'tts', 'target': ['media_player.wiliam_s_tv']}, 'message': 'test213fgd'}
2020-07-02 11:50:28 DEBUG (MainThread) [custom_components.alexa_media.notify] Target type: <class 'NoneType'>
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] Disabling polling for Diz
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] 7******305: Refreshing Isaac's TV
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] Isaac's TV: Last_called check: self: G************2EU reported: G************2EM
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] Disabling polling for Isaac's TV
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] 7******305: Refreshing Edward's TV
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] Edward's TV: Last_called check: self: G************198 reported: G************2EM
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] Disabling polling for Edward's TV
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] 7******305: Refreshing William's TV
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] William's TV: Last_called check: self: G************2EM reported: G************2EM
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] Disabling polling for William's TV
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] 7******305: Refreshing Echo Dot
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] Echo Dot: Last_called check: self: G************U3K reported: G************2EM
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] 7******305: Refreshing This Device
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] This Device: Last_called check: self: f****************************5c9 reported: G************2EM
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] Disabling polling for This Device
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] Disabling polling for Rob's Alexa Apps
2020-07-02 11:50:32 DEBUG (MainThread) [alexapy.alexaapi] GET: https://alexa.amazon.com/api/np/player?deviceSerialNumber=xxxxxxxxxxxxxxxxxxx&deviceType=A3S5BH2HU6VAYF&screenWidth=2560 returned 400:Bad Request:application/json
2020-07-02 11:50:32 DEBUG (MainThread) [custom_components.alexa_media.media_player] Disabling polling for Echo Dot
```
There is also this:
```
Logger: homeassistant.components.websocket_api.http.connection.xxxxxxxxxx
Source: custom_components/alexa_media/notify.py:168
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:50:28 AM (1 occurrences)
Last logged: 11:50:28 AM

'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 119, in async_notify_message
    await notify_service.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 168, in async_send_message
    for target in targets:
TypeError: 'NoneType' object is not iterable
```

**Comment by alandtse** [comment]
Can you provide the logs when you try using the service? This is again probably related to the mobileaccount.

**Comment by alandtse** [comment]
Ok, it looks like something may have changed in HA112. Should have a fix.

**Comment by alandtse** [comment]
Nevermind. It wasn't a HA change. The person who [rewrote](https://github.com/custom-components/alexa_media_player/wiki/Configuration:-Notification-Component/_compare/7c1795122fd6f663d7260f2c886fc2896d2633c4...2d492b952a6bed05ef852d31f5cf58cde13cb959) the wiki examples broke the syntax.

I'll revert the change, please use the proper syntax.
