### ISSUE TITLE
Error while setting up next_reminder sensor

### ISSUE THREAD

**Issue by brianewman** [custom-components/alexa_media_player#826]
**Describe the bug**
Next reminder sensors are showing as "unavailable".

**To Reproduce**
Restart Home Assistant
Look at logs, see error
Look at sensor.xxx_next_reminder sensors, state is "unavailable"

**Expected behavior**
sensor.xxx_next_reminder state should show date and time of next reminder 

**Screenshots**
N/A

**System details**
 - Home-assistant (version): 0.112.1 
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 2.9.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.10.7

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

2020-07-03 09:49:02 INFO (MainThread) [homeassistant.components.switch] Setting up switch.alexa_media
2020-07-03 09:49:02 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.alexa_media
2020-07-03 09:49:02 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarm_control_panel.alexa_media
2020-07-03 09:49:02 INFO (MainThread) [homeassistant.components.notify] Setting up notify.alexa_media
2020-07-03 09:49:03 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 449, in _async_add_entity
    await entity.async_added_to_hass()
  File "/config/custom_components/alexa_media/sensor.py", line 265, in async_added_to_hass
    await self.async_update()
  File "/config/custom_components/alexa_media/sensor.py", line 358, in async_update
    self._process_raw_notifications()
  File "/config/custom_components/alexa_media/sensor.py", line 166, in _process_raw_notifications
    self._all = list(map(self._update_recurring_alarm, self._all))
  File "/config/custom_components/alexa_media/sensor.py", line 229, in _update_recurring_alarm
    and alarm.isoweekday not in RECURRING_PATTERN_ISO_SET[recurring_pattern]
AttributeError: 'float' object has no attribute 'isoweekday'

**Additional context**
One Alexa device has a reminder set for every weekday at 6:30am.  Others have reminders set for specific days.

**Comment by alandtse** [comment]
If you enable logs for `alexa_media`, there should be a value of the alarm that is causing the error right before the exception is raised. Can you please provide that?

**Comment by alandtse** [comment]
I'll close this for now. Please let me know when you're ready to proceed.

**Comment by vajonam** [comment]
@alandtse, I am seeing this same error, can you please reopen this ? 
 
```
2020-11-20 08:42:36 DEBUG (MainThread) [custom_components.alexa_media.sensor] Sensor value ('96bb5c3e-3fa1-3f7d-a2e5-5a798ef73fd6', {'alarmTime': 1606344300000, 'automationId': None, 'createdDate': 1605738767988, 'deferredAtTime': None, 'deliveryType': None, 'deviceName': None, 'deviceSerialNumber': 'G090U608841504W0', 'deviceType': 'A32DOYMUN6DTXA', 'extensibleAttribute': None, 'geoLocationTriggerData': None, 'id': 'A32DOYMUN6DTXA-G090U608841504W0-96bb5c3e-3fa1-3f7d-a2e5-5a798ef73fd6_REMINDER', 'lastOccurrenceTimeInMilli': 0, 'lastUpdatedDate': 0, 'loopCount': None, 'mrmGroupContext': {'groupId': None, 'groupType': None}, 'musicAlarmId': None, 'musicEntity': None, 'notificationIndex': '96bb5c3e-3fa1-3f7d-a2e5-5a798ef73fd6', 'originalDate': '2020-11-25', 'originalTime': '17:45:00.000', 'personProfile': None, 'provider': None, 'rRuleData': {'byMonthDays': None, 'byMonths': None, 'byWeekDays': ['WE'], 'flexibleRecurringPatternType': 'X_TIMES_A_WEEK', 'frequency': None, 'intervals': [1], 'nextTriggerTimes': None, 'notificationTimes': ['17:45:00.000'], 'offset': None, 'recurEndDate': None, 'recurEndTime': None, 'recurStartDate': None, 'recurStartTime': None, 'recurrenceRules': ['FREQ=WEEKLY;BYDAY=WE;BYHOUR=17;BYMINUTE=45;BYSECOND=0;INTERVAL=1;']}, 'recurrenceEligibility': False, 'recurringPattern': 'XXXX-WXX-3', 'remainingTime': 0, 'reminderAppLabel': None, 'reminderLabel': 'Dance', 'reminderSubLabel': None, 'skillInfo': None, 'snoozedToTime': None, 'sound': {'displayName': 'Simple Alarm', 'folder': None, 'id': 'system_alerts_melodic_01', 'isChildDirected': False, 'pricing': None, 'providerId': 'ECHO', 'sampleUrl': 'https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3'}, 'status': 'ON', 'targetPersonProfiles': None, 'timeZoneId': None, 'timerLabel': None, 'tmwNotificationProperties': None, 'triggerTime': 0, 'type': 'Reminder', 'version': '8'})
2020-11-20 08:42:36 DEBUG (MainThread) [custom_components.alexa_media.sensor] <Entity Kid's Echo next Reminder: 2020-11-21T06:40:00-05:00>: Scheduling event in 21:57:23.261620
2020-11-20 08:42:36 DEBUG (MainThread) [custom_components.alexa_media.sensor] Sensor value ('dd2703ca-bc14-30c8-8eca-a06c6fd77cb7', {'alarmTime': 1605958800000.0, 'automationId': None, 'createdDate': 1601208947399, 'deferredAtTime': None, 'deliveryType': None, 'deviceName': None, 'deviceSerialNumber': 'G090U608841504W0', 'deviceType': 'A32DOYMUN6DTXA', 'extensibleAttribute': None, 'geoLocationTriggerData': None, 'id': 'A32DOYMUN6DTXA-G090U608841504W0-dd2703ca-bc14-30c8-8eca-a06c6fd77cb7_REMINDER', 'lastOccurrenceTimeInMilli': 0, 'lastUpdatedDate': 0, 'loopCount': None, 'mrmGroupContext': {'groupId': None, 'groupType': None}, 'musicAlarmId': None, 'musicEntity': None, 'notificationIndex': 'dd2703ca-bc14-30c8-8eca-a06c6fd77cb7', 'originalDate': '2020-11-20', 'originalTime': '07:40:00.000', 'personProfile': None, 'provider': None, 'rRuleData': {'byMonthDays': None, 'byMonths': None, 'byWeekDays': ['MO', 'TU', 'WE', 'TH', 'FR'], 'flexibleRecurringPatternType': 'X_TIMES_A_WEEK', 'frequency': None, 'intervals': [1], 'nextTriggerTimes': None, 'notificationTimes': ['07:40:00.000', '07:40:00.000', '07:40:00.000', '07:40:00.000', '07:40:00.000'], 'offset': None, 'recurEndDate': None, 'recurEndTime': None, 'recurStartDate': None, 'recurStartTime': None, 'recurrenceRules': ['FREQ=WEEKLY;BYDAY=MO;BYHOUR=7;BYMINUTE=40;BYSECOND=0;INTERVAL=1;', 'FREQ=WEEKLY;BYDAY=TU;BYHOUR=7;BYMINUTE=40;BYSECOND=0;INTERVAL=1;', 'FREQ=WEEKLY;BYDAY=WE;BYHOUR=7;BYMINUTE=40;BYSECOND=0;INTERVAL=1;', 'FREQ=WEEKLY;BYDAY=TH;BYHOUR=7;BYMINUTE=40;BYSECOND=0;INTERVAL=1;', 'FREQ=WEEKLY;BYDAY=FR;BYHOUR=7;BYMINUTE=40;BYSECOND=0;INTERVAL=1;']}, 'recurrenceEligibility': False, 'recurringPattern': 'XXXX-WD', 'remainingTime': 0, 'reminderAppLabel': None, 'reminderLabel': "It's time for school", 'reminderSubLabel': None, 'skillInfo': None, 'snoozedToTime': None, 'sound': {'displayName': 'Simple Alarm', 'folder': None, 'id': 'system_alerts_melodic_01', 'isChildDirected': False, 'pricing': None, 'providerId': 'ECHO', 'sampleUrl': 'https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3'}, 'status': 'ON', 'targetPersonProfiles': None, 'timeZoneId': None, 'timerLabel': None, 'tmwNotificationProperties': None, 'triggerTime': 0, 'type': 'Reminder', 'version': '200'})
2020-11-20 08:42:36 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/alexa_media/sensor.py", line 304, in async_added_to_hass
    await self.async_update()
  File "/config/custom_components/alexa_media/sensor.py", line 399, in async_update
    self._process_raw_notifications()
  File "/config/custom_components/alexa_media/sensor.py", line 173, in _process_raw_notifications
    self._all = list(map(self._update_recurring_alarm, self._all))
  File "/config/custom_components/alexa_media/sensor.py", line 267, in _update_recurring_alarm
    and alarm.isoweekday not in RECURRING_PATTERN_ISO_SET[recurring_pattern]
AttributeError: 'float' object has no attribute 'isoweekday'
2020-11-20 08:42:36 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 207, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/alexa_media/sensor.py", line 304, in async_added_to_hass
    await self.async_update()
  File "/config/custom_components/alexa_media/sensor.py", line 399, in async_update
    self._process_raw_notifications()
  File "/config/custom_components/alexa_media/sensor.py", line 173, in _process_raw_notifications
    self._all = list(map(self._update_recurring_alarm, self._all))
  File "/config/custom_components/alexa_media/sensor.py", line 267, in _update_recurring_alarm
    and alarm.isoweekday not in RECURRING_PATTERN_ISO_SET[recurring_pattern]
AttributeError: 'float' object has no attribute 'isoweekday'
```

**Comment by vajonam** [comment]
Let me know if you need more logs. thanks

**Comment by alandtse** [comment]
Thanks for the log data. I think I have a fix. You can try the PR or you can wait for the next release.

**Comment by vajonam** [comment]
Merged in the PR, the error is gone, I wasn't really using that sensor in HA, Thanks for the quick fix!
