### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'float' upon captcha entry

### ISSUE THREAD

**Issue by tlpbu** [custom-components/alexa_media_player#828]
**Describe the bug**
`TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'float'` exception thrown upon Amazon captcha entry

**To Reproduce**
Steps to reproduce the behaviour:
1. When Amazon captcha is requested in HA sidebar open configure modal window
2. Enter captcha and submit 
3. Notice error notification popping up for few seconds un HA lower left corner
4. Open HA logs and look for exception (attached here)

**System details**
 - Home-assistant (version): 0.112.1
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 2.9.0
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
```
2020-07-04 10:05:50 ERROR (MainThread) [alexapy.helpers] alexaapi.send_sequence((<alexapy.alexaapi.AlexaAPI object at 0x6cd48e90>, 'Alexa.DeviceControls.Volume'), {'value': 13.0, 'queue_delay': 1.5}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Session is closed',)
2020-07-04 10:05:50 ERROR (MainThread) [alexapy.helpers] alexaapi.set_volume((<alexapy.alexaapi.AlexaAPI object at 0x6cd48e90>, 0.13), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments:
('Session is closed',)
2020-07-04 10:22:17 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1831490640] unsupported operand type(s) for +: 'datetime.datetime' and 'float'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/configurator/__init__.py", line 235, in async_handle_service_call
    await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
  File "/config/custom_components/alexa_media/configurator.py", line 28, in configuration_callback
    setup_platform_callback, hass, config_entry, login, callback_data
  File "/config/custom_components/alexa_media/configurator.py", line 173, in setup_platform_callback
    await test_login_status(hass, config_entry, login, alexa_setup_callback)
  File "/config/custom_components/alexa_media/configurator.py", line 179, in test_login_status
    await hass.async_add_job(alexa_setup_callback, hass, config_entry, login)
  File "/config/custom_components/alexa_media/__init__.py", line 899, in setup_alexa
    await coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 174, in async_refresh
    self._schedule_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 105, in _schedule_refresh
    utcnow().replace(microsecond=0) + self.update_interval,
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'float'
```

**Comment by starkillerOG** [comment]
I have the same problem

**Comment by poudenes** [comment]
Same problem on HA 0.112.2
Alexa Media Player v2.9.0

**Comment by alandtse** [comment]
Do you have an automation that is automatically setting the volume?

**Comment by alandtse** [comment]
Thanks. Found the cause. Fix in next release.
