### ISSUE TITLE
Notify at Amazon Echo create an error ans no anounce

### ISSUE THREAD

**Issue by Snobs76** [custom-components/alexa_media_player#835]
Hello, 
I create some month befor a script that send a message to my sonos speaker nd one Amazon echo device.

The was always working. Now the anounce for Alexa Echo is broken.
I delete the part from AlexaMediaplayer and the script is running again well

But if I try create a small script that only anounce a test message I got the same erros`s again.
My HA and AMP ist up to date with the last stable versions.

Here a the yaml file:
alias: Alexa Annouce Test
  sequence:
  - data:
      message: Testmessage
      method: speak
      type: announce
    service: notify.alexa_media_echo_buro

and the Error from HA

Protokolldetails ( ERROR )
Logger: homeassistant.components.websocket_api.http.connection.140367275672784
Source: core.py:1222
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:39:13 (6 occurrences)
Last logged: 12:52:35

extra keys not allowed @ data['method']
extra keys not allowed @ data['type']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 204, in service_handler
    await script.async_turn_on(variables=service.data, context=service.context)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 280, in async_turn_on
    await self.script.async_run(kwargs.get(ATTR_VARIABLES), context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 831, in async_run
    await run.async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 555, in async_run
    await self._async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 572, in _async_run
    await self._async_step(log_exceptions=not propagate_exceptions)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 656, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1222, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['method']

Please help me to get it back to work.

Best regards
Sascha

**Comment by chemelli74** [comment]
Check carefully indentation:

```
 data:
   method: spoken
   type: announce
 target: media_player.alexa
```

Simone

**Comment by alandtse** [comment]
Please use the [forum](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/4087) for help on using the component. The github is for technical issues with the component.

As @chemelli74 mentioned, you also need to properly quote.
