### ISSUE TITLE
Config entry has already been setup!

### ISSUE THREAD

**Issue by vlad36N** [custom-components/alexa_media_player#866]
**Describe the bug**
Every time when HA restarted have error on Log:

2020-08-15 06:42:33 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxx@gmail.com - amazon.com for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 222, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 334, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 159, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2020-08-15 06:42:33 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxx@gmail.com - amazon.com for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 222, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 334, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 159, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): Home Assistant 0.114.1
 - System | HassOS 5.0
 - Supervisor Version 234
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): v2.10.1

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
2020-08-15 06:42:33 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxx@gmail.com - amazon.com for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 222, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 334, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 159, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2020-08-15 06:42:33 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxxx@gmail.com - amazon.com for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 222, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 334, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 159, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
**Additional context**

**Comment by alandtse** [comment]
Need debug logs from before this point to help you. Make sure you're not trying set up the same account twice.

**Comment by vlad36N** [comment]
I'm not trying set up the same account twice.
It has been working almost a year without a problems.

**Comment by alandtse** [comment]
This may happen if a media player isn't discovered initially and then discovered while the component is running. I ran into it while debugging something else but it disappeared again so I couldn't reproduce it.

**Comment by photinus** [comment]
Seeing the same errors pop up in my logs, seems to have started after the upgrade to 0.115

Logs:
https://pastebin.com/tjapDpJF

**Comment by Trev-W** [comment]
I have this also, and in the integrations page my amazon account is listed twice and in the logs
`2020-10-10 13:01:01 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry REDACTED@REDACTED.com - amazon.com.au for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 337, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!`

I don't use the echo as a media player per se just for the Alexa Actionable Notifications which work fine.

**Comment by user514** [comment]
same here. Just received the new message with different text body which alerts of 'Alexa Media Reauthentication Required', and about going to integrations page. I went there and authorize my two accounts (with the new forms). Used 2FA as always. When I exit I can see 4 accounts. Which are my 2 accounts repeated. Of course, when I restart I got the 'ValueError: Config entry has already been setup!'. I suppose I have to delete the duplicated onesfrom integrations. I haven't done yet because I dont know right now which is the right one (one have some devices related the other don't).

![duplicate](https://user-images.githubusercontent.com/19530873/95722947-dee19f00-0c74-11eb-8693-ca21f94728e7.jpg)

**Comment by serlinGi** [comment]
same similar error
Homeassistant.OS 4.14-64bit - 0.116.4

my error-log now:

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:155
First occurred: 3:02:45 PM (3 occurrences)
Last logged: 3:02:45 PM

Error setting up entry my_amazon_account@xyz.it - amazon.it for switch
Error setting up entry my_amazon_account@xyz.it - amazon.it for sensor
Error setting up entry my_amazon_accoint@xyz.it - amazon.it for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 73, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Comment by user514** [comment]
> same similar error
> Homeassistant.OS 4.14-64bit - 0.116.4
> 
> my error-log now:
> ValueError: Config entry has already been setup!

  ...check if like me, when authorizing latest version, integration page had created duplicates for your device, like:

john@doe.com amazon.com
john@doe.com amazon.com

  If that's the case, I delete one of them and error dissapear.

**Comment by serlinGi** [comment]
> > same similar error
> > Homeassistant.OS 4.14-64bit - 0.116.4
> > my error-log now:
> > ValueError: Config entry has already been setup!
> 
> ...check if like me, when authorizing latest version, integration page had created duplicates for your device, like:
> 
> ```
> john@doe.com amazon.com
> john@doe.com amazon.com
> ```
> 
> If that's the case, I delete one of them and error dissapear.

no, that's not my case.  I have already happened to find myself with the registered account twice and I solved it as you said.  thanks for the feedback

**Comment by poudenes** [comment]
Hi All,

I get this error when I reboot HA:

```
2020-12-29 17:52:17 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry info@mydomain.com - amazon.co.uk for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 345, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

There is just 1 integration in HA. And there is no new found device that I can add.
So the solution to delete 1 is not work for me

**Comment by TheDarthFather** [comment]
I have exactely the same issue. I also see 2 times the integration as mentione before.
This happened after I upgraded to the current HA & alexa_media_player version (havent done an upgrade since 6 months)
