### ISSUE TITLE
TypeError: object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by poudenes** [custom-components/alexa_media_player#867]
**System details**
 - Home-assistant (version): 0.114.1
 - Hassio (Yes/No): YES
 - alexa_media  (version from `const.py` or HA startup): v2.10.1
 - alexapy (version from `pip show alexapy` or HA startup): unknown 

**Logs**
```
2020-08-16 22:46:38 ERROR (MainThread) [alexapy.helpers] alexaapi.get_device_preferences((<alexapy.alexalogin.AlexaLogin object at 0xacf96f70>,), {}): A login error occured: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 1 column 1 (char 0)',)
2020-08-16 22:46:38 ERROR (MainThread) [custom_components.alexa_media] Unexpected error fetching alexa_media data: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 111, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexaapi.py", line 943, in get_device_preferences
    return await response.json(content_type=None) if response else None
  File "/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/client_reqrep.py", line 1095, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/alexa_media/__init__.py", line 298, in async_update_data
    ) = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 131, in wrapper
    raise AlexapyLoginError
alexapy.errors.AlexapyLoginError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 143, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 131, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alexa_media/__init__.py", line 314, in async_update_data
    await hass.bus.async_fire(
TypeError: object NoneType can't be used in 'await' expression
2020-08-16 22:46:38 ERROR (MainThread) [alexapy.helpers] alexaapi.get_devices((<alexapy.alexalogin.AlexaLogin object at 0xacf96f70>,), {}): A login error occured: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 1 column 1 (char 0)',)
2020-08-16 22:46:38 ERROR (MainThread) [alexapy.helpers] alexaapi.get_notifications((<alexapy.alexalogin.AlexaLogin object at 0xacf96f70>,), {}): A login error occured: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 1 column 1 (char 0)',)
2020-08-16 22:46:38 ERROR (MainThread) [alexapy.helpers] alexaapi.get_dnd_state((<alexapy.alexalogin.AlexaLogin object at 0xacf96f70>,), {}): A login error occured: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 1 column 1 (char 0)',)
2020-08-16 22:46:38 ERROR (MainThread) [alexapy.helpers] alexaapi.get_bluetooth((<alexapy.alexalogin.AlexaLogin object at 0xacf96f70>,), {}): A login error occured: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 1 column 1 (char 0)',)
```

**Comment by alandtse** [comment]
Thanks. There's a bug that I'll fix, but the main issue is your pickle expired.
