### ISSUE TITLE
HA 0.115.0b0 causes a semver failure

### ISSUE THREAD

**Issue by rccoleman** [custom-components/alexa_media_player#915]
**Describe the bug**
Installing Home Assistant 0.115.0b0 results in the following error message during startup:

```
2020-09-07 15:54:26 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alexa_media/sensor.py", line 120, in async_setup_entry
    return await async_setup_platform(
  File "/config/custom_components/alexa_media/sensor.py", line 79, in async_setup_platform
    alexa_client = class_(
  File "/config/custom_components/alexa_media/sensor.py", line 433, in __init__
    if semver.compare(HA_VERSION, "0.113.0") >= 0
  File "/usr/local/lib/python3.8/site-packages/semver.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/semver.py", line 786, in compare
    v1 = VersionInfo.parse(ver1)
  File "/usr/local/lib/python3.8/site-packages/semver.py", line 656, in parse
    raise ValueError("%s is not valid SemVer string" % version)
ValueError: 0.115.0b0 is not valid SemVer string
```

Looks like it doesn't like the string.

**To Reproduce**
Install the latest version of the Alexa Media Player from HACS (v2.11.0), restart Home Assistant, monitor logs.

**Expected behavior**
No errors during startup.

**System details**
 - Home-assistant (version): 0.115.0b0
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 2.11.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.14.1
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```
2020-09-07 15:54:26 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alexa_media/sensor.py", line 120, in async_setup_entry
    return await async_setup_platform(
  File "/config/custom_components/alexa_media/sensor.py", line 79, in async_setup_platform
    alexa_client = class_(
  File "/config/custom_components/alexa_media/sensor.py", line 433, in __init__
    if semver.compare(HA_VERSION, "0.113.0") >= 0
  File "/usr/local/lib/python3.8/site-packages/semver.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/semver.py", line 786, in compare
    v1 = VersionInfo.parse(ver1)
  File "/usr/local/lib/python3.8/site-packages/semver.py", line 656, in parse
    raise ValueError("%s is not valid SemVer string" % version)
ValueError: 0.115.0b0 is not valid SemVer string
```

**Additional context**

**Comment by alandtse** [comment]
Thanks. Apparently HA doesn't actually follow semver [syntax](https://semver.org/).

**Comment by rccoleman** [comment]
Ah, yeah.  It looks like all the betas are tagged that way on purpose.

**Comment by alandtse** [comment]
2.11.1 should solve this. Please let me know if it doesn't.

**Comment by rccoleman** [comment]
Looks good, thanks!
