### ISSUE TITLE
NotADirectoryError when loading translations

### ISSUE THREAD

**Issue by dfederm** [custom-components/alexa_media_player#934]
After installing the latest (2.11.2), I the component doesn't work and I get many errors related to loading translations

```
2020-09-14 09:12:02 ERROR (SyncWorker_32) [homeassistant.util.json] JSON file reading failed: /config/custom_components/alexa_media/translations/en.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 31, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/custom_components/alexa_media/translations/en.json'
2020-09-14 09:12:02 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1801865848] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 31, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/custom_components/alexa_media/translations/en.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 21, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 610, in websocket_get_translations
    resources = await async_get_translations(
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 314, in async_get_translations
    results = await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 210, in async_get_component_strings
    loaded_translations = await load_translations_job
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 79, in load_translations_files
    loaded_json = load_json(translation_file)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 41, in load_json
    raise HomeAssistantError(error)
homeassistant.exceptions.HomeAssistantError: [Errno 20] Not a directory: '/config/custom_components/alexa_media/translations/en.json'
```

**Comment by dfederm** [comment]
Ah, so apparently the "translations" file is actually a symlink to the ".translations" dir, but for whatever reason Git was just writing it as a file and not a symlink.

**Comment by alandtse** [comment]
I assume you were able to resolve it once you created the symlink right? This is a git issue and not a component issue.

**Comment by dfederm** [comment]
I actually just deleted the symlink and renamed the directory. I assume the reason for the symlink is for back-compat. When does it make sense to cut support for older versions?

**Comment by alandtse** [comment]
When I think enough people have moved forward. You're first person I've heard run into an issue with the backwards compatibility.
